In [4]:
import os
import time
import pandas as pd
import akshare as ak
import warnings
import psycopg2
from datetime import timedelta, datetime
warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('expand_frame_repr', False)
pd.set_option('display.unicode.ambiguous_as_wide', True)
pd.set_option('display.unicode.east_asian_width', True)

In [2]:
code_list = pd.read_csv('CodeList.csv')

In [3]:
def create_path(ak_code:str):
    global path
    path = os.path.join(".","Stock_Daily")
    # save data
    if not os.path.exists(path) :
        # os.mkdir(path) 
        os.makedirs(path)  
    file_name = ak_code + ".csv"
    return os.path.join(path,file_name)

In [4]:
def check(ak_code:str):
    path = os.path.join(".","Stock_Daily",ak_code)
    path = path + ".csv"
    print(path)
    if os.path.isfile(path):
        return True
    return False

In [6]:
start_Date = '20230103'
end_Date = '20231124'
stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol='600519', start_date=start_Date, end_date=end_Date, period='daily', adjust='')

           日期     开盘     收盘     最高     最低  成交量        成交额  振幅  涨跌幅  涨跌额  换手率
0    2023-01-03  1731.20  1730.01  1738.43  1706.01   26034  4.487760e+09  1.88    0.17    3.01    0.21
1    2023-01-04  1730.00  1725.01  1738.70  1716.00   20416  3.523582e+09  1.31   -0.29   -5.00    0.16
2    2023-01-05  1737.00  1801.00  1801.00  1733.00   47943  8.541587e+09  3.94    4.41   75.99    0.38
3    2023-01-06  1806.12  1803.77  1811.90  1787.00   24904  4.480839e+09  1.38    0.15    2.77    0.20
4    2023-01-09  1835.00  1841.20  1849.98  1807.82   30977  5.684181e+09  2.34    2.08   37.43    0.25
5    2023-01-10  1839.06  1854.45  1864.50  1830.50   22732  4.204784e+09  1.85    0.72   13.25    0.18
6    2023-01-11  1856.00  1844.95  1860.00  1836.84   22720  4.201488e+09  1.25   -0.51   -9.50    0.18
7    2023-01-12  1848.00  1834.00  1856.00  1833.00   17193  3.162637e+09  1.25   -0.59  -10.95    0.14
8    2023-01-13  1844.18  1887.00  1888.00  1840.00   31940  5.969876e+09  2.62    2.89   53.00    0.25
9    2023-01-16  1886.00  1912.90  1935.00  1881.00   36848  7.059983e+09  2.86    1.37   25.90    0.29
10   2023-01-17  1913.16  1908.00  1923.00  1895.00   21299  4.068321e+09  1.46   -0.26   -4.90    0.17
11   2023-01-18  1914.00  1893.00  1925.30  1890.00   21063  4.008665e+09  1.85   -0.79  -15.00    0.17
12   2023-01-19  1892.50  1880.21  1892.52  1866.00   23439  4.401994e+09  1.40   -0.68  -12.79    0.19
13   2023-01-20  1889.19  1860.01  1898.25  1858.00   25609  4.807356e+09  2.14   -1.07  -20.20    0.20
14   2023-01-30  1909.00  1888.00  1909.00  1880.00   35923  6.799757e+09  1.56    1.50   27.99    0.29
15   2023-01-31  1896.50  1845.76  1899.95  1833.07   32991  6.128312e+09  3.54   -2.24  -42.24    0.26
16   2023-02-01  1854.98  1844.97  1859.00  1811.40   33974  6.244679e+09  2.58   -0.04   -0.79    0.27
17   2023-02-02  1848.38  1836.11  1859.00  1826.00   29759  5.465510e+09  1.79   -0.48   -8.86    0.24
18   2023-02-03  1820.00  1818.00  1826.00  1795.68   34945  6.324635e+09  1.65   -0.99  -18.11    0.28
19   2023-02-06  1780.00  1795.00  1795.00  1760.00   42661  7.595739e+09  1.93   -1.27  -23.00    0.34
20   2023-02-07  1808.08  1797.00  1808.80  1787.73   24322  4.373672e+09  1.17    0.11    2.00    0.19
21   2023-02-08  1800.01  1784.00  1805.97  1775.00   16676  2.980575e+09  1.72   -0.72  -13.00    0.13
22   2023-02-09  1778.00  1818.00  1829.75  1775.01   29754  5.401399e+09  3.07    1.91   34.00    0.24
23   2023-02-10  1810.10  1810.00  1818.49  1801.05   17985  3.253859e+09  0.96   -0.44   -8.00    0.14
24   2023-02-13  1810.00  1856.35  1874.50  1810.00   38147  7.058382e+09  3.56    2.56   46.35    0.30
25   2023-02-14  1856.46  1843.79  1857.40  1835.00   19566  3.601770e+09  1.21   -0.68  -12.56    0.16
26   2023-02-15  1843.78  1841.00  1855.30  1835.81   18177  3.351422e+09  1.06   -0.15   -2.79    0.14
27   2023-02-16  1841.34  1861.82  1887.00  1828.00   33246  6.196915e+09  3.20    1.13   20.82    0.26
28   2023-02-17  1850.16  1820.78  1873.00  1820.05   26443  4.880329e+09  2.84   -2.20  -41.04    0.21
29   2023-02-20  1821.00  1875.00  1878.80  1817.20   29669  5.488800e+09  3.38    2.98   54.22    0.24
30   2023-02-21  1874.00  1867.00  1874.00  1851.00   18751  3.491634e+09  1.23   -0.43   -8.00    0.15
31   2023-02-22  1855.01  1836.00  1863.90  1831.80   21869  4.031016e+09  1.72   -1.66  -31.00    0.17
32   2023-02-23  1840.00  1818.00  1848.80  1805.25   21881  3.983991e+09  2.37   -0.98  -18.00    0.17
33   2023-02-24  1810.11  1788.00  1810.19  1782.18   24635  4.415621e+09  1.54   -1.65  -30.00    0.20
34   2023-02-27  1778.50  1810.41  1815.00  1775.02   22065  3.978129e+09  2.24    1.25   22.41    0.18
35   2023-02-28  1819.00  1813.74  1822.01  1783.30   23952  4.314877e+09  2.14    0.18    3.33    0.19
36   2023-03-01  1813.00  1838.53  1848.00  1803.23   24458  4.475592e+09  2.47    1.37   24.79    0.19
37   2023-03-02  1829.00  1828.00  1838.99  1821.10   13144  2.405292e+09  0.97   -0.57  -10.53    0.10
38   2023-03-03  1839.77  1818.04  1841.61  1802.48   16198  2.946843e+09  2.14   -0.54   -9.96    0.13
39   2023-03-06  1818.18  1807.14  1818.50  1796.77   20646  3.730080e+09  1.20   -0.60  -10.90    0.16
40   2023-03-07  1805.98  1788.30  1816.60  1788.00   22785  4.101302e+09  1.58   -1.04  -18.84    0.18
41   2023-03-08  1780.02  1770.42  1785.94  1761.12   22764  4.035787e+09  1.39   -1.00  -17.88    0.18
42   2023-03-09  1768.00  1770.02  1785.00  1740.00   27612  4.881443e+09  2.54   -0.02   -0.40    0.22
43   2023-03-10  1751.57  1750.00  1781.00  1750.00   21161  3.725139e+09  1.75   -1.13  -20.02    0.17
44   2023-03-13  1751.00  1762.00  1775.00  1749.00   20560  3.626476e+09  1.49    0.69   12.00    0.16
45   2023-03-14  1763.78  1766.00  1779.88  1738.50   23705  4.177289e+09  2.35    0.23    4.00    0.19
46   2023-03-15  1778.37  1750.92  1784.88  1750.12   19213  3.392698e+09  1.97   -0.85  -15.08    0.15
47   2023-03-16  1740.00  1751.99  1770.00  1739.01   17646  3.096791e+09  1.77    0.06    1.07    0.14
48   2023-03-17  1770.00  1742.00  1775.89  1736.00   27023  4.744249e+09  2.28   -0.57   -9.99    0.22
49   2023-03-20  1751.00  1729.60  1755.00  1728.00   20491  3.557872e+09  1.55   -0.71  -12.40    0.16
50   2023-03-21  1735.00  1775.00  1785.85  1723.97   31142  5.491052e+09  3.58    2.62   45.40    0.25
51   2023-03-22  1780.00  1773.35  1793.00  1765.55   15330  2.727649e+09  1.55   -0.09   -1.65    0.12
52   2023-03-23  1766.00  1774.86  1791.11  1765.01   17356  3.082822e+09  1.47    0.09    1.51    0.14
53   2023-03-24  1769.08  1778.62  1783.60  1766.00   12770  2.269649e+09  0.99    0.21    3.76    0.10
54   2023-03-27  1778.60  1767.79  1778.60  1756.00   15296  2.700756e+09  1.27   -0.61  -10.83    0.12
55   2023-03-28  1770.00  1781.80  1790.00  1765.02   17261  3.073113e+09  1.41    0.79   14.01    0.14
56   2023-03-29  1799.00  1790.00  1800.00  1785.07   15393  2.761909e+09  0.84    0.46    8.20    0.12
57   2023-03-30  1793.00  1800.00  1805.00  1779.00   19257  3.453573e+09  1.45    0.56   10.00    0.15
58   2023-03-31  1825.00  1820.00  1848.00  1819.00   27446  5.024790e+09  1.61    1.11   20.00    0.22
59   2023-04-03  1825.00  1802.07  1827.77  1800.08   21417  3.875812e+09  1.52   -0.99  -17.93    0.17
60   2023-04-04  1812.00  1814.59  1815.17  1787.00   20066  3.614275e+09  1.56    0.69   12.52    0.16
61   2023-04-06  1805.00  1796.96  1815.90  1788.22   14874  2.676252e+09  1.53   -0.97  -17.63    0.12
62   2023-04-07  1795.00  1790.99  1806.01  1788.34   13525  2.428161e+09  0.98   -0.33   -5.97    0.11
63   2023-04-10  1790.88  1771.70  1790.88  1744.00   29418  5.171151e+09  2.62   -1.08  -19.29    0.23
64   2023-04-11  1793.00  1745.50  1793.00  1744.00   29209  5.138855e+09  2.77   -1.48  -26.20    0.23
65   2023-04-12  1747.26  1694.10  1750.00  1692.82   51105  8.732657e+09  3.28   -2.94  -51.40    0.41
66   2023-04-13  1690.00  1723.00  1723.59  1684.01   29543  5.049310e+09  2.34    1.71   28.90    0.24
67   2023-04-14  1726.00  1713.42  1733.00  1704.80   21232  3.646527e+09  1.64   -0.56   -9.58    0.17
68   2023-04-17  1740.00  1753.00  1753.00  1728.00   30467  5.303401e+09  1.46    2.31   39.58    0.24
69   2023-04-18  1753.00  1758.00  1769.00  1746.02   18314  3.220108e+09  1.31    0.29    5.00    0.15
70   2023-04-19  1762.00  1759.00  1765.50  1750.00   14601  2.568633e+09  0.88    0.06    1.00    0.12
71   2023-04-20  1760.11  1741.88  1765.00  1729.00   19885  3.468367e+09  2.05   -0.97  -17.12    0.16
72   2023-04-21  1746.00  1725.47  1748.08  1721.28   18518  3.210937e+09  1.54   -0.94  -16.41    0.15
73   2023-04-24  1721.00  1705.00  1722.00  1701.00   20231  3.456729e+09  1.22   -1.19  -20.47    0.16
74   2023-04-25  1706.00  1730.38  1735.98  1702.00   20583  3.534990e+09  1.99    1.49   25.38    0.16
75   2023-04-26  1744.00  1743.91  1761.00  1720.00   27892  4.861478e+09  2.37    0.78   13.53    0.22
76   2023-04-27  1748.00  1757.92  1770.00  1730.00   25605  4.489907e+09  2.29    0.80   14.01    0.20
77   2023-04-28  1763.01  1760.52  1782.77  1753.97   26225  4.636084e+09  1.64    0.15    2.60    0.21
78   2023-05-04  1769.00  1749.90  1777.67  1736.00   27466  4.819000e+09  2.37   -0.60  -10.62    0.22
79   2023-05-05  1766.00  1750.00  1766.00  1736.39   20714  3.621306e+09  1.69    0.01    0.10    0.16
80   2023-05-08  1768.32  1720.52  1769.00  1717.17   33171  5.742916e+09  2.96   -1.68  -29.48    0.26
81   2023-05-09  1715.00  1722.00  1739.98  1707.07   29378  5.057347e+09  1.91    0.09    1.48    0.23
82   2023-05-10  1715.19  1725.00  1736.00  1715.00   20773  3.588551e+09  1.22    0.17    3.00    0.17
83   2023-05-11  1731.00  1717.07  1735.00  1715.00   15246  2.623836e+09  1.16   -0.46   -7.93    0.12
84   2023-05-12  1715.00  1706.40  1729.88  1705.01   19460  3.335039e+09  1.45   -0.62  -10.67    0.15
85   2023-05-15  1702.00  1716.30  1717.00  1691.20   25740  4.384648e+09  1.51    0.58    9.90    0.20
86   2023-05-16  1713.99  1703.29  1719.99  1697.00   22224  3.785812e+09  1.34   -0.76  -13.01    0.18
87   2023-05-17  1708.00  1701.00  1713.00  1699.01   16777  2.858698e+09  0.82   -0.13   -2.29    0.13
88   2023-05-18  1704.99  1691.00  1705.40  1690.00   19219  3.260171e+09  0.91   -0.59  -10.00    0.15
89   2023-05-19  1671.00  1699.50  1704.33  1655.55   26741  4.504023e+09  2.88    0.50    8.50    0.21
90   2023-05-22  1690.01  1746.00  1752.00  1690.00   41284  7.165754e+09  3.65    2.74   46.50    0.33
91   2023-05-23  1753.99  1724.55  1754.00  1724.55   16894  2.934118e+09  1.69   -1.23  -21.45    0.13
92   2023-05-24  1732.33  1710.90  1733.55  1710.11   18479  3.182416e+09  1.36   -0.79  -13.65    0.15
93   2023-05-25  1705.99  1701.00  1710.00  1690.00   22466  3.814504e+09  1.17   -0.58   -9.90    0.18
94   2023-05-26  1702.00  1690.56  1705.00  1675.01   18291  3.090692e+09  1.76   -0.61  -10.44    0.15
95   2023-05-29  1697.00  1689.00  1698.35  1678.00   17771  2.998147e+09  1.20   -0.09   -1.56    0.14
96   2023-05-30  1689.00  1668.29  1698.89  1658.56   26453  4.424707e+09  2.39   -1.23  -20.71    0.21
97   2023-05-31  1661.01  1628.90  1665.72  1626.67   36957  6.053737e+09  2.34   -2.36  -39.39    0.29
98   2023-06-01  1618.00  1635.92  1674.99  1618.00   28645  4.708723e+09  3.50    0.43    7.02    0.23
99   2023-06-02  1645.00  1670.60  1673.15  1636.11   25058  4.163116e+09  2.26    2.12   34.68    0.20
100  2023-06-05  1666.16  1665.00  1682.88  1663.00   16201  2.704294e+09  1.19   -0.34   -5.60    0.13
101  2023-06-06  1670.00  1666.99  1684.00  1651.55   19914  3.326778e+09  1.95    0.12    1.99    0.16
102  2023-06-07  1672.99  1650.90  1678.80  1650.00   17890  2.971782e+09  1.73   -0.97  -16.09    0.14
103  2023-06-08  1655.83  1668.00  1675.00  1650.01   14703  2.441570e+09  1.51    1.04   17.10    0.12
104  2023-06-09  1671.99  1666.00  1677.97  1666.00   17580  2.938014e+09  0.72   -0.12   -2.00    0.14
105  2023-06-12  1666.02  1696.00  1708.00  1661.52   27029  4.562309e+09  2.79    1.80   30.00    0.22
106  2023-06-13  1693.88  1699.00  1704.61  1685.00   14663  2.485399e+09  1.16    0.18    3.00    0.12
107  2023-06-14  1719.00  1726.88  1734.24  1706.21   31506  5.438040e+09  1.65    1.64   27.88    0.25
108  2023-06-15  1730.34  1755.00  1755.65  1723.00   25223  4.395901e+09  1.89    1.63   28.12    0.20
109  2023-06-16  1757.00  1797.69  1800.00  1750.10   37918  6.742301e+09  2.84    2.43   42.69    0.30
110  2023-06-19  1790.00  1744.00  1797.95  1738.00   31700  5.584249e+09  3.33   -2.99  -53.69    0.25
111  2023-06-20  1740.00  1743.46  1765.00  1735.00   20947  3.659825e+09  1.72   -0.03   -0.54    0.17
112  2023-06-21  1740.00  1735.83  1756.60  1735.00   17721  3.088636e+09  1.24   -0.44   -7.63    0.14
113  2023-06-26  1720.11  1709.00  1730.00  1695.00   23993  4.098620e+09  2.02   -1.55  -26.83    0.19
114  2023-06-27  1709.99  1711.05  1719.70  1700.09   15174  2.598139e+09  1.15    0.12    2.05    0.12
115  2023-06-28  1713.18  1728.38  1734.00  1711.00   18574  3.199294e+09  1.34    1.01   17.33    0.15
116  2023-06-29  1731.00  1713.71  1734.99  1713.01   14231  2.446524e+09  1.27   -0.85  -14.67    0.11
117  2023-06-30  1700.00  1691.00  1708.99  1686.48   20459  3.472587e+09  1.31   -1.33  -22.71    0.16
118  2023-07-03  1699.00  1724.10  1725.28  1692.00   19139  3.286738e+09  1.97    1.96   33.10    0.15
119  2023-07-04  1724.20  1730.60  1734.44  1718.08   12472  2.155554e+09  0.95    0.38    6.50    0.10
120  2023-07-05  1730.00  1715.38  1731.97  1700.00   14745  2.523961e+09  1.85   -0.88  -15.22    0.12
121  2023-07-06  1709.16  1702.98  1733.00  1700.00   15141  2.589459e+09  1.92   -0.72  -12.40    0.12
122  2023-07-07  1701.00  1690.03  1708.99  1690.00   15167  2.571459e+09  1.12   -0.76  -12.95    0.12
123  2023-07-10  1705.00  1700.90  1714.96  1700.00   13477  2.298242e+09  0.89    0.64   10.87    0.11
124  2023-07-11  1710.00  1710.00  1715.17  1702.10   12583  2.151079e+09  0.77    0.54    9.10    0.10
125  2023-07-12  1713.04  1713.80  1723.00  1711.33   13285  2.280785e+09  0.68    0.22    3.80    0.11
126  2023-07-13  1721.99  1738.40  1745.41  1719.01   25807  4.479772e+09  1.54    1.44   24.60    0.21
127  2023-07-14  1756.00  1753.00  1758.50  1741.20   18550  3.245530e+09  1.00    0.84   14.60    0.15
128  2023-07-17  1751.00  1729.97  1751.00  1726.60   14336  2.482070e+09  1.39   -1.31  -23.03    0.11
129  2023-07-18  1733.58  1722.80  1734.51  1721.00   14738  2.544005e+09  0.78   -0.41   -7.17    0.12
130  2023-07-19  1715.01  1723.00  1728.00  1713.80   12483  2.147704e+09  0.82    0.01    0.20    0.10
131  2023-07-20  1727.99  1724.00  1748.98  1722.00   16693  2.897176e+09  1.57    0.06    1.00    0.13
132  2023-07-21  1731.88  1771.30  1772.50  1726.00   39377  6.931536e+09  2.70    2.74   47.30    0.31
133  2023-07-24  1750.52  1771.15  1771.15  1750.52   19713  3.476648e+09  1.16   -0.01   -0.15    0.16
134  2023-07-25  1800.00  1828.55  1828.88  1799.99   43086  7.837450e+09  1.63    3.24   57.40    0.34
135  2023-07-26  1828.55  1828.55  1835.99  1815.08   19611  3.580171e+09  1.14    0.00    0.00    0.16
136  2023-07-27  1836.00  1838.03  1854.79  1828.70   20340  3.749635e+09  1.43    0.52    9.48    0.16
137  2023-07-28  1832.00  1897.00  1900.00  1828.01   39018  7.330314e+09  3.92    3.21   58.97    0.31
138  2023-07-31  1908.00  1880.58  1935.00  1874.00   45379  8.615280e+09  3.22   -0.87  -16.42    0.36
139  2023-08-01  1878.01  1889.00  1906.95  1877.89   19231  3.635857e+09  1.55    0.45    8.42    0.15
140  2023-08-02  1883.40  1880.00  1890.00  1866.80   18509  3.478674e+09  1.23   -0.48   -9.00    0.15
141  2023-08-03  1870.00  1878.47  1890.00  1850.50   21543  4.031088e+09  2.10   -0.08   -1.53    0.17
142  2023-08-04  1887.82  1893.47  1906.52  1882.00   24574  4.655814e+09  1.31    0.80   15.00    0.20
143  2023-08-07  1880.95  1887.93  1898.00  1871.03   23892  4.491893e+09  1.42   -0.29   -5.54    0.19
144  2023-08-08  1880.03  1890.00  1893.71  1864.08   17736  3.333560e+09  1.57    0.11    2.07    0.14
145  2023-08-09  1890.00  1890.28  1905.00  1882.96   18523  3.506306e+09  1.17    0.01    0.28    0.15
146  2023-08-10  1882.00  1875.00  1889.00  1862.30   18436  3.454219e+09  1.41   -0.81  -15.28    0.15
147  2023-08-11  1885.00  1834.00  1885.40  1833.88   26786  4.959167e+09  2.75   -2.19  -41.00    0.21
148  2023-08-14  1810.00  1803.00  1824.98  1796.00   23731  4.285362e+09  1.58   -1.69  -31.00    0.19
149  2023-08-15  1809.00  1812.98  1818.00  1801.01   14818  2.682125e+09  0.94    0.55    9.98    0.12
150  2023-08-16  1807.58  1820.00  1823.35  1806.00   13184  2.396262e+09  0.96    0.39    7.02    0.10
151  2023-08-17  1806.08  1828.05  1834.00  1801.55   17290  3.141408e+09  1.78    0.44    8.05    0.14
152  2023-08-18  1831.99  1802.59  1834.99  1802.59   17023  3.084762e+09  1.77   -1.39  -25.46    0.14
153  2023-08-21  1793.00  1791.00  1813.99  1790.07   18912  3.405416e+09  1.33   -0.64  -11.59    0.15
154  2023-08-22  1800.99  1788.00  1802.56  1771.02   26650  4.763131e+09  1.76   -0.17   -3.00    0.21
155  2023-08-23  1797.00  1774.00  1800.00  1770.08   19912  3.556179e+09  1.67   -0.78  -14.00    0.16
156  2023-08-24  1779.62  1816.30  1828.00  1775.00   26055  4.703418e+09  2.99    2.38   42.30    0.21
157  2023-08-25  1808.79  1824.98  1837.77  1806.01   18831  3.433297e+09  1.75    0.48    8.68    0.15
158  2023-08-28  1898.58  1834.97  1898.58  1831.88   41052  7.633221e+09  3.65    0.55    9.99    0.33
159  2023-08-29  1828.00  1851.33  1869.08  1828.00   28950  5.371260e+09  2.24    0.89   16.36    0.23
160  2023-08-30  1867.90  1856.00  1868.00  1843.66   19812  3.672570e+09  1.31    0.25    4.67    0.16
161  2023-08-31  1860.00  1847.00  1860.00  1841.01   14820  2.738446e+09  1.02   -0.48   -9.00    0.12
162  2023-09-01  1852.83  1851.05  1865.47  1846.03   13145  2.438623e+09  1.05    0.22    4.05    0.10
163  2023-09-04  1862.60  1866.00  1879.94  1853.53   23871  4.453823e+09  1.43    0.81   14.95    0.19
164  2023-09-05  1868.00  1858.70  1868.00  1856.80   15659  2.915626e+09  0.60   -0.39   -7.30    0.12
165  2023-09-06  1858.00  1861.00  1866.66  1849.01   11121  2.067606e+09  0.95    0.12    2.30    0.09
166  2023-09-07  1852.60  1838.00  1856.89  1831.19   16982  3.128587e+09  1.38   -1.24  -23.00    0.14
167  2023-09-08  1834.94  1818.50  1834.94  1814.95   12212  2.224338e+09  1.09   -1.06  -19.50    0.10
168  2023-09-11  1808.00  1822.17  1840.00  1808.00   15926  2.902618e+09  1.76    0.20    3.67    0.13
169  2023-09-12  1826.60  1819.96  1826.98  1816.02   12168  2.214514e+09  0.60   -0.12   -2.21    0.10
170  2023-09-13  1829.92  1819.91  1829.92  1800.05   19501  3.540584e+09  1.64    0.00   -0.05    0.16
171  2023-09-14  1822.53  1818.69  1826.98  1806.00   17505  3.180448e+09  1.15   -0.07   -1.22    0.14
172  2023-09-15  1819.00  1781.99  1819.78  1781.30   28431  5.105749e+09  2.12   -2.02  -36.70    0.23
173  2023-09-18  1776.31  1829.20  1829.50  1773.00   32559  5.905121e+09  3.17    2.65   47.21    0.26
174  2023-09-19  1822.20  1826.94  1829.00  1808.00   14990  2.727859e+09  1.15   -0.12   -2.26    0.12
175  2023-09-20  1822.00  1824.00  1830.00  1818.05   12502  2.281584e+09  0.65   -0.16   -2.94    0.10
176  2023-09-21  1818.01  1798.39  1822.00  1798.39   19489  3.521487e+09  1.29   -1.40  -25.61    0.16
177  2023-09-22  1805.63  1849.00  1849.96  1792.41   34390  6.287833e+09  3.20    2.81   50.61    0.27
178  2023-09-25  1847.50  1832.38  1848.00  1826.59   13979  2.565774e+09  1.16   -0.90  -16.62    0.11
179  2023-09-26  1828.00  1816.00  1834.88  1813.10   15762  2.870852e+09  1.19   -0.89  -16.38    0.13
180  2023-09-27  1815.00  1814.00  1833.50  1802.80   20880  3.791876e+09  1.69   -0.11   -2.00    0.17
181  2023-09-28  1824.98  1798.55  1824.98  1797.80   20538  3.704813e+09  1.50   -0.85  -15.45    0.16
182  2023-10-09  1796.94  1777.00  1796.94  1764.90   29763  5.279950e+09  1.78   -1.20  -21.55    0.24
183  2023-10-10  1782.89  1770.00  1798.98  1768.00   20284  3.615557e+09  1.74   -0.39   -7.00    0.16
184  2023-10-11  1784.65  1778.50  1784.65  1768.00   21945  3.896569e+09  0.94    0.48    8.50    0.17
185  2023-10-12  1797.90  1786.00  1798.23  1777.20   14865  2.657096e+09  1.18    0.42    7.50    0.12
186  2023-10-13  1770.88  1751.00  1778.01  1738.19   25028  4.387688e+09  2.23   -1.96  -35.00    0.20
187  2023-10-16  1750.98  1729.90  1756.00  1722.45   20790  3.603605e+09  1.92   -1.21  -21.10    0.17
188  2023-10-17  1739.00  1726.00  1739.44  1716.00   14945  2.577312e+09  1.35   -0.23   -3.90    0.12
189  2023-10-18  1718.80  1728.00  1742.00  1717.18   20318  3.511988e+09  1.44    0.12    2.00    0.16
190  2023-10-19  1700.00  1630.00  1700.03  1626.03   73492  1.214692e+10  4.28   -5.67  -98.00    0.59

In [20]:

start_Date = '20230103'
end_Date = '20231124'
for CodeDes in code_list.values:
    ak_code, ak_name = CodeDes[1],CodeDes[2]
    print(ak_code,ak_name)
    if check(ak_code):
        print(True)
        continue
    try:
        stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=ak_code[2:], start_date=start_Date, end_date=end_Date, period='daily', adjust='')
    except Exception as e:
        print(e)
        continue
    stock_zh_a_hist_df['Date_ID'] = stock_zh_a_hist_df['日期'].apply(lambda x:x.strftime("%Y%m%d")).astype(int)
    stock_zh_a_hist_df['FSD_ID'] = stock_zh_a_hist_df['Date_ID']*1000000+int(ak_code[2:])
    stock_zh_a_hist_df['Stock_ID'] = ak_code
    stock_zh_a_hist_df.rename(columns = {'日期':'Date','开盘':'Open','收盘':'Close','最高':'High','最低':'Low',
                                                '成交量':'Volume','成交额':'Turnover','振幅':'Amplitude',
                                         '涨跌幅':'Percent_Of_Incre_Decre','涨跌额':'Amount_Of_Incre_Decre','换手率':'Turnover_Rate'},inplace = True)
    stock_zh_a_hist_df = stock_zh_a_hist_df[['FSD_ID','Stock_ID','Date_ID','Open','High','Low','Volume',
                                             'Turnover','Amplitude','Percent_Of_Incre_Decre','Amount_Of_Incre_Decre','Turnover_Rate']]
    path=create_path(ak_code)
    print(path)
    #result.append(stock_zh_a_hist_df)
    stock_zh_a_hist_df.to_csv(path, index=False, mode='w',encoding='gbk')

bj430017 星昊医药
./Stock_Daily/bj430017.csv
bj430047 诺思兰德
./Stock_Daily/bj430047.csv
bj430090 同辉信息
./Stock_Daily/bj430090.csv
bj430139 华岭股份
./Stock_Daily/bj430139.csv
bj430198 微创光电
./Stock_Daily/bj430198.csv
bj430300 辰光医疗
./Stock_Daily/bj430300.csv
bj430418 苏轴股份
./Stock_Daily/bj430418.csv
bj430425 乐创技术
./Stock_Daily/bj430425.csv
bj430476 海能技术
./Stock_Daily/bj430476.csv
bj430478 峆一药业
./Stock_Daily/bj430478.csv
bj430489 佳先股份
./Stock_Daily/bj430489.csv
bj430510 丰光精密
./Stock_Daily/bj430510.csv
bj430556 雅达股份
./Stock_Daily/bj430556.csv
bj430564 天润科技
./Stock_Daily/bj430564.csv
bj430685 新芝生物
./Stock_Daily/bj430685.csv
bj430718 合肥高科
./Stock_Daily/bj430718.csv
bj830779 武汉蓝电
./Stock_Daily/bj830779.csv
bj830799 艾融软件
./Stock_Daily/bj830799.csv
bj830809 安达科技
./Stock_Daily/bj830809.csv
bj830832 齐鲁华信
./Stock_Daily/bj830832.csv
bj830839 万通液压
./Stock_Daily/bj830839.csv
bj830879 基康仪器
./Stock_Daily/bj830879.csv
bj830896 旺成科技
./Stock_Daily/bj830896.csv
bj830946 森萱医药
./Stock_Daily/bj830946.csv
bj830964 润农节水
./Stock_Daily/bj830964.csv
bj830974 凯大催化
./Stock_Daily/bj830974.csv
bj831010 凯添燃气
./Stock_Daily/bj831010.csv
bj831039 国义招标
./Stock_Daily/bj831039.csv
bj831087 秋乐种业
./Stock_Daily/bj831087.csv
bj831152 昆工科技
./Stock_Daily/bj831152.csv
bj831167 鑫汇科
./Stock_Daily/bj831167.csv
bj831195 三祥科技
./Stock_Daily/bj831195.csv
bj831278 泰德股份
./Stock_Daily/bj831278.csv
bj831304 迪尔化工
./Stock_Daily/bj831304.csv
bj831305 海希通讯
./Stock_Daily/bj831305.csv
bj831370 新安洁
./Stock_Daily/bj831370.csv
bj831445 龙竹科技
./Stock_Daily/bj831445.csv
bj831526 凯华材料
./Stock_Daily/bj831526.csv
bj831627 力王股份
./Stock_Daily/bj831627.csv
bj831641 格利尔
./Stock_Daily/bj831641.csv
bj831689 克莱特
./Stock_Daily/bj831689.csv
bj831726 朱老六
./Stock_Daily/bj831726.csv
bj831768 拾比佰
./Stock_Daily/bj831768.csv
bj831832 科达自控
./Stock_Daily/bj831832.csv
bj831834 三维股份
./Stock_Daily/bj831834.csv
bj831855 浙江大农
./Stock_Daily/bj831855.csv
bj831856 浩淼科技
./Stock_Daily/bj831856.csv
bj831906 舜宇精工
./Stock_Daily/bj831906.csv
bj831961 创远信科
./Stock_Daily/bj831961.csv
bj832000 安徽凤凰
./Stock_Daily/bj832000.csv
bj832023 田野股份
./Stock_Daily/bj832023.csv
bj832089 禾昌聚合
./Stock_Daily/bj832089.csv
bj832110 雷特科技
./Stock_Daily/bj832110.csv
bj832145 恒合股份
./Stock_Daily/bj832145.csv
bj832149 利尔达
./Stock_Daily/bj832149.csv
bj832171 志晟信息
./Stock_Daily/bj832171.csv
bj832175 东方碳素
./Stock_Daily/bj832175.csv
bj832225 利通科技
./Stock_Daily/bj832225.csv
bj832278 鹿得医疗
./Stock_Daily/bj832278.csv
bj832419 路斯股份
./Stock_Daily/bj832419.csv
bj832469 富恒新材
./Stock_Daily/bj832469.csv
bj832471 美邦科技
./Stock_Daily/bj832471.csv
bj832491 奥迪威
./Stock_Daily/bj832491.csv
bj832522 纳科诺尔
./Stock_Daily/bj832522.csv
bj832566 梓橦宫
./Stock_Daily/bj832566.csv
bj832651 天罡股份
./Stock_Daily/bj832651.csv
bj832662 方盛股份
./Stock_Daily/bj832662.csv
bj832735 德源药业
./Stock_Daily/bj832735.csv
bj832786 骑士乳业
./Stock_Daily/bj832786.csv
bj832802 保丽洁
./Stock_Daily/bj832802.csv
bj832876 慧为智能
./Stock_Daily/bj832876.csv
bj832885 星辰科技
./Stock_Daily/bj832885.csv
bj832978 开特股份
./Stock_Daily/bj832978.csv
bj832982 锦波生物
./Stock_Daily/bj832982.csv
bj833030 立方控股
./Stock_Daily/bj833030.csv
bj833075 柏星龙
./Stock_Daily/bj833075.csv
bj833171 国航远洋
./Stock_Daily/bj833171.csv
bj833230 欧康医药
./Stock_Daily/bj833230.csv
bj833266 生物谷
./Stock_Daily/bj833266.csv
bj833346 威贸电子
./Stock_Daily/bj833346.csv
bj833394 民士达
./Stock_Daily/bj833394.csv
bj833427 华维设计
./Stock_Daily/bj833427.csv
bj833429 康比特
./Stock_Daily/bj833429.csv
bj833454 同心传动
./Stock_Daily/bj833454.csv
bj833455 汇隆活塞
./Stock_Daily/bj833455.csv
bj833509 同惠电子
./Stock_Daily/bj833509.csv
bj833523 德瑞锂电
./Stock_Daily/bj833523.csv
bj833533 骏创科技
./Stock_Daily/bj833533.csv
bj833575 康乐卫士
./Stock_Daily/bj833575.csv
bj833580 科创新材
./Stock_Daily/bj833580.csv
bj833751 惠同新材
./Stock_Daily/bj833751.csv
bj833781 瑞奇智造
./Stock_Daily/bj833781.csv
bj833819 颖泰生物
./Stock_Daily/bj833819.csv
bj833873 中设咨询
./Stock_Daily/bj833873.csv
bj833914 远航精密
./Stock_Daily/bj833914.csv
bj833943 优机股份
./Stock_Daily/bj833943.csv
bj834014 特瑞斯
./Stock_Daily/bj834014.csv
bj834021 流金科技
./Stock_Daily/bj834021.csv
bj834033 康普化学
./Stock_Daily/bj834033.csv
bj834058 华洋赛车
./Stock_Daily/bj834058.csv
bj834062 科润智控
./Stock_Daily/bj834062.csv
bj834261 一诺威
./Stock_Daily/bj834261.csv
bj834407 驰诚股份
./Stock_Daily/bj834407.csv
bj834415 恒拓开源
./Stock_Daily/bj834415.csv
bj834475 三友科技
./Stock_Daily/bj834475.csv
bj834599 同力股份
./Stock_Daily/bj834599.csv
bj834639 晨光电缆
./Stock_Daily/bj834639.csv
bj834682 球冠电缆
./Stock_Daily/bj834682.csv
bj834765 美之高
./Stock_Daily/bj834765.csv
bj834770 艾能聚
./Stock_Daily/bj834770.csv
bj834950 迅安科技
./Stock_Daily/bj834950.csv
bj835174 五新隧装
./Stock_Daily/bj835174.csv
bj835179 凯德石英
./Stock_Daily/bj835179.csv
bj835184 国源科技
./Stock_Daily/bj835184.csv
bj835185 贝特瑞
./Stock_Daily/bj835185.csv
bj835207 众诚科技
./Stock_Daily/bj835207.csv
bj835237 力佳科技
./Stock_Daily/bj835237.csv
bj835305 云创数据
./Stock_Daily/bj835305.csv
bj835368 连城数控
./Stock_Daily/bj835368.csv
bj835508 殷图网联
./Stock_Daily/bj835508.csv
bj835640 富士达
./Stock_Daily/bj835640.csv
bj835670 数字人
./Stock_Daily/bj835670.csv
bj835857 百甲科技
./Stock_Daily/bj835857.csv
bj835892 中科美菱
./Stock_Daily/bj835892.csv
bj835985 海泰新能
./Stock_Daily/bj835985.csv
bj836077 吉林碳谷
./Stock_Daily/bj836077.csv
bj836149 旭杰科技
./Stock_Daily/bj836149.csv
bj836208 青矩技术
./Stock_Daily/bj836208.csv
bj836221 易实精密
./Stock_Daily/bj836221.csv
bj836239 长虹能源
./Stock_Daily/bj836239.csv
bj836247 华密新材
./Stock_Daily/bj836247.csv
bj836260 中寰股份
./Stock_Daily/bj836260.csv
bj836263 中航泰达
./Stock_Daily/bj836263.csv
bj836270 天铭科技
./Stock_Daily/bj836270.csv
bj836395 朗鸿科技
./Stock_Daily/bj836395.csv
bj836414 欧普泰
./Stock_Daily/bj836414.csv
bj836419 万德股份
./Stock_Daily/bj836419.csv
bj836422 润普食品
./Stock_Daily/bj836422.csv
bj836433 大唐药业
./Stock_Daily/bj836433.csv
bj836504 博迅生物
./Stock_Daily/bj836504.csv
bj836675 秉扬科技
./Stock_Daily/bj836675.csv
bj836699 海达尔
./Stock_Daily/bj836699.csv
bj836717 瑞星股份
./Stock_Daily/bj836717.csv
bj836720 吉冈精密
./Stock_Daily/bj836720.csv
bj836807 奔朗新材
./Stock_Daily/bj836807.csv
bj836826 盖世食品
./Stock_Daily/bj836826.csv
bj836871 派特尔
./Stock_Daily/bj836871.csv
bj836892 广咨国际
./Stock_Daily/bj836892.csv
bj836942 恒立钻具
./Stock_Daily/bj836942.csv
bj836957 汉维科技
./Stock_Daily/bj836957.csv
bj837006 晟楠科技
./Stock_Daily/bj837006.csv
bj837046 亿能电力
./Stock_Daily/bj837046.csv
bj837092 汉鑫科技
./Stock_Daily/bj837092.csv
bj837174 宏裕包材
./Stock_Daily/bj837174.csv
bj837212 智新电子
./Stock_Daily/bj837212.csv
bj837242 建邦科技
./Stock_Daily/bj837242.csv
bj837344 三元基因
./Stock_Daily/bj837344.csv
bj837592 华信永道
./Stock_Daily/bj837592.csv
bj837663 明阳科技
./Stock_Daily/bj837663.csv
bj837748 路桥信息
./Stock_Daily/bj837748.csv
bj837821 则成电子
./Stock_Daily/bj837821.csv
bj838030 德众汽车
./Stock_Daily/bj838030.csv
bj838163 方大新材
./Stock_Daily/bj838163.csv
bj838171 邦德股份
./Stock_Daily/bj838171.csv
bj838227 美登科技
./Stock_Daily/bj838227.csv
bj838262 太湖雪
./Stock_Daily/bj838262.csv
bj838275 驱动力
./Stock_Daily/bj838275.csv
bj838402 硅烷科技
./Stock_Daily/bj838402.csv
bj838670 恒进感应
./Stock_Daily/bj838670.csv
bj838701 豪声电子
./Stock_Daily/bj838701.csv
bj838810 春光药装
./Stock_Daily/bj838810.csv
bj838837 华原股份
./Stock_Daily/bj838837.csv
bj838924 广脉科技
./Stock_Daily/bj838924.csv
bj838971 天马新材
./Stock_Daily/bj838971.csv
bj839167 同享科技
./Stock_Daily/bj839167.csv
bj839273 一致魔芋
./Stock_Daily/bj839273.csv
bj839371 欧福蛋业
./Stock_Daily/bj839371.csv
bj839493 并行科技
./Stock_Daily/bj839493.csv
bj839680 广道数字
./Stock_Daily/bj839680.csv
bj839719 宁新新材
./Stock_Daily/bj839719.csv
bj839725 惠丰钻石
./Stock_Daily/bj839725.csv
bj839729 永顺生物
./Stock_Daily/bj839729.csv
bj839790 联迪信息
./Stock_Daily/bj839790.csv
bj839792 东和新材
./Stock_Daily/bj839792.csv
bj839946 华阳变速
./Stock_Daily/bj839946.csv
bj870199 倍益康
./Stock_Daily/bj870199.csv
bj870204 沪江材料
./Stock_Daily/bj870204.csv
bj870299 灿能电力
./Stock_Daily/bj870299.csv
bj870357 雅葆轩
./Stock_Daily/bj870357.csv
bj870436 大地电气
./Stock_Daily/bj870436.csv
bj870508 丰安股份
./Stock_Daily/bj870508.csv
bj870726 鸿智科技
./Stock_Daily/bj870726.csv
bj870866 绿亨科技
./Stock_Daily/bj870866.csv
bj870976 视声智能
./Stock_Daily/bj870976.csv
bj871245 威博液压
./Stock_Daily/bj871245.csv
bj871396 常辅股份
./Stock_Daily/bj871396.csv
bj871478 巨能股份
./Stock_Daily/bj871478.csv
bj871553 凯腾精工
./Stock_Daily/bj871553.csv
bj871634 新威凌
./Stock_Daily/bj871634.csv
bj871642 通易航天
./Stock_Daily/bj871642.csv
bj871694 中裕科技
./Stock_Daily/bj871694.csv
bj871753 天纺标
./Stock_Daily/bj871753.csv
bj871857 泓禧科技
./Stock_Daily/bj871857.csv
bj871970 大禹生物
./Stock_Daily/bj871970.csv
bj871981 晶赛科技
./Stock_Daily/bj871981.csv
bj872190 雷神科技
./Stock_Daily/bj872190.csv
bj872351 华光源海
./Stock_Daily/bj872351.csv
bj872374 云里物里
./Stock_Daily/bj872374.csv
bj872392 佳合科技
./Stock_Daily/bj872392.csv
bj872541 铁大科技
./Stock_Daily/bj872541.csv
bj872808 曙光数创
./Stock_Daily/bj872808.csv
bj872895 花溪科技
./Stock_Daily/bj872895.csv
bj872925 锦好医疗
./Stock_Daily/bj872925.csv
bj872953 国子软件
./Stock_Daily/bj872953.csv
bj873001 纬达光电
./Stock_Daily/bj873001.csv
bj873122 中纺标
./Stock_Daily/bj873122.csv
bj873132 泰鹏智能
./Stock_Daily/bj873132.csv
bj873152 天宏锂电
./Stock_Daily/bj873152.csv
bj873167 新赣江
./Stock_Daily/bj873167.csv
bj873169 七丰精工
./Stock_Daily/bj873169.csv
bj873223 荣亿精密
./Stock_Daily/bj873223.csv
bj873305 九菱科技
./Stock_Daily/bj873305.csv
bj873339 恒太照明
./Stock_Daily/bj873339.csv
bj873527 夜光明
./Stock_Daily/bj873527.csv
bj873576 天力复合
./Stock_Daily/bj873576.csv
bj873593 鼎智科技
./Stock_Daily/bj873593.csv
bj873665 科强股份
./Stock_Daily/bj873665.csv
bj873679 前进科技
./Stock_Daily/bj873679.csv
bj873693 阿为特
./Stock_Daily/bj873693.csv
bj873726 卓兆点胶
./Stock_Daily/bj873726.csv
bj873833 美心翼申
./Stock_Daily/bj873833.csv
sh600000 浦发银行
./Stock_Daily/sh600000.csv
sh600004 白云机场
./Stock_Daily/sh600004.csv
sh600006 东风汽车
./Stock_Daily/sh600006.csv
sh600007 中国国贸
./Stock_Daily/sh600007.csv
sh600008 首创环保
./Stock_Daily/sh600008.csv
sh600009 上海机场
./Stock_Daily/sh600009.csv
sh600010 包钢股份
./Stock_Daily/sh600010.csv
sh600011 华能国际
./Stock_Daily/sh600011.csv
sh600012 皖通高速
./Stock_Daily/sh600012.csv
sh600015 华夏银行
./Stock_Daily/sh600015.csv
sh600016 民生银行
./Stock_Daily/sh600016.csv
sh600017 日照港
./Stock_Daily/sh600017.csv
sh600018 上港集团
./Stock_Daily/sh600018.csv
sh600019 宝钢股份
./Stock_Daily/sh600019.csv
sh600020 中原高速
./Stock_Daily/sh600020.csv
sh600021 上海电力
./Stock_Daily/sh600021.csv
sh600022 山东钢铁
./Stock_Daily/sh600022.csv
sh600023 浙能电力
./Stock_Daily/sh600023.csv
sh600025 华能水电
./Stock_Daily/sh600025.csv
sh600026 中远海能
./Stock_Daily/sh600026.csv
sh600027 华电国际
./Stock_Daily/sh600027.csv
sh600028 中国石化
./Stock_Daily/sh600028.csv
sh600029 南方航空
./Stock_Daily/sh600029.csv
sh600030 中信证券
./Stock_Daily/sh600030.csv
sh600031 三一重工
./Stock_Daily/sh600031.csv
sh600032 浙江新能
./Stock_Daily/sh600032.csv
sh600033 福建高速
./Stock_Daily/sh600033.csv
sh600035 楚天高速
./Stock_Daily/sh600035.csv
sh600036 招商银行
./Stock_Daily/sh600036.csv
sh600037 歌华有线
./Stock_Daily/sh600037.csv
sh600038 中直股份
./Stock_Daily/sh600038.csv
sh600039 四川路桥
./Stock_Daily/sh600039.csv
sh600048 保利发展
./Stock_Daily/sh600048.csv
sh600050 中国联通
./Stock_Daily/sh600050.csv
sh600051 宁波联合
./Stock_Daily/sh600051.csv
sh600052 东望时代
./Stock_Daily/sh600052.csv
sh600053 九鼎投资
./Stock_Daily/sh600053.csv
sh600054 黄山旅游
./Stock_Daily/sh600054.csv
sh600055 万东医疗
./Stock_Daily/sh600055.csv
sh600056 中国医药
./Stock_Daily/sh600056.csv
sh600057 厦门象屿
./Stock_Daily/sh600057.csv
sh600058 五矿发展
./Stock_Daily/sh600058.csv
sh600059 古越龙山
./Stock_Daily/sh600059.csv
sh600060 海信视像
./Stock_Daily/sh600060.csv
sh600061 国投资本
./Stock_Daily/sh600061.csv
sh600062 华润双鹤
./Stock_Daily/sh600062.csv
sh600063 皖维高新
./Stock_Daily/sh600063.csv
sh600064 南京高科
./Stock_Daily/sh600064.csv
sh600066 宇通客车
./Stock_Daily/sh600066.csv
sh600067 冠城大通
./Stock_Daily/sh600067.csv
sh600070 ST富润
./Stock_Daily/sh600070.csv
sh600071 凤凰光学
./Stock_Daily/sh600071.csv
sh600072 中船科技
./Stock_Daily/sh600072.csv
sh600073 上海梅林
./Stock_Daily/sh600073.csv
sh600075 新疆天业
./Stock_Daily/sh600075.csv
sh600076 康欣新材
./Stock_Daily/sh600076.csv
sh600078 ST澄星
./Stock_Daily/sh600078.csv
sh600079 人福医药
./Stock_Daily/sh600079.csv
sh600080 金花股份
./Stock_Daily/sh600080.csv
sh600081 东风科技
./Stock_Daily/sh600081.csv
sh600082 海泰发展
./Stock_Daily/sh600082.csv
sh600083 博信股份
./Stock_Daily/sh600083.csv
sh600084 中信尼雅
./Stock_Daily/sh600084.csv
sh600085 同仁堂
./Stock_Daily/sh600085.csv
sh600088 中视传媒
./Stock_Daily/sh600088.csv
sh600089 特变电工
./Stock_Daily/sh600089.csv
sh600094 大名城
./Stock_Daily/sh600094.csv
sh600095 湘财股份
./Stock_Daily/sh600095.csv
sh600096 云天化
./Stock_Daily/sh600096.csv
sh600097 开创国际
./Stock_Daily/sh600097.csv
sh600098 广州发展
./Stock_Daily/sh600098.csv
sh600099 林海股份
./Stock_Daily/sh600099.csv
sh600100 同方股份
./Stock_Daily/sh600100.csv
sh600101 明星电力
./Stock_Daily/sh600101.csv
sh600103 青山纸业
./Stock_Daily/sh600103.csv
sh600104 上汽集团
./Stock_Daily/sh600104.csv
sh600105 永鼎股份
./Stock_Daily/sh600105.csv
sh600106 重庆路桥
./Stock_Daily/sh600106.csv
sh600107 美尔雅
./Stock_Daily/sh600107.csv
sh600108 亚盛集团
./Stock_Daily/sh600108.csv
sh600109 国金证券
./Stock_Daily/sh600109.csv
sh600110 诺德股份
./Stock_Daily/sh600110.csv
sh600111 北方稀土
./Stock_Daily/sh600111.csv
sh600112 ST天成
./Stock_Daily/sh600112.csv
sh600113 浙江东日
./Stock_Daily/sh600113.csv
sh600114 东睦股份
./Stock_Daily/sh600114.csv
sh600115 中国东航
./Stock_Daily/sh600115.csv
sh600116 三峡水利
./Stock_Daily/sh600116.csv
sh600117 *ST西钢
./Stock_Daily/sh600117.csv
sh600118 中国卫星
./Stock_Daily/sh600118.csv
sh600119 长江投资
./Stock_Daily/sh600119.csv
sh600120 浙江东方
./Stock_Daily/sh600120.csv
sh600121 郑州煤电
./Stock_Daily/sh600121.csv
sh600123 兰花科创
./Stock_Daily/sh600123.csv
sh600125 铁龙物流
./Stock_Daily/sh600125.csv
sh600126 杭钢股份
./Stock_Daily/sh600126.csv
sh600127 金健米业
./Stock_Daily/sh600127.csv
sh600128 苏豪弘业
./Stock_Daily/sh600128.csv
sh600129 太极集团
./Stock_Daily/sh600129.csv
sh600130 波导股份
./Stock_Daily/sh600130.csv
sh600131 国网信通
./Stock_Daily/sh600131.csv
sh600132 重庆啤酒
./Stock_Daily/sh600132.csv
sh600133 东湖高新
./Stock_Daily/sh600133.csv
sh600135 乐凯胶片
./Stock_Daily/sh600135.csv
sh600136 *ST明诚
./Stock_Daily/sh600136.csv
sh600137 浪莎股份
./Stock_Daily/sh600137.csv
sh600138 中青旅
./Stock_Daily/sh600138.csv
sh600141 兴发集团
./Stock_Daily/sh600141.csv
sh600143 金发科技
./Stock_Daily/sh600143.csv
sh600148 长春一东
./Stock_Daily/sh600148.csv
sh600149 廊坊发展
./Stock_Daily/sh600149.csv
sh600150 中国船舶
./Stock_Daily/sh600150.csv
sh600151 航天机电
./Stock_Daily/sh600151.csv
sh600152 维科技术
./Stock_Daily/sh600152.csv
sh600153 建发股份
./Stock_Daily/sh600153.csv
sh600155 华创云信
./Stock_Daily/sh600155.csv
sh600156 华升股份
./Stock_Daily/sh600156.csv
sh600157 永泰能源
./Stock_Daily/sh600157.csv
sh600158 中体产业
./Stock_Daily/sh600158.csv
sh600159 大龙地产
./Stock_Daily/sh600159.csv
sh600160 巨化股份
./Stock_Daily/sh600160.csv
sh600161 天坛生物
./Stock_Daily/sh600161.csv
sh600162 香江控股
./Stock_Daily/sh600162.csv
sh600163 中闽能源
./Stock_Daily/sh600163.csv
sh600165 宁科生物
./Stock_Daily/sh600165.csv
sh600166 福田汽车
./Stock_Daily/sh600166.csv
sh600167 联美控股
./Stock_Daily/sh600167.csv
sh600168 武汉控股
./Stock_Daily/sh600168.csv
sh600169 太原重工
./Stock_Daily/sh600169.csv
sh600170 上海建工
./Stock_Daily/sh600170.csv
sh600171 上海贝岭
./Stock_Daily/sh600171.csv
sh600172 黄河旋风
./Stock_Daily/sh600172.csv
sh600173 卧龙地产
./Stock_Daily/sh600173.csv
sh600176 中国巨石
./Stock_Daily/sh600176.csv
sh600177 雅戈尔
./Stock_Daily/sh600177.csv
sh600178 东安动力
./Stock_Daily/sh600178.csv
sh600179 安通控股
./Stock_Daily/sh600179.csv
sh600180 瑞茂通
./Stock_Daily/sh600180.csv
sh600182 S佳通
./Stock_Daily/sh600182.csv
sh600183 生益科技
./Stock_Daily/sh600183.csv
sh600184 光电股份
./Stock_Daily/sh600184.csv
sh600185 格力地产
./Stock_Daily/sh600185.csv
sh600186 莲花健康
./Stock_Daily/sh600186.csv
sh600187 国中水务
./Stock_Daily/sh600187.csv
sh600188 兖矿能源
./Stock_Daily/sh600188.csv
sh600189 泉阳泉
./Stock_Daily/sh600189.csv
sh600190 锦州港
./Stock_Daily/sh600190.csv
sh600191 华资实业
./Stock_Daily/sh600191.csv
sh600192 长城电工
./Stock_Daily/sh600192.csv
sh600193 创兴资源
./Stock_Daily/sh600193.csv
sh600195 中牧股份
./Stock_Daily/sh600195.csv
sh600196 复星医药
./Stock_Daily/sh600196.csv
sh600197 伊力特
./Stock_Daily/sh600197.csv
sh600198 大唐电信
./Stock_Daily/sh600198.csv
sh600199 金种子酒
./Stock_Daily/sh600199.csv
sh600200 江苏吴中
./Stock_Daily/sh600200.csv
sh600201 生物股份
./Stock_Daily/sh600201.csv
sh600202 哈空调
./Stock_Daily/sh600202.csv
sh600203 福日电子
./Stock_Daily/sh600203.csv
sh600206 有研新材
./Stock_Daily/sh600206.csv
sh600207 安彩高科
./Stock_Daily/sh600207.csv
sh600208 新湖中宝
./Stock_Daily/sh600208.csv
sh600210 紫江企业
./Stock_Daily/sh600210.csv
sh600211 西藏药业
./Stock_Daily/sh600211.csv
sh600212 绿能慧充
./Stock_Daily/sh600212.csv
sh600213 亚星客车
./Stock_Daily/sh600213.csv
sh600215 派斯林
./Stock_Daily/sh600215.csv
sh600216 浙江医药
./Stock_Daily/sh600216.csv
sh600217 中再资环
./Stock_Daily/sh600217.csv
sh600218 全柴动力
./Stock_Daily/sh600218.csv
sh600219 南山铝业
./Stock_Daily/sh600219.csv
sh600220 江苏阳光
./Stock_Daily/sh600220.csv
sh600221 海航控股
./Stock_Daily/sh600221.csv
sh600222 太龙药业
./Stock_Daily/sh600222.csv
sh600223 福瑞达
./Stock_Daily/sh600223.csv
sh600225 卓朗科技
./Stock_Daily/sh600225.csv
sh600226 瀚叶股份
./Stock_Daily/sh600226.csv
sh600227 赤天化
./Stock_Daily/sh600227.csv
sh600228 返利科技
./Stock_Daily/sh600228.csv
sh600229 城市传媒
./Stock_Daily/sh600229.csv
sh600230 沧州大化
./Stock_Daily/sh600230.csv
sh600231 凌钢股份
./Stock_Daily/sh600231.csv
sh600232 金鹰股份
./Stock_Daily/sh600232.csv
sh600233 圆通速递
./Stock_Daily/sh600233.csv
sh600234 科新发展
./Stock_Daily/sh600234.csv
sh600235 民丰特纸
./Stock_Daily/sh600235.csv
sh600236 桂冠电力
./Stock_Daily/sh600236.csv
sh600237 铜峰电子
./Stock_Daily/sh600237.csv
sh600238 海南椰岛
./Stock_Daily/sh600238.csv
sh600239 云南城投
./Stock_Daily/sh600239.csv
sh600241 时代万恒
./Stock_Daily/sh600241.csv
sh600243 青海华鼎
./Stock_Daily/sh600243.csv
sh600246 万通发展
./Stock_Daily/sh600246.csv
sh600248 陕建股份
./Stock_Daily/sh600248.csv
sh600249 两面针
./Stock_Daily/sh600249.csv
sh600250 南纺股份
./Stock_Daily/sh600250.csv
sh600251 冠农股份
./Stock_Daily/sh600251.csv
sh600252 中恒集团
./Stock_Daily/sh600252.csv
sh600255 鑫科材料
./Stock_Daily/sh600255.csv
sh600256 广汇能源
./Stock_Daily/sh600256.csv
sh600257 大湖股份
./Stock_Daily/sh600257.csv
sh600258 首旅酒店
./Stock_Daily/sh600258.csv
sh600259 广晟有色
./Stock_Daily/sh600259.csv
sh600261 阳光照明
./Stock_Daily/sh600261.csv
sh600262 北方股份
./Stock_Daily/sh600262.csv
sh600265 ST景谷
./Stock_Daily/sh600265.csv
sh600266 城建发展
./Stock_Daily/sh600266.csv
sh600267 海正药业
./Stock_Daily/sh600267.csv
sh600268 国电南自
./Stock_Daily/sh600268.csv
sh600269 赣粤高速
./Stock_Daily/sh600269.csv
sh600271 航天信息
./Stock_Daily/sh600271.csv
sh600272 开开实业
./Stock_Daily/sh600272.csv
sh600273 嘉化能源
./Stock_Daily/sh600273.csv
sh600276 恒瑞医药
./Stock_Daily/sh600276.csv
sh600277 亿利洁能
./Stock_Daily/sh600277.csv
sh600278 东方创业
./Stock_Daily/sh600278.csv
sh600279 重庆港
./Stock_Daily/sh600279.csv
sh600280 中央商场
./Stock_Daily/sh600280.csv
sh600281 华阳新材
./Stock_Daily/sh600281.csv
sh600282 南钢股份
./Stock_Daily/sh600282.csv
sh600283 钱江水利
./Stock_Daily/sh600283.csv
sh600284 浦东建设
./Stock_Daily/sh600284.csv
sh600285 羚锐制药
./Stock_Daily/sh600285.csv
sh600287 江苏舜天
./Stock_Daily/sh600287.csv
sh600288 大恒科技
./Stock_Daily/sh600288.csv
sh600289 ST信通
./Stock_Daily/sh600289.csv
sh600290 *ST华仪
./Stock_Daily/sh600290.csv
sh600292 远达环保
./Stock_Daily/sh600292.csv
sh600293 三峡新材
./Stock_Daily/sh600293.csv
sh600295 鄂尔多斯
./Stock_Daily/sh600295.csv
sh600297 广汇汽车
./Stock_Daily/sh600297.csv
sh600298 安琪酵母
./Stock_Daily/sh600298.csv
sh600299 安迪苏
./Stock_Daily/sh600299.csv
sh600300 维维股份
./Stock_Daily/sh600300.csv
sh600301 华锡有色
./Stock_Daily/sh600301.csv
sh600302 标准股份
./Stock_Daily/sh600302.csv
sh600303 ST曙光
./Stock_Daily/sh600303.csv
sh600305 恒顺醋业
./Stock_Daily/sh600305.csv
sh600306 *ST商城
./Stock_Daily/sh600306.csv
sh600307 酒钢宏兴
./Stock_Daily/sh600307.csv
sh600308 华泰股份
./Stock_Daily/sh600308.csv
sh600309 万华化学
./Stock_Daily/sh600309.csv
sh600310 广西能源
./Stock_Daily/sh600310.csv
sh600312 平高电气
./Stock_Daily/sh600312.csv
sh600313 农发种业
./Stock_Daily/sh600313.csv
sh600315 上海家化
./Stock_Daily/sh600315.csv
sh600316 洪都航空
./Stock_Daily/sh600316.csv
sh600318 新力金融
./Stock_Daily/sh600318.csv
sh600319 亚星化学
./Stock_Daily/sh600319.csv
sh600320 振华重工
./Stock_Daily/sh600320.csv
sh600321 正源股份
./Stock_Daily/sh600321.csv
sh600322 津投城开
./Stock_Daily/sh600322.csv
sh600323 瀚蓝环境
./Stock_Daily/sh600323.csv
sh600325 华发股份
./Stock_Daily/sh600325.csv
sh600326 西藏天路
./Stock_Daily/sh600326.csv
sh600327 大东方
./Stock_Daily/sh600327.csv
sh600328 中盐化工
./Stock_Daily/sh600328.csv
sh600329 达仁堂
./Stock_Daily/sh600329.csv

./Stock_Daily/bj871753.csv
bj871857 泓禧科技
./Stock_Daily/bj871857.csv
bj871970 大禹生物
./Stock_Daily/bj871970.csv
bj871981 晶赛科技
./Stock_Daily/bj871981.csv
bj872190 雷神科技
./Stock_Daily/bj872190.csv
bj872351 华光源海
./Stock_Daily/bj872351.csv
bj872374 云里物里
./Stock_Daily/bj872374.csv
bj872392 佳合科技
./Stock_Daily/bj872392.csv
bj872541 铁大科技
./Stock_Daily/bj872541.csv
bj872808 曙光数创
./Stock_Daily/bj872808.csv
bj872895 花溪科技
./Stock_Daily/bj872895.csv
bj872925 锦好医疗
./Stock_Daily/bj872925.csv
bj872953 国子软件
./Stock_Daily/bj872953.csv
bj873001 纬达光电
./Stock_Daily/bj873001.csv
bj873122 中纺标
./Stock_Daily/bj873122.csv
bj873132 泰鹏智能
./Stock_Daily/bj873132.csv
bj873152 天宏锂电
./Stock_Daily/bj873152.csv
bj873167 新赣江
./Stock_Daily/bj873167.csv
bj873169 七丰精工
./Stock_Daily/bj873169.csv
bj873223 荣亿精密
./Stock_Daily/bj873223.csv
bj873305 九菱科技
./Stock_Daily/bj873305.csv
bj873339 恒太照明
./Stock_Daily/bj873339.csv
bj873527 夜光明
./Stock_Daily/bj873527.csv
bj873576 天力复合
./Stock_Daily/bj873576.csv
bj873593 鼎智科技
./Stock_Daily/bj873593.csv
bj873665 科强股份
./Stock_Daily/bj873665.csv
bj873679 前进科技
./Stock_Daily/bj873679.csv
bj873693 阿为特
./Stock_Daily/bj873693.csv
bj873726 卓兆点胶
./Stock_Daily/bj873726.csv
bj873833 美心翼申
./Stock_Daily/bj873833.csv
sh600000 浦发银行
./Stock_Daily/sh600000.csv
sh600004 白云机场
./Stock_Daily/sh600004.csv
sh600006 东风汽车
./Stock_Daily/sh600006.csv
sh600007 中国国贸
./Stock_Daily/sh600007.csv
sh600008 首创环保
./Stock_Daily/sh600008.csv
sh600009 上海机场
./Stock_Daily/sh600009.csv
sh600010 包钢股份
./Stock_Daily/sh600010.csv
sh600011 华能国际
./Stock_Daily/sh600011.csv
sh600012 皖通高速
./Stock_Daily/sh600012.csv
sh600015 华夏银行
./Stock_Daily/sh600015.csv
sh600016 民生银行
./Stock_Daily/sh600016.csv
sh600017 日照港
./Stock_Daily/sh600017.csv
sh600018 上港集团
./Stock_Daily/sh600018.csv
sh600019 宝钢股份
./Stock_Daily/sh600019.csv
sh600020 中原高速
./Stock_Daily/sh600020.csv
sh600021 上海电力
./Stock_Daily/sh600021.csv
sh600022 山东钢铁
./Stock_Daily/sh600022.csv
sh600023 浙能电力
./Stock_Daily/sh600023.csv
sh600025 华能水电
./Stock_Daily/sh600025.csv
sh600026 中远海能
./Stock_Daily/sh600026.csv
sh600027 华电国际
./Stock_Daily/sh600027.csv
sh600028 中国石化
./Stock_Daily/sh600028.csv
sh600029 南方航空
./Stock_Daily/sh600029.csv
sh600030 中信证券
./Stock_Daily/sh600030.csv
sh600031 三一重工
./Stock_Daily/sh600031.csv
sh600032 浙江新能
./Stock_Daily/sh600032.csv
sh600033 福建高速
./Stock_Daily/sh600033.csv
sh600035 楚天高速
./Stock_Daily/sh600035.csv
sh600036 招商银行
./Stock_Daily/sh600036.csv
sh600037 歌华有线
./Stock_Daily/sh600037.csv
sh600038 中直股份
./Stock_Daily/sh600038.csv
sh600039 四川路桥
./Stock_Daily/sh600039.csv
sh600048 保利发展
./Stock_Daily/sh600048.csv
sh600050 中国联通
./Stock_Daily/sh600050.csv
sh600051 宁波联合
./Stock_Daily/sh600051.csv
sh600052 东望时代
./Stock_Daily/sh600052.csv
sh600053 九鼎投资
./Stock_Daily/sh600053.csv
sh600054 黄山旅游
./Stock_Daily/sh600054.csv
sh600055 万东医疗
./Stock_Daily/sh600055.csv
sh600056 中国医药
./Stock_Daily/sh600056.csv
sh600057 厦门象屿
./Stock_Daily/sh600057.csv
sh600058 五矿发展
./Stock_Daily/sh600058.csv
sh600059 古越龙山
./Stock_Daily/sh600059.csv
sh600060 海信视像
./Stock_Daily/sh600060.csv
sh600061 国投资本
./Stock_Daily/sh600061.csv
sh600062 华润双鹤
./Stock_Daily/sh600062.csv
sh600063 皖维高新
./Stock_Daily/sh600063.csv
sh600064 南京高科
./Stock_Daily/sh600064.csv
sh600066 宇通客车
./Stock_Daily/sh600066.csv
sh600067 冠城大通
./Stock_Daily/sh600067.csv
sh600070 ST富润
./Stock_Daily/sh600070.csv
sh600071 凤凰光学
./Stock_Daily/sh600071.csv
sh600072 中船科技
./Stock_Daily/sh600072.csv
sh600073 上海梅林
./Stock_Daily/sh600073.csv
sh600075 新疆天业
./Stock_Daily/sh600075.csv
sh600076 康欣新材
./Stock_Daily/sh600076.csv
sh600078 ST澄星
./Stock_Daily/sh600078.csv
sh600079 人福医药
./Stock_Daily/sh600079.csv
sh600080 金花股份
./Stock_Daily/sh600080.csv
sh600081 东风科技
./Stock_Daily/sh600081.csv
sh600082 海泰发展
./Stock_Daily/sh600082.csv
sh600083 博信股份
./Stock_Daily/sh600083.csv
sh600084 中信尼雅
./Stock_Daily/sh600084.csv
sh600085 同仁堂
./Stock_Daily/sh600085.csv
sh600088 中视传媒
./Stock_Daily/sh600088.csv
sh600089 特变电工
./Stock_Daily/sh600089.csv
sh600094 大名城
./Stock_Daily/sh600094.csv
sh600095 湘财股份
./Stock_Daily/sh600095.csv
sh600096 云天化
./Stock_Daily/sh600096.csv
sh600097 开创国际
./Stock_Daily/sh600097.csv
sh600098 广州发展
./Stock_Daily/sh600098.csv
sh600099 林海股份
./Stock_Daily/sh600099.csv
sh600100 同方股份
./Stock_Daily/sh600100.csv
sh600101 明星电力
./Stock_Daily/sh600101.csv
sh600103 青山纸业
./Stock_Daily/sh600103.csv
sh600104 上汽集团
./Stock_Daily/sh600104.csv
sh600105 永鼎股份
./Stock_Daily/sh600105.csv
sh600106 重庆路桥
./Stock_Daily/sh600106.csv
sh600107 美尔雅
./Stock_Daily/sh600107.csv
sh600108 亚盛集团
./Stock_Daily/sh600108.csv
sh600109 国金证券
./Stock_Daily/sh600109.csv
sh600110 诺德股份
./Stock_Daily/sh600110.csv
sh600111 北方稀土
./Stock_Daily/sh600111.csv
sh600112 ST天成
./Stock_Daily/sh600112.csv
sh600113 浙江东日
./Stock_Daily/sh600113.csv
sh600114 东睦股份
./Stock_Daily/sh600114.csv
sh600115 中国东航
./Stock_Daily/sh600115.csv
sh600116 三峡水利
./Stock_Daily/sh600116.csv
sh600117 *ST西钢
./Stock_Daily/sh600117.csv
sh600118 中国卫星
./Stock_Daily/sh600118.csv
sh600119 长江投资
./Stock_Daily/sh600119.csv
sh600120 浙江东方
./Stock_Daily/sh600120.csv
sh600121 郑州煤电
./Stock_Daily/sh600121.csv
sh600123 兰花科创
./Stock_Daily/sh600123.csv
sh600125 铁龙物流
./Stock_Daily/sh600125.csv
sh600126 杭钢股份
./Stock_Daily/sh600126.csv
sh600127 金健米业
./Stock_Daily/sh600127.csv
sh600128 苏豪弘业
./Stock_Daily/sh600128.csv
sh600129 太极集团
./Stock_Daily/sh600129.csv
sh600130 波导股份
./Stock_Daily/sh600130.csv
sh600131 国网信通
./Stock_Daily/sh600131.csv
sh600132 重庆啤酒
./Stock_Daily/sh600132.csv
sh600133 东湖高新
./Stock_Daily/sh600133.csv
sh600135 乐凯胶片
./Stock_Daily/sh600135.csv
sh600136 *ST明诚
./Stock_Daily/sh600136.csv
sh600137 浪莎股份
./Stock_Daily/sh600137.csv
sh600138 中青旅
./Stock_Daily/sh600138.csv
sh600141 兴发集团
./Stock_Daily/sh600141.csv
sh600143 金发科技
./Stock_Daily/sh600143.csv
sh600148 长春一东
./Stock_Daily/sh600148.csv
sh600149 廊坊发展
./Stock_Daily/sh600149.csv
sh600150 中国船舶
./Stock_Daily/sh600150.csv
sh600151 航天机电
./Stock_Daily/sh600151.csv
sh600152 维科技术
./Stock_Daily/sh600152.csv
sh600153 建发股份
./Stock_Daily/sh600153.csv
sh600155 华创云信
./Stock_Daily/sh600155.csv
sh600156 华升股份
./Stock_Daily/sh600156.csv
sh600157 永泰能源
./Stock_Daily/sh600157.csv
sh600158 中体产业
./Stock_Daily/sh600158.csv
sh600159 大龙地产
./Stock_Daily/sh600159.csv
sh600160 巨化股份
./Stock_Daily/sh600160.csv
sh600161 天坛生物
./Stock_Daily/sh600161.csv
sh600162 香江控股
./Stock_Daily/sh600162.csv
sh600163 中闽能源
./Stock_Daily/sh600163.csv
sh600165 宁科生物
./Stock_Daily/sh600165.csv
sh600166 福田汽车
./Stock_Daily/sh600166.csv
sh600167 联美控股
./Stock_Daily/sh600167.csv
sh600168 武汉控股
./Stock_Daily/sh600168.csv
sh600169 太原重工
./Stock_Daily/sh600169.csv
sh600170 上海建工
./Stock_Daily/sh600170.csv
sh600171 上海贝岭
./Stock_Daily/sh600171.csv
sh600172 黄河旋风
./Stock_Daily/sh600172.csv
sh600173 卧龙地产
./Stock_Daily/sh600173.csv
sh600176 中国巨石
./Stock_Daily/sh600176.csv
sh600177 雅戈尔
./Stock_Daily/sh600177.csv
sh600178 东安动力
./Stock_Daily/sh600178.csv
sh600179 安通控股
./Stock_Daily/sh600179.csv
sh600180 瑞茂通
./Stock_Daily/sh600180.csv
sh600182 S佳通
./Stock_Daily/sh600182.csv
sh600183 生益科技
./Stock_Daily/sh600183.csv
sh600184 光电股份
./Stock_Daily/sh600184.csv
sh600185 格力地产
./Stock_Daily/sh600185.csv
sh600186 莲花健康
./Stock_Daily/sh600186.csv
sh600187 国中水务
./Stock_Daily/sh600187.csv
sh600188 兖矿能源
./Stock_Daily/sh600188.csv
sh600189 泉阳泉
./Stock_Daily/sh600189.csv
sh600190 锦州港
./Stock_Daily/sh600190.csv
sh600191 华资实业
./Stock_Daily/sh600191.csv
sh600192 长城电工
./Stock_Daily/sh600192.csv
sh600193 创兴资源
./Stock_Daily/sh600193.csv
sh600195 中牧股份
./Stock_Daily/sh600195.csv
sh600196 复星医药
./Stock_Daily/sh600196.csv
sh600197 伊力特
./Stock_Daily/sh600197.csv
sh600198 大唐电信
./Stock_Daily/sh600198.csv
sh600199 金种子酒
./Stock_Daily/sh600199.csv
sh600200 江苏吴中
./Stock_Daily/sh600200.csv
sh600201 生物股份
./Stock_Daily/sh600201.csv
sh600202 哈空调
./Stock_Daily/sh600202.csv
sh600203 福日电子
./Stock_Daily/sh600203.csv
sh600206 有研新材
./Stock_Daily/sh600206.csv
sh600207 安彩高科
./Stock_Daily/sh600207.csv
sh600208 新湖中宝
./Stock_Daily/sh600208.csv
sh600210 紫江企业
./Stock_Daily/sh600210.csv
sh600211 西藏药业
./Stock_Daily/sh600211.csv
sh600212 绿能慧充
./Stock_Daily/sh600212.csv
sh600213 亚星客车
./Stock_Daily/sh600213.csv
sh600215 派斯林
./Stock_Daily/sh600215.csv
sh600216 浙江医药
./Stock_Daily/sh600216.csv
sh600217 中再资环
./Stock_Daily/sh600217.csv
sh600218 全柴动力
./Stock_Daily/sh600218.csv
sh600219 南山铝业
./Stock_Daily/sh600219.csv
sh600220 江苏阳光

./Stock_Daily/sh600220.csv
sh600221 海航控股
./Stock_Daily/sh600221.csv
sh600222 太龙药业
./Stock_Daily/sh600222.csv
sh600223 福瑞达
./Stock_Daily/sh600223.csv
sh600225 卓朗科技
./Stock_Daily/sh600225.csv
sh600226 瀚叶股份
./Stock_Daily/sh600226.csv
sh600227 赤天化
./Stock_Daily/sh600227.csv
sh600228 返利科技
./Stock_Daily/sh600228.csv
sh600229 城市传媒
./Stock_Daily/sh600229.csv
sh600230 沧州大化
./Stock_Daily/sh600230.csv
sh600231 凌钢股份
./Stock_Daily/sh600231.csv
sh600232 金鹰股份
./Stock_Daily/sh600232.csv
sh600233 圆通速递
./Stock_Daily/sh600233.csv
sh600234 科新发展
./Stock_Daily/sh600234.csv
sh600235 民丰特纸
./Stock_Daily/sh600235.csv
sh600236 桂冠电力
./Stock_Daily/sh600236.csv
sh600237 铜峰电子
./Stock_Daily/sh600237.csv
sh600238 海南椰岛
./Stock_Daily/sh600238.csv
sh600239 云南城投
./Stock_Daily/sh600239.csv
sh600241 时代万恒
./Stock_Daily/sh600241.csv
sh600243 青海华鼎
./Stock_Daily/sh600243.csv
sh600246 万通发展
./Stock_Daily/sh600246.csv
sh600248 陕建股份
./Stock_Daily/sh600248.csv
sh600249 两面针
./Stock_Daily/sh600249.csv
sh600250 南纺股份
./Stock_Daily/sh600250.csv
sh600251 冠农股份
./Stock_Daily/sh600251.csv
sh600252 中恒集团
./Stock_Daily/sh600252.csv
sh600255 鑫科材料
./Stock_Daily/sh600255.csv
sh600256 广汇能源
./Stock_Daily/sh600256.csv
sh600257 大湖股份
./Stock_Daily/sh600257.csv
sh600258 首旅酒店
./Stock_Daily/sh600258.csv
sh600259 广晟有色
./Stock_Daily/sh600259.csv
sh600261 阳光照明
./Stock_Daily/sh600261.csv
sh600262 北方股份
./Stock_Daily/sh600262.csv
sh600265 ST景谷
./Stock_Daily/sh600265.csv
sh600266 城建发展
./Stock_Daily/sh600266.csv
sh600267 海正药业
./Stock_Daily/sh600267.csv
sh600268 国电南自
./Stock_Daily/sh600268.csv
sh600269 赣粤高速
./Stock_Daily/sh600269.csv
sh600271 航天信息
./Stock_Daily/sh600271.csv
sh600272 开开实业
./Stock_Daily/sh600272.csv
sh600273 嘉化能源
./Stock_Daily/sh600273.csv
sh600276 恒瑞医药
./Stock_Daily/sh600276.csv
sh600277 亿利洁能
./Stock_Daily/sh600277.csv
sh600278 东方创业
./Stock_Daily/sh600278.csv
sh600279 重庆港
./Stock_Daily/sh600279.csv
sh600280 中央商场
./Stock_Daily/sh600280.csv
sh600281 华阳新材
./Stock_Daily/sh600281.csv
sh600282 南钢股份
./Stock_Daily/sh600282.csv
sh600283 钱江水利
./Stock_Daily/sh600283.csv
sh600284 浦东建设
./Stock_Daily/sh600284.csv
sh600285 羚锐制药
./Stock_Daily/sh600285.csv
sh600287 江苏舜天
./Stock_Daily/sh600287.csv
sh600288 大恒科技
./Stock_Daily/sh600288.csv
sh600289 ST信通
./Stock_Daily/sh600289.csv
sh600290 *ST华仪
./Stock_Daily/sh600290.csv
sh600292 远达环保
./Stock_Daily/sh600292.csv
sh600293 三峡新材
./Stock_Daily/sh600293.csv
sh600295 鄂尔多斯
./Stock_Daily/sh600295.csv
sh600297 广汇汽车
./Stock_Daily/sh600297.csv
sh600298 安琪酵母
./Stock_Daily/sh600298.csv
sh600299 安迪苏
./Stock_Daily/sh600299.csv
sh600300 维维股份
./Stock_Daily/sh600300.csv
sh600301 华锡有色
./Stock_Daily/sh600301.csv
sh600302 标准股份
./Stock_Daily/sh600302.csv
sh600303 ST曙光
./Stock_Daily/sh600303.csv
sh600305 恒顺醋业
./Stock_Daily/sh600305.csv
sh600306 *ST商城
./Stock_Daily/sh600306.csv
sh600307 酒钢宏兴
./Stock_Daily/sh600307.csv
sh600308 华泰股份
./Stock_Daily/sh600308.csv
sh600309 万华化学
./Stock_Daily/sh600309.csv
sh600310 广西能源
./Stock_Daily/sh600310.csv
sh600312 平高电气
./Stock_Daily/sh600312.csv
sh600313 农发种业
./Stock_Daily/sh600313.csv
sh600315 上海家化
./Stock_Daily/sh600315.csv
sh600316 洪都航空
./Stock_Daily/sh600316.csv
sh600318 新力金融
./Stock_Daily/sh600318.csv
sh600319 亚星化学
./Stock_Daily/sh600319.csv
sh600320 振华重工
./Stock_Daily/sh600320.csv
sh600321 正源股份
./Stock_Daily/sh600321.csv
sh600322 津投城开
./Stock_Daily/sh600322.csv
sh600323 瀚蓝环境
./Stock_Daily/sh600323.csv
sh600325 华发股份
./Stock_Daily/sh600325.csv
sh600326 西藏天路
./Stock_Daily/sh600326.csv
sh600327 大东方
./Stock_Daily/sh600327.csv
sh600328 中盐化工
./Stock_Daily/sh600328.csv
sh600329 达仁堂
./Stock_Daily/sh600329.csv
sh600330 天通股份
./Stock_Daily/sh600330.csv
sh600331 宏达股份
./Stock_Daily/sh600331.csv
sh600332 白云山
./Stock_Daily/sh600332.csv
sh600333 长春燃气
./Stock_Daily/sh600333.csv
sh600335 国机汽车
./Stock_Daily/sh600335.csv
sh600336 澳柯玛
./Stock_Daily/sh600336.csv
sh600337 美克家居
./Stock_Daily/sh600337.csv
sh600338 西藏珠峰
./Stock_Daily/sh600338.csv
sh600339 中油工程
./Stock_Daily/sh600339.csv
sh600340 华夏幸福
./Stock_Daily/sh600340.csv
sh600343 航天动力
./Stock_Daily/sh600343.csv
sh600345 长江通信
./Stock_Daily/sh600345.csv
sh600346 恒力石化
./Stock_Daily/sh600346.csv
sh600348 华阳股份
./Stock_Daily/sh600348.csv
sh600350 山东高速
./Stock_Daily/sh600350.csv
sh600351 亚宝药业
./Stock_Daily/sh600351.csv
sh600352 浙江龙盛
./Stock_Daily/sh600352.csv
sh600353 旭光电子
./Stock_Daily/sh600353.csv
sh600354 敦煌种业
./Stock_Daily/sh600354.csv
sh600355 精伦电子
./Stock_Daily/sh600355.csv
sh600356 恒丰纸业
./Stock_Daily/sh600356.csv
sh600358 国旅联合
./Stock_Daily/sh600358.csv
sh600359 新农开发
./Stock_Daily/sh600359.csv
sh600360 华微电子
./Stock_Daily/sh600360.csv
sh600361 创新新材
./Stock_Daily/sh600361.csv
sh600362 江西铜业
./Stock_Daily/sh600362.csv
sh600363 联创光电
./Stock_Daily/sh600363.csv
sh600365 ST通葡
./Stock_Daily/sh600365.csv
sh600366 宁波韵升
./Stock_Daily/sh600366.csv
sh600367 红星发展
./Stock_Daily/sh600367.csv
sh600368 五洲交通
./Stock_Daily/sh600368.csv
sh600369 西南证券
./Stock_Daily/sh600369.csv
sh600370 三房巷
./Stock_Daily/sh600370.csv
sh600371 万向德农
./Stock_Daily/sh600371.csv
sh600372 中航机载
./Stock_Daily/sh600372.csv
sh600373 中文传媒
./Stock_Daily/sh600373.csv
sh600375 汉马科技
./Stock_Daily/sh600375.csv
sh600376 首开股份
./Stock_Daily/sh600376.csv
sh600377 宁沪高速
./Stock_Daily/sh600377.csv
sh600378 昊华科技
./Stock_Daily/sh600378.csv
sh600379 宝光股份
./Stock_Daily/sh600379.csv
sh600380 健康元
./Stock_Daily/sh600380.csv
sh600381 青海春天
./Stock_Daily/sh600381.csv
sh600382 广东明珠
./Stock_Daily/sh600382.csv
sh600383 金地集团
./Stock_Daily/sh600383.csv
sh600386 北巴传媒
./Stock_Daily/sh600386.csv
sh600387 ST海越
./Stock_Daily/sh600387.csv
sh600388 龙净环保
./Stock_Daily/sh600388.csv
sh600389 江山股份
./Stock_Daily/sh600389.csv
sh600390 五矿资本
./Stock_Daily/sh600390.csv
sh600391 航发科技
./Stock_Daily/sh600391.csv
sh600392 盛和资源
./Stock_Daily/sh600392.csv
sh600395 盘江股份
./Stock_Daily/sh600395.csv
sh600396 *ST金山
./Stock_Daily/sh600396.csv
sh600397 安源煤业
./Stock_Daily/sh600397.csv
sh600398 海澜之家
./Stock_Daily/sh600398.csv
sh600399 抚顺特钢
./Stock_Daily/sh600399.csv
sh600400 红豆股份
./Stock_Daily/sh600400.csv
sh600403 大有能源
./Stock_Daily/sh600403.csv
sh600405 动力源
./Stock_Daily/sh600405.csv
sh600406 国电南瑞
./Stock_Daily/sh600406.csv
sh600408 安泰集团
./Stock_Daily/sh600408.csv
sh600409 三友化工
./Stock_Daily/sh600409.csv
sh600410 华胜天成
./Stock_Daily/sh600410.csv
sh600415 小商品城
./Stock_Daily/sh600415.csv
sh600416 湘电股份
./Stock_Daily/sh600416.csv
sh600418 江淮汽车
./Stock_Daily/sh600418.csv
sh600419 天润乳业
./Stock_Daily/sh600419.csv
sh600420 国药现代
./Stock_Daily/sh600420.csv
sh600421 华嵘控股
./Stock_Daily/sh600421.csv
sh600422 昆药集团
./Stock_Daily/sh600422.csv
sh600423 柳化股份
./Stock_Daily/sh600423.csv
sh600425 青松建化
./Stock_Daily/sh600425.csv
sh600426 华鲁恒升
./Stock_Daily/sh600426.csv
sh600428 中远海特
./Stock_Daily/sh600428.csv
sh600429 三元股份
./Stock_Daily/sh600429.csv
sh600433 冠豪高新
./Stock_Daily/sh600433.csv
sh600435 北方导航
./Stock_Daily/sh600435.csv
sh600436 片仔癀
./Stock_Daily/sh600436.csv
sh600438 通威股份
./Stock_Daily/sh600438.csv
sh600439 瑞贝卡
./Stock_Daily/sh600439.csv
sh600444 国机通用
./Stock_Daily/sh600444.csv
sh600446 金证股份
./Stock_Daily/sh600446.csv
sh600448 华纺股份
./Stock_Daily/sh600448.csv
sh600449 宁夏建材
./Stock_Daily/sh600449.csv
sh600452 涪陵电力
./Stock_Daily/sh600452.csv
sh600455 博通股份
./Stock_Daily/sh600455.csv
sh600456 宝钛股份
./Stock_Daily/sh600456.csv
sh600458 时代新材
./Stock_Daily/sh600458.csv
sh600459 贵研铂业
./Stock_Daily/sh600459.csv
sh600460 士兰微
./Stock_Daily/sh600460.csv
sh600461 洪城环境
./Stock_Daily/sh600461.csv
sh600462 ST九有
./Stock_Daily/sh600462.csv
sh600463 空港股份
./Stock_Daily/sh600463.csv
sh600467 好当家
./Stock_Daily/sh600467.csv
sh600468 百利电气
./Stock_Daily/sh600468.csv
sh600469 风神股份
./Stock_Daily/sh600469.csv
sh600470 六国化工
./Stock_Daily/sh600470.csv
sh600475 华光环能
./Stock_Daily/sh600475.csv
sh600476 湘邮科技
./Stock_Daily/sh600476.csv
sh600477 杭萧钢构
./Stock_Daily/sh600477.csv
sh600478 科力远
./Stock_Daily/sh600478.csv
sh600479 千金药业
./Stock_Daily/sh600479.csv
sh600480 凌云股份
./Stock_Daily/sh600480.csv
sh600481 双良节能
./Stock_Daily/sh600481.csv
sh600482 中国动力
./Stock_Daily/sh600482.csv
sh600483 福能股份
./Stock_Daily/sh600483.csv
sh600486 扬农化工
./Stock_Daily/sh600486.csv
sh600487 亨通光电
./Stock_Daily/sh600487.csv
sh600488 津药药业
./Stock_Daily/sh600488.csv
sh600489 中金黄金
./Stock_Daily/sh600489.csv
sh600490 鹏欣资源
./Stock_Daily/sh600490.csv
sh600491 龙元建设
./Stock_Daily/sh600491.csv
sh600493 凤竹纺织
./Stock_Daily/sh600493.csv
sh600495 晋西车轴

./Stock_Daily/sh600495.csv
sh600496 精工钢构
./Stock_Daily/sh600496.csv
sh600497 驰宏锌锗
./Stock_Daily/sh600497.csv
sh600498 烽火通信
./Stock_Daily/sh600498.csv
sh600499 科达制造
./Stock_Daily/sh600499.csv
sh600500 中化国际
./Stock_Daily/sh600500.csv
sh600501 航天晨光
./Stock_Daily/sh600501.csv
sh600502 安徽建工
./Stock_Daily/sh600502.csv
sh600503 华丽家族
./Stock_Daily/sh600503.csv
sh600505 西昌电力
./Stock_Daily/sh600505.csv
sh600506 统一股份
./Stock_Daily/sh600506.csv
sh600507 方大特钢
./Stock_Daily/sh600507.csv
sh600508 上海能源
./Stock_Daily/sh600508.csv
sh600509 天富能源
./Stock_Daily/sh600509.csv
sh600510 黑牡丹
./Stock_Daily/sh600510.csv
sh600511 国药股份
./Stock_Daily/sh600511.csv
sh600512 腾达建设
./Stock_Daily/sh600512.csv
sh600513 联环药业
./Stock_Daily/sh600513.csv
sh600515 海南机场
./Stock_Daily/sh600515.csv
sh600516 方大炭素
./Stock_Daily/sh600516.csv
sh600517 国网英大
./Stock_Daily/sh600517.csv
sh600518 ST康美
./Stock_Daily/sh600518.csv
sh600519 贵州茅台
./Stock_Daily/sh600519.csv
sh600520 文一科技
./Stock_Daily/sh600520.csv
sh600521 华海药业
./Stock_Daily/sh600521.csv
sh600522 中天科技
./Stock_Daily/sh600522.csv
sh600523 贵航股份
./Stock_Daily/sh600523.csv
sh600525 长园集团
./Stock_Daily/sh600525.csv
sh600526 菲达环保
./Stock_Daily/sh600526.csv
sh600527 江南高纤
./Stock_Daily/sh600527.csv
sh600528 中铁工业
./Stock_Daily/sh600528.csv
sh600529 山东药玻
./Stock_Daily/sh600529.csv
sh600530 ST交昂
./Stock_Daily/sh600530.csv
sh600531 豫光金铅
./Stock_Daily/sh600531.csv
sh600533 栖霞建设
./Stock_Daily/sh600533.csv
sh600535 天士力
./Stock_Daily/sh600535.csv
sh600536 中国软件
./Stock_Daily/sh600536.csv
sh600537 亿晶光电
./Stock_Daily/sh600537.csv
sh600538 国发股份
./Stock_Daily/sh600538.csv
sh600539 狮头股份
./Stock_Daily/sh600539.csv
sh600540 新赛股份
./Stock_Daily/sh600540.csv
sh600543 *ST莫高
./Stock_Daily/sh600543.csv
sh600545 卓郎智能
./Stock_Daily/sh600545.csv
sh600546 山煤国际
./Stock_Daily/sh600546.csv
sh600547 山东黄金
./Stock_Daily/sh600547.csv
sh600548 深高速
./Stock_Daily/sh600548.csv
sh600549 厦门钨业
./Stock_Daily/sh600549.csv
sh600550 保变电气
./Stock_Daily/sh600550.csv
sh600551 时代出版
./Stock_Daily/sh600551.csv
sh600552 凯盛科技
./Stock_Daily/sh600552.csv
sh600556 天下秀
./Stock_Daily/sh600556.csv
sh600557 康缘药业
./Stock_Daily/sh600557.csv
sh600558 大西洋
./Stock_Daily/sh600558.csv
sh600559 老白干酒
./Stock_Daily/sh600559.csv
sh600560 金自天正
./Stock_Daily/sh600560.csv
sh600561 江西长运
./Stock_Daily/sh600561.csv
sh600562 国睿科技
./Stock_Daily/sh600562.csv
sh600563 法拉电子
./Stock_Daily/sh600563.csv
sh600565 迪马股份
./Stock_Daily/sh600565.csv
sh600566 济川药业
./Stock_Daily/sh600566.csv
sh600567 山鹰国际
./Stock_Daily/sh600567.csv
sh600568 ST中珠
./Stock_Daily/sh600568.csv
sh600569 安阳钢铁
./Stock_Daily/sh600569.csv
sh600570 恒生电子
./Stock_Daily/sh600570.csv
sh600571 信雅达
./Stock_Daily/sh600571.csv
sh600572 康恩贝
./Stock_Daily/sh600572.csv
sh600573 惠泉啤酒
./Stock_Daily/sh600573.csv
sh600575 淮河能源
./Stock_Daily/sh600575.csv
sh600576 祥源文旅
./Stock_Daily/sh600576.csv
sh600577 精达股份
./Stock_Daily/sh600577.csv
sh600578 京能电力
./Stock_Daily/sh600578.csv
sh600579 克劳斯
./Stock_Daily/sh600579.csv
sh600580 卧龙电驱
./Stock_Daily/sh600580.csv
sh600581 八一钢铁
./Stock_Daily/sh600581.csv
sh600582 天地科技
./Stock_Daily/sh600582.csv
sh600583 海油工程
./Stock_Daily/sh600583.csv
sh600584 长电科技
./Stock_Daily/sh600584.csv
sh600585 海螺水泥
./Stock_Daily/sh600585.csv
sh600586 金晶科技
./Stock_Daily/sh600586.csv
sh600587 新华医疗
./Stock_Daily/sh600587.csv
sh600588 用友网络
./Stock_Daily/sh600588.csv
sh600589 *ST榕泰
./Stock_Daily/sh600589.csv
sh600590 泰豪科技
./Stock_Daily/sh600590.csv
sh600592 龙溪股份
./Stock_Daily/sh600592.csv
sh600593 大连圣亚
./Stock_Daily/sh600593.csv
sh600594 益佰制药
./Stock_Daily/sh600594.csv
sh600595 中孚实业
./Stock_Daily/sh600595.csv
sh600596 新安股份
./Stock_Daily/sh600596.csv
sh600597 光明乳业
./Stock_Daily/sh600597.csv
sh600598 北大荒
./Stock_Daily/sh600598.csv
sh600599 ST熊猫
./Stock_Daily/sh600599.csv
sh600600 青岛啤酒
./Stock_Daily/sh600600.csv
sh600601 方正科技
./Stock_Daily/sh600601.csv
sh600602 云赛智联
./Stock_Daily/sh600602.csv
sh600603 广汇物流
./Stock_Daily/sh600603.csv
sh600604 市北高新
./Stock_Daily/sh600604.csv
sh600605 汇通能源
./Stock_Daily/sh600605.csv
sh600606 绿地控股
./Stock_Daily/sh600606.csv
sh600608 ST沪科
./Stock_Daily/sh600608.csv
sh600609 金杯汽车
./Stock_Daily/sh600609.csv
sh600610 中毅达
./Stock_Daily/sh600610.csv
sh600611 大众交通
./Stock_Daily/sh600611.csv
sh600612 老凤祥
./Stock_Daily/sh600612.csv
sh600613 神奇制药
./Stock_Daily/sh600613.csv
sh600615 丰华股份
./Stock_Daily/sh600615.csv
sh600616 金枫酒业
./Stock_Daily/sh600616.csv
sh600617 国新能源
./Stock_Daily/sh600617.csv
sh600618 氯碱化工
./Stock_Daily/sh600618.csv
sh600619 海立股份
./Stock_Daily/sh600619.csv
sh600620 天宸股份
./Stock_Daily/sh600620.csv
sh600621 华鑫股份
./Stock_Daily/sh600621.csv
sh600622 光大嘉宝
./Stock_Daily/sh600622.csv
sh600623 华谊集团
./Stock_Daily/sh600623.csv
sh600624 复旦复华
./Stock_Daily/sh600624.csv
sh600626 申达股份
./Stock_Daily/sh600626.csv
sh600628 新世界
./Stock_Daily/sh600628.csv
sh600629 华建集团
./Stock_Daily/sh600629.csv
sh600630 龙头股份
./Stock_Daily/sh600630.csv
sh600633 浙数文化
./Stock_Daily/sh600633.csv
sh600635 大众公用
./Stock_Daily/sh600635.csv
sh600636 国新文化
./Stock_Daily/sh600636.csv
sh600637 东方明珠
./Stock_Daily/sh600637.csv
sh600638 新黄浦
./Stock_Daily/sh600638.csv
sh600639 浦东金桥
./Stock_Daily/sh600639.csv
sh600640 国脉文化
./Stock_Daily/sh600640.csv
sh600641 万业企业
./Stock_Daily/sh600641.csv
sh600642 申能股份
./Stock_Daily/sh600642.csv
sh600643 爱建集团
./Stock_Daily/sh600643.csv
sh600644 乐山电力
./Stock_Daily/sh600644.csv
sh600645 中源协和
./Stock_Daily/sh600645.csv
sh600647 *ST同达
./Stock_Daily/sh600647.csv
sh600648 外高桥
./Stock_Daily/sh600648.csv
sh600649 城投控股
./Stock_Daily/sh600649.csv
sh600650 锦江在线
./Stock_Daily/sh600650.csv
sh600651 飞乐音响
./Stock_Daily/sh600651.csv
sh600653 申华控股
./Stock_Daily/sh600653.csv
sh600654 ST中安
./Stock_Daily/sh600654.csv
sh600655 豫园股份
./Stock_Daily/sh600655.csv
sh600657 信达地产
./Stock_Daily/sh600657.csv
sh600658 电子城
./Stock_Daily/sh600658.csv
sh600660 福耀玻璃
./Stock_Daily/sh600660.csv
sh600661 昂立教育
./Stock_Daily/sh600661.csv
sh600662 外服控股
./Stock_Daily/sh600662.csv
sh600663 陆家嘴
./Stock_Daily/sh600663.csv
sh600664 哈药股份
./Stock_Daily/sh600664.csv
sh600665 天地源
./Stock_Daily/sh600665.csv
sh600666 ST瑞德
./Stock_Daily/sh600666.csv
sh600667 太极实业
./Stock_Daily/sh600667.csv
sh600668 尖峰集团
./Stock_Daily/sh600668.csv
sh600671 *ST目药
./Stock_Daily/sh600671.csv
sh600673 东阳光
./Stock_Daily/sh600673.csv
sh600674 川投能源
./Stock_Daily/sh600674.csv
sh600675 中华企业
./Stock_Daily/sh600675.csv
sh600676 交运股份
./Stock_Daily/sh600676.csv
sh600678 四川金顶
./Stock_Daily/sh600678.csv
sh600679 上海凤凰
./Stock_Daily/sh600679.csv
sh600681 百川能源
./Stock_Daily/sh600681.csv
sh600682 南京新百
./Stock_Daily/sh600682.csv
sh600683 京投发展
./Stock_Daily/sh600683.csv
sh600684 珠江股份
./Stock_Daily/sh600684.csv
sh600685 中船防务
./Stock_Daily/sh600685.csv
sh600686 金龙汽车
./Stock_Daily/sh600686.csv
sh600688 上海石化
./Stock_Daily/sh600688.csv
sh600689 上海三毛
./Stock_Daily/sh600689.csv
sh600690 海尔智家
./Stock_Daily/sh600690.csv
sh600691 阳煤化工
./Stock_Daily/sh600691.csv
sh600692 亚通股份
./Stock_Daily/sh600692.csv
sh600693 东百集团
./Stock_Daily/sh600693.csv
sh600694 大商股份
./Stock_Daily/sh600694.csv
sh600696 岩石股份
./Stock_Daily/sh600696.csv
sh600697 欧亚集团
./Stock_Daily/sh600697.csv
sh600698 湖南天雁
./Stock_Daily/sh600698.csv
sh600699 均胜电子
./Stock_Daily/sh600699.csv
sh600702 舍得酒业
./Stock_Daily/sh600702.csv
sh600703 三安光电
./Stock_Daily/sh600703.csv
sh600704 物产中大
./Stock_Daily/sh600704.csv
sh600705 中航产融
./Stock_Daily/sh600705.csv
sh600706 曲江文旅
./Stock_Daily/sh600706.csv
sh600707 彩虹股份
./Stock_Daily/sh600707.csv
sh600708 光明地产
./Stock_Daily/sh600708.csv
sh600710 苏美达
./Stock_Daily/sh600710.csv
sh600711 盛屯矿业
./Stock_Daily/sh600711.csv
sh600712 南宁百货
./Stock_Daily/sh600712.csv
sh600713 南京医药
./Stock_Daily/sh600713.csv
sh600714 金瑞矿业
./Stock_Daily/sh600714.csv
sh600715 文投控股
./Stock_Daily/sh600715.csv
sh600716 凤凰股份
./Stock_Daily/sh600716.csv
sh600717 天津港
./Stock_Daily/sh600717.csv
sh600718 东软集团
./Stock_Daily/sh600718.csv
sh600719 大连热电
./Stock_Daily/sh600719.csv
sh600720 祁连山
./Stock_Daily/sh600720.csv
sh600721 百花医药
./Stock_Daily/sh600721.csv
sh600722 金牛化工
./Stock_Daily/sh600722.csv
sh600724 宁波富达
./Stock_Daily/sh600724.csv
sh600725 云维股份
./Stock_Daily/sh600725.csv
sh600726 华电能源
./Stock_Daily/sh600726.csv
sh600727 鲁北化工
./Stock_Daily/sh600727.csv
sh600728 佳都科技
./Stock_Daily/sh600728.csv
sh600729 重庆百货
./Stock_Daily/sh600729.csv
sh600730 中国高科
./Stock_Daily/sh600730.csv
sh600731 湖南海利
./Stock_Daily/sh600731.csv
sh600732 爱旭股份

./Stock_Daily/sh600732.csv
sh600733 北汽蓝谷
./Stock_Daily/sh600733.csv
sh600734 ST实达
./Stock_Daily/sh600734.csv
sh600735 新华锦
./Stock_Daily/sh600735.csv
sh600736 苏州高新
./Stock_Daily/sh600736.csv
sh600737 中粮糖业
./Stock_Daily/sh600737.csv
sh600738 丽尚国潮
./Stock_Daily/sh600738.csv
sh600739 辽宁成大
./Stock_Daily/sh600739.csv
sh600740 山西焦化
./Stock_Daily/sh600740.csv
sh600741 华域汽车
./Stock_Daily/sh600741.csv
sh600742 一汽富维
./Stock_Daily/sh600742.csv
sh600743 华远地产
./Stock_Daily/sh600743.csv
sh600744 华银电力
./Stock_Daily/sh600744.csv
sh600745 闻泰科技
./Stock_Daily/sh600745.csv
sh600746 江苏索普
./Stock_Daily/sh600746.csv
sh600748 上实发展
./Stock_Daily/sh600748.csv
sh600749 西藏旅游
./Stock_Daily/sh600749.csv
sh600750 江中药业
./Stock_Daily/sh600750.csv
sh600751 海航科技
./Stock_Daily/sh600751.csv
sh600753 庚星股份
./Stock_Daily/sh600753.csv
sh600754 锦江酒店
./Stock_Daily/sh600754.csv
sh600755 厦门国贸
./Stock_Daily/sh600755.csv
sh600756 浪潮软件
./Stock_Daily/sh600756.csv
sh600757 长江传媒
./Stock_Daily/sh600757.csv
sh600758 辽宁能源
./Stock_Daily/sh600758.csv
sh600759 *ST洲际
./Stock_Daily/sh600759.csv
sh600760 中航沈飞
./Stock_Daily/sh600760.csv
sh600761 安徽合力
./Stock_Daily/sh600761.csv
sh600763 通策医疗
./Stock_Daily/sh600763.csv
sh600764 中国海防
./Stock_Daily/sh600764.csv
sh600765 中航重机
./Stock_Daily/sh600765.csv
sh600766 *ST园城
./Stock_Daily/sh600766.csv
sh600768 宁波富邦
./Stock_Daily/sh600768.csv
sh600769 祥龙电业
./Stock_Daily/sh600769.csv
sh600770 综艺股份
./Stock_Daily/sh600770.csv
sh600771 广誉远
./Stock_Daily/sh600771.csv
sh600773 西藏城投
./Stock_Daily/sh600773.csv
sh600774 汉商集团
./Stock_Daily/sh600774.csv
sh600775 南京熊猫
./Stock_Daily/sh600775.csv
sh600776 东方通信
./Stock_Daily/sh600776.csv
sh600777 新潮能源
./Stock_Daily/sh600777.csv
sh600778 友好集团
./Stock_Daily/sh600778.csv
sh600779 水井坊
./Stock_Daily/sh600779.csv
sh600780 通宝能源
./Stock_Daily/sh600780.csv
sh600782 新钢股份
./Stock_Daily/sh600782.csv
sh600783 鲁信创投
./Stock_Daily/sh600783.csv
sh600784 鲁银投资
./Stock_Daily/sh600784.csv
sh600785 新华百货
./Stock_Daily/sh600785.csv
sh600787 中储股份
./Stock_Daily/sh600787.csv
sh600789 鲁抗医药
./Stock_Daily/sh600789.csv
sh600790 轻纺城
./Stock_Daily/sh600790.csv
sh600791 京能置业
./Stock_Daily/sh600791.csv
sh600792 云煤能源
./Stock_Daily/sh600792.csv
sh600793 宜宾纸业
./Stock_Daily/sh600793.csv
sh600794 保税科技
./Stock_Daily/sh600794.csv
sh600795 国电电力
./Stock_Daily/sh600795.csv
sh600796 钱江生化
./Stock_Daily/sh600796.csv
sh600797 浙大网新
./Stock_Daily/sh600797.csv
sh600798 宁波海运
./Stock_Daily/sh600798.csv
sh600800 渤海化学
./Stock_Daily/sh600800.csv
sh600801 华新水泥
./Stock_Daily/sh600801.csv
sh600802 福建水泥
./Stock_Daily/sh600802.csv
sh600803 新奥股份
./Stock_Daily/sh600803.csv
sh600804 ST鹏博士
./Stock_Daily/sh600804.csv
sh600805 悦达投资
./Stock_Daily/sh600805.csv
sh600807 济南高新
./Stock_Daily/sh600807.csv
sh600808 马钢股份
./Stock_Daily/sh600808.csv
sh600809 山西汾酒
./Stock_Daily/sh600809.csv
sh600810 神马股份
./Stock_Daily/sh600810.csv
sh600811 东方集团
./Stock_Daily/sh600811.csv
sh600812 华北制药
./Stock_Daily/sh600812.csv
sh600814 杭州解百
./Stock_Daily/sh600814.csv
sh600815 厦工股份
./Stock_Daily/sh600815.csv
sh600816 建元信托
./Stock_Daily/sh600816.csv
sh600817 宇通重工
./Stock_Daily/sh600817.csv
sh600818 中路股份
./Stock_Daily/sh600818.csv
sh600819 耀皮玻璃
./Stock_Daily/sh600819.csv
sh600820 隧道股份
./Stock_Daily/sh600820.csv
sh600821 金开新能
./Stock_Daily/sh600821.csv
sh600822 上海物贸
./Stock_Daily/sh600822.csv
sh600823 ST世茂
./Stock_Daily/sh600823.csv
sh600824 益民集团
./Stock_Daily/sh600824.csv
sh600825 新华传媒
./Stock_Daily/sh600825.csv
sh600826 兰生股份
./Stock_Daily/sh600826.csv
sh600827 百联股份
./Stock_Daily/sh600827.csv
sh600828 茂业商业
./Stock_Daily/sh600828.csv
sh600829 人民同泰
./Stock_Daily/sh600829.csv
sh600830 香溢融通
./Stock_Daily/sh600830.csv
sh600831 广电网络
./Stock_Daily/sh600831.csv
sh600833 第一医药
./Stock_Daily/sh600833.csv
sh600834 申通地铁
./Stock_Daily/sh600834.csv
sh600835 上海机电
./Stock_Daily/sh600835.csv
sh600836 上海易连
./Stock_Daily/sh600836.csv
sh600837 海通证券
./Stock_Daily/sh600837.csv
sh600838 上海九百
./Stock_Daily/sh600838.csv
sh600839 四川长虹
./Stock_Daily/sh600839.csv
sh600841 动力新科
./Stock_Daily/sh600841.csv
sh600843 上工申贝
./Stock_Daily/sh600843.csv
sh600844 丹化科技
./Stock_Daily/sh600844.csv
sh600845 宝信软件
./Stock_Daily/sh600845.csv
sh600846 同济科技
./Stock_Daily/sh600846.csv
sh600847 万里股份
./Stock_Daily/sh600847.csv
sh600848 上海临港
./Stock_Daily/sh600848.csv
sh600850 电科数字
./Stock_Daily/sh600850.csv
sh600851 海欣股份
./Stock_Daily/sh600851.csv
sh600853 龙建股份
./Stock_Daily/sh600853.csv
sh600854 春兰股份
./Stock_Daily/sh600854.csv
sh600855 航天长峰
./Stock_Daily/sh600855.csv
sh600857 宁波中百
./Stock_Daily/sh600857.csv
sh600858 银座股份
./Stock_Daily/sh600858.csv
sh600859 王府井
./Stock_Daily/sh600859.csv
sh600860 京城股份
./Stock_Daily/sh600860.csv
sh600861 北京人力
./Stock_Daily/sh600861.csv
sh600862 中航高科
./Stock_Daily/sh600862.csv
sh600863 内蒙华电
./Stock_Daily/sh600863.csv
sh600864 哈投股份
./Stock_Daily/sh600864.csv
sh600865 百大集团
./Stock_Daily/sh600865.csv
sh600866 星湖科技
./Stock_Daily/sh600866.csv
sh600867 通化东宝
./Stock_Daily/sh600867.csv
sh600868 梅雁吉祥
./Stock_Daily/sh600868.csv
sh600869 远东股份
./Stock_Daily/sh600869.csv
sh600871 石化油服
./Stock_Daily/sh600871.csv
sh600872 中炬高新
./Stock_Daily/sh600872.csv
sh600873 梅花生物
./Stock_Daily/sh600873.csv
sh600874 创业环保
./Stock_Daily/sh600874.csv
sh600875 东方电气
./Stock_Daily/sh600875.csv
sh600876 凯盛新能
./Stock_Daily/sh600876.csv
sh600877 电科芯片
./Stock_Daily/sh600877.csv
sh600879 航天电子
./Stock_Daily/sh600879.csv
sh600880 博瑞传播
./Stock_Daily/sh600880.csv
sh600881 亚泰集团
./Stock_Daily/sh600881.csv
sh600882 妙可蓝多
./Stock_Daily/sh600882.csv
sh600883 博闻科技
./Stock_Daily/sh600883.csv
sh600884 杉杉股份
./Stock_Daily/sh600884.csv
sh600885 宏发股份
./Stock_Daily/sh600885.csv
sh600886 国投电力
./Stock_Daily/sh600886.csv
sh600887 伊利股份
./Stock_Daily/sh600887.csv
sh600888 新疆众和
./Stock_Daily/sh600888.csv
sh600889 南京化纤
./Stock_Daily/sh600889.csv
sh600892 大晟文化
./Stock_Daily/sh600892.csv
sh600893 航发动力
./Stock_Daily/sh600893.csv
sh600894 广日股份
./Stock_Daily/sh600894.csv
sh600895 张江高科
./Stock_Daily/sh600895.csv
sh600897 厦门空港
./Stock_Daily/sh600897.csv
sh600898 ST美讯
./Stock_Daily/sh600898.csv
sh600900 长江电力
./Stock_Daily/sh600900.csv
sh600901 江苏金租
./Stock_Daily/sh600901.csv
sh600903 贵州燃气
./Stock_Daily/sh600903.csv
sh600905 三峡能源
./Stock_Daily/sh600905.csv
sh600906 财达证券
./Stock_Daily/sh600906.csv
sh600908 无锡银行
./Stock_Daily/sh600908.csv
sh600909 华安证券
./Stock_Daily/sh600909.csv
sh600916 中国黄金
./Stock_Daily/sh600916.csv
sh600917 重庆燃气
./Stock_Daily/sh600917.csv
sh600918 中泰证券
./Stock_Daily/sh600918.csv
sh600919 江苏银行
./Stock_Daily/sh600919.csv
sh600925 苏能股份
./Stock_Daily/sh600925.csv
sh600926 杭州银行
./Stock_Daily/sh600926.csv
sh600927 永安期货
./Stock_Daily/sh600927.csv
sh600928 西安银行
./Stock_Daily/sh600928.csv
sh600929 雪天盐业
./Stock_Daily/sh600929.csv
sh600933 爱柯迪
./Stock_Daily/sh600933.csv
sh600935 华塑股份
./Stock_Daily/sh600935.csv
sh600936 广西广电
./Stock_Daily/sh600936.csv
sh600938 中国海油
./Stock_Daily/sh600938.csv
sh600939 重庆建工
./Stock_Daily/sh600939.csv
sh600941 中国移动
./Stock_Daily/sh600941.csv
sh600955 维远股份
./Stock_Daily/sh600955.csv
sh600956 新天绿能
./Stock_Daily/sh600956.csv
sh600958 东方证券
./Stock_Daily/sh600958.csv
sh600959 江苏有线
./Stock_Daily/sh600959.csv
sh600960 渤海汽车
./Stock_Daily/sh600960.csv
sh600961 株冶集团
./Stock_Daily/sh600961.csv
sh600962 国投中鲁
./Stock_Daily/sh600962.csv
sh600963 岳阳林纸
./Stock_Daily/sh600963.csv
sh600965 福成股份
./Stock_Daily/sh600965.csv
sh600966 博汇纸业
./Stock_Daily/sh600966.csv
sh600967 内蒙一机
./Stock_Daily/sh600967.csv
sh600968 海油发展
./Stock_Daily/sh600968.csv
sh600969 郴电国际
./Stock_Daily/sh600969.csv
sh600970 中材国际
./Stock_Daily/sh600970.csv
sh600971 恒源煤电
./Stock_Daily/sh600971.csv
sh600973 宝胜股份
./Stock_Daily/sh600973.csv
sh600975 新五丰
./Stock_Daily/sh600975.csv
sh600976 健民集团
./Stock_Daily/sh600976.csv
sh600977 中国电影
./Stock_Daily/sh600977.csv
sh600979 广安爱众
./Stock_Daily/sh600979.csv
sh600980 北矿科技
./Stock_Daily/sh600980.csv
sh600981 汇鸿集团
./Stock_Daily/sh600981.csv
sh600982 宁波能源
./Stock_Daily/sh600982.csv
sh600983 惠而浦
./Stock_Daily/sh600983.csv
sh600984 建设机械
./Stock_Daily/sh600984.csv
sh600985 淮北矿业
./Stock_Daily/sh600985.csv
sh600986 浙文互联
./Stock_Daily/sh600986.csv
sh600987 航民股份
./Stock_Daily/sh600987.csv
sh600988 赤峰黄金
./Stock_Daily/sh600988.csv
sh600989 宝丰能源
./Stock_Daily/sh600989.csv
sh600990 四创电子
./Stock_Daily/sh600990.csv
sh600992 贵绳股份
./Stock_Daily/sh600992.csv
sh600993 马应龙
./Stock_Daily/sh600993.csv
sh600995 南网储能

./Stock_Daily/sh600995.csv
sh600996 贵广网络
./Stock_Daily/sh600996.csv
sh600997 开滦股份
./Stock_Daily/sh600997.csv
sh600998 九州通
./Stock_Daily/sh600998.csv
sh600999 招商证券
./Stock_Daily/sh600999.csv
sh601000 唐山港
./Stock_Daily/sh601000.csv
sh601001 晋控煤业
./Stock_Daily/sh601001.csv
sh601002 晋亿实业
./Stock_Daily/sh601002.csv
sh601003 柳钢股份
./Stock_Daily/sh601003.csv
sh601005 重庆钢铁
./Stock_Daily/sh601005.csv
sh601006 大秦铁路
./Stock_Daily/sh601006.csv
sh601007 金陵饭店
./Stock_Daily/sh601007.csv
sh601008 连云港
./Stock_Daily/sh601008.csv
sh601009 南京银行
./Stock_Daily/sh601009.csv
sh601010 文峰股份
./Stock_Daily/sh601010.csv
sh601011 宝泰隆
./Stock_Daily/sh601011.csv
sh601012 隆基绿能
./Stock_Daily/sh601012.csv
sh601015 陕西黑猫
./Stock_Daily/sh601015.csv
sh601016 节能风电
./Stock_Daily/sh601016.csv
sh601018 宁波港
./Stock_Daily/sh601018.csv
sh601019 山东出版
./Stock_Daily/sh601019.csv
sh601020 华钰矿业
./Stock_Daily/sh601020.csv
sh601021 春秋航空
./Stock_Daily/sh601021.csv
sh601022 宁波远洋
./Stock_Daily/sh601022.csv
sh601028 玉龙股份
./Stock_Daily/sh601028.csv
sh601038 一拖股份
./Stock_Daily/sh601038.csv
sh601058 赛轮轮胎
./Stock_Daily/sh601058.csv
sh601059 信达证券
./Stock_Daily/sh601059.csv
sh601061 中信金属
./Stock_Daily/sh601061.csv
sh601065 江盐集团
./Stock_Daily/sh601065.csv
sh601066 中信建投
./Stock_Daily/sh601066.csv
sh601068 中铝国际
./Stock_Daily/sh601068.csv
sh601069 西部黄金
./Stock_Daily/sh601069.csv
sh601077 渝农商行
./Stock_Daily/sh601077.csv
sh601086 国芳集团
./Stock_Daily/sh601086.csv
sh601088 中国神华
./Stock_Daily/sh601088.csv
sh601089 福元医药
./Stock_Daily/sh601089.csv
sh601098 中南传媒
./Stock_Daily/sh601098.csv
sh601099 太平洋
./Stock_Daily/sh601099.csv
sh601100 恒立液压
./Stock_Daily/sh601100.csv
sh601101 昊华能源
./Stock_Daily/sh601101.csv
sh601106 中国一重
./Stock_Daily/sh601106.csv
sh601107 四川成渝
./Stock_Daily/sh601107.csv
sh601108 财通证券
./Stock_Daily/sh601108.csv
sh601111 中国国航
./Stock_Daily/sh601111.csv
sh601113 华鼎股份
./Stock_Daily/sh601113.csv
sh601116 三江购物
./Stock_Daily/sh601116.csv
sh601117 中国化学
./Stock_Daily/sh601117.csv
sh601118 海南橡胶
./Stock_Daily/sh601118.csv
sh601121 宝地矿业
./Stock_Daily/sh601121.csv
sh601126 四方股份
./Stock_Daily/sh601126.csv
sh601127 赛力斯
./Stock_Daily/sh601127.csv
sh601128 常熟银行
./Stock_Daily/sh601128.csv
sh601133 柏诚股份
./Stock_Daily/sh601133.csv
sh601136 首创证券
./Stock_Daily/sh601136.csv
sh601137 博威合金
./Stock_Daily/sh601137.csv
sh601138 工业富联
./Stock_Daily/sh601138.csv
sh601139 深圳燃气
./Stock_Daily/sh601139.csv
sh601155 新城控股
./Stock_Daily/sh601155.csv
sh601156 东航物流
./Stock_Daily/sh601156.csv
sh601158 重庆水务
./Stock_Daily/sh601158.csv
sh601162 天风证券
./Stock_Daily/sh601162.csv
sh601163 三角轮胎
./Stock_Daily/sh601163.csv
sh601166 兴业银行
./Stock_Daily/sh601166.csv
sh601168 西部矿业
./Stock_Daily/sh601168.csv
sh601169 北京银行
./Stock_Daily/sh601169.csv
sh601177 杭齿前进
./Stock_Daily/sh601177.csv
sh601179 中国西电
./Stock_Daily/sh601179.csv
sh601186 中国铁建
./Stock_Daily/sh601186.csv
sh601187 厦门银行
./Stock_Daily/sh601187.csv
sh601188 龙江交通
./Stock_Daily/sh601188.csv
sh601198 东兴证券
./Stock_Daily/sh601198.csv
sh601199 江南水务
./Stock_Daily/sh601199.csv
sh601200 上海环境
./Stock_Daily/sh601200.csv
sh601208 东材科技
./Stock_Daily/sh601208.csv
sh601211 国泰君安
./Stock_Daily/sh601211.csv
sh601212 白银有色
./Stock_Daily/sh601212.csv
sh601216 君正集团
./Stock_Daily/sh601216.csv
sh601218 吉鑫科技
./Stock_Daily/sh601218.csv
sh601222 林洋能源
./Stock_Daily/sh601222.csv
sh601225 陕西煤业
./Stock_Daily/sh601225.csv
sh601226 华电重工
./Stock_Daily/sh601226.csv
sh601228 广州港
./Stock_Daily/sh601228.csv
sh601229 上海银行
./Stock_Daily/sh601229.csv
sh601231 环旭电子
./Stock_Daily/sh601231.csv
sh601233 桐昆股份
./Stock_Daily/sh601233.csv
sh601236 红塔证券
./Stock_Daily/sh601236.csv
sh601238 广汽集团
./Stock_Daily/sh601238.csv
sh601279 英利汽车
./Stock_Daily/sh601279.csv
sh601288 农业银行
./Stock_Daily/sh601288.csv
sh601298 青岛港
./Stock_Daily/sh601298.csv
sh601311 骆驼股份
./Stock_Daily/sh601311.csv
sh601318 中国平安
./Stock_Daily/sh601318.csv
sh601319 中国人保
./Stock_Daily/sh601319.csv
sh601326 秦港股份
./Stock_Daily/sh601326.csv
sh601328 交通银行
./Stock_Daily/sh601328.csv
sh601330 绿色动力
./Stock_Daily/sh601330.csv
sh601333 广深铁路
./Stock_Daily/sh601333.csv
sh601336 新华保险
./Stock_Daily/sh601336.csv
sh601339 百隆东方
./Stock_Daily/sh601339.csv
sh601360 三六零
./Stock_Daily/sh601360.csv
sh601366 利群股份
./Stock_Daily/sh601366.csv
sh601368 绿城水务
./Stock_Daily/sh601368.csv
sh601369 陕鼓动力
./Stock_Daily/sh601369.csv
sh601375 中原证券
./Stock_Daily/sh601375.csv
sh601377 兴业证券
./Stock_Daily/sh601377.csv
sh601388 怡球资源
./Stock_Daily/sh601388.csv
sh601390 中国中铁
./Stock_Daily/sh601390.csv
sh601398 工商银行
./Stock_Daily/sh601398.csv
sh601399 国机重装
./Stock_Daily/sh601399.csv
sh601456 国联证券
./Stock_Daily/sh601456.csv
sh601500 通用股份
./Stock_Daily/sh601500.csv
sh601512 中新集团
./Stock_Daily/sh601512.csv
sh601515 东峰集团
./Stock_Daily/sh601515.csv
sh601518 吉林高速
./Stock_Daily/sh601518.csv
sh601519 大智慧
./Stock_Daily/sh601519.csv
sh601528 瑞丰银行
./Stock_Daily/sh601528.csv
sh601555 东吴证券
./Stock_Daily/sh601555.csv
sh601566 九牧王
./Stock_Daily/sh601566.csv
sh601567 三星医疗
./Stock_Daily/sh601567.csv
sh601568 北元集团
./Stock_Daily/sh601568.csv
sh601577 长沙银行
./Stock_Daily/sh601577.csv
sh601579 会稽山
./Stock_Daily/sh601579.csv
sh601588 北辰实业
./Stock_Daily/sh601588.csv
sh601595 上海电影
./Stock_Daily/sh601595.csv
sh601598 中国外运
./Stock_Daily/sh601598.csv
sh601599 浙文影业
./Stock_Daily/sh601599.csv
sh601600 中国铝业
./Stock_Daily/sh601600.csv
sh601601 中国太保
./Stock_Daily/sh601601.csv
sh601606 长城军工
./Stock_Daily/sh601606.csv
sh601607 上海医药
./Stock_Daily/sh601607.csv
sh601608 中信重工
./Stock_Daily/sh601608.csv
sh601609 金田股份
./Stock_Daily/sh601609.csv
sh601611 中国核建
./Stock_Daily/sh601611.csv
sh601615 明阳智能
./Stock_Daily/sh601615.csv
sh601616 广电电气
./Stock_Daily/sh601616.csv
sh601618 中国中冶
./Stock_Daily/sh601618.csv
sh601619 嘉泽新能
./Stock_Daily/sh601619.csv
sh601628 中国人寿
./Stock_Daily/sh601628.csv
sh601633 长城汽车
./Stock_Daily/sh601633.csv
sh601636 旗滨集团
./Stock_Daily/sh601636.csv
sh601658 邮储银行
./Stock_Daily/sh601658.csv
sh601665 齐鲁银行
./Stock_Daily/sh601665.csv
sh601666 平煤股份
./Stock_Daily/sh601666.csv
sh601668 中国建筑
./Stock_Daily/sh601668.csv
sh601669 中国电建
./Stock_Daily/sh601669.csv
sh601677 明泰铝业
./Stock_Daily/sh601677.csv
sh601678 滨化股份
./Stock_Daily/sh601678.csv
sh601686 友发集团
./Stock_Daily/sh601686.csv
sh601688 华泰证券
./Stock_Daily/sh601688.csv
sh601689 拓普集团
./Stock_Daily/sh601689.csv
sh601696 中银证券
./Stock_Daily/sh601696.csv
sh601698 中国卫通
./Stock_Daily/sh601698.csv
sh601699 潞安环能
./Stock_Daily/sh601699.csv
sh601700 风范股份
./Stock_Daily/sh601700.csv
sh601702 华峰铝业
./Stock_Daily/sh601702.csv
sh601717 郑煤机
./Stock_Daily/sh601717.csv
sh601718 际华集团
./Stock_Daily/sh601718.csv
sh601727 上海电气
./Stock_Daily/sh601727.csv
sh601728 中国电信
./Stock_Daily/sh601728.csv
sh601766 中国中车
./Stock_Daily/sh601766.csv
sh601777 力帆科技
./Stock_Daily/sh601777.csv
sh601778 晶科科技
./Stock_Daily/sh601778.csv
sh601788 光大证券
./Stock_Daily/sh601788.csv
sh601789 宁波建工
./Stock_Daily/sh601789.csv
sh601798 蓝科高新
./Stock_Daily/sh601798.csv
sh601799 星宇股份
./Stock_Daily/sh601799.csv
sh601800 中国交建
./Stock_Daily/sh601800.csv
sh601801 皖新传媒
./Stock_Daily/sh601801.csv
sh601808 中海油服
./Stock_Daily/sh601808.csv
sh601811 新华文轩
./Stock_Daily/sh601811.csv
sh601816 京沪高铁
./Stock_Daily/sh601816.csv
sh601818 光大银行
./Stock_Daily/sh601818.csv
sh601825 沪农商行
./Stock_Daily/sh601825.csv
sh601827 三峰环境
./Stock_Daily/sh601827.csv
sh601828 美凯龙
./Stock_Daily/sh601828.csv
sh601838 成都银行
./Stock_Daily/sh601838.csv
sh601857 中国石油
./Stock_Daily/sh601857.csv
sh601858 中国科传
./Stock_Daily/sh601858.csv
sh601860 紫金银行
./Stock_Daily/sh601860.csv
sh601865 福莱特
./Stock_Daily/sh601865.csv
sh601866 中远海发
./Stock_Daily/sh601866.csv
sh601868 中国能建
./Stock_Daily/sh601868.csv
sh601869 长飞光纤
./Stock_Daily/sh601869.csv
sh601872 招商轮船
./Stock_Daily/sh601872.csv
sh601877 正泰电器
./Stock_Daily/sh601877.csv
sh601878 浙商证券
./Stock_Daily/sh601878.csv
sh601880 辽港股份
./Stock_Daily/sh601880.csv
sh601881 中国银河
./Stock_Daily/sh601881.csv
sh601882 海天精工
./Stock_Daily/sh601882.csv
sh601886 江河集团
./Stock_Daily/sh601886.csv
sh601888 中国中免
./Stock_Daily/sh601888.csv
sh601890 亚星锚链
./Stock_Daily/sh601890.csv
sh601898 中煤能源
./Stock_Daily/sh601898.csv
sh601899 紫金矿业
./Stock_Daily/sh601899.csv
sh601900 南方传媒
./Stock_Daily/sh601900.csv
sh601901 方正证券
./Stock_Daily/sh601901.csv
sh601908 京运通
./Stock_Daily/sh601908.csv
sh601916 浙商银行
./Stock_Daily/sh601916.csv
sh601918 新集能源
./Stock_Daily/sh601918.csv
sh601919 中远海控
./Stock_Daily/sh601919.csv
sh601921 浙版传媒

./Stock_Daily/sh601921.csv
sh601928 凤凰传媒
./Stock_Daily/sh601928.csv
sh601929 吉视传媒
./Stock_Daily/sh601929.csv
sh601933 永辉超市
./Stock_Daily/sh601933.csv
sh601939 建设银行
./Stock_Daily/sh601939.csv
sh601949 中国出版
./Stock_Daily/sh601949.csv
sh601952 苏垦农发
./Stock_Daily/sh601952.csv
sh601956 东贝集团
./Stock_Daily/sh601956.csv
sh601958 金钼股份
./Stock_Daily/sh601958.csv
sh601963 重庆银行
./Stock_Daily/sh601963.csv
sh601965 中国汽研
./Stock_Daily/sh601965.csv
sh601966 玲珑轮胎
./Stock_Daily/sh601966.csv
sh601968 宝钢包装
./Stock_Daily/sh601968.csv
sh601969 海南矿业
./Stock_Daily/sh601969.csv
sh601975 招商南油
./Stock_Daily/sh601975.csv
sh601985 中国核电
./Stock_Daily/sh601985.csv
sh601988 中国银行
./Stock_Daily/sh601988.csv
sh601989 中国重工
./Stock_Daily/sh601989.csv
sh601990 南京证券
./Stock_Daily/sh601990.csv
sh601991 大唐发电
./Stock_Daily/sh601991.csv
sh601992 金隅集团
./Stock_Daily/sh601992.csv
sh601995 中金公司
./Stock_Daily/sh601995.csv
sh601996 丰林集团
./Stock_Daily/sh601996.csv
sh601997 贵阳银行
./Stock_Daily/sh601997.csv
sh601998 中信银行
./Stock_Daily/sh601998.csv
sh601999 出版传媒
./Stock_Daily/sh601999.csv
sh603000 人民网
./Stock_Daily/sh603000.csv
sh603001 ST奥康
./Stock_Daily/sh603001.csv
sh603002 宏昌电子
./Stock_Daily/sh603002.csv
sh603003 龙宇股份
./Stock_Daily/sh603003.csv
sh603005 晶方科技
./Stock_Daily/sh603005.csv
sh603006 联明股份
./Stock_Daily/sh603006.csv
sh603007 ST花王
./Stock_Daily/sh603007.csv
sh603008 喜临门
./Stock_Daily/sh603008.csv
sh603009 北特科技
./Stock_Daily/sh603009.csv
sh603010 万盛股份
./Stock_Daily/sh603010.csv
sh603011 合锻智能
./Stock_Daily/sh603011.csv
sh603012 创力集团
./Stock_Daily/sh603012.csv
sh603013 亚普股份
./Stock_Daily/sh603013.csv
sh603015 弘讯科技
./Stock_Daily/sh603015.csv
sh603016 新宏泰
./Stock_Daily/sh603016.csv
sh603017 中衡设计
./Stock_Daily/sh603017.csv
sh603018 华设集团
./Stock_Daily/sh603018.csv
sh603019 中科曙光
./Stock_Daily/sh603019.csv
sh603020 爱普股份
./Stock_Daily/sh603020.csv
sh603021 山东华鹏
./Stock_Daily/sh603021.csv
sh603022 新通联
./Stock_Daily/sh603022.csv
sh603023 威帝股份
./Stock_Daily/sh603023.csv
sh603025 大豪科技
./Stock_Daily/sh603025.csv
sh603026 胜华新材
./Stock_Daily/sh603026.csv
sh603027 千禾味业
./Stock_Daily/sh603027.csv
sh603028 赛福天
./Stock_Daily/sh603028.csv
sh603029 天鹅股份
./Stock_Daily/sh603029.csv
sh603030 *ST全筑
./Stock_Daily/sh603030.csv
sh603031 安孚科技
./Stock_Daily/sh603031.csv
sh603032 德新科技
./Stock_Daily/sh603032.csv
sh603033 三维股份
./Stock_Daily/sh603033.csv
sh603035 常熟汽饰
./Stock_Daily/sh603035.csv
sh603036 如通股份
./Stock_Daily/sh603036.csv
sh603037 凯众股份
./Stock_Daily/sh603037.csv
sh603038 华立股份
./Stock_Daily/sh603038.csv
sh603039 泛微网络
./Stock_Daily/sh603039.csv
sh603040 新坐标
./Stock_Daily/sh603040.csv
sh603041 美思德
./Stock_Daily/sh603041.csv
sh603042 华脉科技
./Stock_Daily/sh603042.csv
sh603043 广州酒家
./Stock_Daily/sh603043.csv
sh603045 福达合金
./Stock_Daily/sh603045.csv
sh603048 浙江黎明
./Stock_Daily/sh603048.csv
sh603050 科林电气
./Stock_Daily/sh603050.csv
sh603051 鹿山新材
./Stock_Daily/sh603051.csv
sh603052 可川科技
./Stock_Daily/sh603052.csv
sh603053 成都燃气
./Stock_Daily/sh603053.csv
sh603055 台华新材
./Stock_Daily/sh603055.csv
sh603056 德邦股份
./Stock_Daily/sh603056.csv
sh603057 紫燕食品
./Stock_Daily/sh603057.csv
sh603058 永吉股份
./Stock_Daily/sh603058.csv
sh603059 倍加洁
./Stock_Daily/sh603059.csv
sh603060 国检集团
./Stock_Daily/sh603060.csv
sh603061 金海通
./Stock_Daily/sh603061.csv
sh603062 麦加芯彩
./Stock_Daily/sh603062.csv
sh603063 禾望电气
./Stock_Daily/sh603063.csv
sh603065 宿迁联盛
./Stock_Daily/sh603065.csv
sh603066 音飞储存
./Stock_Daily/sh603066.csv
sh603067 振华股份
./Stock_Daily/sh603067.csv
sh603068 博通集成
./Stock_Daily/sh603068.csv
sh603069 海汽集团
./Stock_Daily/sh603069.csv
sh603070 万控智造
./Stock_Daily/sh603070.csv
sh603071 物产环能
./Stock_Daily/sh603071.csv
sh603073 彩蝶实业
./Stock_Daily/sh603073.csv
sh603075 热威股份
./Stock_Daily/sh603075.csv
sh603076 乐惠国际
./Stock_Daily/sh603076.csv
sh603077 和邦生物
./Stock_Daily/sh603077.csv
sh603078 江化微
./Stock_Daily/sh603078.csv
sh603079 圣达生物
./Stock_Daily/sh603079.csv
sh603080 新疆火炬
./Stock_Daily/sh603080.csv
sh603081 大丰实业
./Stock_Daily/sh603081.csv
sh603083 剑桥科技
./Stock_Daily/sh603083.csv
sh603085 天成自控
./Stock_Daily/sh603085.csv
sh603086 先达股份
./Stock_Daily/sh603086.csv
sh603087 甘李药业
./Stock_Daily/sh603087.csv
sh603088 宁波精达
./Stock_Daily/sh603088.csv
sh603089 正裕工业
./Stock_Daily/sh603089.csv
sh603090 宏盛股份
./Stock_Daily/sh603090.csv
sh603093 南华期货
./Stock_Daily/sh603093.csv
sh603095 越剑智能
./Stock_Daily/sh603095.csv
sh603096 新经典
./Stock_Daily/sh603096.csv
sh603097 江苏华辰
./Stock_Daily/sh603097.csv
sh603098 森特股份
./Stock_Daily/sh603098.csv
sh603099 长白山
./Stock_Daily/sh603099.csv
sh603100 川仪股份
./Stock_Daily/sh603100.csv
sh603101 汇嘉时代
./Stock_Daily/sh603101.csv
sh603102 百合股份
./Stock_Daily/sh603102.csv
sh603103 横店影视
./Stock_Daily/sh603103.csv
sh603105 芯能科技
./Stock_Daily/sh603105.csv
sh603106 恒银科技
./Stock_Daily/sh603106.csv
sh603107 上海汽配
./Stock_Daily/sh603107.csv
sh603108 润达医疗
./Stock_Daily/sh603108.csv
sh603109 神驰机电
./Stock_Daily/sh603109.csv
sh603110 东方材料
./Stock_Daily/sh603110.csv
sh603111 康尼机电
./Stock_Daily/sh603111.csv
sh603112 华翔股份
./Stock_Daily/sh603112.csv
sh603113 金能科技
./Stock_Daily/sh603113.csv
sh603115 海星股份
./Stock_Daily/sh603115.csv
sh603116 红蜻蜓
./Stock_Daily/sh603116.csv
sh603117 ST万林
./Stock_Daily/sh603117.csv
sh603118 共进股份
./Stock_Daily/sh603118.csv
sh603119 浙江荣泰
./Stock_Daily/sh603119.csv
sh603121 华培动力
./Stock_Daily/sh603121.csv
sh603122 合富中国
./Stock_Daily/sh603122.csv
sh603123 翠微股份
./Stock_Daily/sh603123.csv
sh603125 常青科技
./Stock_Daily/sh603125.csv
sh603126 中材节能
./Stock_Daily/sh603126.csv
sh603127 昭衍新药
./Stock_Daily/sh603127.csv
sh603128 华贸物流
./Stock_Daily/sh603128.csv
sh603129 春风动力
./Stock_Daily/sh603129.csv
sh603130 云中马
./Stock_Daily/sh603130.csv
sh603131 上海沪工
./Stock_Daily/sh603131.csv
sh603132 金徽股份
./Stock_Daily/sh603132.csv
sh603133 *ST碳元
./Stock_Daily/sh603133.csv
sh603135 中重科技
./Stock_Daily/sh603135.csv
sh603136 天目湖
./Stock_Daily/sh603136.csv
sh603137 恒尚节能
./Stock_Daily/sh603137.csv
sh603138 海量数据
./Stock_Daily/sh603138.csv
sh603139 康惠制药
./Stock_Daily/sh603139.csv
sh603150 万朗磁塑
./Stock_Daily/sh603150.csv
sh603151 邦基科技
./Stock_Daily/sh603151.csv
sh603153 上海建科
./Stock_Daily/sh603153.csv
sh603155 新亚强
./Stock_Daily/sh603155.csv
sh603156 养元饮品
./Stock_Daily/sh603156.csv
sh603158 腾龙股份
./Stock_Daily/sh603158.csv
sh603159 上海亚虹
./Stock_Daily/sh603159.csv
sh603160 汇顶科技
./Stock_Daily/sh603160.csv
sh603161 科华控股
./Stock_Daily/sh603161.csv
sh603162 海通发展
./Stock_Daily/sh603162.csv
sh603163 圣晖集成
./Stock_Daily/sh603163.csv
sh603165 荣晟环保
./Stock_Daily/sh603165.csv
sh603166 福达股份
./Stock_Daily/sh603166.csv
sh603167 渤海轮渡
./Stock_Daily/sh603167.csv
sh603168 莎普爱思
./Stock_Daily/sh603168.csv
sh603169 兰石重装
./Stock_Daily/sh603169.csv
sh603170 宝立食品
./Stock_Daily/sh603170.csv
sh603171 税友股份
./Stock_Daily/sh603171.csv
sh603172 万丰股份
./Stock_Daily/sh603172.csv
sh603173 福斯达
./Stock_Daily/sh603173.csv
sh603176 汇通集团
./Stock_Daily/sh603176.csv
sh603177 德创环保
./Stock_Daily/sh603177.csv
sh603178 圣龙股份
./Stock_Daily/sh603178.csv
sh603179 新泉股份
./Stock_Daily/sh603179.csv
sh603180 金牌厨柜
./Stock_Daily/sh603180.csv
sh603181 皇马科技
./Stock_Daily/sh603181.csv
sh603182 嘉华股份
./Stock_Daily/sh603182.csv
sh603183 建研院
./Stock_Daily/sh603183.csv
sh603185 弘元绿能
./Stock_Daily/sh603185.csv
sh603186 华正新材
./Stock_Daily/sh603186.csv
sh603187 海容冷链
./Stock_Daily/sh603187.csv
sh603188 亚邦股份
./Stock_Daily/sh603188.csv
sh603189 网达软件
./Stock_Daily/sh603189.csv
sh603190 亚通精工
./Stock_Daily/sh603190.csv
sh603191 望变电气
./Stock_Daily/sh603191.csv
sh603192 汇得科技
./Stock_Daily/sh603192.csv
sh603193 润本股份
./Stock_Daily/sh603193.csv
sh603195 公牛集团
./Stock_Daily/sh603195.csv
sh603196 日播时尚
./Stock_Daily/sh603196.csv
sh603197 保隆科技
./Stock_Daily/sh603197.csv
sh603198 迎驾贡酒
./Stock_Daily/sh603198.csv
sh603199 九华旅游
./Stock_Daily/sh603199.csv
sh603200 上海洗霸
./Stock_Daily/sh603200.csv
sh603201 常润股份
./Stock_Daily/sh603201.csv
sh603203 快克智能
./Stock_Daily/sh603203.csv
sh603206 嘉环科技
./Stock_Daily/sh603206.csv
sh603208 江山欧派
./Stock_Daily/sh603208.csv
sh603209 兴通股份
./Stock_Daily/sh603209.csv
sh603211 晋拓股份
./Stock_Daily/sh603211.csv
sh603212 赛伍技术
./Stock_Daily/sh603212.csv
sh603213 镇洋发展
./Stock_Daily/sh603213.csv
sh603214 爱婴室
./Stock_Daily/sh603214.csv
sh603215 比依股份
./Stock_Daily/sh603215.csv
sh603216 梦天家居
./Stock_Daily/sh603216.csv
sh603217 元利科技
./Stock_Daily/sh603217.csv
sh603218 日月股份
./Stock_Daily/sh603218.csv
sh603219 富佳股份
./Stock_Daily/sh603219.csv
sh603220 中贝通信

./Stock_Daily/sh603220.csv
sh603221 爱丽家居
./Stock_Daily/sh603221.csv
sh603222 济民医疗
./Stock_Daily/sh603222.csv
sh603223 恒通股份
./Stock_Daily/sh603223.csv
sh603225 新凤鸣
./Stock_Daily/sh603225.csv
sh603226 菲林格尔
./Stock_Daily/sh603226.csv
sh603227 雪峰科技
./Stock_Daily/sh603227.csv
sh603228 景旺电子
./Stock_Daily/sh603228.csv
sh603229 奥翔药业
./Stock_Daily/sh603229.csv
sh603230 内蒙新华
./Stock_Daily/sh603230.csv
sh603232 格尔软件
./Stock_Daily/sh603232.csv
sh603233 大参林
./Stock_Daily/sh603233.csv
sh603235 天新药业
./Stock_Daily/sh603235.csv
sh603236 移远通信
./Stock_Daily/sh603236.csv
sh603237 五芳斋
./Stock_Daily/sh603237.csv
sh603238 诺邦股份
./Stock_Daily/sh603238.csv
sh603239 浙江仙通
./Stock_Daily/sh603239.csv
sh603255 鼎际得
./Stock_Daily/sh603255.csv
sh603256 宏和科技
./Stock_Daily/sh603256.csv
sh603258 电魂网络
./Stock_Daily/sh603258.csv
sh603259 药明康德
./Stock_Daily/sh603259.csv
sh603260 合盛硅业
./Stock_Daily/sh603260.csv
sh603261 立航科技
./Stock_Daily/sh603261.csv
sh603266 天龙股份
./Stock_Daily/sh603266.csv
sh603267 鸿远电子
./Stock_Daily/sh603267.csv
sh603268 松发股份
./Stock_Daily/sh603268.csv
sh603269 海鸥股份
./Stock_Daily/sh603269.csv
sh603270 金帝股份
./Stock_Daily/sh603270.csv
sh603272 联翔股份
./Stock_Daily/sh603272.csv
sh603273 天元智能
./Stock_Daily/sh603273.csv
sh603275 众辰科技
./Stock_Daily/sh603275.csv
sh603276 恒兴新材
./Stock_Daily/sh603276.csv
sh603277 银都股份
./Stock_Daily/sh603277.csv
sh603278 大业股份
./Stock_Daily/sh603278.csv
sh603279 景津装备
./Stock_Daily/sh603279.csv
sh603280 南方路机
./Stock_Daily/sh603280.csv
sh603281 江瀚新材
./Stock_Daily/sh603281.csv
sh603282 亚光股份
./Stock_Daily/sh603282.csv
sh603283 赛腾股份
./Stock_Daily/sh603283.csv
sh603286 日盈电子
./Stock_Daily/sh603286.csv
sh603288 海天味业
./Stock_Daily/sh603288.csv
sh603289 泰瑞机器
./Stock_Daily/sh603289.csv
sh603290 斯达半导
./Stock_Daily/sh603290.csv
sh603291 联合水务
./Stock_Daily/sh603291.csv
sh603296 华勤技术
./Stock_Daily/sh603296.csv
sh603297 永新光学
./Stock_Daily/sh603297.csv
sh603298 杭叉集团
./Stock_Daily/sh603298.csv
sh603299 苏盐井神
./Stock_Daily/sh603299.csv
sh603300 华铁应急
./Stock_Daily/sh603300.csv
sh603301 振德医疗
./Stock_Daily/sh603301.csv
sh603303 得邦照明
./Stock_Daily/sh603303.csv
sh603305 旭升集团
./Stock_Daily/sh603305.csv
sh603306 华懋科技
./Stock_Daily/sh603306.csv
sh603307 扬州金泉
./Stock_Daily/sh603307.csv
sh603308 应流股份
./Stock_Daily/sh603308.csv
sh603309 维力医疗
./Stock_Daily/sh603309.csv
sh603311 金海高科
./Stock_Daily/sh603311.csv
sh603313 梦百合
./Stock_Daily/sh603313.csv
sh603315 福鞍股份
./Stock_Daily/sh603315.csv
sh603316 诚邦股份
./Stock_Daily/sh603316.csv
sh603317 天味食品
./Stock_Daily/sh603317.csv
sh603318 水发燃气
./Stock_Daily/sh603318.csv
sh603319 湘油泵
./Stock_Daily/sh603319.csv
sh603320 迪贝电气
./Stock_Daily/sh603320.csv
sh603321 梅轮电梯
./Stock_Daily/sh603321.csv
sh603322 超讯通信
./Stock_Daily/sh603322.csv
sh603323 苏农银行
./Stock_Daily/sh603323.csv
sh603324 盛剑环境
./Stock_Daily/sh603324.csv
sh603326 我乐家居
./Stock_Daily/sh603326.csv
sh603327 福蓉科技
./Stock_Daily/sh603327.csv
sh603328 依顿电子
./Stock_Daily/sh603328.csv
sh603329 上海雅仕
./Stock_Daily/sh603329.csv
sh603330 天洋新材
./Stock_Daily/sh603330.csv
sh603331 百达精工
./Stock_Daily/sh603331.csv
sh603332 苏州龙杰
./Stock_Daily/sh603332.csv
sh603333 尚纬股份
./Stock_Daily/sh603333.csv
sh603335 迪生力
./Stock_Daily/sh603335.csv
sh603336 宏辉果蔬
./Stock_Daily/sh603336.csv
sh603337 杰克股份
./Stock_Daily/sh603337.csv
sh603338 浙江鼎力
./Stock_Daily/sh603338.csv
sh603339 四方科技
./Stock_Daily/sh603339.csv
sh603345 安井食品
./Stock_Daily/sh603345.csv
sh603348 文灿股份
./Stock_Daily/sh603348.csv
sh603351 威尔药业
./Stock_Daily/sh603351.csv
sh603353 和顺石油
./Stock_Daily/sh603353.csv
sh603355 莱克电气
./Stock_Daily/sh603355.csv
sh603356 华菱精工
./Stock_Daily/sh603356.csv
sh603357 设计总院
./Stock_Daily/sh603357.csv
sh603358 华达科技
./Stock_Daily/sh603358.csv
sh603359 东珠生态
./Stock_Daily/sh603359.csv
sh603360 百傲化学
./Stock_Daily/sh603360.csv
sh603363 傲农生物
./Stock_Daily/sh603363.csv
sh603365 水星家纺
./Stock_Daily/sh603365.csv
sh603366 日出东方
./Stock_Daily/sh603366.csv
sh603367 辰欣药业
./Stock_Daily/sh603367.csv
sh603368 柳药集团
./Stock_Daily/sh603368.csv
sh603369 今世缘
./Stock_Daily/sh603369.csv
sh603377 东方时尚
./Stock_Daily/sh603377.csv
sh603378 亚士创能
./Stock_Daily/sh603378.csv
sh603379 三美股份
./Stock_Daily/sh603379.csv
sh603380 易德龙
./Stock_Daily/sh603380.csv
sh603383 顶点软件
./Stock_Daily/sh603383.csv
sh603385 惠达卫浴
./Stock_Daily/sh603385.csv
sh603386 骏亚科技
./Stock_Daily/sh603386.csv
sh603387 基蛋生物
./Stock_Daily/sh603387.csv
sh603388 元成股份
./Stock_Daily/sh603388.csv
sh603389 亚振家居
./Stock_Daily/sh603389.csv
sh603390 通达电气
./Stock_Daily/sh603390.csv
sh603392 万泰生物
./Stock_Daily/sh603392.csv
sh603393 新天然气
./Stock_Daily/sh603393.csv
sh603396 金辰股份
./Stock_Daily/sh603396.csv
sh603398 沐邦高科
./Stock_Daily/sh603398.csv
sh603399 吉翔股份
./Stock_Daily/sh603399.csv
sh603408 建霖家居
./Stock_Daily/sh603408.csv
sh603416 信捷电气
./Stock_Daily/sh603416.csv
sh603421 鼎信通讯
./Stock_Daily/sh603421.csv
sh603429 集友股份
./Stock_Daily/sh603429.csv
sh603439 贵州三力
./Stock_Daily/sh603439.csv
sh603444 吉比特
./Stock_Daily/sh603444.csv
sh603456 九洲药业
./Stock_Daily/sh603456.csv
sh603458 勘设股份
./Stock_Daily/sh603458.csv
sh603466 风语筑
./Stock_Daily/sh603466.csv
sh603477 巨星农牧
./Stock_Daily/sh603477.csv
sh603486 科沃斯
./Stock_Daily/sh603486.csv
sh603488 展鹏科技
./Stock_Daily/sh603488.csv
sh603489 八方股份
./Stock_Daily/sh603489.csv
sh603496 恒为科技
./Stock_Daily/sh603496.csv
sh603499 翔港科技
./Stock_Daily/sh603499.csv
sh603500 祥和实业
./Stock_Daily/sh603500.csv
sh603501 韦尔股份
./Stock_Daily/sh603501.csv
sh603505 金石资源
./Stock_Daily/sh603505.csv
sh603506 南都物业
./Stock_Daily/sh603506.csv
sh603507 振江股份
./Stock_Daily/sh603507.csv
sh603508 思维列控
./Stock_Daily/sh603508.csv
sh603511 爱慕股份
./Stock_Daily/sh603511.csv
sh603515 欧普照明
./Stock_Daily/sh603515.csv
sh603516 淳中科技
./Stock_Daily/sh603516.csv
sh603517 绝味食品
./Stock_Daily/sh603517.csv
sh603518 锦泓集团
./Stock_Daily/sh603518.csv
sh603519 立霸股份
./Stock_Daily/sh603519.csv
sh603520 司太立
./Stock_Daily/sh603520.csv
sh603527 众源新材
./Stock_Daily/sh603527.csv
sh603528 多伦科技
./Stock_Daily/sh603528.csv
sh603529 爱玛科技
./Stock_Daily/sh603529.csv
sh603530 神马电力
./Stock_Daily/sh603530.csv
sh603533 掌阅科技
./Stock_Daily/sh603533.csv
sh603535 嘉诚国际
./Stock_Daily/sh603535.csv
sh603536 惠发食品
./Stock_Daily/sh603536.csv
sh603538 美诺华
./Stock_Daily/sh603538.csv
sh603551 奥普家居
./Stock_Daily/sh603551.csv
sh603555 ST贵人
./Stock_Daily/sh603555.csv
sh603556 海兴电力
./Stock_Daily/sh603556.csv
sh603557 ST起步
./Stock_Daily/sh603557.csv
sh603558 健盛集团
./Stock_Daily/sh603558.csv
sh603559 ST通脉
./Stock_Daily/sh603559.csv
sh603565 中谷物流
./Stock_Daily/sh603565.csv
sh603566 普莱柯
./Stock_Daily/sh603566.csv
sh603567 珍宝岛
./Stock_Daily/sh603567.csv
sh603568 伟明环保
./Stock_Daily/sh603568.csv
sh603569 长久物流
./Stock_Daily/sh603569.csv
sh603577 汇金通
./Stock_Daily/sh603577.csv
sh603578 三星新材
./Stock_Daily/sh603578.csv
sh603579 荣泰健康
./Stock_Daily/sh603579.csv
sh603580 艾艾精工
./Stock_Daily/sh603580.csv
sh603583 捷昌驱动
./Stock_Daily/sh603583.csv
sh603585 苏利股份
./Stock_Daily/sh603585.csv
sh603586 金麒麟
./Stock_Daily/sh603586.csv
sh603587 地素时尚
./Stock_Daily/sh603587.csv
sh603588 高能环境
./Stock_Daily/sh603588.csv
sh603589 口子窖
./Stock_Daily/sh603589.csv
sh603590 康辰药业
./Stock_Daily/sh603590.csv
sh603595 东尼电子
./Stock_Daily/sh603595.csv
sh603596 伯特利
./Stock_Daily/sh603596.csv
sh603598 引力传媒
./Stock_Daily/sh603598.csv
sh603599 广信股份
./Stock_Daily/sh603599.csv
sh603600 永艺股份
./Stock_Daily/sh603600.csv
sh603601 再升科技
./Stock_Daily/sh603601.csv
sh603602 纵横通信
./Stock_Daily/sh603602.csv
sh603603 *ST博天
./Stock_Daily/sh603603.csv
sh603605 珀莱雅
./Stock_Daily/sh603605.csv
sh603606 东方电缆
./Stock_Daily/sh603606.csv
sh603607 京华激光
./Stock_Daily/sh603607.csv
sh603608 天创时尚
./Stock_Daily/sh603608.csv
sh603609 禾丰股份
./Stock_Daily/sh603609.csv
sh603610 麒盛科技
./Stock_Daily/sh603610.csv
sh603611 诺力股份
./Stock_Daily/sh603611.csv
sh603612 索通发展
./Stock_Daily/sh603612.csv
sh603613 国联股份
./Stock_Daily/sh603613.csv
sh603615 茶花股份
./Stock_Daily/sh603615.csv
sh603616 韩建河山
./Stock_Daily/sh603616.csv
sh603617 君禾股份
./Stock_Daily/sh603617.csv
sh603618 杭电股份
./Stock_Daily/sh603618.csv
sh603619 中曼石油
./Stock_Daily/sh603619.csv
sh603626 科森科技
./Stock_Daily/sh603626.csv
sh603628 清源股份
./Stock_Daily/sh603628.csv
sh603629 利通电子
./Stock_Daily/sh603629.csv
sh603630 拉芳家化
./Stock_Daily/sh603630.csv
sh603633 徕木股份
./Stock_Daily/sh603633.csv
sh603636 南威软件
./Stock_Daily/sh603636.csv
sh603637 镇海股份
./Stock_Daily/sh603637.csv
sh603638 艾迪精密
./Stock_Daily/sh603638.csv
sh603639 海利尔

./Stock_Daily/sh603639.csv
sh603648 畅联股份
./Stock_Daily/sh603648.csv
sh603650 彤程新材
./Stock_Daily/sh603650.csv
sh603655 朗博科技
./Stock_Daily/sh603655.csv
sh603656 泰禾智能
./Stock_Daily/sh603656.csv
sh603657 春光科技
./Stock_Daily/sh603657.csv
sh603658 安图生物
./Stock_Daily/sh603658.csv
sh603659 璞泰来
./Stock_Daily/sh603659.csv
sh603660 苏州科达
./Stock_Daily/sh603660.csv
sh603661 恒林股份
./Stock_Daily/sh603661.csv
sh603662 柯力传感
./Stock_Daily/sh603662.csv
sh603663 三祥新材
./Stock_Daily/sh603663.csv
sh603665 康隆达
./Stock_Daily/sh603665.csv
sh603666 亿嘉和
./Stock_Daily/sh603666.csv
sh603667 五洲新春
./Stock_Daily/sh603667.csv
sh603668 天马科技
./Stock_Daily/sh603668.csv
sh603669 灵康药业
./Stock_Daily/sh603669.csv
sh603676 卫信康
./Stock_Daily/sh603676.csv
sh603677 奇精机械
./Stock_Daily/sh603677.csv
sh603678 火炬电子
./Stock_Daily/sh603678.csv
sh603679 华体科技
./Stock_Daily/sh603679.csv
sh603680 今创集团
./Stock_Daily/sh603680.csv
sh603681 永冠新材
./Stock_Daily/sh603681.csv
sh603682 锦和商管
./Stock_Daily/sh603682.csv
sh603683 晶华新材
./Stock_Daily/sh603683.csv
sh603685 晨丰科技
./Stock_Daily/sh603685.csv
sh603686 福龙马
./Stock_Daily/sh603686.csv
sh603687 大胜达
./Stock_Daily/sh603687.csv
sh603688 石英股份
./Stock_Daily/sh603688.csv
sh603689 皖天然气
./Stock_Daily/sh603689.csv
sh603690 至纯科技
./Stock_Daily/sh603690.csv
sh603693 江苏新能
./Stock_Daily/sh603693.csv
sh603696 安记食品
./Stock_Daily/sh603696.csv
sh603697 有友食品
./Stock_Daily/sh603697.csv
sh603698 航天工程
./Stock_Daily/sh603698.csv
sh603699 纽威股份
./Stock_Daily/sh603699.csv
sh603700 宁水集团
./Stock_Daily/sh603700.csv
sh603701 德宏股份
./Stock_Daily/sh603701.csv
sh603703 盛洋科技
./Stock_Daily/sh603703.csv
sh603706 东方环宇
./Stock_Daily/sh603706.csv
sh603707 健友股份
./Stock_Daily/sh603707.csv
sh603708 家家悦
./Stock_Daily/sh603708.csv
sh603709 中源家居
./Stock_Daily/sh603709.csv
sh603711 香飘飘
./Stock_Daily/sh603711.csv
sh603712 七一二
./Stock_Daily/sh603712.csv
sh603713 密尔克卫
./Stock_Daily/sh603713.csv
sh603716 塞力医疗
./Stock_Daily/sh603716.csv
sh603717 天域生态
./Stock_Daily/sh603717.csv
sh603718 海利生物
./Stock_Daily/sh603718.csv
sh603719 良品铺子
./Stock_Daily/sh603719.csv
sh603721 中广天择
./Stock_Daily/sh603721.csv
sh603722 阿科力
./Stock_Daily/sh603722.csv
sh603725 天安新材
./Stock_Daily/sh603725.csv
sh603726 朗迪集团
./Stock_Daily/sh603726.csv
sh603727 博迈科
./Stock_Daily/sh603727.csv
sh603728 鸣志电器
./Stock_Daily/sh603728.csv
sh603729 龙韵股份
./Stock_Daily/sh603729.csv
sh603730 岱美股份
./Stock_Daily/sh603730.csv
sh603733 仙鹤股份
./Stock_Daily/sh603733.csv
sh603737 三棵树
./Stock_Daily/sh603737.csv
sh603738 泰晶科技
./Stock_Daily/sh603738.csv
sh603739 蔚蓝生物
./Stock_Daily/sh603739.csv
sh603755 日辰股份
./Stock_Daily/sh603755.csv
sh603757 大元泵业
./Stock_Daily/sh603757.csv
sh603758 秦安股份
./Stock_Daily/sh603758.csv
sh603759 海天股份
./Stock_Daily/sh603759.csv
sh603766 隆鑫通用
./Stock_Daily/sh603766.csv
sh603767 中马传动
./Stock_Daily/sh603767.csv
sh603768 常青股份
./Stock_Daily/sh603768.csv
sh603773 沃格光电
./Stock_Daily/sh603773.csv
sh603776 永安行
./Stock_Daily/sh603776.csv
sh603777 来伊份
./Stock_Daily/sh603777.csv
sh603778 乾景园林
./Stock_Daily/sh603778.csv
sh603779 威龙股份
./Stock_Daily/sh603779.csv
sh603786 科博达
./Stock_Daily/sh603786.csv
sh603787 新日股份
./Stock_Daily/sh603787.csv
sh603788 宁波高发
./Stock_Daily/sh603788.csv
sh603789 星光农机
./Stock_Daily/sh603789.csv
sh603790 雅运股份
./Stock_Daily/sh603790.csv
sh603797 联泰环保
./Stock_Daily/sh603797.csv
sh603798 康普顿
./Stock_Daily/sh603798.csv
sh603799 华友钴业
./Stock_Daily/sh603799.csv
sh603800 道森股份
./Stock_Daily/sh603800.csv
sh603801 志邦家居
./Stock_Daily/sh603801.csv
sh603803 瑞斯康达
./Stock_Daily/sh603803.csv
sh603806 福斯特
./Stock_Daily/sh603806.csv
sh603808 歌力思
./Stock_Daily/sh603808.csv
sh603809 豪能股份
./Stock_Daily/sh603809.csv
sh603810 丰山集团
./Stock_Daily/sh603810.csv
sh603811 诚意药业
./Stock_Daily/sh603811.csv
sh603813 原尚股份
./Stock_Daily/sh603813.csv
sh603815 交建股份
./Stock_Daily/sh603815.csv
sh603816 顾家家居
./Stock_Daily/sh603816.csv
sh603817 海峡环保
./Stock_Daily/sh603817.csv
sh603818 曲美家居
./Stock_Daily/sh603818.csv
sh603819 神力股份
./Stock_Daily/sh603819.csv
sh603822 嘉澳环保
./Stock_Daily/sh603822.csv
sh603823 百合花
./Stock_Daily/sh603823.csv
sh603825 华扬联众
./Stock_Daily/sh603825.csv
sh603826 坤彩科技
./Stock_Daily/sh603826.csv
sh603828 柯利达
./Stock_Daily/sh603828.csv
sh603829 洛凯股份
./Stock_Daily/sh603829.csv
sh603833 欧派家居
./Stock_Daily/sh603833.csv
sh603836 海程邦达
./Stock_Daily/sh603836.csv
sh603838 四通股份
./Stock_Daily/sh603838.csv
sh603839 安正时尚
./Stock_Daily/sh603839.csv
sh603843 正平股份
./Stock_Daily/sh603843.csv
sh603848 好太太
./Stock_Daily/sh603848.csv
sh603855 华荣股份
./Stock_Daily/sh603855.csv
sh603856 东宏股份
./Stock_Daily/sh603856.csv
sh603858 步长制药
./Stock_Daily/sh603858.csv
sh603859 能科科技
./Stock_Daily/sh603859.csv
sh603860 中公高科
./Stock_Daily/sh603860.csv
sh603861 白云电器
./Stock_Daily/sh603861.csv
sh603863 松炀资源
./Stock_Daily/sh603863.csv
sh603866 桃李面包
./Stock_Daily/sh603866.csv
sh603867 新化股份
./Stock_Daily/sh603867.csv
sh603868 飞科电器
./Stock_Daily/sh603868.csv
sh603869 新智认知
./Stock_Daily/sh603869.csv
sh603871 嘉友国际
./Stock_Daily/sh603871.csv
sh603876 鼎胜新材
./Stock_Daily/sh603876.csv
sh603877 太平鸟
./Stock_Daily/sh603877.csv
sh603878 武进不锈
./Stock_Daily/sh603878.csv
sh603879 永悦科技
./Stock_Daily/sh603879.csv
sh603880 ST南卫
./Stock_Daily/sh603880.csv
sh603881 数据港
./Stock_Daily/sh603881.csv
sh603882 金域医学
./Stock_Daily/sh603882.csv
sh603883 老百姓
./Stock_Daily/sh603883.csv
sh603885 吉祥航空
./Stock_Daily/sh603885.csv
sh603886 元祖股份
./Stock_Daily/sh603886.csv
sh603887 城地香江
./Stock_Daily/sh603887.csv
sh603888 新华网
./Stock_Daily/sh603888.csv
sh603889 新澳股份
./Stock_Daily/sh603889.csv
sh603890 春秋电子
./Stock_Daily/sh603890.csv
sh603893 瑞芯微
./Stock_Daily/sh603893.csv
sh603895 天永智能
./Stock_Daily/sh603895.csv
sh603896 寿仙谷
./Stock_Daily/sh603896.csv
sh603897 长城科技
./Stock_Daily/sh603897.csv
sh603898 好莱客
./Stock_Daily/sh603898.csv
sh603899 晨光股份
./Stock_Daily/sh603899.csv
sh603900 莱绅通灵
./Stock_Daily/sh603900.csv
sh603901 永创智能
./Stock_Daily/sh603901.csv
sh603903 中持股份
./Stock_Daily/sh603903.csv
sh603906 龙蟠科技
./Stock_Daily/sh603906.csv
sh603908 牧高笛
./Stock_Daily/sh603908.csv
sh603909 建发合诚
./Stock_Daily/sh603909.csv
sh603912 佳力图
./Stock_Daily/sh603912.csv
sh603915 国茂股份
./Stock_Daily/sh603915.csv
sh603916 苏博特
./Stock_Daily/sh603916.csv
sh603917 合力科技
./Stock_Daily/sh603917.csv
sh603918 金桥信息
./Stock_Daily/sh603918.csv
sh603919 金徽酒
./Stock_Daily/sh603919.csv
sh603920 世运电路
./Stock_Daily/sh603920.csv
sh603922 金鸿顺
./Stock_Daily/sh603922.csv
sh603926 铁流股份
./Stock_Daily/sh603926.csv
sh603927 中科软
./Stock_Daily/sh603927.csv
sh603928 兴业股份
./Stock_Daily/sh603928.csv
sh603929 亚翔集成
./Stock_Daily/sh603929.csv
sh603931 格林达
./Stock_Daily/sh603931.csv
sh603933 睿能科技
./Stock_Daily/sh603933.csv
sh603936 博敏电子
./Stock_Daily/sh603936.csv
sh603937 丽岛新材
./Stock_Daily/sh603937.csv
sh603938 三孚股份
./Stock_Daily/sh603938.csv
sh603939 益丰药房
./Stock_Daily/sh603939.csv
sh603948 建业股份
./Stock_Daily/sh603948.csv
sh603949 雪龙集团
./Stock_Daily/sh603949.csv
sh603950 长源东谷
./Stock_Daily/sh603950.csv
sh603955 大千生态
./Stock_Daily/sh603955.csv
sh603956 威派格
./Stock_Daily/sh603956.csv
sh603958 哈森股份
./Stock_Daily/sh603958.csv
sh603959 百利科技
./Stock_Daily/sh603959.csv
sh603960 克来机电
./Stock_Daily/sh603960.csv
sh603963 大理药业
./Stock_Daily/sh603963.csv
sh603966 法兰泰克
./Stock_Daily/sh603966.csv
sh603967 中创物流
./Stock_Daily/sh603967.csv
sh603968 醋化股份
./Stock_Daily/sh603968.csv
sh603969 银龙股份
./Stock_Daily/sh603969.csv
sh603970 中农立华
./Stock_Daily/sh603970.csv
sh603976 正川股份
./Stock_Daily/sh603976.csv
sh603977 国泰集团
./Stock_Daily/sh603977.csv
sh603978 深圳新星
./Stock_Daily/sh603978.csv
sh603979 金诚信
./Stock_Daily/sh603979.csv
sh603980 吉华集团
./Stock_Daily/sh603980.csv
sh603982 泉峰汽车
./Stock_Daily/sh603982.csv
sh603983 丸美股份
./Stock_Daily/sh603983.csv
sh603985 恒润股份
./Stock_Daily/sh603985.csv
sh603986 兆易创新
./Stock_Daily/sh603986.csv
sh603987 康德莱
./Stock_Daily/sh603987.csv
sh603988 中电电机
./Stock_Daily/sh603988.csv
sh603989 艾华集团
./Stock_Daily/sh603989.csv
sh603990 麦迪科技
./Stock_Daily/sh603990.csv
sh603991 至正股份
./Stock_Daily/sh603991.csv
sh603992 松霖科技
./Stock_Daily/sh603992.csv
sh603993 洛阳钼业
./Stock_Daily/sh603993.csv
sh603995 甬金股份
./Stock_Daily/sh603995.csv
sh603997 继峰股份
./Stock_Daily/sh603997.csv
sh603998 方盛制药
./Stock_Daily/sh603998.csv
sh603999 读者传媒
./Stock_Daily/sh603999.csv
sh605001 威奥股份
./Stock_Daily/sh605001.csv
sh605003 众望布艺
./Stock_Daily/sh605003.csv
sh605005 合兴股份
./Stock_Daily/sh605005.csv
sh605006 山东玻纤

./Stock_Daily/sh605006.csv
sh605007 五洲特纸
./Stock_Daily/sh605007.csv
sh605008 长鸿高科
./Stock_Daily/sh605008.csv
sh605009 豪悦护理
./Stock_Daily/sh605009.csv
sh605011 杭州热电
./Stock_Daily/sh605011.csv
sh605016 百龙创园
./Stock_Daily/sh605016.csv
sh605018 长华集团
./Stock_Daily/sh605018.csv
sh605020 永和股份
./Stock_Daily/sh605020.csv
sh605028 世茂能源
./Stock_Daily/sh605028.csv
sh605033 美邦股份
./Stock_Daily/sh605033.csv
sh605050 福然德
./Stock_Daily/sh605050.csv
sh605055 迎丰股份
./Stock_Daily/sh605055.csv
sh605056 咸亨国际
./Stock_Daily/sh605056.csv
sh605058 澳弘电子
./Stock_Daily/sh605058.csv
sh605060 联德股份
./Stock_Daily/sh605060.csv
sh605066 天正电气
./Stock_Daily/sh605066.csv
sh605068 明新旭腾
./Stock_Daily/sh605068.csv
sh605069 正和生态
./Stock_Daily/sh605069.csv
sh605077 华康股份
./Stock_Daily/sh605077.csv
sh605080 浙江自然
./Stock_Daily/sh605080.csv
sh605081 太和水
./Stock_Daily/sh605081.csv
sh605086 龙高股份
./Stock_Daily/sh605086.csv
sh605088 冠盛股份
./Stock_Daily/sh605088.csv
sh605089 味知香
./Stock_Daily/sh605089.csv
sh605090 九丰能源
./Stock_Daily/sh605090.csv
sh605098 行动教育
./Stock_Daily/sh605098.csv
sh605099 共创草坪
./Stock_Daily/sh605099.csv
sh605100 华丰股份
./Stock_Daily/sh605100.csv
sh605108 同庆楼
./Stock_Daily/sh605108.csv
sh605111 新洁能
./Stock_Daily/sh605111.csv
sh605116 奥锐特
./Stock_Daily/sh605116.csv
sh605117 德业股份
./Stock_Daily/sh605117.csv
sh605118 力鼎光电
./Stock_Daily/sh605118.csv
sh605122 四方新材
./Stock_Daily/sh605122.csv
sh605123 派克新材
./Stock_Daily/sh605123.csv
sh605128 上海沿浦
./Stock_Daily/sh605128.csv
sh605133 嵘泰股份
./Stock_Daily/sh605133.csv
sh605136 丽人丽妆
./Stock_Daily/sh605136.csv
sh605138 盛泰集团
./Stock_Daily/sh605138.csv
sh605151 西上海
./Stock_Daily/sh605151.csv
sh605155 西大门
./Stock_Daily/sh605155.csv
sh605158 华达新材
./Stock_Daily/sh605158.csv
sh605162 新中港
./Stock_Daily/sh605162.csv
sh605166 聚合顺
./Stock_Daily/sh605166.csv
sh605167 利柏特
./Stock_Daily/sh605167.csv
sh605168 三人行
./Stock_Daily/sh605168.csv
sh605169 洪通燃气
./Stock_Daily/sh605169.csv
sh605177 东亚药业
./Stock_Daily/sh605177.csv
sh605178 时空科技
./Stock_Daily/sh605178.csv
sh605179 一鸣食品
./Stock_Daily/sh605179.csv
sh605180 华生科技
./Stock_Daily/sh605180.csv
sh605183 确成股份
./Stock_Daily/sh605183.csv
sh605186 健麾信息
./Stock_Daily/sh605186.csv
sh605188 国光连锁
./Stock_Daily/sh605188.csv
sh605189 富春染织
./Stock_Daily/sh605189.csv
sh605196 华通线缆
./Stock_Daily/sh605196.csv
sh605198 安德利
./Stock_Daily/sh605198.csv
sh605199 葫芦娃
./Stock_Daily/sh605199.csv
sh605208 永茂泰
./Stock_Daily/sh605208.csv
sh605218 伟时电子
./Stock_Daily/sh605218.csv
sh605222 起帆电缆
./Stock_Daily/sh605222.csv
sh605228 神通科技
./Stock_Daily/sh605228.csv
sh605255 天普股份
./Stock_Daily/sh605255.csv
sh605258 协和电子
./Stock_Daily/sh605258.csv
sh605259 绿田机械
./Stock_Daily/sh605259.csv
sh605266 健之佳
./Stock_Daily/sh605266.csv
sh605268 王力安防
./Stock_Daily/sh605268.csv
sh605277 新亚电子
./Stock_Daily/sh605277.csv
sh605286 同力日升
./Stock_Daily/sh605286.csv
sh605287 德才股份
./Stock_Daily/sh605287.csv
sh605288 凯迪股份
./Stock_Daily/sh605288.csv
sh605289 罗曼股份
./Stock_Daily/sh605289.csv
sh605296 神农集团
./Stock_Daily/sh605296.csv
sh605298 必得科技
./Stock_Daily/sh605298.csv
sh605299 舒华体育
./Stock_Daily/sh605299.csv
sh605300 佳禾食品
./Stock_Daily/sh605300.csv
sh605303 园林股份
./Stock_Daily/sh605303.csv
sh605305 中际联合
./Stock_Daily/sh605305.csv
sh605318 法狮龙
./Stock_Daily/sh605318.csv
sh605319 无锡振华
./Stock_Daily/sh605319.csv
sh605333 沪光股份
./Stock_Daily/sh605333.csv
sh605336 帅丰电器
./Stock_Daily/sh605336.csv
sh605337 李子园
./Stock_Daily/sh605337.csv
sh605338 巴比食品
./Stock_Daily/sh605338.csv
sh605339 南侨食品
./Stock_Daily/sh605339.csv
sh605358 立昂微
./Stock_Daily/sh605358.csv
sh605365 立达信
./Stock_Daily/sh605365.csv
sh605366 宏柏新材
./Stock_Daily/sh605366.csv
sh605368 蓝天燃气
./Stock_Daily/sh605368.csv
sh605369 拱东医疗
./Stock_Daily/sh605369.csv
sh605376 博迁新材
./Stock_Daily/sh605376.csv
sh605377 华旺科技
./Stock_Daily/sh605377.csv
sh605378 野马电池
./Stock_Daily/sh605378.csv
sh605388 均瑶健康
./Stock_Daily/sh605388.csv
sh605389 长龄液压
./Stock_Daily/sh605389.csv
sh605398 新炬网络
./Stock_Daily/sh605398.csv
sh605399 晨光新材
./Stock_Daily/sh605399.csv
sh605488 福莱新材
./Stock_Daily/sh605488.csv
sh605499 东鹏饮料
./Stock_Daily/sh605499.csv
sh605500 森林包装
./Stock_Daily/sh605500.csv
sh605507 国邦医药
./Stock_Daily/sh605507.csv
sh605555 德昌股份
./Stock_Daily/sh605555.csv
sh605566 福莱蒽特
./Stock_Daily/sh605566.csv
sh605567 春雪食品
./Stock_Daily/sh605567.csv
sh605577 龙版传媒
./Stock_Daily/sh605577.csv
sh605580 恒盛能源
./Stock_Daily/sh605580.csv
sh605588 冠石科技
./Stock_Daily/sh605588.csv
sh605589 圣泉集团
./Stock_Daily/sh605589.csv
sh605598 上海港湾
./Stock_Daily/sh605598.csv
sh605599 菜百股份
./Stock_Daily/sh605599.csv
sh688001 华兴源创
./Stock_Daily/sh688001.csv
sh688002 睿创微纳
./Stock_Daily/sh688002.csv
sh688003 天准科技
./Stock_Daily/sh688003.csv
sh688004 博汇科技
./Stock_Daily/sh688004.csv
sh688005 容百科技
./Stock_Daily/sh688005.csv
sh688006 杭可科技
./Stock_Daily/sh688006.csv
sh688007 光峰科技
./Stock_Daily/sh688007.csv
sh688008 澜起科技
./Stock_Daily/sh688008.csv
sh688009 中国通号
./Stock_Daily/sh688009.csv
sh688010 福光股份
./Stock_Daily/sh688010.csv
sh688011 新光光电
./Stock_Daily/sh688011.csv
sh688012 中微公司
./Stock_Daily/sh688012.csv
sh688013 天臣医疗
./Stock_Daily/sh688013.csv
sh688015 交控科技
./Stock_Daily/sh688015.csv
sh688016 心脉医疗
./Stock_Daily/sh688016.csv
sh688017 绿的谐波
./Stock_Daily/sh688017.csv
sh688018 乐鑫科技
./Stock_Daily/sh688018.csv
sh688019 安集科技
./Stock_Daily/sh688019.csv
sh688020 方邦股份
./Stock_Daily/sh688020.csv
sh688021 奥福环保
./Stock_Daily/sh688021.csv
sh688022 瀚川智能
./Stock_Daily/sh688022.csv
sh688023 安恒信息
./Stock_Daily/sh688023.csv
sh688025 杰普特
./Stock_Daily/sh688025.csv
sh688026 洁特生物
./Stock_Daily/sh688026.csv
sh688027 国盾量子
./Stock_Daily/sh688027.csv
sh688028 沃尔德
./Stock_Daily/sh688028.csv
sh688029 南微医学
./Stock_Daily/sh688029.csv
sh688030 山石网科
./Stock_Daily/sh688030.csv
sh688031 星环科技
./Stock_Daily/sh688031.csv
sh688032 禾迈股份
./Stock_Daily/sh688032.csv
sh688033 天宜上佳
./Stock_Daily/sh688033.csv
sh688035 德邦科技
./Stock_Daily/sh688035.csv
sh688036 传音控股
./Stock_Daily/sh688036.csv
sh688037 芯源微
./Stock_Daily/sh688037.csv
sh688038 中科通达
./Stock_Daily/sh688038.csv
sh688039 当虹科技
./Stock_Daily/sh688039.csv
sh688041 海光信息
./Stock_Daily/sh688041.csv
sh688045 必易微
./Stock_Daily/sh688045.csv
sh688046 药康生物
./Stock_Daily/sh688046.csv
sh688047 龙芯中科
./Stock_Daily/sh688047.csv
sh688048 长光华芯
./Stock_Daily/sh688048.csv
sh688049 炬芯科技
./Stock_Daily/sh688049.csv
sh688050 爱博医疗
./Stock_Daily/sh688050.csv
sh688051 佳华科技
./Stock_Daily/sh688051.csv
sh688052 纳芯微
./Stock_Daily/sh688052.csv
sh688053 思科瑞
./Stock_Daily/sh688053.csv
sh688055 龙腾光电
./Stock_Daily/sh688055.csv
sh688056 莱伯泰科
./Stock_Daily/sh688056.csv
sh688057 金达莱
./Stock_Daily/sh688057.csv
sh688058 宝兰德
./Stock_Daily/sh688058.csv
sh688059 华锐精密
./Stock_Daily/sh688059.csv
sh688060 云涌科技
./Stock_Daily/sh688060.csv
sh688061 灿瑞科技
./Stock_Daily/sh688061.csv
sh688062 迈威生物
./Stock_Daily/sh688062.csv
sh688063 派能科技
./Stock_Daily/sh688063.csv
sh688065 凯赛生物
./Stock_Daily/sh688065.csv
sh688066 航天宏图
./Stock_Daily/sh688066.csv
sh688067 爱威科技
./Stock_Daily/sh688067.csv
sh688068 热景生物
./Stock_Daily/sh688068.csv
sh688069 德林海
./Stock_Daily/sh688069.csv
sh688070 纵横股份
./Stock_Daily/sh688070.csv
sh688071 华依科技
./Stock_Daily/sh688071.csv
sh688072 拓荆科技
./Stock_Daily/sh688072.csv
sh688073 毕得医药
./Stock_Daily/sh688073.csv
sh688075 安旭生物
./Stock_Daily/sh688075.csv
sh688076 诺泰生物
./Stock_Daily/sh688076.csv
sh688077 大地熊
./Stock_Daily/sh688077.csv
sh688078 龙软科技
./Stock_Daily/sh688078.csv
sh688079 美迪凯
./Stock_Daily/sh688079.csv
sh688080 映翰通
./Stock_Daily/sh688080.csv
sh688081 兴图新科
./Stock_Daily/sh688081.csv
sh688082 盛美上海
./Stock_Daily/sh688082.csv
sh688083 中望软件
./Stock_Daily/sh688083.csv
sh688084 晶品特装
./Stock_Daily/sh688084.csv
sh688085 三友医疗
./Stock_Daily/sh688085.csv
sh688087 英科再生
./Stock_Daily/sh688087.csv
sh688088 虹软科技
./Stock_Daily/sh688088.csv
sh688089 嘉必优
./Stock_Daily/sh688089.csv
sh688090 瑞松科技
./Stock_Daily/sh688090.csv
sh688091 上海谊众
./Stock_Daily/sh688091.csv
sh688092 爱科科技
./Stock_Daily/sh688092.csv
sh688093 世华科技
./Stock_Daily/sh688093.csv
sh688095 福昕软件
./Stock_Daily/sh688095.csv
sh688096 京源环保
./Stock_Daily/sh688096.csv
sh688097 博众精工
./Stock_Daily/sh688097.csv
sh688098 申联生物
./Stock_Daily/sh688098.csv
sh688099 晶晨股份
./Stock_Daily/sh688099.csv
sh688100 威胜信息
./Stock_Daily/sh688100.csv
sh688101 三达膜
./Stock_Daily/sh688101.csv
sh688102 斯瑞新材
./Stock_Daily/sh688102.csv
sh688103 国力股份
./Stock_Daily/sh688103.csv
sh688105 诺唯赞

./Stock_Daily/sh688105.csv
sh688106 金宏气体
./Stock_Daily/sh688106.csv
sh688107 安路科技
./Stock_Daily/sh688107.csv
sh688108 赛诺医疗
./Stock_Daily/sh688108.csv
sh688109 品茗科技
./Stock_Daily/sh688109.csv
sh688110 东芯股份
./Stock_Daily/sh688110.csv
sh688111 金山办公
./Stock_Daily/sh688111.csv
sh688112 鼎阳科技
./Stock_Daily/sh688112.csv
sh688113 联测科技
./Stock_Daily/sh688113.csv
sh688114 华大智造
./Stock_Daily/sh688114.csv
sh688115 思林杰
./Stock_Daily/sh688115.csv
sh688116 天奈科技
./Stock_Daily/sh688116.csv
sh688117 圣诺生物
./Stock_Daily/sh688117.csv
sh688118 普元信息
./Stock_Daily/sh688118.csv
sh688119 中钢洛耐
./Stock_Daily/sh688119.csv
sh688120 华海清科
./Stock_Daily/sh688120.csv
sh688121 卓然股份
./Stock_Daily/sh688121.csv
sh688122 西部超导
./Stock_Daily/sh688122.csv
sh688123 聚辰股份
./Stock_Daily/sh688123.csv
sh688125 安达智能
./Stock_Daily/sh688125.csv
sh688126 沪硅产业
./Stock_Daily/sh688126.csv
sh688127 蓝特光学
./Stock_Daily/sh688127.csv
sh688128 中国电研
./Stock_Daily/sh688128.csv
sh688129 东来技术
./Stock_Daily/sh688129.csv
sh688130 晶华微
./Stock_Daily/sh688130.csv
sh688131 皓元医药
./Stock_Daily/sh688131.csv
sh688132 邦彦技术
./Stock_Daily/sh688132.csv
sh688133 泰坦科技
./Stock_Daily/sh688133.csv
sh688135 利扬芯片
./Stock_Daily/sh688135.csv
sh688136 科兴制药
./Stock_Daily/sh688136.csv
sh688137 近岸蛋白
./Stock_Daily/sh688137.csv
sh688138 清溢光电
./Stock_Daily/sh688138.csv
sh688139 海尔生物
./Stock_Daily/sh688139.csv
sh688141 杰华特
./Stock_Daily/sh688141.csv
sh688143 长盈通
./Stock_Daily/sh688143.csv
sh688146 中船特气
./Stock_Daily/sh688146.csv
sh688147 微导纳米
./Stock_Daily/sh688147.csv
sh688148 芳源股份
./Stock_Daily/sh688148.csv
sh688150 莱特光电
./Stock_Daily/sh688150.csv
sh688151 华强科技
./Stock_Daily/sh688151.csv
sh688152 麒麟信安
./Stock_Daily/sh688152.csv
sh688153 唯捷创芯
./Stock_Daily/sh688153.csv
sh688155 先惠技术
./Stock_Daily/sh688155.csv
sh688156 路德环境
./Stock_Daily/sh688156.csv
sh688157 松井股份
./Stock_Daily/sh688157.csv
sh688158 优刻得
./Stock_Daily/sh688158.csv
sh688159 有方科技
./Stock_Daily/sh688159.csv
sh688160 步科股份
./Stock_Daily/sh688160.csv
sh688161 威高骨科
./Stock_Daily/sh688161.csv
sh688162 巨一科技
./Stock_Daily/sh688162.csv
sh688163 赛伦生物
./Stock_Daily/sh688163.csv
sh688165 埃夫特
./Stock_Daily/sh688165.csv
sh688166 博瑞医药
./Stock_Daily/sh688166.csv
sh688167 炬光科技
./Stock_Daily/sh688167.csv
sh688168 安博通
./Stock_Daily/sh688168.csv
sh688169 石头科技
./Stock_Daily/sh688169.csv
sh688170 德龙激光
./Stock_Daily/sh688170.csv
sh688171 纬德信息
./Stock_Daily/sh688171.csv
sh688172 燕东微
./Stock_Daily/sh688172.csv
sh688173 希荻微
./Stock_Daily/sh688173.csv
sh688175 高凌信息
./Stock_Daily/sh688175.csv
sh688176 亚虹医药
./Stock_Daily/sh688176.csv
sh688177 百奥泰
./Stock_Daily/sh688177.csv
sh688178 万德斯
./Stock_Daily/sh688178.csv
sh688179 阿拉丁
./Stock_Daily/sh688179.csv
sh688180 君实生物
./Stock_Daily/sh688180.csv
sh688181 八亿时空
./Stock_Daily/sh688181.csv
sh688182 灿勤科技
./Stock_Daily/sh688182.csv
sh688183 生益电子
./Stock_Daily/sh688183.csv
sh688184 帕瓦股份
./Stock_Daily/sh688184.csv
sh688185 康希诺
./Stock_Daily/sh688185.csv
sh688186 广大特材
./Stock_Daily/sh688186.csv
sh688187 时代电气
./Stock_Daily/sh688187.csv
sh688188 柏楚电子
./Stock_Daily/sh688188.csv
sh688189 南新制药
./Stock_Daily/sh688189.csv
sh688190 云路股份
./Stock_Daily/sh688190.csv
sh688191 智洋创新
./Stock_Daily/sh688191.csv
sh688192 迪哲医药
./Stock_Daily/sh688192.csv
sh688193 仁度生物
./Stock_Daily/sh688193.csv
sh688195 腾景科技
./Stock_Daily/sh688195.csv
sh688196 卓越新能
./Stock_Daily/sh688196.csv
sh688197 首药控股
./Stock_Daily/sh688197.csv
sh688198 佰仁医疗
./Stock_Daily/sh688198.csv
sh688199 久日新材
./Stock_Daily/sh688199.csv
sh688200 华峰测控
./Stock_Daily/sh688200.csv
sh688201 信安世纪
./Stock_Daily/sh688201.csv
sh688202 美迪西
./Stock_Daily/sh688202.csv
sh688203 海正生材
./Stock_Daily/sh688203.csv
sh688205 德科立
./Stock_Daily/sh688205.csv
sh688206 概伦电子
./Stock_Daily/sh688206.csv
sh688207 格灵深瞳
./Stock_Daily/sh688207.csv
sh688208 道通科技
./Stock_Daily/sh688208.csv
sh688209 英集芯
./Stock_Daily/sh688209.csv
sh688210 统联精密
./Stock_Daily/sh688210.csv
sh688211 中科微至
./Stock_Daily/sh688211.csv
sh688212 澳华内镜
./Stock_Daily/sh688212.csv
sh688213 思特威
./Stock_Daily/sh688213.csv
sh688215 瑞晟智能
./Stock_Daily/sh688215.csv
sh688216 气派科技
./Stock_Daily/sh688216.csv
sh688217 睿昂基因
./Stock_Daily/sh688217.csv
sh688218 江苏北人
./Stock_Daily/sh688218.csv
sh688219 会通股份
./Stock_Daily/sh688219.csv
sh688220 翱捷科技
./Stock_Daily/sh688220.csv
sh688221 前沿生物
./Stock_Daily/sh688221.csv
sh688222 成都先导
./Stock_Daily/sh688222.csv
sh688223 晶科能源
./Stock_Daily/sh688223.csv
sh688225 亚信安全
./Stock_Daily/sh688225.csv
sh688226 威腾电气
./Stock_Daily/sh688226.csv
sh688227 品高股份
./Stock_Daily/sh688227.csv
sh688228 开普云
./Stock_Daily/sh688228.csv
sh688229 博睿数据
./Stock_Daily/sh688229.csv
sh688230 芯导科技
./Stock_Daily/sh688230.csv
sh688231 隆达股份
./Stock_Daily/sh688231.csv
sh688232 新点软件
./Stock_Daily/sh688232.csv
sh688233 神工股份
./Stock_Daily/sh688233.csv
sh688234 天岳先进
./Stock_Daily/sh688234.csv
sh688235 百济神州
./Stock_Daily/sh688235.csv
sh688236 春立医疗
./Stock_Daily/sh688236.csv
sh688237 超卓航科
./Stock_Daily/sh688237.csv
sh688238 和元生物
./Stock_Daily/sh688238.csv
sh688239 航宇科技
./Stock_Daily/sh688239.csv
sh688244 永信至诚
./Stock_Daily/sh688244.csv
sh688246 嘉和美康
./Stock_Daily/sh688246.csv
sh688247 宣泰医药
./Stock_Daily/sh688247.csv
sh688248 南网科技
./Stock_Daily/sh688248.csv
sh688249 晶合集成
./Stock_Daily/sh688249.csv
sh688251 井松智能
./Stock_Daily/sh688251.csv
sh688252 天德钰
./Stock_Daily/sh688252.csv
sh688253 英诺特
./Stock_Daily/sh688253.csv
sh688255 凯尔达
./Stock_Daily/sh688255.csv
sh688256 寒武纪
./Stock_Daily/sh688256.csv
sh688257 新锐股份
./Stock_Daily/sh688257.csv
sh688258 卓易信息
./Stock_Daily/sh688258.csv
sh688259 创耀科技
./Stock_Daily/sh688259.csv
sh688260 昀冢科技
./Stock_Daily/sh688260.csv
sh688261 东微半导
./Stock_Daily/sh688261.csv
sh688262 国芯科技
./Stock_Daily/sh688262.csv
sh688265 南模生物
./Stock_Daily/sh688265.csv
sh688266 泽璟制药
./Stock_Daily/sh688266.csv
sh688267 中触媒
./Stock_Daily/sh688267.csv
sh688268 华特气体
./Stock_Daily/sh688268.csv
sh688269 凯立新材
./Stock_Daily/sh688269.csv
sh688270 臻镭科技
./Stock_Daily/sh688270.csv
sh688271 联影医疗
./Stock_Daily/sh688271.csv
sh688272 *ST富吉
./Stock_Daily/sh688272.csv
sh688273 麦澜德
./Stock_Daily/sh688273.csv
sh688275 万润新能
./Stock_Daily/sh688275.csv
sh688276 百克生物
./Stock_Daily/sh688276.csv
sh688277 天智航
./Stock_Daily/sh688277.csv
sh688278 特宝生物
./Stock_Daily/sh688278.csv
sh688279 峰岹科技
./Stock_Daily/sh688279.csv
sh688280 精进电动
./Stock_Daily/sh688280.csv
sh688281 华秦科技
./Stock_Daily/sh688281.csv
sh688282 理工导航
./Stock_Daily/sh688282.csv
sh688283 坤恒顺维
./Stock_Daily/sh688283.csv
sh688285 高铁电气
./Stock_Daily/sh688285.csv
sh688286 敏芯股份
./Stock_Daily/sh688286.csv
sh688287 观典防务
./Stock_Daily/sh688287.csv
sh688288 鸿泉物联
./Stock_Daily/sh688288.csv
sh688289 圣湘生物
./Stock_Daily/sh688289.csv
sh688290 景业智能
./Stock_Daily/sh688290.csv
sh688291 金橙子
./Stock_Daily/sh688291.csv
sh688292 浩瀚深度
./Stock_Daily/sh688292.csv
sh688293 奥浦迈
./Stock_Daily/sh688293.csv
sh688295 中复神鹰
./Stock_Daily/sh688295.csv
sh688296 和达科技
./Stock_Daily/sh688296.csv
sh688297 中无人机
./Stock_Daily/sh688297.csv
sh688298 东方生物
./Stock_Daily/sh688298.csv
sh688299 长阳科技
./Stock_Daily/sh688299.csv
sh688300 联瑞新材
./Stock_Daily/sh688300.csv
sh688301 奕瑞科技
./Stock_Daily/sh688301.csv
sh688302 海创药业
./Stock_Daily/sh688302.csv
sh688303 大全能源
./Stock_Daily/sh688303.csv
sh688305 科德数控
./Stock_Daily/sh688305.csv
sh688306 均普智能
./Stock_Daily/sh688306.csv
sh688307 中润光学
./Stock_Daily/sh688307.csv
sh688308 欧科亿
./Stock_Daily/sh688308.csv
sh688309 恒誉环保
./Stock_Daily/sh688309.csv
sh688310 迈得医疗
./Stock_Daily/sh688310.csv
sh688311 盟升电子
./Stock_Daily/sh688311.csv
sh688312 燕麦科技
./Stock_Daily/sh688312.csv
sh688313 仕佳光子
./Stock_Daily/sh688313.csv
sh688314 康拓医疗
./Stock_Daily/sh688314.csv
sh688315 诺禾致源
./Stock_Daily/sh688315.csv
sh688316 青云科技
./Stock_Daily/sh688316.csv
sh688317 之江生物
./Stock_Daily/sh688317.csv
sh688318 财富趋势
./Stock_Daily/sh688318.csv
sh688319 欧林生物
./Stock_Daily/sh688319.csv
sh688320 禾川科技
./Stock_Daily/sh688320.csv
sh688321 微芯生物
./Stock_Daily/sh688321.csv
sh688322 奥比中光
./Stock_Daily/sh688322.csv
sh688323 瑞华泰
./Stock_Daily/sh688323.csv
sh688325 赛微微电
./Stock_Daily/sh688325.csv
sh688326 经纬恒润
./Stock_Daily/sh688326.csv
sh688327 云从科技
./Stock_Daily/sh688327.csv
sh688328 深科达
./Stock_Daily/sh688328.csv
sh688329 艾隆科技
./Stock_Daily/sh688329.csv
sh688330 宏力达
./Stock_Daily/sh688330.csv
sh688331 荣昌生物
./Stock_Daily/sh688331.csv
sh688332 中科蓝讯
./Stock_Daily/sh688332.csv
sh688333 铂力特
./Stock_Daily/sh688333.csv
sh688334 西高院

./Stock_Daily/sh688334.csv
sh688335 复洁环保
./Stock_Daily/sh688335.csv
sh688336 三生国健
./Stock_Daily/sh688336.csv
sh688337 普源精电
./Stock_Daily/sh688337.csv
sh688338 赛科希德
./Stock_Daily/sh688338.csv
sh688339 亿华通
./Stock_Daily/sh688339.csv
sh688343 云天励飞
./Stock_Daily/sh688343.csv
sh688345 博力威
./Stock_Daily/sh688345.csv
sh688347 华虹公司
./Stock_Daily/sh688347.csv
sh688348 昱能科技
./Stock_Daily/sh688348.csv
sh688349 三一重能
./Stock_Daily/sh688349.csv
sh688350 富淼科技
./Stock_Daily/sh688350.csv
sh688351 微电生理
./Stock_Daily/sh688351.csv
sh688352 颀中科技
./Stock_Daily/sh688352.csv
sh688353 华盛锂电
./Stock_Daily/sh688353.csv
sh688355 明志科技
./Stock_Daily/sh688355.csv
sh688356 键凯科技
./Stock_Daily/sh688356.csv
sh688357 建龙微纳
./Stock_Daily/sh688357.csv
sh688358 祥生医疗
./Stock_Daily/sh688358.csv
sh688359 三孚新科
./Stock_Daily/sh688359.csv
sh688360 德马科技
./Stock_Daily/sh688360.csv
sh688361 中科飞测
./Stock_Daily/sh688361.csv
sh688362 甬矽电子
./Stock_Daily/sh688362.csv
sh688363 华熙生物
./Stock_Daily/sh688363.csv
sh688365 光云科技
./Stock_Daily/sh688365.csv
sh688366 昊海生科
./Stock_Daily/sh688366.csv
sh688367 工大高科
./Stock_Daily/sh688367.csv
sh688368 晶丰明源
./Stock_Daily/sh688368.csv
sh688369 致远互联
./Stock_Daily/sh688369.csv
sh688370 丛麟科技
./Stock_Daily/sh688370.csv
sh688371 菲沃泰
./Stock_Daily/sh688371.csv
sh688372 伟测科技
./Stock_Daily/sh688372.csv
sh688373 盟科药业
./Stock_Daily/sh688373.csv
sh688375 国博电子
./Stock_Daily/sh688375.csv
sh688376 美埃科技
./Stock_Daily/sh688376.csv
sh688377 迪威尔
./Stock_Daily/sh688377.csv
sh688378 奥来德
./Stock_Daily/sh688378.csv
sh688379 华光新材
./Stock_Daily/sh688379.csv
sh688380 中微半导
./Stock_Daily/sh688380.csv
sh688381 帝奥微
./Stock_Daily/sh688381.csv
sh688382 益方生物
./Stock_Daily/sh688382.csv
sh688383 新益昌
./Stock_Daily/sh688383.csv
sh688385 复旦微电
./Stock_Daily/sh688385.csv
sh688386 泛亚微透
./Stock_Daily/sh688386.csv
sh688387 信科移动
./Stock_Daily/sh688387.csv
sh688388 嘉元科技
./Stock_Daily/sh688388.csv
sh688389 普门科技
./Stock_Daily/sh688389.csv
sh688390 固德威
./Stock_Daily/sh688390.csv
sh688391 钜泉科技
./Stock_Daily/sh688391.csv
sh688392 骄成超声
./Stock_Daily/sh688392.csv
sh688393 安必平
./Stock_Daily/sh688393.csv
sh688395 正弦电气
./Stock_Daily/sh688395.csv
sh688396 华润微
./Stock_Daily/sh688396.csv
sh688398 赛特新材
./Stock_Daily/sh688398.csv
sh688399 硕世生物
./Stock_Daily/sh688399.csv
sh688400 凌云光
./Stock_Daily/sh688400.csv
sh688401 路维光电
./Stock_Daily/sh688401.csv
sh688403 汇成股份
./Stock_Daily/sh688403.csv
sh688408 中信博
./Stock_Daily/sh688408.csv
sh688409 富创精密
./Stock_Daily/sh688409.csv
sh688410 山外山
./Stock_Daily/sh688410.csv
sh688416 恒烁股份
./Stock_Daily/sh688416.csv
sh688418 震有科技
./Stock_Daily/sh688418.csv
sh688419 耐科装备
./Stock_Daily/sh688419.csv
sh688420 美腾科技
./Stock_Daily/sh688420.csv
sh688425 铁建重工
./Stock_Daily/sh688425.csv
sh688426 康为世纪
./Stock_Daily/sh688426.csv
sh688428 诺诚健华
./Stock_Daily/sh688428.csv
sh688429 时创能源
./Stock_Daily/sh688429.csv
sh688432 有研硅
./Stock_Daily/sh688432.csv
sh688433 华曙高科
./Stock_Daily/sh688433.csv
sh688435 英方软件
./Stock_Daily/sh688435.csv
sh688439 振华风光
./Stock_Daily/sh688439.csv
sh688443 智翔金泰
./Stock_Daily/sh688443.csv
sh688448 磁谷科技
./Stock_Daily/sh688448.csv
sh688450 光格科技
./Stock_Daily/sh688450.csv
sh688455 科捷智能
./Stock_Daily/sh688455.csv
sh688456 有研粉材
./Stock_Daily/sh688456.csv
sh688458 美芯晟
./Stock_Daily/sh688458.csv
sh688459 哈铁科技
./Stock_Daily/sh688459.csv
sh688466 金科环境
./Stock_Daily/sh688466.csv
sh688468 科美诊断
./Stock_Daily/sh688468.csv
sh688469 中芯集成
./Stock_Daily/sh688469.csv
sh688472 阿特斯
./Stock_Daily/sh688472.csv
sh688475 萤石网络
./Stock_Daily/sh688475.csv
sh688478 晶升股份
./Stock_Daily/sh688478.csv
sh688479 友车科技
./Stock_Daily/sh688479.csv
sh688480 赛恩斯
./Stock_Daily/sh688480.csv
sh688484 南芯科技
./Stock_Daily/sh688484.csv
sh688485 九州一轨
./Stock_Daily/sh688485.csv
sh688486 龙迅股份
./Stock_Daily/sh688486.csv
sh688488 艾迪药业
./Stock_Daily/sh688488.csv
sh688489 三未信安
./Stock_Daily/sh688489.csv
sh688496 清越科技
./Stock_Daily/sh688496.csv
sh688498 源杰科技
./Stock_Daily/sh688498.csv
sh688499 利元亨
./Stock_Daily/sh688499.csv
sh688500 *ST慧辰
./Stock_Daily/sh688500.csv
sh688501 青达环保
./Stock_Daily/sh688501.csv
sh688502 茂莱光学
./Stock_Daily/sh688502.csv
sh688503 聚和材料
./Stock_Daily/sh688503.csv
sh688505 复旦张江
./Stock_Daily/sh688505.csv
sh688506 百利天恒
./Stock_Daily/sh688506.csv
sh688507 索辰科技
./Stock_Daily/sh688507.csv
sh688508 芯朋微
./Stock_Daily/sh688508.csv
sh688509 正元地信
./Stock_Daily/sh688509.csv
sh688510 航亚科技
./Stock_Daily/sh688510.csv
sh688511 天微电子
./Stock_Daily/sh688511.csv
sh688512 慧智微
./Stock_Daily/sh688512.csv
sh688513 苑东生物
./Stock_Daily/sh688513.csv
sh688515 裕太微
./Stock_Daily/sh688515.csv
sh688516 XR奥特维
./Stock_Daily/sh688516.csv
sh688517 金冠电气
./Stock_Daily/sh688517.csv
sh688518 联赢激光
./Stock_Daily/sh688518.csv
sh688519 南亚新材
./Stock_Daily/sh688519.csv
sh688520 神州细胞
./Stock_Daily/sh688520.csv
sh688521 芯原股份
./Stock_Daily/sh688521.csv
sh688522 纳睿雷达
./Stock_Daily/sh688522.csv
sh688523 航天环宇
./Stock_Daily/sh688523.csv
sh688525 佰维存储
./Stock_Daily/sh688525.csv
sh688526 科前生物
./Stock_Daily/sh688526.csv
sh688528 秦川物联
./Stock_Daily/sh688528.csv
sh688529 豪森股份
./Stock_Daily/sh688529.csv
sh688531 日联科技
./Stock_Daily/sh688531.csv
sh688533 上声电子
./Stock_Daily/sh688533.csv
sh688535 华海诚科
./Stock_Daily/sh688535.csv
sh688536 思瑞浦
./Stock_Daily/sh688536.csv
sh688538 和辉光电
./Stock_Daily/sh688538.csv
sh688539 高华科技
./Stock_Daily/sh688539.csv
sh688543 国科军工
./Stock_Daily/sh688543.csv
sh688548 广钢气体
./Stock_Daily/sh688548.csv
sh688549 中巨芯
./Stock_Daily/sh688549.csv
sh688550 瑞联新材
./Stock_Daily/sh688550.csv
sh688551 科威尔
./Stock_Daily/sh688551.csv
sh688552 航天南湖
./Stock_Daily/sh688552.csv
sh688553 汇宇制药
./Stock_Daily/sh688553.csv
sh688556 高测股份
./Stock_Daily/sh688556.csv
sh688557 兰剑智能
./Stock_Daily/sh688557.csv
sh688558 国盛智科
./Stock_Daily/sh688558.csv
sh688559 海目星
./Stock_Daily/sh688559.csv
sh688560 明冠新材
./Stock_Daily/sh688560.csv
sh688561 奇安信
./Stock_Daily/sh688561.csv
sh688562 航天软件
./Stock_Daily/sh688562.csv
sh688563 航材股份
./Stock_Daily/sh688563.csv
sh688565 力源科技
./Stock_Daily/sh688565.csv
sh688566 吉贝尔
./Stock_Daily/sh688566.csv
sh688567 孚能科技
./Stock_Daily/sh688567.csv
sh688568 中科星图
./Stock_Daily/sh688568.csv
sh688569 铁科轨道
./Stock_Daily/sh688569.csv
sh688570 天玛智控
./Stock_Daily/sh688570.csv
sh688571 杭华股份
./Stock_Daily/sh688571.csv
sh688573 信宇人
./Stock_Daily/sh688573.csv
sh688575 亚辉龙
./Stock_Daily/sh688575.csv
sh688576 西山科技
./Stock_Daily/sh688576.csv
sh688577 浙海德曼
./Stock_Daily/sh688577.csv
sh688578 艾力斯
./Stock_Daily/sh688578.csv
sh688579 山大地纬
./Stock_Daily/sh688579.csv
sh688580 伟思医疗
./Stock_Daily/sh688580.csv
sh688581 安杰思
./Stock_Daily/sh688581.csv
sh688582 芯动联科
./Stock_Daily/sh688582.csv
sh688585 上纬新材
./Stock_Daily/sh688585.csv
sh688586 江航装备
./Stock_Daily/sh688586.csv
sh688588 凌志软件
./Stock_Daily/sh688588.csv
sh688589 力合微
./Stock_Daily/sh688589.csv
sh688590 新致软件
./Stock_Daily/sh688590.csv
sh688591 泰凌微
./Stock_Daily/sh688591.csv
sh688592 司南导航
./Stock_Daily/sh688592.csv
sh688593 新相微
./Stock_Daily/sh688593.csv
sh688595 芯海科技
./Stock_Daily/sh688595.csv
sh688596 正帆科技
./Stock_Daily/sh688596.csv
sh688597 煜邦电力
./Stock_Daily/sh688597.csv
sh688598 金博股份
./Stock_Daily/sh688598.csv
sh688599 天合光能
./Stock_Daily/sh688599.csv
sh688600 皖仪科技
./Stock_Daily/sh688600.csv
sh688601 力芯微
./Stock_Daily/sh688601.csv
sh688602 康鹏科技
./Stock_Daily/sh688602.csv
sh688603 天承科技
./Stock_Daily/sh688603.csv
sh688606 奥泰生物
./Stock_Daily/sh688606.csv
sh688607 康众医疗
./Stock_Daily/sh688607.csv
sh688608 恒玄科技
./Stock_Daily/sh688608.csv
sh688609 九联科技
./Stock_Daily/sh688609.csv
sh688610 埃科光电
./Stock_Daily/sh688610.csv
sh688611 杭州柯林
./Stock_Daily/sh688611.csv
sh688612 威迈斯
./Stock_Daily/sh688612.csv
sh688613 奥精医疗
./Stock_Daily/sh688613.csv
sh688616 西力科技
./Stock_Daily/sh688616.csv
sh688617 惠泰医疗
./Stock_Daily/sh688617.csv
sh688618 三旺通信
./Stock_Daily/sh688618.csv
sh688619 罗普特
./Stock_Daily/sh688619.csv
sh688620 安凯微
./Stock_Daily/sh688620.csv
sh688621 阳光诺和
./Stock_Daily/sh688621.csv
sh688622 禾信仪器
./Stock_Daily/sh688622.csv
sh688623 双元科技
./Stock_Daily/sh688623.csv
sh688625 呈和科技
./Stock_Daily/sh688625.csv
sh688626 翔宇医疗
./Stock_Daily/sh688626.csv
sh688627 精智达
./Stock_Daily/sh688627.csv
sh688628 优利德
./Stock_Daily/sh688628.csv
sh688629 华丰科技
./Stock_Daily/sh688629.csv
sh688630 芯碁微装
./Stock_Daily/sh688630.csv
sh688631 莱斯信息
./Stock_Daily/sh688631.csv
sh688633 星球石墨
./Stock_Daily/sh688633.csv
sh688636 智明达
./Stock_Daily/sh688636.csv
sh688638 誉辰智能

./Stock_Daily/sh688638.csv
sh688639 华恒生物
./Stock_Daily/sh688639.csv
sh688646 逸飞激光
./Stock_Daily/sh688646.csv
sh688648 C中邮
./Stock_Daily/sh688648.csv
sh688651 盛邦安全
./Stock_Daily/sh688651.csv
sh688653 N康希
./Stock_Daily/sh688653.csv
sh688655 迅捷兴
./Stock_Daily/sh688655.csv
sh688656 浩欧博
./Stock_Daily/sh688656.csv
sh688657 浩辰软件
./Stock_Daily/sh688657.csv
sh688658 悦康药业
./Stock_Daily/sh688658.csv
sh688659 元琛科技
./Stock_Daily/sh688659.csv
sh688660 电气风电
./Stock_Daily/sh688660.csv
sh688661 和林微纳
./Stock_Daily/sh688661.csv
sh688662 富信科技
./Stock_Daily/sh688662.csv
sh688663 新风光
./Stock_Daily/sh688663.csv
sh688665 四方光电
./Stock_Daily/sh688665.csv
sh688667 菱电电控
./Stock_Daily/sh688667.csv
sh688668 鼎通科技
./Stock_Daily/sh688668.csv
sh688669 聚石化学
./Stock_Daily/sh688669.csv
sh688670 金迪克
./Stock_Daily/sh688670.csv
sh688671 碧兴物联
./Stock_Daily/sh688671.csv
sh688676 金盘科技
./Stock_Daily/sh688676.csv
sh688677 海泰新光
./Stock_Daily/sh688677.csv
sh688678 福立旺
./Stock_Daily/sh688678.csv
sh688679 通源环境
./Stock_Daily/sh688679.csv
sh688680 海优新材
./Stock_Daily/sh688680.csv
sh688681 科汇股份
./Stock_Daily/sh688681.csv
sh688682 霍莱沃
./Stock_Daily/sh688682.csv
sh688683 莱尔科技
./Stock_Daily/sh688683.csv
sh688685 迈信林
./Stock_Daily/sh688685.csv
sh688686 奥普特
./Stock_Daily/sh688686.csv
sh688687 凯因科技
./Stock_Daily/sh688687.csv
sh688689 银河微电
./Stock_Daily/sh688689.csv
sh688690 纳微科技
./Stock_Daily/sh688690.csv
sh688693 锴威特
./Stock_Daily/sh688693.csv
sh688696 极米科技
./Stock_Daily/sh688696.csv
sh688697 纽威数控
./Stock_Daily/sh688697.csv
sh688698 伟创电气
./Stock_Daily/sh688698.csv
sh688699 明微电子
./Stock_Daily/sh688699.csv
sh688700 东威科技
./Stock_Daily/sh688700.csv
sh688701 卓锦股份
./Stock_Daily/sh688701.csv
sh688702 盛科通信
./Stock_Daily/sh688702.csv
sh688707 振华新材
./Stock_Daily/sh688707.csv
sh688711 宏微科技
./Stock_Daily/sh688711.csv
sh688716 中研股份
./Stock_Daily/sh688716.csv
sh688718 唯赛勃
./Stock_Daily/sh688718.csv
sh688719 爱科赛博
./Stock_Daily/sh688719.csv
sh688722 同益中
./Stock_Daily/sh688722.csv
sh688728 格科微
./Stock_Daily/sh688728.csv
sh688733 壹石通
./Stock_Daily/sh688733.csv
sh688737 中自科技
./Stock_Daily/sh688737.csv
sh688739 成大生物
./Stock_Daily/sh688739.csv
sh688766 普冉股份
./Stock_Daily/sh688766.csv
sh688767 博拓生物
./Stock_Daily/sh688767.csv
sh688768 容知日新
./Stock_Daily/sh688768.csv
sh688772 珠海冠宇
./Stock_Daily/sh688772.csv
sh688776 国光电气
./Stock_Daily/sh688776.csv
sh688777 中控技术
./Stock_Daily/sh688777.csv
sh688778 厦钨新能
./Stock_Daily/sh688778.csv
sh688779 长远锂科
./Stock_Daily/sh688779.csv
sh688786 悦安新材
./Stock_Daily/sh688786.csv
sh688787 海天瑞声
./Stock_Daily/sh688787.csv
sh688788 科思科技
./Stock_Daily/sh688788.csv
sh688789 宏华数科
./Stock_Daily/sh688789.csv
sh688793 倍轻松
./Stock_Daily/sh688793.csv
sh688798 艾为电子
./Stock_Daily/sh688798.csv
sh688799 华纳药厂
./Stock_Daily/sh688799.csv
sh688800 瑞可达
./Stock_Daily/sh688800.csv
sh688819 天能股份
./Stock_Daily/sh688819.csv
sh688981 中芯国际
./Stock_Daily/sh688981.csv
sz000001 平安银行
./Stock_Daily/sz000001.csv
sz000002 万 科Ａ
./Stock_Daily/sz000002.csv
sz000004 国华网安
./Stock_Daily/sz000004.csv
sz000005 ST星源
./Stock_Daily/sz000005.csv
sz000006 深振业Ａ
./Stock_Daily/sz000006.csv
sz000007 *ST全新
./Stock_Daily/sz000007.csv
sz000008 神州高铁
./Stock_Daily/sz000008.csv
sz000009 中国宝安
./Stock_Daily/sz000009.csv
sz000010 美丽生态
./Stock_Daily/sz000010.csv
sz000011 深物业A
./Stock_Daily/sz000011.csv
sz000012 南 玻Ａ
./Stock_Daily/sz000012.csv
sz000014 沙河股份
./Stock_Daily/sz000014.csv
sz000016 深康佳Ａ
./Stock_Daily/sz000016.csv
sz000017 深中华A
./Stock_Daily/sz000017.csv
sz000019 深粮控股
./Stock_Daily/sz000019.csv
sz000020 深华发Ａ
./Stock_Daily/sz000020.csv
sz000021 深科技
./Stock_Daily/sz000021.csv
sz000023 ST深天
./Stock_Daily/sz000023.csv
sz000025 特 力Ａ
./Stock_Daily/sz000025.csv
sz000026 飞亚达
./Stock_Daily/sz000026.csv
sz000027 深圳能源
./Stock_Daily/sz000027.csv
sz000028 国药一致
./Stock_Daily/sz000028.csv
sz000029 深深房Ａ
./Stock_Daily/sz000029.csv
sz000030 富奥股份
./Stock_Daily/sz000030.csv
sz000031 大悦城
./Stock_Daily/sz000031.csv
sz000032 深桑达Ａ
./Stock_Daily/sz000032.csv
sz000034 神州数码
./Stock_Daily/sz000034.csv
sz000035 中国天楹
./Stock_Daily/sz000035.csv
sz000036 华联控股
./Stock_Daily/sz000036.csv
sz000037 深南电A
./Stock_Daily/sz000037.csv
sz000039 中集集团
./Stock_Daily/sz000039.csv
sz000040 东旭蓝天
./Stock_Daily/sz000040.csv
sz000042 中洲控股
./Stock_Daily/sz000042.csv
sz000045 深纺织Ａ
./Stock_Daily/sz000045.csv
sz000046 *ST泛海
./Stock_Daily/sz000046.csv
sz000048 京基智农
./Stock_Daily/sz000048.csv
sz000049 德赛电池
./Stock_Daily/sz000049.csv
sz000050 深天马Ａ
./Stock_Daily/sz000050.csv
sz000055 方大集团
./Stock_Daily/sz000055.csv
sz000056 皇庭国际
./Stock_Daily/sz000056.csv
sz000058 深 赛 格
./Stock_Daily/sz000058.csv
sz000059 华锦股份
./Stock_Daily/sz000059.csv
sz000060 中金岭南
./Stock_Daily/sz000060.csv
sz000061 农 产 品
./Stock_Daily/sz000061.csv
sz000062 深圳华强
./Stock_Daily/sz000062.csv
sz000063 中兴通讯
./Stock_Daily/sz000063.csv
sz000065 北方国际
./Stock_Daily/sz000065.csv
sz000066 中国长城
./Stock_Daily/sz000066.csv
sz000068 华控赛格
./Stock_Daily/sz000068.csv
sz000069 华侨城Ａ
./Stock_Daily/sz000069.csv
sz000070 特发信息
./Stock_Daily/sz000070.csv
sz000078 海王生物
./Stock_Daily/sz000078.csv
sz000088 盐 田 港
./Stock_Daily/sz000088.csv
sz000089 深圳机场
./Stock_Daily/sz000089.csv
sz000090 天健集团
./Stock_Daily/sz000090.csv
sz000096 广聚能源
./Stock_Daily/sz000096.csv
sz000099 中信海直
./Stock_Daily/sz000099.csv
sz000100 TCL科技
./Stock_Daily/sz000100.csv
sz000151 中成股份
./Stock_Daily/sz000151.csv
sz000153 丰原药业
./Stock_Daily/sz000153.csv
sz000155 川能动力
./Stock_Daily/sz000155.csv
sz000156 华数传媒
./Stock_Daily/sz000156.csv
sz000157 中联重科
./Stock_Daily/sz000157.csv
sz000158 常山北明
./Stock_Daily/sz000158.csv
sz000159 国际实业
./Stock_Daily/sz000159.csv
sz000166 申万宏源
./Stock_Daily/sz000166.csv
sz000301 东方盛虹
./Stock_Daily/sz000301.csv
sz000333 美的集团
./Stock_Daily/sz000333.csv
sz000338 潍柴动力
./Stock_Daily/sz000338.csv
sz000400 许继电气
./Stock_Daily/sz000400.csv
sz000401 冀东水泥
./Stock_Daily/sz000401.csv
sz000402 金 融 街
./Stock_Daily/sz000402.csv
sz000403 派林生物
./Stock_Daily/sz000403.csv
sz000404 长虹华意
./Stock_Daily/sz000404.csv
sz000407 胜利股份
./Stock_Daily/sz000407.csv
sz000408 藏格矿业
./Stock_Daily/sz000408.csv
sz000409 云鼎科技
./Stock_Daily/sz000409.csv
sz000410 沈阳机床
./Stock_Daily/sz000410.csv
sz000411 英特集团
./Stock_Daily/sz000411.csv
sz000413 东旭光电
./Stock_Daily/sz000413.csv
sz000415 渤海租赁
./Stock_Daily/sz000415.csv
sz000416 *ST民控
./Stock_Daily/sz000416.csv
sz000417 合肥百货
./Stock_Daily/sz000417.csv
sz000419 通程控股
./Stock_Daily/sz000419.csv
sz000420 吉林化纤
./Stock_Daily/sz000420.csv
sz000421 南京公用
./Stock_Daily/sz000421.csv
sz000422 湖北宜化
./Stock_Daily/sz000422.csv
sz000423 东阿阿胶
./Stock_Daily/sz000423.csv
sz000425 徐工机械
./Stock_Daily/sz000425.csv
sz000426 兴业银锡
./Stock_Daily/sz000426.csv
sz000428 华天酒店
./Stock_Daily/sz000428.csv
sz000429 粤高速Ａ
./Stock_Daily/sz000429.csv
sz000430 张家界
./Stock_Daily/sz000430.csv
sz000488 晨鸣纸业
./Stock_Daily/sz000488.csv
sz000498 山东路桥
./Stock_Daily/sz000498.csv
sz000501 武商集团
./Stock_Daily/sz000501.csv
sz000503 国新健康
./Stock_Daily/sz000503.csv
sz000504 南华生物
./Stock_Daily/sz000504.csv
sz000505 京粮控股
./Stock_Daily/sz000505.csv
sz000506 中润资源
./Stock_Daily/sz000506.csv
sz000507 珠海港
./Stock_Daily/sz000507.csv
sz000509 华塑控股
./Stock_Daily/sz000509.csv
sz000510 新金路
./Stock_Daily/sz000510.csv
sz000513 丽珠集团
./Stock_Daily/sz000513.csv
sz000514 渝 开 发
./Stock_Daily/sz000514.csv
sz000516 国际医学
./Stock_Daily/sz000516.csv
sz000517 荣安地产
./Stock_Daily/sz000517.csv
sz000518 四环生物
./Stock_Daily/sz000518.csv
sz000519 中兵红箭
./Stock_Daily/sz000519.csv
sz000520 凤凰航运
./Stock_Daily/sz000520.csv
sz000521 长虹美菱
./Stock_Daily/sz000521.csv
sz000523 广州浪奇
./Stock_Daily/sz000523.csv
sz000524 岭南控股
./Stock_Daily/sz000524.csv
sz000525 ST红太阳
./Stock_Daily/sz000525.csv
sz000526 学大教育
./Stock_Daily/sz000526.csv
sz000528 柳 工
./Stock_Daily/sz000528.csv
sz000529 广弘控股
./Stock_Daily/sz000529.csv
sz000530 冰山冷热
./Stock_Daily/sz000530.csv
sz000531 穗恒运Ａ
./Stock_Daily/sz000531.csv
sz000532 华金资本
./Stock_Daily/sz000532.csv
sz000533 顺钠股份
./Stock_Daily/sz000533.csv
sz000534 万泽股份
./Stock_Daily/sz000534.csv
sz000536 华映科技
./Stock_Daily/sz000536.csv
sz000537 广宇发展
./Stock_Daily/sz000537.csv
sz000538 云南白药
./Stock_Daily/sz000538.csv
sz000539 粤电力Ａ
./Stock_Daily/sz000539.csv
sz000541 佛山照明
./Stock_Daily/sz000541.csv
sz000543 皖能电力
./Stock_Daily/sz000543.csv
sz000544 中原环保
./Stock_Daily/sz000544.csv
sz000545 金浦钛业
./Stock_Daily/sz000545.csv
sz000546 金圆股份
./Stock_Daily/sz000546.csv
sz000547 航天发展

./Stock_Daily/sz000547.csv
sz000548 湖南投资
./Stock_Daily/sz000548.csv
sz000550 江铃汽车
./Stock_Daily/sz000550.csv
sz000551 创元科技
./Stock_Daily/sz000551.csv
sz000552 甘肃能化
./Stock_Daily/sz000552.csv
sz000553 安道麦A
./Stock_Daily/sz000553.csv
sz000554 泰山石油
./Stock_Daily/sz000554.csv
sz000555 神州信息
./Stock_Daily/sz000555.csv
sz000557 西部创业
./Stock_Daily/sz000557.csv
sz000558 莱茵体育
./Stock_Daily/sz000558.csv
sz000559 万向钱潮
./Stock_Daily/sz000559.csv
sz000560 我爱我家
./Stock_Daily/sz000560.csv
sz000561 烽火电子
./Stock_Daily/sz000561.csv
sz000563 陕国投Ａ
./Stock_Daily/sz000563.csv
sz000564 ST大集
./Stock_Daily/sz000564.csv
sz000565 渝三峡Ａ
./Stock_Daily/sz000565.csv
sz000566 海南海药
./Stock_Daily/sz000566.csv
sz000567 海德股份
./Stock_Daily/sz000567.csv
sz000568 泸州老窖
./Stock_Daily/sz000568.csv
sz000570 苏常柴Ａ
./Stock_Daily/sz000570.csv
sz000571 新大洲A
./Stock_Daily/sz000571.csv
sz000572 海马汽车
./Stock_Daily/sz000572.csv
sz000573 粤宏远Ａ
./Stock_Daily/sz000573.csv
sz000576 甘化科工
./Stock_Daily/sz000576.csv
sz000581 威孚高科
./Stock_Daily/sz000581.csv
sz000582 北部湾港
./Stock_Daily/sz000582.csv
sz000584 ST工智
./Stock_Daily/sz000584.csv
sz000586 汇源通信
./Stock_Daily/sz000586.csv
sz000589 贵州轮胎
./Stock_Daily/sz000589.csv
sz000590 启迪药业
./Stock_Daily/sz000590.csv
sz000591 太阳能
./Stock_Daily/sz000591.csv
sz000592 平潭发展
./Stock_Daily/sz000592.csv
sz000593 德龙汇能
./Stock_Daily/sz000593.csv
sz000595 宝塔实业
./Stock_Daily/sz000595.csv
sz000596 古井贡酒
./Stock_Daily/sz000596.csv
sz000597 东北制药
./Stock_Daily/sz000597.csv
sz000598 兴蓉环境
./Stock_Daily/sz000598.csv
sz000599 青岛双星
./Stock_Daily/sz000599.csv
sz000600 建投能源
./Stock_Daily/sz000600.csv
sz000601 韶能股份
./Stock_Daily/sz000601.csv
sz000603 盛达资源
./Stock_Daily/sz000603.csv
sz000605 渤海股份
./Stock_Daily/sz000605.csv
sz000607 华媒控股
./Stock_Daily/sz000607.csv
sz000608 阳光股份
./Stock_Daily/sz000608.csv
sz000609 中迪投资
./Stock_Daily/sz000609.csv
sz000610 西安旅游
./Stock_Daily/sz000610.csv
sz000612 焦作万方
./Stock_Daily/sz000612.csv
sz000615 *ST美谷
./Stock_Daily/sz000615.csv
sz000617 中油资本
./Stock_Daily/sz000617.csv
sz000619 海螺新材
./Stock_Daily/sz000619.csv
sz000620 *ST新联
./Stock_Daily/sz000620.csv
sz000622 恒立实业
./Stock_Daily/sz000622.csv
sz000623 吉林敖东
./Stock_Daily/sz000623.csv
sz000625 长安汽车
./Stock_Daily/sz000625.csv
sz000626 远大控股
./Stock_Daily/sz000626.csv
sz000627 天茂集团
./Stock_Daily/sz000627.csv
sz000628 高新发展
./Stock_Daily/sz000628.csv
sz000629 钒钛股份
./Stock_Daily/sz000629.csv
sz000630 铜陵有色
./Stock_Daily/sz000630.csv
sz000631 顺发恒业
./Stock_Daily/sz000631.csv
sz000632 三木集团
./Stock_Daily/sz000632.csv
sz000633 合金投资
./Stock_Daily/sz000633.csv
sz000635 英 力 特
./Stock_Daily/sz000635.csv
sz000636 风华高科
./Stock_Daily/sz000636.csv
sz000637 ST实华
./Stock_Daily/sz000637.csv
sz000638 万方发展
./Stock_Daily/sz000638.csv
sz000639 西王食品
./Stock_Daily/sz000639.csv
sz000650 仁和药业
./Stock_Daily/sz000650.csv
sz000651 格力电器
./Stock_Daily/sz000651.csv
sz000652 泰达股份
./Stock_Daily/sz000652.csv
sz000655 金岭矿业
./Stock_Daily/sz000655.csv
sz000656 金科股份
./Stock_Daily/sz000656.csv
sz000657 中钨高新
./Stock_Daily/sz000657.csv
sz000659 珠海中富
./Stock_Daily/sz000659.csv
sz000661 长春高新
./Stock_Daily/sz000661.csv
sz000663 永安林业
./Stock_Daily/sz000663.csv
sz000665 湖北广电
./Stock_Daily/sz000665.csv
sz000668 荣丰控股
./Stock_Daily/sz000668.csv
sz000669 ST金鸿
./Stock_Daily/sz000669.csv
sz000670 盈方微
./Stock_Daily/sz000670.csv
sz000672 上峰水泥
./Stock_Daily/sz000672.csv
sz000676 智度股份
./Stock_Daily/sz000676.csv
sz000677 恒天海龙
./Stock_Daily/sz000677.csv
sz000678 襄阳轴承
./Stock_Daily/sz000678.csv
sz000679 大连友谊
./Stock_Daily/sz000679.csv
sz000680 山推股份
./Stock_Daily/sz000680.csv
sz000681 视觉中国
./Stock_Daily/sz000681.csv
sz000682 东方电子
./Stock_Daily/sz000682.csv
sz000683 远兴能源
./Stock_Daily/sz000683.csv
sz000685 中山公用
./Stock_Daily/sz000685.csv
sz000686 东北证券
./Stock_Daily/sz000686.csv
sz000688 国城矿业
./Stock_Daily/sz000688.csv
sz000690 宝新能源
./Stock_Daily/sz000690.csv
sz000691 亚太实业
./Stock_Daily/sz000691.csv
sz000692 *ST惠天
./Stock_Daily/sz000692.csv
sz000695 滨海能源
./Stock_Daily/sz000695.csv
sz000697 *ST炼石
./Stock_Daily/sz000697.csv
sz000698 沈阳化工
./Stock_Daily/sz000698.csv
sz000700 模塑科技
./Stock_Daily/sz000700.csv
sz000701 厦门信达
./Stock_Daily/sz000701.csv
sz000702 正虹科技
./Stock_Daily/sz000702.csv
sz000703 恒逸石化
./Stock_Daily/sz000703.csv
sz000705 浙江震元
./Stock_Daily/sz000705.csv
sz000707 双环科技
./Stock_Daily/sz000707.csv
sz000708 中信特钢
./Stock_Daily/sz000708.csv
sz000709 河钢股份
./Stock_Daily/sz000709.csv
sz000710 贝瑞基因
./Stock_Daily/sz000710.csv
sz000711 *ST京蓝
./Stock_Daily/sz000711.csv
sz000712 锦龙股份
./Stock_Daily/sz000712.csv
sz000713 丰乐种业
./Stock_Daily/sz000713.csv
sz000715 中兴商业
./Stock_Daily/sz000715.csv
sz000716 黑芝麻
./Stock_Daily/sz000716.csv
sz000717 中南股份
./Stock_Daily/sz000717.csv
sz000718 苏宁环球
./Stock_Daily/sz000718.csv
sz000719 中原传媒
./Stock_Daily/sz000719.csv
sz000720 新能泰山
./Stock_Daily/sz000720.csv
sz000721 西安饮食
./Stock_Daily/sz000721.csv
sz000722 湖南发展
./Stock_Daily/sz000722.csv
sz000723 美锦能源
./Stock_Daily/sz000723.csv
sz000725 京东方Ａ
./Stock_Daily/sz000725.csv
sz000726 鲁 泰Ａ
./Stock_Daily/sz000726.csv
sz000727 冠捷科技
./Stock_Daily/sz000727.csv
sz000728 国元证券
./Stock_Daily/sz000728.csv
sz000729 燕京啤酒
./Stock_Daily/sz000729.csv
sz000731 四川美丰
./Stock_Daily/sz000731.csv
sz000733 振华科技
./Stock_Daily/sz000733.csv
sz000735 罗 牛 山
./Stock_Daily/sz000735.csv
sz000736 中交地产
./Stock_Daily/sz000736.csv
sz000737 北方铜业
./Stock_Daily/sz000737.csv
sz000738 航发控制
./Stock_Daily/sz000738.csv
sz000739 普洛药业
./Stock_Daily/sz000739.csv
sz000750 国海证券
./Stock_Daily/sz000750.csv
sz000751 锌业股份
./Stock_Daily/sz000751.csv
sz000752 *ST西发
./Stock_Daily/sz000752.csv
sz000753 漳州发展
./Stock_Daily/sz000753.csv
sz000755 山西路桥
./Stock_Daily/sz000755.csv
sz000756 新华制药
./Stock_Daily/sz000756.csv
sz000757 浩物股份
./Stock_Daily/sz000757.csv
sz000758 中色股份
./Stock_Daily/sz000758.csv
sz000759 中百集团
./Stock_Daily/sz000759.csv
sz000761 本钢板材
./Stock_Daily/sz000761.csv
sz000762 西藏矿业
./Stock_Daily/sz000762.csv
sz000766 通化金马
./Stock_Daily/sz000766.csv
sz000767 晋控电力
./Stock_Daily/sz000767.csv
sz000768 中航西飞
./Stock_Daily/sz000768.csv
sz000776 广发证券
./Stock_Daily/sz000776.csv
sz000777 中核科技
./Stock_Daily/sz000777.csv
sz000778 新兴铸管
./Stock_Daily/sz000778.csv
sz000779 甘咨询
./Stock_Daily/sz000779.csv
sz000782 美达股份
./Stock_Daily/sz000782.csv
sz000783 长江证券
./Stock_Daily/sz000783.csv
sz000785 居然之家
./Stock_Daily/sz000785.csv
sz000786 北新建材
./Stock_Daily/sz000786.csv
sz000788 北大医药
./Stock_Daily/sz000788.csv
sz000789 万年青
./Stock_Daily/sz000789.csv
sz000790 华神科技
./Stock_Daily/sz000790.csv
sz000791 甘肃能源
./Stock_Daily/sz000791.csv
sz000792 盐湖股份
./Stock_Daily/sz000792.csv
sz000793 华闻集团
./Stock_Daily/sz000793.csv
sz000795 英洛华
./Stock_Daily/sz000795.csv
sz000796 *ST凯撒
./Stock_Daily/sz000796.csv
sz000797 中国武夷
./Stock_Daily/sz000797.csv
sz000798 中水渔业
./Stock_Daily/sz000798.csv
sz000799 酒鬼酒
./Stock_Daily/sz000799.csv
sz000800 一汽解放
./Stock_Daily/sz000800.csv
sz000801 四川九洲
./Stock_Daily/sz000801.csv
sz000802 北京文化
./Stock_Daily/sz000802.csv
sz000803 山高环能
./Stock_Daily/sz000803.csv
sz000807 云铝股份
./Stock_Daily/sz000807.csv
sz000809 铁岭新城
./Stock_Daily/sz000809.csv
sz000810 创维数字
./Stock_Daily/sz000810.csv
sz000811 冰轮环境
./Stock_Daily/sz000811.csv
sz000812 陕西金叶
./Stock_Daily/sz000812.csv
sz000813 德展健康
./Stock_Daily/sz000813.csv
sz000815 美利云
./Stock_Daily/sz000815.csv
sz000816 智慧农业
./Stock_Daily/sz000816.csv
sz000818 航锦科技
./Stock_Daily/sz000818.csv
sz000819 岳阳兴长
./Stock_Daily/sz000819.csv
sz000820 神雾节能
./Stock_Daily/sz000820.csv
sz000821 京山轻机
./Stock_Daily/sz000821.csv
sz000822 山东海化
./Stock_Daily/sz000822.csv
sz000823 超声电子
./Stock_Daily/sz000823.csv
sz000825 太钢不锈
./Stock_Daily/sz000825.csv
sz000826 启迪环境
./Stock_Daily/sz000826.csv
sz000828 东莞控股
./Stock_Daily/sz000828.csv
sz000829 天音控股
./Stock_Daily/sz000829.csv
sz000830 鲁西化工
./Stock_Daily/sz000830.csv
sz000831 中国稀土
./Stock_Daily/sz000831.csv
sz000833 粤桂股份
./Stock_Daily/sz000833.csv
sz000836 富通信息
./Stock_Daily/sz000836.csv
sz000837 秦川机床
./Stock_Daily/sz000837.csv
sz000838 财信发展
./Stock_Daily/sz000838.csv
sz000839 ST国安
./Stock_Daily/sz000839.csv
sz000848 承德露露
./Stock_Daily/sz000848.csv
sz000850 华茂股份
./Stock_Daily/sz000850.csv
sz000851 高鸿股份
./Stock_Daily/sz000851.csv
sz000852 石化机械
./Stock_Daily/sz000852.csv
sz000856 冀东装备
./Stock_Daily/sz000856.csv
sz000858 五 粮 液
./Stock_Daily/sz000858.csv
sz000859 国风新材
./Stock_Daily/sz000859.csv
sz000860 顺鑫农业

./Stock_Daily/sz000860.csv
sz000861 海印股份
./Stock_Daily/sz000861.csv
sz000862 银星能源
./Stock_Daily/sz000862.csv
sz000863 三湘印象
./Stock_Daily/sz000863.csv
sz000868 安凯客车
./Stock_Daily/sz000868.csv
sz000869 张 裕Ａ
./Stock_Daily/sz000869.csv
sz000875 吉电股份
./Stock_Daily/sz000875.csv
sz000876 新 希 望
./Stock_Daily/sz000876.csv
sz000877 天山股份
./Stock_Daily/sz000877.csv
sz000878 云南铜业
./Stock_Daily/sz000878.csv
sz000880 潍柴重机
./Stock_Daily/sz000880.csv
sz000881 中广核技
./Stock_Daily/sz000881.csv
sz000882 华联股份
./Stock_Daily/sz000882.csv
sz000883 湖北能源
./Stock_Daily/sz000883.csv
sz000885 城发环境
./Stock_Daily/sz000885.csv
sz000886 海南高速
./Stock_Daily/sz000886.csv
sz000887 中鼎股份
./Stock_Daily/sz000887.csv
sz000888 峨眉山Ａ
./Stock_Daily/sz000888.csv
sz000889 ST中嘉
./Stock_Daily/sz000889.csv
sz000890 法尔胜
./Stock_Daily/sz000890.csv
sz000892 欢瑞世纪
./Stock_Daily/sz000892.csv
sz000893 亚钾国际
./Stock_Daily/sz000893.csv
sz000895 双汇发展
./Stock_Daily/sz000895.csv
sz000897 津滨发展
./Stock_Daily/sz000897.csv
sz000898 鞍钢股份
./Stock_Daily/sz000898.csv
sz000899 赣能股份
./Stock_Daily/sz000899.csv
sz000900 现代投资
./Stock_Daily/sz000900.csv
sz000901 航天科技
./Stock_Daily/sz000901.csv
sz000902 新洋丰
./Stock_Daily/sz000902.csv
sz000903 云内动力
./Stock_Daily/sz000903.csv
sz000905 厦门港务
./Stock_Daily/sz000905.csv
sz000906 浙商中拓
./Stock_Daily/sz000906.csv
sz000908 景峰医药
./Stock_Daily/sz000908.csv
sz000909 ST数源
./Stock_Daily/sz000909.csv
sz000910 大亚圣象
./Stock_Daily/sz000910.csv
sz000911 广农糖业
./Stock_Daily/sz000911.csv
sz000912 泸天化
./Stock_Daily/sz000912.csv
sz000913 钱江摩托
./Stock_Daily/sz000913.csv
sz000915 华特达因
./Stock_Daily/sz000915.csv
sz000917 电广传媒
./Stock_Daily/sz000917.csv
sz000919 金陵药业
./Stock_Daily/sz000919.csv
sz000920 沃顿科技
./Stock_Daily/sz000920.csv
sz000921 海信家电
./Stock_Daily/sz000921.csv
sz000922 佳电股份
./Stock_Daily/sz000922.csv
sz000923 河钢资源
./Stock_Daily/sz000923.csv
sz000925 众合科技
./Stock_Daily/sz000925.csv
sz000926 福星股份
./Stock_Daily/sz000926.csv
sz000927 中国铁物
./Stock_Daily/sz000927.csv
sz000928 中钢国际
./Stock_Daily/sz000928.csv
sz000929 兰州黄河
./Stock_Daily/sz000929.csv
sz000930 中粮科技
./Stock_Daily/sz000930.csv
sz000931 中 关 村
./Stock_Daily/sz000931.csv
sz000932 华菱钢铁
./Stock_Daily/sz000932.csv
sz000933 神火股份
./Stock_Daily/sz000933.csv
sz000935 四川双马
./Stock_Daily/sz000935.csv
sz000936 华西股份
./Stock_Daily/sz000936.csv
sz000937 冀中能源
./Stock_Daily/sz000937.csv
sz000938 紫光股份
./Stock_Daily/sz000938.csv
sz000948 南天信息
./Stock_Daily/sz000948.csv
sz000949 新乡化纤
./Stock_Daily/sz000949.csv
sz000950 重药控股
./Stock_Daily/sz000950.csv
sz000951 中国重汽
./Stock_Daily/sz000951.csv
sz000952 广济药业
./Stock_Daily/sz000952.csv
sz000953 河化股份
./Stock_Daily/sz000953.csv
sz000955 欣龙控股
./Stock_Daily/sz000955.csv
sz000957 中通客车
./Stock_Daily/sz000957.csv
sz000958 电投产融
./Stock_Daily/sz000958.csv
sz000959 首钢股份
./Stock_Daily/sz000959.csv
sz000960 锡业股份
./Stock_Daily/sz000960.csv
sz000961 中南建设
./Stock_Daily/sz000961.csv
sz000962 东方钽业
./Stock_Daily/sz000962.csv
sz000963 华东医药
./Stock_Daily/sz000963.csv
sz000965 天保基建
./Stock_Daily/sz000965.csv
sz000966 长源电力
./Stock_Daily/sz000966.csv
sz000967 盈峰环境
./Stock_Daily/sz000967.csv
sz000968 蓝焰控股
./Stock_Daily/sz000968.csv
sz000969 安泰科技
./Stock_Daily/sz000969.csv
sz000970 中科三环
./Stock_Daily/sz000970.csv
sz000971 ST高升
./Stock_Daily/sz000971.csv
sz000972 中基健康
./Stock_Daily/sz000972.csv
sz000973 佛塑科技
./Stock_Daily/sz000973.csv
sz000975 银泰黄金
./Stock_Daily/sz000975.csv
sz000976 ST华铁
./Stock_Daily/sz000976.csv
sz000977 浪潮信息
./Stock_Daily/sz000977.csv
sz000978 桂林旅游
./Stock_Daily/sz000978.csv
sz000980 众泰汽车
./Stock_Daily/sz000980.csv
sz000981 山子股份
./Stock_Daily/sz000981.csv
sz000982 中银绒业
./Stock_Daily/sz000982.csv
sz000983 山西焦煤
./Stock_Daily/sz000983.csv
sz000985 大庆华科
./Stock_Daily/sz000985.csv
sz000987 越秀资本
./Stock_Daily/sz000987.csv
sz000988 华工科技
./Stock_Daily/sz000988.csv
sz000989 九 芝 堂
./Stock_Daily/sz000989.csv
sz000990 诚志股份
./Stock_Daily/sz000990.csv
sz000993 闽东电力
./Stock_Daily/sz000993.csv
sz000995 皇台酒业
./Stock_Daily/sz000995.csv
sz000996 *ST中期
./Stock_Daily/sz000996.csv
sz000997 新 大 陆
./Stock_Daily/sz000997.csv
sz000998 隆平高科
./Stock_Daily/sz000998.csv
sz000999 华润三九
./Stock_Daily/sz000999.csv
sz001201 东瑞股份
./Stock_Daily/sz001201.csv
sz001202 炬申股份
./Stock_Daily/sz001202.csv
sz001203 大中矿业
./Stock_Daily/sz001203.csv
sz001205 盛航股份
./Stock_Daily/sz001205.csv
sz001206 依依股份
./Stock_Daily/sz001206.csv
sz001207 联科科技
./Stock_Daily/sz001207.csv
sz001208 华菱线缆
./Stock_Daily/sz001208.csv
sz001209 洪兴股份
./Stock_Daily/sz001209.csv
sz001210 金房能源
./Stock_Daily/sz001210.csv
sz001211 双枪科技
./Stock_Daily/sz001211.csv
sz001212 中旗新材
./Stock_Daily/sz001212.csv
sz001213 中铁特货
./Stock_Daily/sz001213.csv
sz001215 千味央厨
./Stock_Daily/sz001215.csv
sz001216 华瓷股份
./Stock_Daily/sz001216.csv
sz001217 华尔泰
./Stock_Daily/sz001217.csv
sz001218 丽臣实业
./Stock_Daily/sz001218.csv
sz001219 青岛食品
./Stock_Daily/sz001219.csv
sz001222 源飞宠物
./Stock_Daily/sz001222.csv
sz001223 欧克科技
./Stock_Daily/sz001223.csv
sz001225 和泰机电
./Stock_Daily/sz001225.csv
sz001226 拓山重工
./Stock_Daily/sz001226.csv
sz001227 兰州银行
./Stock_Daily/sz001227.csv
sz001228 永泰运
./Stock_Daily/sz001228.csv
sz001229 魅视科技
./Stock_Daily/sz001229.csv
sz001230 劲旅环境
./Stock_Daily/sz001230.csv
sz001231 农心科技
./Stock_Daily/sz001231.csv
sz001234 泰慕士
./Stock_Daily/sz001234.csv
sz001236 弘业期货
./Stock_Daily/sz001236.csv
sz001238 浙江正特
./Stock_Daily/sz001238.csv
sz001255 博菲电气
./Stock_Daily/sz001255.csv
sz001256 炜冈科技
./Stock_Daily/sz001256.csv
sz001258 立新能源
./Stock_Daily/sz001258.csv
sz001259 利仁科技
./Stock_Daily/sz001259.csv
sz001260 坤泰股份
./Stock_Daily/sz001260.csv
sz001266 宏英智能
./Stock_Daily/sz001266.csv
sz001267 汇绿生态
./Stock_Daily/sz001267.csv
sz001268 联合精密
./Stock_Daily/sz001268.csv
sz001269 欧晶科技
./Stock_Daily/sz001269.csv
sz001270 铖昌科技
./Stock_Daily/sz001270.csv
sz001278 一彬科技
./Stock_Daily/sz001278.csv
sz001282 三联锻造
./Stock_Daily/sz001282.csv
sz001283 豪鹏科技
./Stock_Daily/sz001283.csv
sz001286 陕西能源
./Stock_Daily/sz001286.csv
sz001287 中电港
./Stock_Daily/sz001287.csv
sz001288 运机集团
./Stock_Daily/sz001288.csv
sz001289 龙源电力
./Stock_Daily/sz001289.csv
sz001296 长江材料
./Stock_Daily/sz001296.csv
sz001298 好上好
./Stock_Daily/sz001298.csv
sz001299 美能能源
./Stock_Daily/sz001299.csv
sz001300 三柏硕
./Stock_Daily/sz001300.csv
sz001301 尚太科技
./Stock_Daily/sz001301.csv
sz001306 C夏厦
./Stock_Daily/sz001306.csv
sz001308 康冠科技
./Stock_Daily/sz001308.csv
sz001309 德明利
./Stock_Daily/sz001309.csv
sz001311 多利科技
./Stock_Daily/sz001311.csv
sz001313 粤海饲料
./Stock_Daily/sz001313.csv
sz001314 亿道信息
./Stock_Daily/sz001314.csv
sz001316 润贝航科
./Stock_Daily/sz001316.csv
sz001317 三羊马
./Stock_Daily/sz001317.csv
sz001318 阳光乳业
./Stock_Daily/sz001318.csv
sz001319 铭科精技
./Stock_Daily/sz001319.csv
sz001322 箭牌家居
./Stock_Daily/sz001322.csv
sz001323 慕思股份
./Stock_Daily/sz001323.csv
sz001324 长青科技
./Stock_Daily/sz001324.csv
sz001326 联域股份
./Stock_Daily/sz001326.csv
sz001328 登康口腔
./Stock_Daily/sz001328.csv
sz001330 博纳影业
./Stock_Daily/sz001330.csv
sz001331 胜通能源
./Stock_Daily/sz001331.csv
sz001332 锡装股份
./Stock_Daily/sz001332.csv
sz001333 光华股份
./Stock_Daily/sz001333.csv
sz001336 楚环科技
./Stock_Daily/sz001336.csv
sz001337 四川黄金
./Stock_Daily/sz001337.csv
sz001338 永顺泰
./Stock_Daily/sz001338.csv
sz001339 智微智能
./Stock_Daily/sz001339.csv
sz001360 南矿集团
./Stock_Daily/sz001360.csv
sz001366 播恩集团
./Stock_Daily/sz001366.csv
sz001367 海森药业
./Stock_Daily/sz001367.csv
sz001368 通达创智
./Stock_Daily/sz001368.csv
sz001373 翔腾新材
./Stock_Daily/sz001373.csv
sz001376 百通能源
./Stock_Daily/sz001376.csv
sz001378 德冠新材
./Stock_Daily/sz001378.csv
sz001380 华纬科技
./Stock_Daily/sz001380.csv
sz001696 宗申动力
./Stock_Daily/sz001696.csv
sz001872 招商港口
./Stock_Daily/sz001872.csv
sz001896 豫能控股
./Stock_Daily/sz001896.csv
sz001914 招商积余
./Stock_Daily/sz001914.csv
sz001965 招商公路
./Stock_Daily/sz001965.csv
sz001979 招商蛇口
./Stock_Daily/sz001979.csv
sz002001 新 和 成
./Stock_Daily/sz002001.csv
sz002002 ST鸿达
./Stock_Daily/sz002002.csv
sz002003 伟星股份
./Stock_Daily/sz002003.csv
sz002004 华邦健康
./Stock_Daily/sz002004.csv
sz002005 ST德豪
./Stock_Daily/sz002005.csv
sz002006 精工科技
./Stock_Daily/sz002006.csv
sz002007 华兰生物
./Stock_Daily/sz002007.csv
sz002008 大族激光
./Stock_Daily/sz002008.csv
sz002009 天奇股份
./Stock_Daily/sz002009.csv
sz002010 传化智联
./Stock_Daily/sz002010.csv
sz002011 盾安环境
./Stock_Daily/sz002011.csv
sz002012 凯恩股份
./Stock_Daily/sz002012.csv
sz002014 永新股份

./Stock_Daily/sz002014.csv
sz002015 协鑫能科
./Stock_Daily/sz002015.csv
sz002016 世荣兆业
./Stock_Daily/sz002016.csv
sz002017 东信和平
./Stock_Daily/sz002017.csv
sz002019 亿帆医药
./Stock_Daily/sz002019.csv
sz002020 京新药业
./Stock_Daily/sz002020.csv
sz002021 *ST中捷
./Stock_Daily/sz002021.csv
sz002022 科华生物
./Stock_Daily/sz002022.csv
sz002023 海特高新
./Stock_Daily/sz002023.csv
sz002024 ST易购
./Stock_Daily/sz002024.csv
sz002025 航天电器
./Stock_Daily/sz002025.csv
sz002026 山东威达
./Stock_Daily/sz002026.csv
sz002027 分众传媒
./Stock_Daily/sz002027.csv
sz002028 思源电气
./Stock_Daily/sz002028.csv
sz002029 七 匹 狼
./Stock_Daily/sz002029.csv
sz002030 达安基因
./Stock_Daily/sz002030.csv
sz002031 巨轮智能
./Stock_Daily/sz002031.csv
sz002032 苏 泊 尔
./Stock_Daily/sz002032.csv
sz002033 丽江股份
./Stock_Daily/sz002033.csv
sz002034 旺能环境
./Stock_Daily/sz002034.csv
sz002035 华帝股份
./Stock_Daily/sz002035.csv
sz002036 联创电子
./Stock_Daily/sz002036.csv
sz002037 保利联合
./Stock_Daily/sz002037.csv
sz002038 双鹭药业
./Stock_Daily/sz002038.csv
sz002039 黔源电力
./Stock_Daily/sz002039.csv
sz002040 南 京 港
./Stock_Daily/sz002040.csv
sz002041 登海种业
./Stock_Daily/sz002041.csv
sz002042 华孚时尚
./Stock_Daily/sz002042.csv
sz002043 兔 宝 宝
./Stock_Daily/sz002043.csv
sz002044 美年健康
./Stock_Daily/sz002044.csv
sz002045 国光电器
./Stock_Daily/sz002045.csv
sz002046 国机精工
./Stock_Daily/sz002046.csv
sz002047 宝鹰股份
./Stock_Daily/sz002047.csv
sz002048 宁波华翔
./Stock_Daily/sz002048.csv
sz002049 紫光国微
./Stock_Daily/sz002049.csv
sz002050 三花智控
./Stock_Daily/sz002050.csv
sz002051 中工国际
./Stock_Daily/sz002051.csv
sz002052 ST同洲
./Stock_Daily/sz002052.csv
sz002053 云南能投
./Stock_Daily/sz002053.csv
sz002054 德美化工
./Stock_Daily/sz002054.csv
sz002055 得润电子
./Stock_Daily/sz002055.csv
sz002056 横店东磁
./Stock_Daily/sz002056.csv
sz002057 中钢天源
./Stock_Daily/sz002057.csv
sz002058 威尔泰
./Stock_Daily/sz002058.csv
sz002059 云南旅游
./Stock_Daily/sz002059.csv
sz002060 粤 水 电
./Stock_Daily/sz002060.csv
sz002061 浙江交科
./Stock_Daily/sz002061.csv
sz002062 宏润建设
./Stock_Daily/sz002062.csv
sz002063 远光软件
./Stock_Daily/sz002063.csv
sz002064 华峰化学
./Stock_Daily/sz002064.csv
sz002065 东华软件
./Stock_Daily/sz002065.csv
sz002066 瑞泰科技
./Stock_Daily/sz002066.csv
sz002067 景兴纸业
./Stock_Daily/sz002067.csv
sz002068 黑猫股份
./Stock_Daily/sz002068.csv
sz002069 獐子岛
./Stock_Daily/sz002069.csv
sz002072 凯瑞德
./Stock_Daily/sz002072.csv
sz002073 软控股份
./Stock_Daily/sz002073.csv
sz002074 国轩高科
./Stock_Daily/sz002074.csv
sz002075 沙钢股份
./Stock_Daily/sz002075.csv
sz002076 星光股份
./Stock_Daily/sz002076.csv
sz002077 大港股份
./Stock_Daily/sz002077.csv
sz002078 太阳纸业
./Stock_Daily/sz002078.csv
sz002079 苏州固锝
./Stock_Daily/sz002079.csv
sz002080 中材科技
./Stock_Daily/sz002080.csv
sz002081 金 螳 螂
./Stock_Daily/sz002081.csv
sz002082 万邦德
./Stock_Daily/sz002082.csv
sz002083 孚日股份
./Stock_Daily/sz002083.csv
sz002084 海鸥住工
./Stock_Daily/sz002084.csv
sz002085 万丰奥威
./Stock_Daily/sz002085.csv
sz002086 *ST东洋
./Stock_Daily/sz002086.csv
sz002087 *ST新纺
./Stock_Daily/sz002087.csv
sz002088 鲁阳节能
./Stock_Daily/sz002088.csv
sz002089 *ST新海
./Stock_Daily/sz002089.csv
sz002090 金智科技
./Stock_Daily/sz002090.csv
sz002091 江苏国泰
./Stock_Daily/sz002091.csv
sz002092 中泰化学
./Stock_Daily/sz002092.csv
sz002093 国脉科技
./Stock_Daily/sz002093.csv
sz002094 青岛金王
./Stock_Daily/sz002094.csv
sz002095 生 意 宝
./Stock_Daily/sz002095.csv
sz002096 易普力
./Stock_Daily/sz002096.csv
sz002097 山河智能
./Stock_Daily/sz002097.csv
sz002098 浔兴股份
./Stock_Daily/sz002098.csv
sz002099 海翔药业
./Stock_Daily/sz002099.csv
sz002100 天康生物
./Stock_Daily/sz002100.csv
sz002101 广东鸿图
./Stock_Daily/sz002101.csv
sz002102 冠福股份
./Stock_Daily/sz002102.csv
sz002103 广博股份
./Stock_Daily/sz002103.csv
sz002104 恒宝股份
./Stock_Daily/sz002104.csv
sz002105 信隆健康
./Stock_Daily/sz002105.csv
sz002106 莱宝高科
./Stock_Daily/sz002106.csv
sz002107 沃华医药
./Stock_Daily/sz002107.csv
sz002108 沧州明珠
./Stock_Daily/sz002108.csv
sz002109 兴化股份
./Stock_Daily/sz002109.csv
sz002110 三钢闽光
./Stock_Daily/sz002110.csv
sz002111 威海广泰
./Stock_Daily/sz002111.csv
sz002112 三变科技
./Stock_Daily/sz002112.csv
sz002114 罗平锌电
./Stock_Daily/sz002114.csv
sz002115 三维通信
./Stock_Daily/sz002115.csv
sz002116 中国海诚
./Stock_Daily/sz002116.csv
sz002117 东港股份
./Stock_Daily/sz002117.csv
sz002119 康强电子
./Stock_Daily/sz002119.csv
sz002120 韵达股份
./Stock_Daily/sz002120.csv
sz002121 科陆电子
./Stock_Daily/sz002121.csv
sz002122 汇洲智能
./Stock_Daily/sz002122.csv
sz002123 梦网科技
./Stock_Daily/sz002123.csv
sz002124 天邦食品
./Stock_Daily/sz002124.csv
sz002125 湘潭电化
./Stock_Daily/sz002125.csv
sz002126 银轮股份
./Stock_Daily/sz002126.csv
sz002127 南极电商
./Stock_Daily/sz002127.csv
sz002128 电投能源
./Stock_Daily/sz002128.csv
sz002129 TCL中环
./Stock_Daily/sz002129.csv
sz002130 沃尔核材
./Stock_Daily/sz002130.csv
sz002131 利欧股份
./Stock_Daily/sz002131.csv
sz002132 恒星科技
./Stock_Daily/sz002132.csv
sz002133 广宇集团
./Stock_Daily/sz002133.csv
sz002134 天津普林
./Stock_Daily/sz002134.csv
sz002135 东南网架
./Stock_Daily/sz002135.csv
sz002136 安 纳 达
./Stock_Daily/sz002136.csv
sz002137 实益达
./Stock_Daily/sz002137.csv
sz002138 顺络电子
./Stock_Daily/sz002138.csv
sz002139 拓邦股份
./Stock_Daily/sz002139.csv
sz002140 东华科技
./Stock_Daily/sz002140.csv
sz002141 贤丰控股
./Stock_Daily/sz002141.csv
sz002142 宁波银行
./Stock_Daily/sz002142.csv
sz002144 宏达高科
./Stock_Daily/sz002144.csv
sz002145 中核钛白
./Stock_Daily/sz002145.csv
sz002146 荣盛发展
./Stock_Daily/sz002146.csv
sz002148 北纬科技
./Stock_Daily/sz002148.csv
sz002149 西部材料
./Stock_Daily/sz002149.csv
sz002150 通润装备
./Stock_Daily/sz002150.csv
sz002151 北斗星通
./Stock_Daily/sz002151.csv
sz002152 广电运通
./Stock_Daily/sz002152.csv
sz002153 石基信息
./Stock_Daily/sz002153.csv
sz002154 报 喜 鸟
./Stock_Daily/sz002154.csv
sz002155 湖南黄金
./Stock_Daily/sz002155.csv
sz002156 通富微电
./Stock_Daily/sz002156.csv
sz002157 *ST 正邦
./Stock_Daily/sz002157.csv
sz002158 汉钟精机
./Stock_Daily/sz002158.csv
sz002159 三特索道
./Stock_Daily/sz002159.csv
sz002160 常铝股份
./Stock_Daily/sz002160.csv
sz002161 远 望 谷
./Stock_Daily/sz002161.csv
sz002162 悦心健康
./Stock_Daily/sz002162.csv
sz002163 海南发展
./Stock_Daily/sz002163.csv
sz002164 宁波东力
./Stock_Daily/sz002164.csv
sz002165 红 宝 丽
./Stock_Daily/sz002165.csv
sz002166 莱茵生物
./Stock_Daily/sz002166.csv
sz002167 东方锆业
./Stock_Daily/sz002167.csv
sz002168 惠程科技
./Stock_Daily/sz002168.csv
sz002169 智光电气
./Stock_Daily/sz002169.csv
sz002170 芭田股份
./Stock_Daily/sz002170.csv
sz002171 楚江新材
./Stock_Daily/sz002171.csv
sz002172 澳洋健康
./Stock_Daily/sz002172.csv
sz002173 创新医疗
./Stock_Daily/sz002173.csv
sz002174 游族网络
./Stock_Daily/sz002174.csv
sz002175 东方智造
./Stock_Daily/sz002175.csv
sz002176 江特电机
./Stock_Daily/sz002176.csv
sz002177 御银股份
./Stock_Daily/sz002177.csv
sz002178 延华智能
./Stock_Daily/sz002178.csv
sz002179 中航光电
./Stock_Daily/sz002179.csv
sz002180 纳思达
./Stock_Daily/sz002180.csv
sz002181 粤 传 媒
./Stock_Daily/sz002181.csv
sz002182 宝武镁业
./Stock_Daily/sz002182.csv
sz002183 怡 亚 通
./Stock_Daily/sz002183.csv
sz002184 海得控制
./Stock_Daily/sz002184.csv
sz002185 华天科技
./Stock_Daily/sz002185.csv
sz002186 全 聚 德
./Stock_Daily/sz002186.csv
sz002187 广百股份
./Stock_Daily/sz002187.csv
sz002188 中天服务
./Stock_Daily/sz002188.csv
sz002189 中光学
./Stock_Daily/sz002189.csv
sz002190 成飞集成
./Stock_Daily/sz002190.csv
sz002191 劲嘉股份
./Stock_Daily/sz002191.csv
sz002192 融捷股份
./Stock_Daily/sz002192.csv
sz002193 如意集团
./Stock_Daily/sz002193.csv
sz002194 武汉凡谷
./Stock_Daily/sz002194.csv
sz002195 岩山科技
./Stock_Daily/sz002195.csv
sz002196 方正电机
./Stock_Daily/sz002196.csv
sz002197 证通电子
./Stock_Daily/sz002197.csv
sz002198 嘉应制药
./Stock_Daily/sz002198.csv
sz002199 东晶电子
./Stock_Daily/sz002199.csv
sz002200 ST交投
./Stock_Daily/sz002200.csv
sz002201 正威新材
./Stock_Daily/sz002201.csv
sz002202 金风科技
./Stock_Daily/sz002202.csv
sz002203 海亮股份
./Stock_Daily/sz002203.csv
sz002204 大连重工
./Stock_Daily/sz002204.csv
sz002205 国统股份
./Stock_Daily/sz002205.csv
sz002206 海 利 得
./Stock_Daily/sz002206.csv
sz002207 准油股份
./Stock_Daily/sz002207.csv
sz002208 合肥城建
./Stock_Daily/sz002208.csv
sz002209 达 意 隆
./Stock_Daily/sz002209.csv
sz002210 飞马国际
./Stock_Daily/sz002210.csv
sz002211 宏达新材
./Stock_Daily/sz002211.csv
sz002212 天融信
./Stock_Daily/sz002212.csv
sz002213 大为股份
./Stock_Daily/sz002213.csv
sz002214 大立科技
./Stock_Daily/sz002214.csv
sz002215 诺 普 信
./Stock_Daily/sz002215.csv
sz002216 三全食品
./Stock_Daily/sz002216.csv
sz002217 合力泰
./Stock_Daily/sz002217.csv
sz002218 拓日新能
./Stock_Daily/sz002218.csv
sz002219 新里程
./Stock_Daily/sz002219.csv
sz002221 东华能源
./Stock_Daily/sz002221.csv
sz002222 福晶科技

./Stock_Daily/sz002222.csv
sz002223 鱼跃医疗
./Stock_Daily/sz002223.csv
sz002224 三 力 士
./Stock_Daily/sz002224.csv
sz002225 濮耐股份
./Stock_Daily/sz002225.csv
sz002226 江南化工
./Stock_Daily/sz002226.csv
sz002227 奥 特 迅
./Stock_Daily/sz002227.csv
sz002228 合兴包装
./Stock_Daily/sz002228.csv
sz002229 鸿博股份
./Stock_Daily/sz002229.csv
sz002230 科大讯飞
./Stock_Daily/sz002230.csv
sz002231 奥维通信
./Stock_Daily/sz002231.csv
sz002232 启明信息
./Stock_Daily/sz002232.csv
sz002233 塔牌集团
./Stock_Daily/sz002233.csv
sz002234 民和股份
./Stock_Daily/sz002234.csv
sz002235 安妮股份
./Stock_Daily/sz002235.csv
sz002236 大华股份
./Stock_Daily/sz002236.csv
sz002237 恒邦股份
./Stock_Daily/sz002237.csv
sz002238 天威视讯
./Stock_Daily/sz002238.csv
sz002239 奥特佳
./Stock_Daily/sz002239.csv
sz002240 盛新锂能
./Stock_Daily/sz002240.csv
sz002241 歌尔股份
./Stock_Daily/sz002241.csv
sz002242 九阳股份
./Stock_Daily/sz002242.csv
sz002243 力合科创
./Stock_Daily/sz002243.csv
sz002244 滨江集团
./Stock_Daily/sz002244.csv
sz002245 蔚蓝锂芯
./Stock_Daily/sz002245.csv
sz002246 北化股份
./Stock_Daily/sz002246.csv
sz002247 聚力文化
./Stock_Daily/sz002247.csv
sz002248 华东数控
./Stock_Daily/sz002248.csv
sz002249 大洋电机
./Stock_Daily/sz002249.csv
sz002250 联化科技
./Stock_Daily/sz002250.csv
sz002251 *ST步高
./Stock_Daily/sz002251.csv
sz002252 上海莱士
./Stock_Daily/sz002252.csv
sz002253 川大智胜
./Stock_Daily/sz002253.csv
sz002254 泰和新材
./Stock_Daily/sz002254.csv
sz002255 海陆重工
./Stock_Daily/sz002255.csv
sz002256 兆新股份
./Stock_Daily/sz002256.csv
sz002258 利尔化学
./Stock_Daily/sz002258.csv
sz002259 ST升达
./Stock_Daily/sz002259.csv
sz002261 拓维信息
./Stock_Daily/sz002261.csv
sz002262 恩华药业
./Stock_Daily/sz002262.csv
sz002263 大东南
./Stock_Daily/sz002263.csv
sz002264 新 华 都
./Stock_Daily/sz002264.csv
sz002265 建设工业
./Stock_Daily/sz002265.csv
sz002266 浙富控股
./Stock_Daily/sz002266.csv
sz002267 陕天然气
./Stock_Daily/sz002267.csv
sz002268 电科网安
./Stock_Daily/sz002268.csv
sz002269 美邦服饰
./Stock_Daily/sz002269.csv
sz002270 华明装备
./Stock_Daily/sz002270.csv
sz002271 东方雨虹
./Stock_Daily/sz002271.csv
sz002272 川润股份
./Stock_Daily/sz002272.csv
sz002273 水晶光电
./Stock_Daily/sz002273.csv
sz002274 华昌化工
./Stock_Daily/sz002274.csv
sz002275 桂林三金
./Stock_Daily/sz002275.csv
sz002276 万马股份
./Stock_Daily/sz002276.csv
sz002277 友阿股份
./Stock_Daily/sz002277.csv
sz002278 神开股份
./Stock_Daily/sz002278.csv
sz002279 久其软件
./Stock_Daily/sz002279.csv
sz002280 联络互动
./Stock_Daily/sz002280.csv
sz002281 光迅科技
./Stock_Daily/sz002281.csv
sz002282 博深股份
./Stock_Daily/sz002282.csv
sz002283 天润工业
./Stock_Daily/sz002283.csv
sz002284 亚太股份
./Stock_Daily/sz002284.csv
sz002285 世联行
./Stock_Daily/sz002285.csv
sz002286 保龄宝
./Stock_Daily/sz002286.csv
sz002287 奇正藏药
./Stock_Daily/sz002287.csv
sz002288 超华科技
./Stock_Daily/sz002288.csv
sz002289 ST宇顺
./Stock_Daily/sz002289.csv
sz002290 禾盛新材
./Stock_Daily/sz002290.csv
sz002291 遥望科技
./Stock_Daily/sz002291.csv
sz002292 奥飞娱乐
./Stock_Daily/sz002292.csv
sz002293 罗莱生活
./Stock_Daily/sz002293.csv
sz002294 信立泰
./Stock_Daily/sz002294.csv
sz002295 精艺股份
./Stock_Daily/sz002295.csv
sz002296 辉煌科技
./Stock_Daily/sz002296.csv
sz002297 博云新材
./Stock_Daily/sz002297.csv
sz002298 中电兴发
./Stock_Daily/sz002298.csv
sz002299 圣农发展
./Stock_Daily/sz002299.csv
sz002300 太阳电缆
./Stock_Daily/sz002300.csv
sz002301 齐心集团
./Stock_Daily/sz002301.csv
sz002302 西部建设
./Stock_Daily/sz002302.csv
sz002303 美盈森
./Stock_Daily/sz002303.csv
sz002304 洋河股份
./Stock_Daily/sz002304.csv
sz002305 南国置业
./Stock_Daily/sz002305.csv
sz002306 中科云网
./Stock_Daily/sz002306.csv
sz002307 北新路桥
./Stock_Daily/sz002307.csv
sz002308 威创股份
./Stock_Daily/sz002308.csv
sz002309 ST中利
./Stock_Daily/sz002309.csv
sz002310 东方园林
./Stock_Daily/sz002310.csv
sz002311 海大集团
./Stock_Daily/sz002311.csv
sz002312 川发龙蟒
./Stock_Daily/sz002312.csv
sz002313 日海智能
./Stock_Daily/sz002313.csv
sz002314 南山控股
./Stock_Daily/sz002314.csv
sz002315 焦点科技
./Stock_Daily/sz002315.csv
sz002316 亚联发展
./Stock_Daily/sz002316.csv
sz002317 众生药业
./Stock_Daily/sz002317.csv
sz002318 久立特材
./Stock_Daily/sz002318.csv
sz002319 乐通股份
./Stock_Daily/sz002319.csv
sz002320 海峡股份
./Stock_Daily/sz002320.csv
sz002321 华英农业
./Stock_Daily/sz002321.csv
sz002322 理工能科
./Stock_Daily/sz002322.csv
sz002323 雅博股份
./Stock_Daily/sz002323.csv
sz002324 普利特
./Stock_Daily/sz002324.csv
sz002325 洪涛股份
./Stock_Daily/sz002325.csv
sz002326 永太科技
./Stock_Daily/sz002326.csv
sz002327 富安娜
./Stock_Daily/sz002327.csv
sz002328 新朋股份
./Stock_Daily/sz002328.csv
sz002329 皇氏集团
./Stock_Daily/sz002329.csv
sz002330 得利斯
./Stock_Daily/sz002330.csv
sz002331 皖通科技
./Stock_Daily/sz002331.csv
sz002332 仙琚制药
./Stock_Daily/sz002332.csv
sz002333 罗普斯金
./Stock_Daily/sz002333.csv
sz002334 英威腾
./Stock_Daily/sz002334.csv
sz002335 科华数据
./Stock_Daily/sz002335.csv
sz002336 人人乐
./Stock_Daily/sz002336.csv
sz002337 赛象科技
./Stock_Daily/sz002337.csv
sz002338 奥普光电
./Stock_Daily/sz002338.csv
sz002339 积成电子
./Stock_Daily/sz002339.csv
sz002340 格林美
./Stock_Daily/sz002340.csv
sz002341 新纶新材
./Stock_Daily/sz002341.csv
sz002342 巨力索具
./Stock_Daily/sz002342.csv
sz002343 慈文传媒
./Stock_Daily/sz002343.csv
sz002344 海宁皮城
./Stock_Daily/sz002344.csv
sz002345 潮宏基
./Stock_Daily/sz002345.csv
sz002346 柘中股份
./Stock_Daily/sz002346.csv
sz002347 泰尔股份
./Stock_Daily/sz002347.csv
sz002348 高乐股份
./Stock_Daily/sz002348.csv
sz002349 精华制药
./Stock_Daily/sz002349.csv
sz002350 北京科锐
./Stock_Daily/sz002350.csv
sz002351 漫步者
./Stock_Daily/sz002351.csv
sz002352 顺丰控股
./Stock_Daily/sz002352.csv
sz002353 杰瑞股份
./Stock_Daily/sz002353.csv
sz002354 天娱数科
./Stock_Daily/sz002354.csv
sz002355 兴民智通
./Stock_Daily/sz002355.csv
sz002356 赫美集团
./Stock_Daily/sz002356.csv
sz002357 富临运业
./Stock_Daily/sz002357.csv
sz002358 森源电气
./Stock_Daily/sz002358.csv
sz002360 同德化工
./Stock_Daily/sz002360.csv
sz002361 神剑股份
./Stock_Daily/sz002361.csv
sz002362 汉王科技
./Stock_Daily/sz002362.csv
sz002363 隆基机械
./Stock_Daily/sz002363.csv
sz002364 中恒电气
./Stock_Daily/sz002364.csv
sz002365 永安药业
./Stock_Daily/sz002365.csv
sz002366 融发核电
./Stock_Daily/sz002366.csv
sz002367 康力电梯
./Stock_Daily/sz002367.csv
sz002368 太极股份
./Stock_Daily/sz002368.csv
sz002369 卓翼科技
./Stock_Daily/sz002369.csv
sz002370 亚太药业
./Stock_Daily/sz002370.csv
sz002371 北方华创
./Stock_Daily/sz002371.csv
sz002372 伟星新材
./Stock_Daily/sz002372.csv
sz002373 千方科技
./Stock_Daily/sz002373.csv
sz002374 中锐股份
./Stock_Daily/sz002374.csv
sz002375 亚厦股份
./Stock_Daily/sz002375.csv
sz002376 新北洋
./Stock_Daily/sz002376.csv
sz002377 国创高新
./Stock_Daily/sz002377.csv
sz002378 章源钨业
./Stock_Daily/sz002378.csv
sz002379 宏创控股
./Stock_Daily/sz002379.csv
sz002380 科远智慧
./Stock_Daily/sz002380.csv
sz002381 双箭股份
./Stock_Daily/sz002381.csv
sz002382 蓝帆医疗
./Stock_Daily/sz002382.csv
sz002383 合众思壮
./Stock_Daily/sz002383.csv
sz002384 东山精密
./Stock_Daily/sz002384.csv
sz002385 大北农
./Stock_Daily/sz002385.csv
sz002386 天原股份
./Stock_Daily/sz002386.csv
sz002387 维信诺
./Stock_Daily/sz002387.csv
sz002388 新亚制程
./Stock_Daily/sz002388.csv
sz002389 航天彩虹
./Stock_Daily/sz002389.csv
sz002390 信邦制药
./Stock_Daily/sz002390.csv
sz002391 长青股份
./Stock_Daily/sz002391.csv
sz002392 北京利尔
./Stock_Daily/sz002392.csv
sz002393 力生制药
./Stock_Daily/sz002393.csv
sz002394 联发股份
./Stock_Daily/sz002394.csv
sz002395 双象股份
./Stock_Daily/sz002395.csv
sz002396 星网锐捷
./Stock_Daily/sz002396.csv
sz002397 梦洁股份
./Stock_Daily/sz002397.csv
sz002398 垒知集团
./Stock_Daily/sz002398.csv
sz002399 海普瑞
./Stock_Daily/sz002399.csv
sz002400 省广集团
./Stock_Daily/sz002400.csv
sz002401 中远海科
./Stock_Daily/sz002401.csv
sz002402 和而泰
./Stock_Daily/sz002402.csv
sz002403 爱仕达
./Stock_Daily/sz002403.csv
sz002404 嘉欣丝绸
./Stock_Daily/sz002404.csv
sz002405 四维图新
./Stock_Daily/sz002405.csv
sz002406 远东传动
./Stock_Daily/sz002406.csv
sz002407 多氟多
./Stock_Daily/sz002407.csv
sz002408 齐翔腾达
./Stock_Daily/sz002408.csv
sz002409 雅克科技
./Stock_Daily/sz002409.csv
sz002410 广联达
./Stock_Daily/sz002410.csv
sz002412 汉森制药
./Stock_Daily/sz002412.csv
sz002413 雷科防务
./Stock_Daily/sz002413.csv
sz002414 高德红外
./Stock_Daily/sz002414.csv
sz002415 海康威视
./Stock_Daily/sz002415.csv
sz002416 爱施德
./Stock_Daily/sz002416.csv
sz002418 康盛股份
./Stock_Daily/sz002418.csv
sz002419 天虹股份
./Stock_Daily/sz002419.csv
sz002420 毅昌科技
./Stock_Daily/sz002420.csv
sz002421 达实智能
./Stock_Daily/sz002421.csv
sz002422 科伦药业
./Stock_Daily/sz002422.csv
sz002423 中粮资本
./Stock_Daily/sz002423.csv
sz002424 贵州百灵
./Stock_Daily/sz002424.csv
sz002425 凯撒文化
./Stock_Daily/sz002425.csv
sz002426 胜利精密
./Stock_Daily/sz002426.csv
sz002427 尤夫股份
./Stock_Daily/sz002427.csv
sz002428 云南锗业

./Stock_Daily/sz002428.csv
sz002429 兆驰股份
./Stock_Daily/sz002429.csv
sz002430 杭氧股份
./Stock_Daily/sz002430.csv
sz002431 棕榈股份
./Stock_Daily/sz002431.csv
sz002432 九安医疗
./Stock_Daily/sz002432.csv
sz002433 *ST太安
./Stock_Daily/sz002433.csv
sz002434 万里扬
./Stock_Daily/sz002434.csv
sz002435 长江健康
./Stock_Daily/sz002435.csv
sz002436 兴森科技
./Stock_Daily/sz002436.csv
sz002437 誉衡药业
./Stock_Daily/sz002437.csv
sz002438 江苏神通
./Stock_Daily/sz002438.csv
sz002439 启明星辰
./Stock_Daily/sz002439.csv
sz002440 闰土股份
./Stock_Daily/sz002440.csv
sz002441 众业达
./Stock_Daily/sz002441.csv
sz002442 龙星化工
./Stock_Daily/sz002442.csv
sz002443 金洲管道
./Stock_Daily/sz002443.csv
sz002444 巨星科技
./Stock_Daily/sz002444.csv
sz002445 中南文化
./Stock_Daily/sz002445.csv
sz002446 盛路通信
./Stock_Daily/sz002446.csv
sz002448 中原内配
./Stock_Daily/sz002448.csv
sz002449 国星光电
./Stock_Daily/sz002449.csv
sz002451 摩恩电气
./Stock_Daily/sz002451.csv
sz002452 长高电新
./Stock_Daily/sz002452.csv
sz002453 华软科技
./Stock_Daily/sz002453.csv
sz002454 松芝股份
./Stock_Daily/sz002454.csv
sz002455 百川股份
./Stock_Daily/sz002455.csv
sz002456 欧菲光
./Stock_Daily/sz002456.csv
sz002457 青龙管业
./Stock_Daily/sz002457.csv
sz002458 益生股份
./Stock_Daily/sz002458.csv
sz002459 晶澳科技
./Stock_Daily/sz002459.csv
sz002460 赣锋锂业
./Stock_Daily/sz002460.csv
sz002461 珠江啤酒
./Stock_Daily/sz002461.csv
sz002462 嘉事堂
./Stock_Daily/sz002462.csv
sz002463 沪电股份
./Stock_Daily/sz002463.csv
sz002465 海格通信
./Stock_Daily/sz002465.csv
sz002466 天齐锂业
./Stock_Daily/sz002466.csv
sz002467 二六三
./Stock_Daily/sz002467.csv
sz002468 申通快递
./Stock_Daily/sz002468.csv
sz002469 三维化学
./Stock_Daily/sz002469.csv
sz002470 金正大
./Stock_Daily/sz002470.csv
sz002471 中超控股
./Stock_Daily/sz002471.csv
sz002472 双环传动
./Stock_Daily/sz002472.csv
sz002474 榕基软件
./Stock_Daily/sz002474.csv
sz002475 立讯精密
./Stock_Daily/sz002475.csv
sz002476 宝莫股份
./Stock_Daily/sz002476.csv
sz002478 常宝股份
./Stock_Daily/sz002478.csv
sz002479 富春环保
./Stock_Daily/sz002479.csv
sz002480 新筑股份
./Stock_Daily/sz002480.csv
sz002481 双塔食品
./Stock_Daily/sz002481.csv
sz002482 *ST广田
./Stock_Daily/sz002482.csv
sz002483 润邦股份
./Stock_Daily/sz002483.csv
sz002484 江海股份
./Stock_Daily/sz002484.csv
sz002485 *ST雪发
./Stock_Daily/sz002485.csv
sz002486 嘉麟杰
./Stock_Daily/sz002486.csv
sz002487 大金重工
./Stock_Daily/sz002487.csv
sz002488 金固股份
./Stock_Daily/sz002488.csv
sz002489 浙江永强
./Stock_Daily/sz002489.csv
sz002490 山东墨龙
./Stock_Daily/sz002490.csv
sz002491 通鼎互联
./Stock_Daily/sz002491.csv
sz002492 恒基达鑫
./Stock_Daily/sz002492.csv
sz002493 荣盛石化
./Stock_Daily/sz002493.csv
sz002494 华斯股份
./Stock_Daily/sz002494.csv
sz002495 佳隆股份
./Stock_Daily/sz002495.csv
sz002496 辉丰股份
./Stock_Daily/sz002496.csv
sz002497 雅化集团
./Stock_Daily/sz002497.csv
sz002498 汉缆股份
./Stock_Daily/sz002498.csv
sz002500 山西证券
./Stock_Daily/sz002500.csv
sz002501 利源股份
./Stock_Daily/sz002501.csv
sz002502 ST鼎龙
./Stock_Daily/sz002502.csv
sz002505 鹏都农牧
./Stock_Daily/sz002505.csv
sz002506 协鑫集成
./Stock_Daily/sz002506.csv
sz002507 涪陵榨菜
./Stock_Daily/sz002507.csv
sz002508 老板电器
./Stock_Daily/sz002508.csv
sz002510 天汽模
./Stock_Daily/sz002510.csv
sz002511 中顺洁柔
./Stock_Daily/sz002511.csv
sz002512 达华智能
./Stock_Daily/sz002512.csv
sz002513 蓝丰生化
./Stock_Daily/sz002513.csv
sz002514 宝馨科技
./Stock_Daily/sz002514.csv
sz002515 金字火腿
./Stock_Daily/sz002515.csv
sz002516 旷达科技
./Stock_Daily/sz002516.csv
sz002517 恺英网络
./Stock_Daily/sz002517.csv
sz002518 科士达
./Stock_Daily/sz002518.csv
sz002519 银河电子
./Stock_Daily/sz002519.csv
sz002520 日发精机
./Stock_Daily/sz002520.csv
sz002521 齐峰新材
./Stock_Daily/sz002521.csv
sz002522 浙江众成
./Stock_Daily/sz002522.csv
sz002523 天桥起重
./Stock_Daily/sz002523.csv
sz002524 光正眼科
./Stock_Daily/sz002524.csv
sz002526 山东矿机
./Stock_Daily/sz002526.csv
sz002527 新时达
./Stock_Daily/sz002527.csv
sz002528 英飞拓
./Stock_Daily/sz002528.csv
sz002529 海源复材
./Stock_Daily/sz002529.csv
sz002530 金财互联
./Stock_Daily/sz002530.csv
sz002531 天顺风能
./Stock_Daily/sz002531.csv
sz002532 天山铝业
./Stock_Daily/sz002532.csv
sz002533 金杯电工
./Stock_Daily/sz002533.csv
sz002534 西子洁能
./Stock_Daily/sz002534.csv
sz002535 林州重机
./Stock_Daily/sz002535.csv
sz002536 飞龙股份
./Stock_Daily/sz002536.csv
sz002537 海联金汇
./Stock_Daily/sz002537.csv
sz002538 司尔特
./Stock_Daily/sz002538.csv
sz002539 云图控股
./Stock_Daily/sz002539.csv
sz002540 亚太科技
./Stock_Daily/sz002540.csv
sz002541 鸿路钢构
./Stock_Daily/sz002541.csv
sz002542 中化岩土
./Stock_Daily/sz002542.csv
sz002543 万和电气
./Stock_Daily/sz002543.csv
sz002544 普天科技
./Stock_Daily/sz002544.csv
sz002545 东方铁塔
./Stock_Daily/sz002545.csv
sz002546 新联电子
./Stock_Daily/sz002546.csv
sz002547 春兴精工
./Stock_Daily/sz002547.csv
sz002548 金新农
./Stock_Daily/sz002548.csv
sz002549 凯美特气
./Stock_Daily/sz002549.csv
sz002550 千红制药
./Stock_Daily/sz002550.csv
sz002551 尚荣医疗
./Stock_Daily/sz002551.csv
sz002552 宝鼎科技
./Stock_Daily/sz002552.csv
sz002553 南方精工
./Stock_Daily/sz002553.csv
sz002554 惠博普
./Stock_Daily/sz002554.csv
sz002555 三七互娱
./Stock_Daily/sz002555.csv
sz002556 辉隆股份
./Stock_Daily/sz002556.csv
sz002557 洽洽食品
./Stock_Daily/sz002557.csv
sz002558 巨人网络
./Stock_Daily/sz002558.csv
sz002559 亚威股份
./Stock_Daily/sz002559.csv
sz002560 通达股份
./Stock_Daily/sz002560.csv
sz002561 徐家汇
./Stock_Daily/sz002561.csv
sz002562 兄弟科技
./Stock_Daily/sz002562.csv
sz002563 森马服饰
./Stock_Daily/sz002563.csv
sz002564 *ST天沃
./Stock_Daily/sz002564.csv
sz002565 顺灏股份
./Stock_Daily/sz002565.csv
sz002566 益盛药业
./Stock_Daily/sz002566.csv
sz002567 唐人神
./Stock_Daily/sz002567.csv
sz002568 百润股份
./Stock_Daily/sz002568.csv
sz002569 ST步森
./Stock_Daily/sz002569.csv
sz002570 贝因美
./Stock_Daily/sz002570.csv
sz002571 德力股份
./Stock_Daily/sz002571.csv
sz002572 索菲亚
./Stock_Daily/sz002572.csv
sz002573 清新环境
./Stock_Daily/sz002573.csv
sz002574 明牌珠宝
./Stock_Daily/sz002574.csv
sz002575 群兴玩具
./Stock_Daily/sz002575.csv
sz002576 通达动力
./Stock_Daily/sz002576.csv
sz002577 雷柏科技
./Stock_Daily/sz002577.csv
sz002578 闽发铝业
./Stock_Daily/sz002578.csv
sz002579 中京电子
./Stock_Daily/sz002579.csv
sz002580 圣阳股份
./Stock_Daily/sz002580.csv
sz002581 未名医药
./Stock_Daily/sz002581.csv
sz002582 好想你
./Stock_Daily/sz002582.csv
sz002583 海能达
./Stock_Daily/sz002583.csv
sz002584 西陇科学
./Stock_Daily/sz002584.csv
sz002585 双星新材
./Stock_Daily/sz002585.csv
sz002586 *ST围海
./Stock_Daily/sz002586.csv
sz002587 奥拓电子
./Stock_Daily/sz002587.csv
sz002588 史丹利
./Stock_Daily/sz002588.csv
sz002589 瑞康医药
./Stock_Daily/sz002589.csv
sz002590 万安科技
./Stock_Daily/sz002590.csv
sz002591 恒大高新
./Stock_Daily/sz002591.csv
sz002592 ST八菱
./Stock_Daily/sz002592.csv
sz002593 日上集团
./Stock_Daily/sz002593.csv
sz002594 比亚迪
./Stock_Daily/sz002594.csv
sz002595 豪迈科技
./Stock_Daily/sz002595.csv
sz002596 海南瑞泽
./Stock_Daily/sz002596.csv
sz002597 金禾实业
./Stock_Daily/sz002597.csv
sz002598 山东章鼓
./Stock_Daily/sz002598.csv
sz002599 盛通股份
./Stock_Daily/sz002599.csv
sz002600 领益智造
./Stock_Daily/sz002600.csv
sz002601 龙佰集团
./Stock_Daily/sz002601.csv
sz002602 世纪华通
./Stock_Daily/sz002602.csv
sz002603 以岭药业
./Stock_Daily/sz002603.csv
sz002605 姚记科技
./Stock_Daily/sz002605.csv
sz002606 大连电瓷
./Stock_Daily/sz002606.csv
sz002607 中公教育
./Stock_Daily/sz002607.csv
sz002608 江苏国信
./Stock_Daily/sz002608.csv
sz002609 捷顺科技
./Stock_Daily/sz002609.csv
sz002610 爱康科技
./Stock_Daily/sz002610.csv
sz002611 东方精工
./Stock_Daily/sz002611.csv
sz002612 朗姿股份
./Stock_Daily/sz002612.csv
sz002613 北玻股份
./Stock_Daily/sz002613.csv
sz002614 奥佳华
./Stock_Daily/sz002614.csv
sz002615 哈尔斯
./Stock_Daily/sz002615.csv
sz002616 长青集团
./Stock_Daily/sz002616.csv
sz002617 露笑科技
./Stock_Daily/sz002617.csv
sz002620 瑞和股份
./Stock_Daily/sz002620.csv
sz002621 美吉姆
./Stock_Daily/sz002621.csv
sz002622 皓宸医疗
./Stock_Daily/sz002622.csv
sz002623 亚玛顿
./Stock_Daily/sz002623.csv
sz002624 完美世界
./Stock_Daily/sz002624.csv
sz002625 光启技术
./Stock_Daily/sz002625.csv
sz002626 金达威
./Stock_Daily/sz002626.csv
sz002627 三峡旅游
./Stock_Daily/sz002627.csv
sz002628 成都路桥
./Stock_Daily/sz002628.csv
sz002629 仁智股份
./Stock_Daily/sz002629.csv
sz002630 华西能源
./Stock_Daily/sz002630.csv
sz002631 德尔未来
./Stock_Daily/sz002631.csv
sz002632 道明光学
./Stock_Daily/sz002632.csv
sz002633 申科股份
./Stock_Daily/sz002633.csv
sz002634 棒杰股份
./Stock_Daily/sz002634.csv
sz002635 安洁科技
./Stock_Daily/sz002635.csv
sz002636 金安国纪
./Stock_Daily/sz002636.csv
sz002637 赞宇科技
./Stock_Daily/sz002637.csv
sz002638 勤上股份
./Stock_Daily/sz002638.csv
sz002639 雪人股份
./Stock_Daily/sz002639.csv
sz002640 跨境通
./Stock_Daily/sz002640.csv
sz002641 公元股份
./Stock_Daily/sz002641.csv
sz002642 荣联科技

./Stock_Daily/sz002642.csv
sz002643 万润股份
./Stock_Daily/sz002643.csv
sz002644 佛慈制药
./Stock_Daily/sz002644.csv
sz002645 华宏科技
./Stock_Daily/sz002645.csv
sz002646 天佑德酒
./Stock_Daily/sz002646.csv
sz002647 仁东控股
./Stock_Daily/sz002647.csv
sz002648 卫星化学
./Stock_Daily/sz002648.csv
sz002649 博彦科技
./Stock_Daily/sz002649.csv
sz002650 加加食品
./Stock_Daily/sz002650.csv
sz002651 利君股份
./Stock_Daily/sz002651.csv
sz002652 扬子新材
./Stock_Daily/sz002652.csv
sz002653 海思科
./Stock_Daily/sz002653.csv
sz002654 万润科技
./Stock_Daily/sz002654.csv
sz002655 共达电声
./Stock_Daily/sz002655.csv
sz002656 ST摩登
./Stock_Daily/sz002656.csv
sz002657 中科金财
./Stock_Daily/sz002657.csv
sz002658 雪迪龙
./Stock_Daily/sz002658.csv
sz002659 凯文教育
./Stock_Daily/sz002659.csv
sz002660 茂硕电源
./Stock_Daily/sz002660.csv
sz002661 克明食品
./Stock_Daily/sz002661.csv
sz002662 京威股份
./Stock_Daily/sz002662.csv
sz002663 普邦股份
./Stock_Daily/sz002663.csv
sz002664 信质集团
./Stock_Daily/sz002664.csv
sz002665 首航高科
./Stock_Daily/sz002665.csv
sz002666 德联集团
./Stock_Daily/sz002666.csv
sz002667 威领股份
./Stock_Daily/sz002667.csv
sz002668 奥马电器
./Stock_Daily/sz002668.csv
sz002669 康达新材
./Stock_Daily/sz002669.csv
sz002670 国盛金控
./Stock_Daily/sz002670.csv
sz002671 龙泉股份
./Stock_Daily/sz002671.csv
sz002672 东江环保
./Stock_Daily/sz002672.csv
sz002673 西部证券
./Stock_Daily/sz002673.csv
sz002674 兴业科技
./Stock_Daily/sz002674.csv
sz002675 东诚药业
./Stock_Daily/sz002675.csv
sz002676 顺威股份
./Stock_Daily/sz002676.csv
sz002677 浙江美大
./Stock_Daily/sz002677.csv
sz002678 珠江钢琴
./Stock_Daily/sz002678.csv
sz002679 福建金森
./Stock_Daily/sz002679.csv
sz002681 奋达科技
./Stock_Daily/sz002681.csv
sz002682 龙洲股份
./Stock_Daily/sz002682.csv
sz002683 广东宏大
./Stock_Daily/sz002683.csv
sz002685 华东重机
./Stock_Daily/sz002685.csv
sz002686 亿利达
./Stock_Daily/sz002686.csv
sz002687 乔治白
./Stock_Daily/sz002687.csv
sz002688 金河生物
./Stock_Daily/sz002688.csv
sz002689 远大智能
./Stock_Daily/sz002689.csv
sz002690 美亚光电
./Stock_Daily/sz002690.csv
sz002691 冀凯股份
./Stock_Daily/sz002691.csv
sz002692 远程股份
./Stock_Daily/sz002692.csv
sz002693 双成药业
./Stock_Daily/sz002693.csv
sz002694 顾地科技
./Stock_Daily/sz002694.csv
sz002695 煌上煌
./Stock_Daily/sz002695.csv
sz002696 百洋股份
./Stock_Daily/sz002696.csv
sz002697 红旗连锁
./Stock_Daily/sz002697.csv
sz002698 博实股份
./Stock_Daily/sz002698.csv
sz002699 *ST美盛
./Stock_Daily/sz002699.csv
sz002700 ST浩源
./Stock_Daily/sz002700.csv
sz002701 奥瑞金
./Stock_Daily/sz002701.csv
sz002702 海欣食品
./Stock_Daily/sz002702.csv
sz002703 浙江世宝
./Stock_Daily/sz002703.csv
sz002705 新宝股份
./Stock_Daily/sz002705.csv
sz002706 良信股份
./Stock_Daily/sz002706.csv
sz002707 众信旅游
./Stock_Daily/sz002707.csv
sz002708 光洋股份
./Stock_Daily/sz002708.csv
sz002709 天赐材料
./Stock_Daily/sz002709.csv
sz002712 思美传媒
./Stock_Daily/sz002712.csv
sz002713 东易日盛
./Stock_Daily/sz002713.csv
sz002714 牧原股份
./Stock_Daily/sz002714.csv
sz002715 登云股份
./Stock_Daily/sz002715.csv
sz002716 金贵银业
./Stock_Daily/sz002716.csv
sz002717 岭南股份
./Stock_Daily/sz002717.csv
sz002718 友邦吊顶
./Stock_Daily/sz002718.csv
sz002719 麦趣尔
./Stock_Daily/sz002719.csv
sz002721 *ST金一
./Stock_Daily/sz002721.csv
sz002722 物产金轮
./Stock_Daily/sz002722.csv
sz002723 小崧股份
./Stock_Daily/sz002723.csv
sz002724 海洋王
./Stock_Daily/sz002724.csv
sz002725 跃岭股份
./Stock_Daily/sz002725.csv
sz002726 龙大美食
./Stock_Daily/sz002726.csv
sz002727 一心堂
./Stock_Daily/sz002727.csv
sz002728 特一药业
./Stock_Daily/sz002728.csv
sz002729 好利科技
./Stock_Daily/sz002729.csv
sz002730 电光科技
./Stock_Daily/sz002730.csv
sz002731 萃华珠宝
./Stock_Daily/sz002731.csv
sz002732 燕塘乳业
./Stock_Daily/sz002732.csv
sz002733 雄韬股份
./Stock_Daily/sz002733.csv
sz002734 利民股份
./Stock_Daily/sz002734.csv
sz002735 王子新材
./Stock_Daily/sz002735.csv
sz002736 国信证券
./Stock_Daily/sz002736.csv
sz002737 葵花药业
./Stock_Daily/sz002737.csv
sz002738 中矿资源
./Stock_Daily/sz002738.csv
sz002739 万达电影
./Stock_Daily/sz002739.csv
sz002740 *ST爱迪
./Stock_Daily/sz002740.csv
sz002741 光华科技
./Stock_Daily/sz002741.csv
sz002742 ST三圣
./Stock_Daily/sz002742.csv
sz002743 富煌钢构
./Stock_Daily/sz002743.csv
sz002745 木林森
./Stock_Daily/sz002745.csv
sz002746 仙坛股份
./Stock_Daily/sz002746.csv
sz002747 埃斯顿
./Stock_Daily/sz002747.csv
sz002748 世龙实业
./Stock_Daily/sz002748.csv
sz002749 国光股份
./Stock_Daily/sz002749.csv
sz002750 龙津药业
./Stock_Daily/sz002750.csv
sz002752 昇兴股份
./Stock_Daily/sz002752.csv
sz002753 永东股份
./Stock_Daily/sz002753.csv
sz002755 奥赛康
./Stock_Daily/sz002755.csv
sz002756 永兴材料
./Stock_Daily/sz002756.csv
sz002757 南兴股份
./Stock_Daily/sz002757.csv
sz002758 浙农股份
./Stock_Daily/sz002758.csv
sz002759 天际股份
./Stock_Daily/sz002759.csv
sz002760 凤形股份
./Stock_Daily/sz002760.csv
sz002761 浙江建投
./Stock_Daily/sz002761.csv
sz002762 金发拉比
./Stock_Daily/sz002762.csv
sz002763 汇洁股份
./Stock_Daily/sz002763.csv
sz002765 蓝黛科技
./Stock_Daily/sz002765.csv
sz002766 索菱股份
./Stock_Daily/sz002766.csv
sz002767 先锋电子
./Stock_Daily/sz002767.csv
sz002768 国恩股份
./Stock_Daily/sz002768.csv
sz002769 普路通
./Stock_Daily/sz002769.csv
sz002771 真视通
./Stock_Daily/sz002771.csv
sz002772 众兴菌业
./Stock_Daily/sz002772.csv
sz002773 康弘药业
./Stock_Daily/sz002773.csv
sz002774 快意电梯
./Stock_Daily/sz002774.csv
sz002775 文科园林
./Stock_Daily/sz002775.csv
sz002776 *ST柏龙
./Stock_Daily/sz002776.csv
sz002777 久远银海
./Stock_Daily/sz002777.csv
sz002778 中晟高科
./Stock_Daily/sz002778.csv
sz002779 中坚科技
./Stock_Daily/sz002779.csv
sz002780 三夫户外
./Stock_Daily/sz002780.csv
sz002782 可立克
./Stock_Daily/sz002782.csv
sz002783 凯龙股份
./Stock_Daily/sz002783.csv
sz002785 万里石
./Stock_Daily/sz002785.csv
sz002786 银宝山新
./Stock_Daily/sz002786.csv
sz002787 华源控股
./Stock_Daily/sz002787.csv
sz002788 鹭燕医药
./Stock_Daily/sz002788.csv
sz002789 建艺集团
./Stock_Daily/sz002789.csv
sz002790 瑞尔特
./Stock_Daily/sz002790.csv
sz002791 坚朗五金
./Stock_Daily/sz002791.csv
sz002792 通宇通讯
./Stock_Daily/sz002792.csv
sz002793 罗欣药业
./Stock_Daily/sz002793.csv
sz002795 永和智控
./Stock_Daily/sz002795.csv
sz002796 世嘉科技
./Stock_Daily/sz002796.csv
sz002797 第一创业
./Stock_Daily/sz002797.csv
sz002798 帝欧家居
./Stock_Daily/sz002798.csv
sz002799 环球印务
./Stock_Daily/sz002799.csv
sz002800 ST天顺
./Stock_Daily/sz002800.csv
sz002801 微光股份
./Stock_Daily/sz002801.csv
sz002802 洪汇新材
./Stock_Daily/sz002802.csv
sz002803 吉宏股份
./Stock_Daily/sz002803.csv
sz002805 丰元股份
./Stock_Daily/sz002805.csv
sz002806 华锋股份
./Stock_Daily/sz002806.csv
sz002807 江阴银行
./Stock_Daily/sz002807.csv
sz002808 ST恒久
./Stock_Daily/sz002808.csv
sz002809 红墙股份
./Stock_Daily/sz002809.csv
sz002810 山东赫达
./Stock_Daily/sz002810.csv
sz002811 郑中设计
./Stock_Daily/sz002811.csv
sz002812 恩捷股份
./Stock_Daily/sz002812.csv
sz002813 路畅科技
./Stock_Daily/sz002813.csv
sz002815 崇达技术
./Stock_Daily/sz002815.csv
sz002816 *ST和科
./Stock_Daily/sz002816.csv
sz002817 黄山胶囊
./Stock_Daily/sz002817.csv
sz002818 富森美
./Stock_Daily/sz002818.csv
sz002819 东方中科
./Stock_Daily/sz002819.csv
sz002820 桂发祥
./Stock_Daily/sz002820.csv
sz002821 凯莱英
./Stock_Daily/sz002821.csv
sz002822 中装建设
./Stock_Daily/sz002822.csv
sz002823 凯中精密
./Stock_Daily/sz002823.csv
sz002824 和胜股份
./Stock_Daily/sz002824.csv
sz002825 纳尔股份
./Stock_Daily/sz002825.csv
sz002826 易明医药
./Stock_Daily/sz002826.csv
sz002827 高争民爆
./Stock_Daily/sz002827.csv
sz002828 贝肯能源
./Stock_Daily/sz002828.csv
sz002829 星网宇达
./Stock_Daily/sz002829.csv
sz002830 名雕股份
./Stock_Daily/sz002830.csv
sz002831 裕同科技
./Stock_Daily/sz002831.csv
sz002832 比音勒芬
./Stock_Daily/sz002832.csv
sz002833 弘亚数控
./Stock_Daily/sz002833.csv
sz002835 同为股份
./Stock_Daily/sz002835.csv
sz002836 新宏泽
./Stock_Daily/sz002836.csv
sz002837 英维克
./Stock_Daily/sz002837.csv
sz002838 道恩股份
./Stock_Daily/sz002838.csv
sz002839 张家港行
./Stock_Daily/sz002839.csv
sz002840 华统股份
./Stock_Daily/sz002840.csv
sz002841 视源股份
./Stock_Daily/sz002841.csv
sz002842 翔鹭钨业
./Stock_Daily/sz002842.csv
sz002843 泰嘉股份
./Stock_Daily/sz002843.csv
sz002845 同兴达
./Stock_Daily/sz002845.csv
sz002846 英联股份
./Stock_Daily/sz002846.csv
sz002847 盐津铺子
./Stock_Daily/sz002847.csv
sz002848 高斯贝尔
./Stock_Daily/sz002848.csv
sz002849 威星智能
./Stock_Daily/sz002849.csv
sz002850 科达利
./Stock_Daily/sz002850.csv
sz002851 麦格米特
./Stock_Daily/sz002851.csv
sz002852 道道全
./Stock_Daily/sz002852.csv
sz002853 皮阿诺
./Stock_Daily/sz002853.csv
sz002855 捷荣技术
./Stock_Daily/sz002855.csv
sz002856 美芝股份
./Stock_Daily/sz002856.csv
sz002857 三晖电气
./Stock_Daily/sz002857.csv
sz002858 力盛体育
./Stock_Daily/sz002858.csv
sz002859 洁美科技
./Stock_Daily/sz002859.csv
sz002860 星帅尔
./Stock_Daily/sz002860.csv
sz002861 瀛通通讯
./Stock_Daily/sz002861.csv
sz002862 实丰文化

./Stock_Daily/sz002862.csv
sz002863 今飞凯达
./Stock_Daily/sz002863.csv
sz002864 盘龙药业
./Stock_Daily/sz002864.csv
sz002865 钧达股份
./Stock_Daily/sz002865.csv
sz002866 传艺科技
./Stock_Daily/sz002866.csv
sz002867 周大生
./Stock_Daily/sz002867.csv
sz002868 绿康生化
./Stock_Daily/sz002868.csv
sz002869 金溢科技
./Stock_Daily/sz002869.csv
sz002870 香山股份
./Stock_Daily/sz002870.csv
sz002871 伟隆股份
./Stock_Daily/sz002871.csv
sz002872 ST天圣
./Stock_Daily/sz002872.csv
sz002873 新天药业
./Stock_Daily/sz002873.csv
sz002875 安奈儿
./Stock_Daily/sz002875.csv
sz002876 三利谱
./Stock_Daily/sz002876.csv
sz002877 智能自控
./Stock_Daily/sz002877.csv
sz002878 元隆雅图
./Stock_Daily/sz002878.csv
sz002879 长缆科技
./Stock_Daily/sz002879.csv
sz002880 卫光生物
./Stock_Daily/sz002880.csv
sz002881 美格智能
./Stock_Daily/sz002881.csv
sz002882 金龙羽
./Stock_Daily/sz002882.csv
sz002883 中设股份
./Stock_Daily/sz002883.csv
sz002884 凌霄泵业
./Stock_Daily/sz002884.csv
sz002885 京泉华
./Stock_Daily/sz002885.csv
sz002886 沃特股份
./Stock_Daily/sz002886.csv
sz002887 绿茵生态
./Stock_Daily/sz002887.csv
sz002888 惠威科技
./Stock_Daily/sz002888.csv
sz002889 东方嘉盛
./Stock_Daily/sz002889.csv
sz002890 弘宇股份
./Stock_Daily/sz002890.csv
sz002891 中宠股份
./Stock_Daily/sz002891.csv
sz002892 科力尔
./Stock_Daily/sz002892.csv
sz002893 京能热力
./Stock_Daily/sz002893.csv
sz002895 川恒股份
./Stock_Daily/sz002895.csv
sz002896 中大力德
./Stock_Daily/sz002896.csv
sz002897 意华股份
./Stock_Daily/sz002897.csv
sz002898 赛隆药业
./Stock_Daily/sz002898.csv
sz002899 英派斯
./Stock_Daily/sz002899.csv
sz002900 哈三联
./Stock_Daily/sz002900.csv
sz002901 大博医疗
./Stock_Daily/sz002901.csv
sz002902 铭普光磁
./Stock_Daily/sz002902.csv
sz002903 宇环数控
./Stock_Daily/sz002903.csv
sz002905 金逸影视
./Stock_Daily/sz002905.csv
sz002906 华阳集团
./Stock_Daily/sz002906.csv
sz002907 华森制药
./Stock_Daily/sz002907.csv
sz002908 德生科技
./Stock_Daily/sz002908.csv
sz002909 集泰股份
./Stock_Daily/sz002909.csv
sz002910 庄园牧场
./Stock_Daily/sz002910.csv
sz002911 佛燃能源
./Stock_Daily/sz002911.csv
sz002912 中新赛克
./Stock_Daily/sz002912.csv
sz002913 奥士康
./Stock_Daily/sz002913.csv
sz002915 中欣氟材
./Stock_Daily/sz002915.csv
sz002916 深南电路
./Stock_Daily/sz002916.csv
sz002917 金奥博
./Stock_Daily/sz002917.csv
sz002918 蒙娜丽莎
./Stock_Daily/sz002918.csv
sz002919 名臣健康
./Stock_Daily/sz002919.csv
sz002920 德赛西威
./Stock_Daily/sz002920.csv
sz002921 联诚精密
./Stock_Daily/sz002921.csv
sz002922 伊戈尔
./Stock_Daily/sz002922.csv
sz002923 润都股份
./Stock_Daily/sz002923.csv
sz002925 盈趣科技
./Stock_Daily/sz002925.csv
sz002926 华西证券
./Stock_Daily/sz002926.csv
sz002927 泰永长征
./Stock_Daily/sz002927.csv
sz002928 华夏航空
./Stock_Daily/sz002928.csv
sz002929 润建股份
./Stock_Daily/sz002929.csv
sz002930 宏川智慧
./Stock_Daily/sz002930.csv
sz002931 锋龙股份
./Stock_Daily/sz002931.csv
sz002932 明德生物
./Stock_Daily/sz002932.csv
sz002933 新兴装备
./Stock_Daily/sz002933.csv
sz002935 天奥电子
./Stock_Daily/sz002935.csv
sz002936 郑州银行
./Stock_Daily/sz002936.csv
sz002937 兴瑞科技
./Stock_Daily/sz002937.csv
sz002938 鹏鼎控股
./Stock_Daily/sz002938.csv
sz002939 长城证券
./Stock_Daily/sz002939.csv
sz002940 昂利康
./Stock_Daily/sz002940.csv
sz002941 新疆交建
./Stock_Daily/sz002941.csv
sz002942 新农股份
./Stock_Daily/sz002942.csv
sz002943 宇晶股份
./Stock_Daily/sz002943.csv
sz002945 华林证券
./Stock_Daily/sz002945.csv
sz002946 新乳业
./Stock_Daily/sz002946.csv
sz002947 恒铭达
./Stock_Daily/sz002947.csv
sz002948 青岛银行
./Stock_Daily/sz002948.csv
sz002949 华阳国际
./Stock_Daily/sz002949.csv
sz002950 奥美医疗
./Stock_Daily/sz002950.csv
sz002951 ST金时
./Stock_Daily/sz002951.csv
sz002952 亚世光电
./Stock_Daily/sz002952.csv
sz002953 日丰股份
./Stock_Daily/sz002953.csv
sz002955 鸿合科技
./Stock_Daily/sz002955.csv
sz002956 西麦食品
./Stock_Daily/sz002956.csv
sz002957 科瑞技术
./Stock_Daily/sz002957.csv
sz002958 青农商行
./Stock_Daily/sz002958.csv
sz002959 小熊电器
./Stock_Daily/sz002959.csv
sz002960 青鸟消防
./Stock_Daily/sz002960.csv
sz002961 瑞达期货
./Stock_Daily/sz002961.csv
sz002962 五方光电
./Stock_Daily/sz002962.csv
sz002963 豪尔赛
./Stock_Daily/sz002963.csv
sz002965 祥鑫科技
./Stock_Daily/sz002965.csv
sz002966 苏州银行
./Stock_Daily/sz002966.csv
sz002967 广电计量
./Stock_Daily/sz002967.csv
sz002968 新大正
./Stock_Daily/sz002968.csv
sz002969 嘉美包装
./Stock_Daily/sz002969.csv
sz002970 锐明技术
./Stock_Daily/sz002970.csv
sz002971 和远气体
./Stock_Daily/sz002971.csv
sz002972 科安达
./Stock_Daily/sz002972.csv
sz002973 侨银股份
./Stock_Daily/sz002973.csv
sz002975 博杰股份
./Stock_Daily/sz002975.csv
sz002976 瑞玛精密
./Stock_Daily/sz002976.csv
sz002977 天箭科技
./Stock_Daily/sz002977.csv
sz002978 安宁股份
./Stock_Daily/sz002978.csv
sz002979 雷赛智能
./Stock_Daily/sz002979.csv
sz002980 华盛昌
./Stock_Daily/sz002980.csv
sz002981 朝阳科技
./Stock_Daily/sz002981.csv
sz002982 湘佳股份
./Stock_Daily/sz002982.csv
sz002983 芯瑞达
./Stock_Daily/sz002983.csv
sz002984 森麒麟
./Stock_Daily/sz002984.csv
sz002985 北摩高科
./Stock_Daily/sz002985.csv
sz002986 宇新股份
./Stock_Daily/sz002986.csv
sz002987 京北方
./Stock_Daily/sz002987.csv
sz002988 豪美新材
./Stock_Daily/sz002988.csv
sz002989 中天精装
./Stock_Daily/sz002989.csv
sz002990 盛视科技
./Stock_Daily/sz002990.csv
sz002991 甘源食品
./Stock_Daily/sz002991.csv
sz002992 宝明科技
./Stock_Daily/sz002992.csv
sz002993 奥海科技
./Stock_Daily/sz002993.csv
sz002995 天地在线
./Stock_Daily/sz002995.csv
sz002996 顺博合金
./Stock_Daily/sz002996.csv
sz002997 瑞鹄模具
./Stock_Daily/sz002997.csv
sz002998 优彩资源
./Stock_Daily/sz002998.csv
sz002999 天禾股份
./Stock_Daily/sz002999.csv
sz003000 劲仔食品
./Stock_Daily/sz003000.csv
sz003001 中岩大地
./Stock_Daily/sz003001.csv
sz003002 壶化股份
./Stock_Daily/sz003002.csv
sz003003 天元股份
./Stock_Daily/sz003003.csv
sz003004 声迅股份
./Stock_Daily/sz003004.csv
sz003005 竞业达
./Stock_Daily/sz003005.csv
sz003006 百亚股份
./Stock_Daily/sz003006.csv
sz003007 直真科技
./Stock_Daily/sz003007.csv
sz003008 开普检测
./Stock_Daily/sz003008.csv
sz003009 中天火箭
./Stock_Daily/sz003009.csv
sz003010 若羽臣
./Stock_Daily/sz003010.csv
sz003011 海象新材
./Stock_Daily/sz003011.csv
sz003012 东鹏控股
./Stock_Daily/sz003012.csv
sz003013 地铁设计
./Stock_Daily/sz003013.csv
sz003015 日久光电
./Stock_Daily/sz003015.csv
sz003016 欣贺股份
./Stock_Daily/sz003016.csv
sz003017 大洋生物
./Stock_Daily/sz003017.csv
sz003018 金富科技
./Stock_Daily/sz003018.csv
sz003019 宸展光电
./Stock_Daily/sz003019.csv
sz003020 立方制药
./Stock_Daily/sz003020.csv
sz003021 兆威机电
./Stock_Daily/sz003021.csv
sz003022 联泓新科
./Stock_Daily/sz003022.csv
sz003023 彩虹集团
./Stock_Daily/sz003023.csv
sz003025 思进智能
./Stock_Daily/sz003025.csv
sz003026 中晶科技
./Stock_Daily/sz003026.csv
sz003027 同兴环保
./Stock_Daily/sz003027.csv
sz003028 振邦智能
./Stock_Daily/sz003028.csv
sz003029 吉大正元
./Stock_Daily/sz003029.csv
sz003030 祖名股份
./Stock_Daily/sz003030.csv
sz003031 中瓷电子
./Stock_Daily/sz003031.csv
sz003032 传智教育
./Stock_Daily/sz003032.csv
sz003033 征和工业
./Stock_Daily/sz003033.csv
sz003035 南网能源
./Stock_Daily/sz003035.csv
sz003036 泰坦股份
./Stock_Daily/sz003036.csv
sz003037 三和管桩
./Stock_Daily/sz003037.csv
sz003038 鑫铂股份
./Stock_Daily/sz003038.csv
sz003039 顺控发展
./Stock_Daily/sz003039.csv
sz003040 楚天龙
./Stock_Daily/sz003040.csv
sz003041 真爱美家
./Stock_Daily/sz003041.csv
sz003042 中农联合
./Stock_Daily/sz003042.csv
sz003043 华亚智能
./Stock_Daily/sz003043.csv
sz003816 中国广核
./Stock_Daily/sz003816.csv
sz300001 特锐德
./Stock_Daily/sz300001.csv
sz300002 神州泰岳
./Stock_Daily/sz300002.csv
sz300003 乐普医疗
./Stock_Daily/sz300003.csv
sz300004 南风股份
./Stock_Daily/sz300004.csv
sz300005 探路者
./Stock_Daily/sz300005.csv
sz300006 莱美药业
./Stock_Daily/sz300006.csv
sz300007 汉威科技
./Stock_Daily/sz300007.csv
sz300008 天海防务
./Stock_Daily/sz300008.csv
sz300009 安科生物
./Stock_Daily/sz300009.csv
sz300010 *ST豆神
./Stock_Daily/sz300010.csv
sz300011 鼎汉技术
./Stock_Daily/sz300011.csv
sz300012 华测检测
./Stock_Daily/sz300012.csv
sz300013 新宁物流
./Stock_Daily/sz300013.csv
sz300014 亿纬锂能
./Stock_Daily/sz300014.csv
sz300015 爱尔眼科
./Stock_Daily/sz300015.csv
sz300016 北陆药业
./Stock_Daily/sz300016.csv
sz300017 网宿科技
./Stock_Daily/sz300017.csv
sz300018 中元股份
./Stock_Daily/sz300018.csv
sz300019 硅宝科技
./Stock_Daily/sz300019.csv
sz300020 银江技术
./Stock_Daily/sz300020.csv
sz300021 大禹节水
./Stock_Daily/sz300021.csv
sz300022 吉峰科技
./Stock_Daily/sz300022.csv
sz300024 机器人
./Stock_Daily/sz300024.csv
sz300025 华星创业
./Stock_Daily/sz300025.csv
sz300026 红日药业
./Stock_Daily/sz300026.csv
sz300027 华谊兄弟
./Stock_Daily/sz300027.csv
sz300029 ST天龙
./Stock_Daily/sz300029.csv
sz300030 阳普医疗
./Stock_Daily/sz300030.csv
sz300031 宝通科技
./Stock_Daily/sz300031.csv
sz300032 金龙机电
./Stock_Daily/sz300032.csv
sz300033 同花顺
./Stock_Daily/sz300033.csv
sz300034 钢研高纳
./Stock_Daily/sz300034.csv
sz300035 中科电气

./Stock_Daily/sz300035.csv
sz300036 超图软件
./Stock_Daily/sz300036.csv
sz300037 新宙邦
./Stock_Daily/sz300037.csv
sz300039 上海凯宝
./Stock_Daily/sz300039.csv
sz300040 九洲集团
./Stock_Daily/sz300040.csv
sz300041 回天新材
./Stock_Daily/sz300041.csv
sz300042 朗科科技
./Stock_Daily/sz300042.csv
sz300043 星辉娱乐
./Stock_Daily/sz300043.csv
sz300044 赛为智能
./Stock_Daily/sz300044.csv
sz300045 华力创通
./Stock_Daily/sz300045.csv
sz300046 台基股份
./Stock_Daily/sz300046.csv
sz300047 天源迪科
./Stock_Daily/sz300047.csv
sz300048 合康新能
./Stock_Daily/sz300048.csv
sz300049 福瑞股份
./Stock_Daily/sz300049.csv
sz300050 世纪鼎利
./Stock_Daily/sz300050.csv
sz300051 琏升科技
./Stock_Daily/sz300051.csv
sz300052 中青宝
./Stock_Daily/sz300052.csv
sz300053 航宇微
./Stock_Daily/sz300053.csv
sz300054 鼎龙股份
./Stock_Daily/sz300054.csv
sz300055 万邦达
./Stock_Daily/sz300055.csv
sz300056 中创环保
./Stock_Daily/sz300056.csv
sz300057 万顺新材
./Stock_Daily/sz300057.csv
sz300058 蓝色光标
./Stock_Daily/sz300058.csv
sz300059 东方财富
./Stock_Daily/sz300059.csv
sz300061 旗天科技
./Stock_Daily/sz300061.csv
sz300062 中能电气
./Stock_Daily/sz300062.csv
sz300063 天龙集团
./Stock_Daily/sz300063.csv
sz300065 海兰信
./Stock_Daily/sz300065.csv
sz300066 三川智慧
./Stock_Daily/sz300066.csv
sz300067 安诺其
./Stock_Daily/sz300067.csv
sz300068 南都电源
./Stock_Daily/sz300068.csv
sz300069 金利华电
./Stock_Daily/sz300069.csv
sz300070 碧水源
./Stock_Daily/sz300070.csv
sz300071 福石控股
./Stock_Daily/sz300071.csv
sz300072 海新能科
./Stock_Daily/sz300072.csv
sz300073 当升科技
./Stock_Daily/sz300073.csv
sz300074 华平股份
./Stock_Daily/sz300074.csv
sz300075 数字政通
./Stock_Daily/sz300075.csv
sz300076 GQY视讯
./Stock_Daily/sz300076.csv
sz300077 国民技术
./Stock_Daily/sz300077.csv
sz300078 思创医惠
./Stock_Daily/sz300078.csv
sz300079 数码视讯
./Stock_Daily/sz300079.csv
sz300080 易成新能
./Stock_Daily/sz300080.csv
sz300081 恒信东方
./Stock_Daily/sz300081.csv
sz300082 奥克股份
./Stock_Daily/sz300082.csv
sz300083 创世纪
./Stock_Daily/sz300083.csv
sz300084 海默科技
./Stock_Daily/sz300084.csv
sz300085 银之杰
./Stock_Daily/sz300085.csv
sz300086 康芝药业
./Stock_Daily/sz300086.csv
sz300087 荃银高科
./Stock_Daily/sz300087.csv
sz300088 长信科技
./Stock_Daily/sz300088.csv
sz300091 金通灵
./Stock_Daily/sz300091.csv
sz300092 科新机电
./Stock_Daily/sz300092.csv
sz300093 金刚光伏
./Stock_Daily/sz300093.csv
sz300094 国联水产
./Stock_Daily/sz300094.csv
sz300095 华伍股份
./Stock_Daily/sz300095.csv
sz300096 易联众
./Stock_Daily/sz300096.csv
sz300097 智云股份
./Stock_Daily/sz300097.csv
sz300098 高新兴
./Stock_Daily/sz300098.csv
sz300099 尤洛卡
./Stock_Daily/sz300099.csv
sz300100 双林股份
./Stock_Daily/sz300100.csv
sz300101 振芯科技
./Stock_Daily/sz300101.csv
sz300102 乾照光电
./Stock_Daily/sz300102.csv
sz300103 达刚控股
./Stock_Daily/sz300103.csv
sz300105 龙源技术
./Stock_Daily/sz300105.csv
sz300106 西部牧业
./Stock_Daily/sz300106.csv
sz300107 建新股份
./Stock_Daily/sz300107.csv
sz300108 ST吉药
./Stock_Daily/sz300108.csv
sz300109 新开源
./Stock_Daily/sz300109.csv
sz300110 华仁药业
./Stock_Daily/sz300110.csv
sz300111 向日葵
./Stock_Daily/sz300111.csv
sz300112 万讯自控
./Stock_Daily/sz300112.csv
sz300113 顺网科技
./Stock_Daily/sz300113.csv
sz300114 中航电测
./Stock_Daily/sz300114.csv
sz300115 长盈精密
./Stock_Daily/sz300115.csv
sz300116 保力新
./Stock_Daily/sz300116.csv
sz300117 嘉寓股份
./Stock_Daily/sz300117.csv
sz300118 东方日升
./Stock_Daily/sz300118.csv
sz300119 瑞普生物
./Stock_Daily/sz300119.csv
sz300120 经纬辉开
./Stock_Daily/sz300120.csv
sz300121 阳谷华泰
./Stock_Daily/sz300121.csv
sz300122 智飞生物
./Stock_Daily/sz300122.csv
sz300123 亚光科技
./Stock_Daily/sz300123.csv
sz300124 汇川技术
./Stock_Daily/sz300124.csv
sz300125 聆达股份
./Stock_Daily/sz300125.csv
sz300126 锐奇股份
./Stock_Daily/sz300126.csv
sz300127 银河磁体
./Stock_Daily/sz300127.csv
sz300128 锦富技术
./Stock_Daily/sz300128.csv
sz300129 泰胜风能
./Stock_Daily/sz300129.csv
sz300130 新国都
./Stock_Daily/sz300130.csv
sz300131 英唐智控
./Stock_Daily/sz300131.csv
sz300132 青松股份
./Stock_Daily/sz300132.csv
sz300133 华策影视
./Stock_Daily/sz300133.csv
sz300134 大富科技
./Stock_Daily/sz300134.csv
sz300135 宝利国际
./Stock_Daily/sz300135.csv
sz300136 信维通信
./Stock_Daily/sz300136.csv
sz300137 先河环保
./Stock_Daily/sz300137.csv
sz300138 晨光生物
./Stock_Daily/sz300138.csv
sz300139 晓程科技
./Stock_Daily/sz300139.csv
sz300140 节能环境
./Stock_Daily/sz300140.csv
sz300141 和顺电气
./Stock_Daily/sz300141.csv
sz300142 沃森生物
./Stock_Daily/sz300142.csv
sz300143 盈康生命
./Stock_Daily/sz300143.csv
sz300144 宋城演艺
./Stock_Daily/sz300144.csv
sz300145 中金环境
./Stock_Daily/sz300145.csv
sz300146 汤臣倍健
./Stock_Daily/sz300146.csv
sz300147 香雪制药
./Stock_Daily/sz300147.csv
sz300148 天舟文化
./Stock_Daily/sz300148.csv
sz300149 睿智医药
./Stock_Daily/sz300149.csv
sz300150 世纪瑞尔
./Stock_Daily/sz300150.csv
sz300151 昌红科技
./Stock_Daily/sz300151.csv
sz300152 新动力
./Stock_Daily/sz300152.csv
sz300153 科泰电源
./Stock_Daily/sz300153.csv
sz300154 瑞凌股份
./Stock_Daily/sz300154.csv
sz300155 安居宝
./Stock_Daily/sz300155.csv
sz300157 新锦动力
./Stock_Daily/sz300157.csv
sz300158 振东制药
./Stock_Daily/sz300158.csv
sz300159 新研股份
./Stock_Daily/sz300159.csv
sz300160 秀强股份
./Stock_Daily/sz300160.csv
sz300161 华中数控
./Stock_Daily/sz300161.csv
sz300162 雷曼光电
./Stock_Daily/sz300162.csv
sz300163 先锋新材
./Stock_Daily/sz300163.csv
sz300164 通源石油
./Stock_Daily/sz300164.csv
sz300165 天瑞仪器
./Stock_Daily/sz300165.csv
sz300166 东方国信
./Stock_Daily/sz300166.csv
sz300167 ST迪威迅
./Stock_Daily/sz300167.csv
sz300168 万达信息
./Stock_Daily/sz300168.csv
sz300169 天晟新材
./Stock_Daily/sz300169.csv
sz300170 汉得信息
./Stock_Daily/sz300170.csv
sz300171 东富龙
./Stock_Daily/sz300171.csv
sz300172 中电环保
./Stock_Daily/sz300172.csv
sz300173 福能东方
./Stock_Daily/sz300173.csv
sz300174 元力股份
./Stock_Daily/sz300174.csv
sz300175 朗源股份
./Stock_Daily/sz300175.csv
sz300176 派生科技
./Stock_Daily/sz300176.csv
sz300177 中海达
./Stock_Daily/sz300177.csv
sz300179 四方达
./Stock_Daily/sz300179.csv
sz300180 华峰超纤
./Stock_Daily/sz300180.csv
sz300181 佐力药业
./Stock_Daily/sz300181.csv
sz300182 捷成股份
./Stock_Daily/sz300182.csv
sz300183 东软载波
./Stock_Daily/sz300183.csv
sz300184 力源信息
./Stock_Daily/sz300184.csv
sz300185 通裕重工
./Stock_Daily/sz300185.csv
sz300187 永清环保
./Stock_Daily/sz300187.csv
sz300188 美亚柏科
./Stock_Daily/sz300188.csv
sz300189 神农科技
./Stock_Daily/sz300189.csv
sz300190 维尔利
./Stock_Daily/sz300190.csv
sz300191 潜能恒信
./Stock_Daily/sz300191.csv
sz300192 科德教育
./Stock_Daily/sz300192.csv
sz300193 佳士科技
./Stock_Daily/sz300193.csv
sz300194 福安药业
./Stock_Daily/sz300194.csv
sz300195 长荣股份
./Stock_Daily/sz300195.csv
sz300196 长海股份
./Stock_Daily/sz300196.csv
sz300197 节能铁汉
./Stock_Daily/sz300197.csv
sz300198 纳川股份
./Stock_Daily/sz300198.csv
sz300199 翰宇药业
./Stock_Daily/sz300199.csv
sz300200 高盟新材
./Stock_Daily/sz300200.csv
sz300201 海伦哲
./Stock_Daily/sz300201.csv
sz300203 聚光科技
./Stock_Daily/sz300203.csv
sz300204 舒泰神
./Stock_Daily/sz300204.csv
sz300205 天喻信息
./Stock_Daily/sz300205.csv
sz300206 理邦仪器
./Stock_Daily/sz300206.csv
sz300207 欣旺达
./Stock_Daily/sz300207.csv
sz300208 青岛中程
./Stock_Daily/sz300208.csv
sz300209 ST有棵树
./Stock_Daily/sz300209.csv
sz300210 森远股份
./Stock_Daily/sz300210.csv
sz300211 亿通科技
./Stock_Daily/sz300211.csv
sz300212 易华录
./Stock_Daily/sz300212.csv
sz300213 佳讯飞鸿
./Stock_Daily/sz300213.csv
sz300214 日科化学
./Stock_Daily/sz300214.csv
sz300215 电科院
./Stock_Daily/sz300215.csv
sz300217 东方电热
./Stock_Daily/sz300217.csv
sz300218 安利股份
./Stock_Daily/sz300218.csv
sz300219 鸿利智汇
./Stock_Daily/sz300219.csv
sz300220 ST金运
./Stock_Daily/sz300220.csv
sz300221 银禧科技
./Stock_Daily/sz300221.csv
sz300222 科大智能
./Stock_Daily/sz300222.csv
sz300223 北京君正
./Stock_Daily/sz300223.csv
sz300224 正海磁材
./Stock_Daily/sz300224.csv
sz300225 金力泰
./Stock_Daily/sz300225.csv
sz300226 上海钢联
./Stock_Daily/sz300226.csv
sz300227 光韵达
./Stock_Daily/sz300227.csv
sz300228 富瑞特装
./Stock_Daily/sz300228.csv
sz300229 拓尔思
./Stock_Daily/sz300229.csv
sz300230 永利股份
./Stock_Daily/sz300230.csv
sz300231 银信科技
./Stock_Daily/sz300231.csv
sz300232 洲明科技
./Stock_Daily/sz300232.csv
sz300233 金城医药
./Stock_Daily/sz300233.csv
sz300234 开尔新材
./Stock_Daily/sz300234.csv
sz300235 方直科技
./Stock_Daily/sz300235.csv
sz300236 上海新阳
./Stock_Daily/sz300236.csv
sz300237 美晨生态
./Stock_Daily/sz300237.csv
sz300238 冠昊生物
./Stock_Daily/sz300238.csv
sz300239 东宝生物
./Stock_Daily/sz300239.csv
sz300240 飞力达
./Stock_Daily/sz300240.csv
sz300241 瑞丰光电
./Stock_Daily/sz300241.csv
sz300242 佳云科技
./Stock_Daily/sz300242.csv
sz300243 瑞丰高材
./Stock_Daily/sz300243.csv
sz300244 迪安诊断
./Stock_Daily/sz300244.csv
sz300245 天玑科技
./Stock_Daily/sz300245.csv
sz300246 宝莱特
./Stock_Daily/sz300246.csv
sz300247 融捷健康

./Stock_Daily/sz300247.csv
sz300248 新开普
./Stock_Daily/sz300248.csv
sz300249 依米康
./Stock_Daily/sz300249.csv
sz300250 初灵信息
./Stock_Daily/sz300250.csv
sz300251 光线传媒
./Stock_Daily/sz300251.csv
sz300252 金信诺
./Stock_Daily/sz300252.csv
sz300253 卫宁健康
./Stock_Daily/sz300253.csv
sz300254 仟源医药
./Stock_Daily/sz300254.csv
sz300255 常山药业
./Stock_Daily/sz300255.csv
sz300256 星星科技
./Stock_Daily/sz300256.csv
sz300257 开山股份
./Stock_Daily/sz300257.csv
sz300258 精锻科技
./Stock_Daily/sz300258.csv
sz300259 新天科技
./Stock_Daily/sz300259.csv
sz300260 新莱应材
./Stock_Daily/sz300260.csv
sz300261 雅本化学
./Stock_Daily/sz300261.csv
sz300262 巴安水务
./Stock_Daily/sz300262.csv
sz300263 隆华科技
./Stock_Daily/sz300263.csv
sz300264 佳创视讯
./Stock_Daily/sz300264.csv
sz300265 通光线缆
./Stock_Daily/sz300265.csv
sz300266 兴源环境
./Stock_Daily/sz300266.csv
sz300267 尔康制药
./Stock_Daily/sz300267.csv
sz300268 *ST佳沃
./Stock_Daily/sz300268.csv
sz300269 联建光电
./Stock_Daily/sz300269.csv
sz300270 中威电子
./Stock_Daily/sz300270.csv
sz300271 华宇软件
./Stock_Daily/sz300271.csv
sz300272 开能健康
./Stock_Daily/sz300272.csv
sz300274 阳光电源
./Stock_Daily/sz300274.csv
sz300275 梅安森
./Stock_Daily/sz300275.csv
sz300276 三丰智能
./Stock_Daily/sz300276.csv
sz300277 海联讯
./Stock_Daily/sz300277.csv
sz300278 华昌达
./Stock_Daily/sz300278.csv
sz300279 和晶科技
./Stock_Daily/sz300279.csv
sz300280 紫天科技
./Stock_Daily/sz300280.csv
sz300281 金明精机
./Stock_Daily/sz300281.csv
sz300282 *ST三盛
./Stock_Daily/sz300282.csv
sz300283 温州宏丰
./Stock_Daily/sz300283.csv
sz300284 苏交科
./Stock_Daily/sz300284.csv
sz300285 国瓷材料
./Stock_Daily/sz300285.csv
sz300286 安科瑞
./Stock_Daily/sz300286.csv
sz300287 飞利信
./Stock_Daily/sz300287.csv
sz300288 朗玛信息
./Stock_Daily/sz300288.csv
sz300289 利德曼
./Stock_Daily/sz300289.csv
sz300290 荣科科技
./Stock_Daily/sz300290.csv
sz300291 百纳千成
./Stock_Daily/sz300291.csv
sz300292 吴通控股
./Stock_Daily/sz300292.csv
sz300293 蓝英装备
./Stock_Daily/sz300293.csv
sz300294 博雅生物
./Stock_Daily/sz300294.csv
sz300295 三六五网
./Stock_Daily/sz300295.csv
sz300296 利亚德
./Stock_Daily/sz300296.csv
sz300298 三诺生物
./Stock_Daily/sz300298.csv
sz300299 富春股份
./Stock_Daily/sz300299.csv
sz300300 海峡创新
./Stock_Daily/sz300300.csv
sz300301 *ST长方
./Stock_Daily/sz300301.csv
sz300302 同有科技
./Stock_Daily/sz300302.csv
sz300303 聚飞光电
./Stock_Daily/sz300303.csv
sz300304 云意电气
./Stock_Daily/sz300304.csv
sz300305 裕兴股份
./Stock_Daily/sz300305.csv
sz300306 远方信息
./Stock_Daily/sz300306.csv
sz300307 慈星股份
./Stock_Daily/sz300307.csv
sz300308 中际旭创
./Stock_Daily/sz300308.csv
sz300310 宜通世纪
./Stock_Daily/sz300310.csv
sz300311 任子行
./Stock_Daily/sz300311.csv
sz300313 *ST天山
./Stock_Daily/sz300313.csv
sz300314 戴维医疗
./Stock_Daily/sz300314.csv
sz300315 掌趣科技
./Stock_Daily/sz300315.csv
sz300316 晶盛机电
./Stock_Daily/sz300316.csv
sz300317 珈伟新能
./Stock_Daily/sz300317.csv
sz300318 博晖创新
./Stock_Daily/sz300318.csv
sz300319 麦捷科技
./Stock_Daily/sz300319.csv
sz300320 海达股份
./Stock_Daily/sz300320.csv
sz300321 同大股份
./Stock_Daily/sz300321.csv
sz300322 硕贝德
./Stock_Daily/sz300322.csv
sz300323 华灿光电
./Stock_Daily/sz300323.csv
sz300324 旋极信息
./Stock_Daily/sz300324.csv
sz300326 凯利泰
./Stock_Daily/sz300326.csv
sz300327 中颖电子
./Stock_Daily/sz300327.csv
sz300328 宜安科技
./Stock_Daily/sz300328.csv
sz300329 海伦钢琴
./Stock_Daily/sz300329.csv
sz300331 苏大维格
./Stock_Daily/sz300331.csv
sz300332 天壕能源
./Stock_Daily/sz300332.csv
sz300333 兆日科技
./Stock_Daily/sz300333.csv
sz300334 津膜科技
./Stock_Daily/sz300334.csv
sz300335 迪森股份
./Stock_Daily/sz300335.csv
sz300337 银邦股份
./Stock_Daily/sz300337.csv
sz300338 开元教育
./Stock_Daily/sz300338.csv
sz300339 润和软件
./Stock_Daily/sz300339.csv
sz300340 科恒股份
./Stock_Daily/sz300340.csv
sz300341 麦克奥迪
./Stock_Daily/sz300341.csv
sz300342 天银机电
./Stock_Daily/sz300342.csv
sz300343 联创股份
./Stock_Daily/sz300343.csv
sz300344 立方数科
./Stock_Daily/sz300344.csv
sz300345 华民股份
./Stock_Daily/sz300345.csv
sz300346 南大光电
./Stock_Daily/sz300346.csv
sz300347 泰格医药
./Stock_Daily/sz300347.csv
sz300348 长亮科技
./Stock_Daily/sz300348.csv
sz300349 金卡智能
./Stock_Daily/sz300349.csv
sz300350 华鹏飞
./Stock_Daily/sz300350.csv
sz300351 永贵电器
./Stock_Daily/sz300351.csv
sz300352 北信源
./Stock_Daily/sz300352.csv
sz300353 东土科技
./Stock_Daily/sz300353.csv
sz300354 东华测试
./Stock_Daily/sz300354.csv
sz300355 蒙草生态
./Stock_Daily/sz300355.csv
sz300357 我武生物
./Stock_Daily/sz300357.csv
sz300358 楚天科技
./Stock_Daily/sz300358.csv
sz300359 全通教育
./Stock_Daily/sz300359.csv
sz300360 炬华科技
./Stock_Daily/sz300360.csv
sz300363 博腾股份
./Stock_Daily/sz300363.csv
sz300364 中文在线
./Stock_Daily/sz300364.csv
sz300365 恒华科技
./Stock_Daily/sz300365.csv
sz300366 创意信息
./Stock_Daily/sz300366.csv
sz300368 汇金股份
./Stock_Daily/sz300368.csv
sz300369 绿盟科技
./Stock_Daily/sz300369.csv
sz300370 安控科技
./Stock_Daily/sz300370.csv
sz300371 汇中股份
./Stock_Daily/sz300371.csv
sz300373 扬杰科技
./Stock_Daily/sz300373.csv
sz300374 中铁装配
./Stock_Daily/sz300374.csv
sz300375 鹏翎股份
./Stock_Daily/sz300375.csv
sz300376 易事特
./Stock_Daily/sz300376.csv
sz300377 赢时胜
./Stock_Daily/sz300377.csv
sz300378 鼎捷软件
./Stock_Daily/sz300378.csv
sz300379 东方通
./Stock_Daily/sz300379.csv
sz300380 安硕信息
./Stock_Daily/sz300380.csv
sz300381 溢多利
./Stock_Daily/sz300381.csv
sz300382 斯莱克
./Stock_Daily/sz300382.csv
sz300383 光环新网
./Stock_Daily/sz300383.csv
sz300384 三联虹普
./Stock_Daily/sz300384.csv
sz300385 雪浪环境
./Stock_Daily/sz300385.csv
sz300386 飞天诚信
./Stock_Daily/sz300386.csv
sz300387 富邦股份
./Stock_Daily/sz300387.csv
sz300388 节能国祯
./Stock_Daily/sz300388.csv
sz300389 艾比森
./Stock_Daily/sz300389.csv
sz300390 天华新能
./Stock_Daily/sz300390.csv
sz300391 长药控股
./Stock_Daily/sz300391.csv
sz300393 中来股份
./Stock_Daily/sz300393.csv
sz300394 天孚通信
./Stock_Daily/sz300394.csv
sz300395 菲利华
./Stock_Daily/sz300395.csv
sz300396 迪瑞医疗
./Stock_Daily/sz300396.csv
sz300397 天和防务
./Stock_Daily/sz300397.csv
sz300398 飞凯材料
./Stock_Daily/sz300398.csv
sz300399 天利科技
./Stock_Daily/sz300399.csv
sz300400 劲拓股份
./Stock_Daily/sz300400.csv
sz300401 花园生物
./Stock_Daily/sz300401.csv
sz300402 宝色股份
./Stock_Daily/sz300402.csv
sz300403 汉宇集团
./Stock_Daily/sz300403.csv
sz300404 博济医药
./Stock_Daily/sz300404.csv
sz300405 科隆股份
./Stock_Daily/sz300405.csv
sz300406 九强生物
./Stock_Daily/sz300406.csv
sz300407 凯发电气
./Stock_Daily/sz300407.csv
sz300408 三环集团
./Stock_Daily/sz300408.csv
sz300409 道氏技术
./Stock_Daily/sz300409.csv
sz300410 正业科技
./Stock_Daily/sz300410.csv
sz300411 金盾股份
./Stock_Daily/sz300411.csv
sz300412 迦南科技
./Stock_Daily/sz300412.csv
sz300413 芒果超媒
./Stock_Daily/sz300413.csv
sz300414 中光防雷
./Stock_Daily/sz300414.csv
sz300415 伊之密
./Stock_Daily/sz300415.csv
sz300416 苏试试验
./Stock_Daily/sz300416.csv
sz300417 南华仪器
./Stock_Daily/sz300417.csv
sz300418 昆仑万维
./Stock_Daily/sz300418.csv
sz300419 浩丰科技
./Stock_Daily/sz300419.csv
sz300420 五洋停车
./Stock_Daily/sz300420.csv
sz300421 力星股份
./Stock_Daily/sz300421.csv
sz300422 博世科
./Stock_Daily/sz300422.csv
sz300423 昇辉科技
./Stock_Daily/sz300423.csv
sz300424 航新科技
./Stock_Daily/sz300424.csv
sz300425 中建环能
./Stock_Daily/sz300425.csv
sz300426 唐德影视
./Stock_Daily/sz300426.csv
sz300427 *ST红相
./Stock_Daily/sz300427.csv
sz300428 立中集团
./Stock_Daily/sz300428.csv
sz300429 强力新材
./Stock_Daily/sz300429.csv
sz300430 诚益通
./Stock_Daily/sz300430.csv
sz300432 富临精工
./Stock_Daily/sz300432.csv
sz300433 蓝思科技
./Stock_Daily/sz300433.csv
sz300434 金石亚药
./Stock_Daily/sz300434.csv
sz300435 中泰股份
./Stock_Daily/sz300435.csv
sz300436 广生堂
./Stock_Daily/sz300436.csv
sz300437 清水源
./Stock_Daily/sz300437.csv
sz300438 鹏辉能源
./Stock_Daily/sz300438.csv
sz300439 美康生物
./Stock_Daily/sz300439.csv
sz300440 运达科技
./Stock_Daily/sz300440.csv
sz300441 鲍斯股份
./Stock_Daily/sz300441.csv
sz300442 润泽科技
./Stock_Daily/sz300442.csv
sz300443 金雷股份
./Stock_Daily/sz300443.csv
sz300444 双杰电气
./Stock_Daily/sz300444.csv
sz300445 康斯特
./Stock_Daily/sz300445.csv
sz300446 航天智造
./Stock_Daily/sz300446.csv
sz300447 全信股份
./Stock_Daily/sz300447.csv
sz300448 浩云科技
./Stock_Daily/sz300448.csv
sz300449 汉邦高科
./Stock_Daily/sz300449.csv
sz300450 先导智能
./Stock_Daily/sz300450.csv
sz300451 创业慧康
./Stock_Daily/sz300451.csv
sz300452 山河药辅
./Stock_Daily/sz300452.csv
sz300453 三鑫医疗
./Stock_Daily/sz300453.csv
sz300454 深信服
./Stock_Daily/sz300454.csv
sz300455 航天智装
./Stock_Daily/sz300455.csv
sz300456 赛微电子
./Stock_Daily/sz300456.csv
sz300457 赢合科技
./Stock_Daily/sz300457.csv
sz300458 全志科技
./Stock_Daily/sz300458.csv
sz300459 汤姆猫
./Stock_Daily/sz300459.csv
sz300460 惠伦晶体
./Stock_Daily/sz300460.csv
sz300461 田中精机
./Stock_Daily/sz300461.csv
sz300462 华铭智能

./Stock_Daily/sz300462.csv
sz300463 迈克生物
./Stock_Daily/sz300463.csv
sz300464 星徽股份
./Stock_Daily/sz300464.csv
sz300465 高伟达
./Stock_Daily/sz300465.csv
sz300466 赛摩智能
./Stock_Daily/sz300466.csv
sz300467 迅游科技
./Stock_Daily/sz300467.csv
sz300468 四方精创
./Stock_Daily/sz300468.csv
sz300469 信息发展
./Stock_Daily/sz300469.csv
sz300470 中密控股
./Stock_Daily/sz300470.csv
sz300471 厚普股份
./Stock_Daily/sz300471.csv
sz300472 新元科技
./Stock_Daily/sz300472.csv
sz300473 德尔股份
./Stock_Daily/sz300473.csv
sz300474 景嘉微
./Stock_Daily/sz300474.csv
sz300475 香农芯创
./Stock_Daily/sz300475.csv
sz300476 胜宏科技
./Stock_Daily/sz300476.csv
sz300477 合纵科技
./Stock_Daily/sz300477.csv
sz300478 杭州高新
./Stock_Daily/sz300478.csv
sz300479 神思电子
./Stock_Daily/sz300479.csv
sz300480 光力科技
./Stock_Daily/sz300480.csv
sz300481 濮阳惠成
./Stock_Daily/sz300481.csv
sz300482 万孚生物
./Stock_Daily/sz300482.csv
sz300483 首华燃气
./Stock_Daily/sz300483.csv
sz300484 蓝海华腾
./Stock_Daily/sz300484.csv
sz300485 赛升药业
./Stock_Daily/sz300485.csv
sz300486 东杰智能
./Stock_Daily/sz300486.csv
sz300487 蓝晓科技
./Stock_Daily/sz300487.csv
sz300488 恒锋工具
./Stock_Daily/sz300488.csv
sz300489 光智科技
./Stock_Daily/sz300489.csv
sz300490 华自科技
./Stock_Daily/sz300490.csv
sz300491 通合科技
./Stock_Daily/sz300491.csv
sz300492 华图山鼎
./Stock_Daily/sz300492.csv
sz300493 润欣科技
./Stock_Daily/sz300493.csv
sz300494 盛天网络
./Stock_Daily/sz300494.csv
sz300495 *ST美尚
./Stock_Daily/sz300495.csv
sz300496 中科创达
./Stock_Daily/sz300496.csv
sz300497 富祥药业
./Stock_Daily/sz300497.csv
sz300498 温氏股份
./Stock_Daily/sz300498.csv
sz300499 高澜股份
./Stock_Daily/sz300499.csv
sz300500 启迪设计
./Stock_Daily/sz300500.csv
sz300501 海顺新材
./Stock_Daily/sz300501.csv
sz300502 新易盛
./Stock_Daily/sz300502.csv
sz300503 昊志机电
./Stock_Daily/sz300503.csv
sz300504 天邑股份
./Stock_Daily/sz300504.csv
sz300505 川金诺
./Stock_Daily/sz300505.csv
sz300506 名家汇
./Stock_Daily/sz300506.csv
sz300507 苏奥传感
./Stock_Daily/sz300507.csv
sz300508 维宏股份
./Stock_Daily/sz300508.csv
sz300509 新美星
./Stock_Daily/sz300509.csv
sz300510 金冠股份
./Stock_Daily/sz300510.csv
sz300511 雪榕生物
./Stock_Daily/sz300511.csv
sz300512 中亚股份
./Stock_Daily/sz300512.csv
sz300513 恒实科技
./Stock_Daily/sz300513.csv
sz300514 友讯达
./Stock_Daily/sz300514.csv
sz300515 三德科技
./Stock_Daily/sz300515.csv
sz300516 久之洋
./Stock_Daily/sz300516.csv
sz300517 海波重科
./Stock_Daily/sz300517.csv
sz300518 新迅达
./Stock_Daily/sz300518.csv
sz300519 新光药业
./Stock_Daily/sz300519.csv
sz300520 科大国创
./Stock_Daily/sz300520.csv
sz300521 爱司凯
./Stock_Daily/sz300521.csv
sz300522 世名科技
./Stock_Daily/sz300522.csv
sz300523 辰安科技
./Stock_Daily/sz300523.csv
sz300525 博思软件
./Stock_Daily/sz300525.csv
sz300527 中船应急
./Stock_Daily/sz300527.csv
sz300528 幸福蓝海
./Stock_Daily/sz300528.csv
sz300529 健帆生物
./Stock_Daily/sz300529.csv
sz300530 领湃科技
./Stock_Daily/sz300530.csv
sz300531 优博讯
./Stock_Daily/sz300531.csv
sz300532 今天国际
./Stock_Daily/sz300532.csv
sz300533 冰川网络
./Stock_Daily/sz300533.csv
sz300534 陇神戎发
./Stock_Daily/sz300534.csv
sz300535 达威股份
./Stock_Daily/sz300535.csv
sz300536 农尚环境
./Stock_Daily/sz300536.csv
sz300537 广信材料
./Stock_Daily/sz300537.csv
sz300538 同益股份
./Stock_Daily/sz300538.csv
sz300539 横河精密
./Stock_Daily/sz300539.csv
sz300540 蜀道装备
./Stock_Daily/sz300540.csv
sz300541 先进数通
./Stock_Daily/sz300541.csv
sz300542 新晨科技
./Stock_Daily/sz300542.csv
sz300543 朗科智能
./Stock_Daily/sz300543.csv
sz300545 联得装备
./Stock_Daily/sz300545.csv
sz300546 雄帝科技
./Stock_Daily/sz300546.csv
sz300547 川环科技
./Stock_Daily/sz300547.csv
sz300548 博创科技
./Stock_Daily/sz300548.csv
sz300549 优德精密
./Stock_Daily/sz300549.csv
sz300550 和仁科技
./Stock_Daily/sz300550.csv
sz300551 古鳌科技
./Stock_Daily/sz300551.csv
sz300552 万集科技
./Stock_Daily/sz300552.csv
sz300553 集智股份
./Stock_Daily/sz300553.csv
sz300554 三超新材
./Stock_Daily/sz300554.csv
sz300555 ST路通
./Stock_Daily/sz300555.csv
sz300556 丝路视觉
./Stock_Daily/sz300556.csv
sz300557 理工光科
./Stock_Daily/sz300557.csv
sz300558 贝达药业
./Stock_Daily/sz300558.csv
sz300559 佳发教育
./Stock_Daily/sz300559.csv
sz300560 中富通
./Stock_Daily/sz300560.csv
sz300561 汇金科技
./Stock_Daily/sz300561.csv
sz300562 乐心医疗
./Stock_Daily/sz300562.csv
sz300563 神宇股份
./Stock_Daily/sz300563.csv
sz300564 筑博设计
./Stock_Daily/sz300564.csv
sz300565 科信技术
./Stock_Daily/sz300565.csv
sz300566 激智科技
./Stock_Daily/sz300566.csv
sz300567 精测电子
./Stock_Daily/sz300567.csv
sz300568 星源材质
./Stock_Daily/sz300568.csv
sz300569 天能重工
./Stock_Daily/sz300569.csv
sz300570 太辰光
./Stock_Daily/sz300570.csv
sz300571 平治信息
./Stock_Daily/sz300571.csv
sz300572 安车检测
./Stock_Daily/sz300572.csv
sz300573 兴齐眼药
./Stock_Daily/sz300573.csv
sz300575 中旗股份
./Stock_Daily/sz300575.csv
sz300576 容大感光
./Stock_Daily/sz300576.csv
sz300577 开润股份
./Stock_Daily/sz300577.csv
sz300578 会畅通讯
./Stock_Daily/sz300578.csv
sz300579 数字认证
./Stock_Daily/sz300579.csv
sz300580 贝斯特
./Stock_Daily/sz300580.csv
sz300581 晨曦航空
./Stock_Daily/sz300581.csv
sz300582 英飞特
./Stock_Daily/sz300582.csv
sz300583 赛托生物
./Stock_Daily/sz300583.csv
sz300584 海辰药业
./Stock_Daily/sz300584.csv
sz300585 奥联电子
./Stock_Daily/sz300585.csv
sz300586 美联新材
./Stock_Daily/sz300586.csv
sz300587 天铁股份
./Stock_Daily/sz300587.csv
sz300588 熙菱信息
./Stock_Daily/sz300588.csv
sz300589 江龙船艇
./Stock_Daily/sz300589.csv
sz300590 移为通信
./Stock_Daily/sz300590.csv
sz300591 万里马
./Stock_Daily/sz300591.csv
sz300592 华凯易佰
./Stock_Daily/sz300592.csv
sz300593 新雷能
./Stock_Daily/sz300593.csv
sz300594 朗进科技
./Stock_Daily/sz300594.csv
sz300595 欧普康视
./Stock_Daily/sz300595.csv
sz300596 利安隆
./Stock_Daily/sz300596.csv
sz300597 吉大通信
./Stock_Daily/sz300597.csv
sz300598 诚迈科技
./Stock_Daily/sz300598.csv
sz300599 雄塑科技
./Stock_Daily/sz300599.csv
sz300600 国瑞科技
./Stock_Daily/sz300600.csv
sz300601 康泰生物
./Stock_Daily/sz300601.csv
sz300602 飞荣达
./Stock_Daily/sz300602.csv
sz300603 立昂技术
./Stock_Daily/sz300603.csv
sz300604 长川科技
./Stock_Daily/sz300604.csv
sz300605 恒锋信息
./Stock_Daily/sz300605.csv
sz300606 金太阳
./Stock_Daily/sz300606.csv
sz300607 拓斯达
./Stock_Daily/sz300607.csv
sz300608 思特奇
./Stock_Daily/sz300608.csv
sz300609 汇纳科技
./Stock_Daily/sz300609.csv
sz300610 晨化股份
./Stock_Daily/sz300610.csv
sz300611 美力科技
./Stock_Daily/sz300611.csv
sz300612 宣亚国际
./Stock_Daily/sz300612.csv
sz300613 富瀚微
./Stock_Daily/sz300613.csv
sz300614 百川畅银
./Stock_Daily/sz300614.csv
sz300615 欣天科技
./Stock_Daily/sz300615.csv
sz300616 尚品宅配
./Stock_Daily/sz300616.csv
sz300617 安靠智电
./Stock_Daily/sz300617.csv
sz300618 寒锐钴业
./Stock_Daily/sz300618.csv
sz300619 金银河
./Stock_Daily/sz300619.csv
sz300620 光库科技
./Stock_Daily/sz300620.csv
sz300621 维业股份
./Stock_Daily/sz300621.csv
sz300622 博士眼镜
./Stock_Daily/sz300622.csv
sz300623 捷捷微电
./Stock_Daily/sz300623.csv
sz300624 万兴科技
./Stock_Daily/sz300624.csv
sz300625 三雄极光
./Stock_Daily/sz300625.csv
sz300626 华瑞股份
./Stock_Daily/sz300626.csv
sz300627 华测导航
./Stock_Daily/sz300627.csv
sz300628 亿联网络
./Stock_Daily/sz300628.csv
sz300629 新劲刚
./Stock_Daily/sz300629.csv
sz300630 普利制药
./Stock_Daily/sz300630.csv
sz300631 久吾高科
./Stock_Daily/sz300631.csv
sz300632 光莆股份
./Stock_Daily/sz300632.csv
sz300633 开立医疗
./Stock_Daily/sz300633.csv
sz300634 彩讯股份
./Stock_Daily/sz300634.csv
sz300635 中达安
./Stock_Daily/sz300635.csv
sz300636 同和药业
./Stock_Daily/sz300636.csv
sz300637 扬帆新材
./Stock_Daily/sz300637.csv
sz300638 广和通
./Stock_Daily/sz300638.csv
sz300639 凯普生物
./Stock_Daily/sz300639.csv
sz300640 德艺文创
./Stock_Daily/sz300640.csv
sz300641 正丹股份
./Stock_Daily/sz300641.csv
sz300642 透景生命
./Stock_Daily/sz300642.csv
sz300643 万通智控
./Stock_Daily/sz300643.csv
sz300644 南京聚隆
./Stock_Daily/sz300644.csv
sz300645 正元智慧
./Stock_Daily/sz300645.csv
sz300647 超频三
./Stock_Daily/sz300647.csv
sz300648 星云股份
./Stock_Daily/sz300648.csv
sz300649 杭州园林
./Stock_Daily/sz300649.csv
sz300650 太龙股份
./Stock_Daily/sz300650.csv
sz300651 金陵体育
./Stock_Daily/sz300651.csv
sz300652 雷迪克
./Stock_Daily/sz300652.csv
sz300653 正海生物
./Stock_Daily/sz300653.csv
sz300654 世纪天鸿
./Stock_Daily/sz300654.csv
sz300655 晶瑞电材
./Stock_Daily/sz300655.csv
sz300656 民德电子
./Stock_Daily/sz300656.csv
sz300657 弘信电子
./Stock_Daily/sz300657.csv
sz300658 延江股份
./Stock_Daily/sz300658.csv
sz300659 中孚信息
./Stock_Daily/sz300659.csv
sz300660 江苏雷利
./Stock_Daily/sz300660.csv
sz300661 圣邦股份
./Stock_Daily/sz300661.csv
sz300662 科锐国际
./Stock_Daily/sz300662.csv
sz300663 科蓝软件
./Stock_Daily/sz300663.csv
sz300664 鹏鹞环保
./Stock_Daily/sz300664.csv
sz300665 飞鹿股份
./Stock_Daily/sz300665.csv
sz300666 江丰电子
./Stock_Daily/sz300666.csv
sz300667 必创科技
./Stock_Daily/sz300667.csv
sz300668 杰恩设计

./Stock_Daily/sz300668.csv
sz300669 沪宁股份
./Stock_Daily/sz300669.csv
sz300670 大烨智能
./Stock_Daily/sz300670.csv
sz300671 富满微
./Stock_Daily/sz300671.csv
sz300672 国科微
./Stock_Daily/sz300672.csv
sz300673 佩蒂股份
./Stock_Daily/sz300673.csv
sz300674 宇信科技
./Stock_Daily/sz300674.csv
sz300675 建科院
./Stock_Daily/sz300675.csv
sz300676 华大基因
./Stock_Daily/sz300676.csv
sz300677 英科医疗
./Stock_Daily/sz300677.csv
sz300678 中科信息
./Stock_Daily/sz300678.csv
sz300679 电连技术
./Stock_Daily/sz300679.csv
sz300680 隆盛科技
./Stock_Daily/sz300680.csv
sz300681 英搏尔
./Stock_Daily/sz300681.csv
sz300682 朗新科技
./Stock_Daily/sz300682.csv
sz300683 海特生物
./Stock_Daily/sz300683.csv
sz300684 中石科技
./Stock_Daily/sz300684.csv
sz300685 艾德生物
./Stock_Daily/sz300685.csv
sz300686 智动力
./Stock_Daily/sz300686.csv
sz300687 赛意信息
./Stock_Daily/sz300687.csv
sz300688 创业黑马
./Stock_Daily/sz300688.csv
sz300689 澄天伟业
./Stock_Daily/sz300689.csv
sz300690 双一科技
./Stock_Daily/sz300690.csv
sz300691 联合光电
./Stock_Daily/sz300691.csv
sz300692 中环环保
./Stock_Daily/sz300692.csv
sz300693 盛弘股份
./Stock_Daily/sz300693.csv
sz300694 蠡湖股份
./Stock_Daily/sz300694.csv
sz300695 兆丰股份
./Stock_Daily/sz300695.csv
sz300696 爱乐达
./Stock_Daily/sz300696.csv
sz300697 电工合金
./Stock_Daily/sz300697.csv
sz300698 万马科技
./Stock_Daily/sz300698.csv
sz300699 光威复材
./Stock_Daily/sz300699.csv
sz300700 岱勒新材
./Stock_Daily/sz300700.csv
sz300701 森霸传感
./Stock_Daily/sz300701.csv
sz300702 天宇股份
./Stock_Daily/sz300702.csv
sz300703 创源股份
./Stock_Daily/sz300703.csv
sz300705 九典制药
./Stock_Daily/sz300705.csv
sz300706 阿石创
./Stock_Daily/sz300706.csv
sz300707 威唐工业
./Stock_Daily/sz300707.csv
sz300708 聚灿光电
./Stock_Daily/sz300708.csv
sz300709 精研科技
./Stock_Daily/sz300709.csv
sz300710 万隆光电
./Stock_Daily/sz300710.csv
sz300711 广哈通信
./Stock_Daily/sz300711.csv
sz300712 永福股份
./Stock_Daily/sz300712.csv
sz300713 英可瑞
./Stock_Daily/sz300713.csv
sz300715 凯伦股份
./Stock_Daily/sz300715.csv
sz300716 泉为科技
./Stock_Daily/sz300716.csv
sz300717 华信新材
./Stock_Daily/sz300717.csv
sz300718 长盛轴承
./Stock_Daily/sz300718.csv
sz300719 安达维尔
./Stock_Daily/sz300719.csv
sz300720 海川智能
./Stock_Daily/sz300720.csv
sz300721 怡达股份
./Stock_Daily/sz300721.csv
sz300722 新余国科
./Stock_Daily/sz300722.csv
sz300723 一品红
./Stock_Daily/sz300723.csv
sz300724 捷佳伟创
./Stock_Daily/sz300724.csv
sz300725 药石科技
./Stock_Daily/sz300725.csv
sz300726 宏达电子
./Stock_Daily/sz300726.csv
sz300727 润禾材料
./Stock_Daily/sz300727.csv
sz300729 乐歌股份
./Stock_Daily/sz300729.csv
sz300730 科创信息
./Stock_Daily/sz300730.csv
sz300731 科创新源
./Stock_Daily/sz300731.csv
sz300732 设研院
./Stock_Daily/sz300732.csv
sz300733 西菱动力
./Stock_Daily/sz300733.csv
sz300735 光弘科技
./Stock_Daily/sz300735.csv
sz300736 百邦科技
./Stock_Daily/sz300736.csv
sz300737 科顺股份
./Stock_Daily/sz300737.csv
sz300738 奥飞数据
./Stock_Daily/sz300738.csv
sz300739 明阳电路
./Stock_Daily/sz300739.csv
sz300740 水羊股份
./Stock_Daily/sz300740.csv
sz300741 华宝股份
./Stock_Daily/sz300741.csv
sz300742 *ST越博
./Stock_Daily/sz300742.csv
sz300743 天地数码
./Stock_Daily/sz300743.csv
sz300745 欣锐科技
./Stock_Daily/sz300745.csv
sz300746 汉嘉设计
./Stock_Daily/sz300746.csv
sz300747 锐科激光
./Stock_Daily/sz300747.csv
sz300748 金力永磁
./Stock_Daily/sz300748.csv
sz300749 顶固集创
./Stock_Daily/sz300749.csv
sz300750 宁德时代
./Stock_Daily/sz300750.csv
sz300751 迈为股份
./Stock_Daily/sz300751.csv
sz300752 隆利科技
./Stock_Daily/sz300752.csv
sz300753 爱朋医疗
./Stock_Daily/sz300753.csv
sz300755 华致酒行
./Stock_Daily/sz300755.csv
sz300756 金马游乐
./Stock_Daily/sz300756.csv
sz300757 罗博特科
./Stock_Daily/sz300757.csv
sz300758 七彩化学
./Stock_Daily/sz300758.csv
sz300759 康龙化成
./Stock_Daily/sz300759.csv
sz300760 迈瑞医疗
./Stock_Daily/sz300760.csv
sz300761 立华股份
./Stock_Daily/sz300761.csv
sz300762 上海瀚讯
./Stock_Daily/sz300762.csv
sz300763 锦浪科技
./Stock_Daily/sz300763.csv
sz300765 新诺威
./Stock_Daily/sz300765.csv
sz300766 每日互动
./Stock_Daily/sz300766.csv
sz300767 震安科技
./Stock_Daily/sz300767.csv
sz300768 迪普科技
./Stock_Daily/sz300768.csv
sz300769 德方纳米
./Stock_Daily/sz300769.csv
sz300770 新媒股份
./Stock_Daily/sz300770.csv
sz300771 智莱科技
./Stock_Daily/sz300771.csv
sz300772 运达股份
./Stock_Daily/sz300772.csv
sz300773 拉卡拉
./Stock_Daily/sz300773.csv
sz300774 倍杰特
./Stock_Daily/sz300774.csv
sz300775 三角防务
./Stock_Daily/sz300775.csv
sz300776 帝尔激光
./Stock_Daily/sz300776.csv
sz300777 中简科技
./Stock_Daily/sz300777.csv
sz300778 新城市
./Stock_Daily/sz300778.csv
sz300779 惠城环保
./Stock_Daily/sz300779.csv
sz300780 德恩精工
./Stock_Daily/sz300780.csv
sz300781 因赛集团
./Stock_Daily/sz300781.csv
sz300782 卓胜微
./Stock_Daily/sz300782.csv
sz300783 三只松鼠
./Stock_Daily/sz300783.csv
sz300785 值得买
./Stock_Daily/sz300785.csv
sz300786 国林科技
./Stock_Daily/sz300786.csv
sz300787 海能实业
./Stock_Daily/sz300787.csv
sz300788 中信出版
./Stock_Daily/sz300788.csv
sz300789 唐源电气
./Stock_Daily/sz300789.csv
sz300790 宇瞳光学
./Stock_Daily/sz300790.csv
sz300791 仙乐健康
./Stock_Daily/sz300791.csv
sz300792 壹网壹创
./Stock_Daily/sz300792.csv
sz300793 佳禾智能
./Stock_Daily/sz300793.csv
sz300795 米奥会展
./Stock_Daily/sz300795.csv
sz300796 贝斯美
./Stock_Daily/sz300796.csv
sz300797 钢研纳克
./Stock_Daily/sz300797.csv
sz300798 锦鸡股份
./Stock_Daily/sz300798.csv
sz300799 *ST左江
./Stock_Daily/sz300799.csv
sz300800 力合科技
./Stock_Daily/sz300800.csv
sz300801 泰和科技
./Stock_Daily/sz300801.csv
sz300802 矩子科技
./Stock_Daily/sz300802.csv
sz300803 指南针
./Stock_Daily/sz300803.csv
sz300804 广康生化
./Stock_Daily/sz300804.csv
sz300805 电声股份
./Stock_Daily/sz300805.csv
sz300806 斯迪克
./Stock_Daily/sz300806.csv
sz300807 天迈科技
./Stock_Daily/sz300807.csv
sz300808 久量股份
./Stock_Daily/sz300808.csv
sz300809 华辰装备
./Stock_Daily/sz300809.csv
sz300810 中科海讯
./Stock_Daily/sz300810.csv
sz300811 铂科新材
./Stock_Daily/sz300811.csv
sz300812 易天股份
./Stock_Daily/sz300812.csv
sz300813 泰林生物
./Stock_Daily/sz300813.csv
sz300814 中富电路
./Stock_Daily/sz300814.csv
sz300815 玉禾田
./Stock_Daily/sz300815.csv
sz300816 艾可蓝
./Stock_Daily/sz300816.csv
sz300817 双飞集团
./Stock_Daily/sz300817.csv
sz300818 耐普矿机
./Stock_Daily/sz300818.csv
sz300819 聚杰微纤
./Stock_Daily/sz300819.csv
sz300820 英杰电气
./Stock_Daily/sz300820.csv
sz300821 东岳硅材
./Stock_Daily/sz300821.csv
sz300822 贝仕达克
./Stock_Daily/sz300822.csv
sz300823 建科机械
./Stock_Daily/sz300823.csv
sz300824 北鼎股份
./Stock_Daily/sz300824.csv
sz300825 阿尔特
./Stock_Daily/sz300825.csv
sz300826 测绘股份
./Stock_Daily/sz300826.csv
sz300827 上能电气
./Stock_Daily/sz300827.csv
sz300828 锐新科技
./Stock_Daily/sz300828.csv
sz300829 金丹科技
./Stock_Daily/sz300829.csv
sz300830 金现代
./Stock_Daily/sz300830.csv
sz300831 派瑞股份
./Stock_Daily/sz300831.csv
sz300832 新产业
./Stock_Daily/sz300832.csv
sz300833 浩洋股份
./Stock_Daily/sz300833.csv
sz300834 星辉环材
./Stock_Daily/sz300834.csv
sz300835 龙磁科技
./Stock_Daily/sz300835.csv
sz300836 佰奥智能
./Stock_Daily/sz300836.csv
sz300837 浙矿股份
./Stock_Daily/sz300837.csv
sz300838 浙江力诺
./Stock_Daily/sz300838.csv
sz300839 博汇股份
./Stock_Daily/sz300839.csv
sz300840 酷特智能
./Stock_Daily/sz300840.csv
sz300841 康华生物
./Stock_Daily/sz300841.csv
sz300842 帝科股份
./Stock_Daily/sz300842.csv
sz300843 胜蓝股份
./Stock_Daily/sz300843.csv
sz300844 山水比德
./Stock_Daily/sz300844.csv
sz300845 捷安高科
./Stock_Daily/sz300845.csv
sz300846 首都在线
./Stock_Daily/sz300846.csv
sz300847 中船汉光
./Stock_Daily/sz300847.csv
sz300848 美瑞新材
./Stock_Daily/sz300848.csv
sz300849 锦盛新材
./Stock_Daily/sz300849.csv
sz300850 新强联
./Stock_Daily/sz300850.csv
sz300851 交大思诺
./Stock_Daily/sz300851.csv
sz300852 四会富仕
./Stock_Daily/sz300852.csv
sz300853 申昊科技
./Stock_Daily/sz300853.csv
sz300854 中兰环保
./Stock_Daily/sz300854.csv
sz300855 图南股份
./Stock_Daily/sz300855.csv
sz300856 科思股份
./Stock_Daily/sz300856.csv
sz300857 协创数据
./Stock_Daily/sz300857.csv
sz300858 科拓生物
./Stock_Daily/sz300858.csv
sz300859 *ST西域
./Stock_Daily/sz300859.csv
sz300860 锋尚文化
./Stock_Daily/sz300860.csv
sz300861 美畅股份
./Stock_Daily/sz300861.csv
sz300862 蓝盾光电
./Stock_Daily/sz300862.csv
sz300863 卡倍亿
./Stock_Daily/sz300863.csv
sz300864 南大环境
./Stock_Daily/sz300864.csv
sz300865 大宏立
./Stock_Daily/sz300865.csv
sz300866 安克创新
./Stock_Daily/sz300866.csv
sz300867 圣元环保
./Stock_Daily/sz300867.csv
sz300868 杰美特
./Stock_Daily/sz300868.csv
sz300869 康泰医学
./Stock_Daily/sz300869.csv
sz300870 欧陆通
./Stock_Daily/sz300870.csv
sz300871 回盛生物
./Stock_Daily/sz300871.csv
sz300872 天阳科技
./Stock_Daily/sz300872.csv
sz300873 海晨股份
./Stock_Daily/sz300873.csv
sz300875 捷强装备
./Stock_Daily/sz300875.csv
sz300876 蒙泰高新
./Stock_Daily/sz300876.csv
sz300877 金春股份
./Stock_Daily/sz300877.csv
sz300878 维康药业
./Stock_Daily/sz300878.csv
sz300879 大叶股份

./Stock_Daily/sz300879.csv
sz300880 迦南智能
./Stock_Daily/sz300880.csv
sz300881 盛德鑫泰
./Stock_Daily/sz300881.csv
sz300882 万胜智能
./Stock_Daily/sz300882.csv
sz300883 龙利得
./Stock_Daily/sz300883.csv
sz300884 狄耐克
./Stock_Daily/sz300884.csv
sz300885 海昌新材
./Stock_Daily/sz300885.csv
sz300886 华业香料
./Stock_Daily/sz300886.csv
sz300887 谱尼测试
./Stock_Daily/sz300887.csv
sz300888 稳健医疗
./Stock_Daily/sz300888.csv
sz300889 爱克股份
./Stock_Daily/sz300889.csv
sz300890 翔丰华
./Stock_Daily/sz300890.csv
sz300891 惠云钛业
./Stock_Daily/sz300891.csv
sz300892 品渥食品
./Stock_Daily/sz300892.csv
sz300893 松原股份
./Stock_Daily/sz300893.csv
sz300894 火星人
./Stock_Daily/sz300894.csv
sz300895 铜牛信息
./Stock_Daily/sz300895.csv
sz300896 爱美客
./Stock_Daily/sz300896.csv
sz300897 山科智能
./Stock_Daily/sz300897.csv
sz300898 熊猫乳品
./Stock_Daily/sz300898.csv
sz300899 上海凯鑫
./Stock_Daily/sz300899.csv
sz300900 广联航空
./Stock_Daily/sz300900.csv
sz300901 中胤时尚
./Stock_Daily/sz300901.csv
sz300902 国安达
./Stock_Daily/sz300902.csv
sz300903 科翔股份
./Stock_Daily/sz300903.csv
sz300904 威力传动
./Stock_Daily/sz300904.csv
sz300905 宝丽迪
./Stock_Daily/sz300905.csv
sz300906 日月明
./Stock_Daily/sz300906.csv
sz300907 康平科技
./Stock_Daily/sz300907.csv
sz300908 仲景食品
./Stock_Daily/sz300908.csv
sz300909 汇创达
./Stock_Daily/sz300909.csv
sz300910 瑞丰新材
./Stock_Daily/sz300910.csv
sz300911 亿田智能
./Stock_Daily/sz300911.csv
sz300912 凯龙高科
./Stock_Daily/sz300912.csv
sz300913 兆龙互连
./Stock_Daily/sz300913.csv
sz300915 海融科技
./Stock_Daily/sz300915.csv
sz300916 朗特智能
./Stock_Daily/sz300916.csv
sz300917 特发服务
./Stock_Daily/sz300917.csv
sz300918 南山智尚
./Stock_Daily/sz300918.csv
sz300919 中伟股份
./Stock_Daily/sz300919.csv
sz300920 润阳科技
./Stock_Daily/sz300920.csv
sz300921 南凌科技
./Stock_Daily/sz300921.csv
sz300922 天秦装备
./Stock_Daily/sz300922.csv
sz300923 研奥股份
./Stock_Daily/sz300923.csv
sz300925 法本信息
./Stock_Daily/sz300925.csv
sz300926 博俊科技
./Stock_Daily/sz300926.csv
sz300927 江天化学
./Stock_Daily/sz300927.csv
sz300928 华安鑫创
./Stock_Daily/sz300928.csv
sz300929 华骐环保
./Stock_Daily/sz300929.csv
sz300930 屹通新材
./Stock_Daily/sz300930.csv
sz300931 通用电梯
./Stock_Daily/sz300931.csv
sz300932 三友联众
./Stock_Daily/sz300932.csv
sz300933 中辰股份
./Stock_Daily/sz300933.csv
sz300935 盈建科
./Stock_Daily/sz300935.csv
sz300936 中英科技
./Stock_Daily/sz300936.csv
sz300937 药易购
./Stock_Daily/sz300937.csv
sz300938 信测标准
./Stock_Daily/sz300938.csv
sz300939 秋田微
./Stock_Daily/sz300939.csv
sz300940 南极光
./Stock_Daily/sz300940.csv
sz300941 创识科技
./Stock_Daily/sz300941.csv
sz300942 易瑞生物
./Stock_Daily/sz300942.csv
sz300943 春晖智控
./Stock_Daily/sz300943.csv
sz300945 曼卡龙
./Stock_Daily/sz300945.csv
sz300946 恒而达
./Stock_Daily/sz300946.csv
sz300947 德必集团
./Stock_Daily/sz300947.csv
sz300948 冠中生态
./Stock_Daily/sz300948.csv
sz300949 奥雅股份
./Stock_Daily/sz300949.csv
sz300950 德固特
./Stock_Daily/sz300950.csv
sz300951 博硕科技
./Stock_Daily/sz300951.csv
sz300952 恒辉安防
./Stock_Daily/sz300952.csv
sz300953 震裕科技
./Stock_Daily/sz300953.csv
sz300955 嘉亨家化
./Stock_Daily/sz300955.csv
sz300956 英力股份
./Stock_Daily/sz300956.csv
sz300957 贝泰妮
./Stock_Daily/sz300957.csv
sz300958 建工修复
./Stock_Daily/sz300958.csv
sz300959 线上线下
./Stock_Daily/sz300959.csv
sz300960 通业科技
./Stock_Daily/sz300960.csv
sz300961 深水海纳
./Stock_Daily/sz300961.csv
sz300962 中金辐照
./Stock_Daily/sz300962.csv
sz300963 中洲特材
./Stock_Daily/sz300963.csv
sz300964 本川智能
./Stock_Daily/sz300964.csv
sz300965 恒宇信通
./Stock_Daily/sz300965.csv
sz300966 共同药业
./Stock_Daily/sz300966.csv
sz300967 晓鸣股份
./Stock_Daily/sz300967.csv
sz300968 格林精密
./Stock_Daily/sz300968.csv
sz300969 恒帅股份
./Stock_Daily/sz300969.csv
sz300970 华绿生物
./Stock_Daily/sz300970.csv
sz300971 博亚精工
./Stock_Daily/sz300971.csv
sz300972 万辰集团
./Stock_Daily/sz300972.csv
sz300973 立高食品
./Stock_Daily/sz300973.csv
sz300975 商络电子
./Stock_Daily/sz300975.csv
sz300976 达瑞电子
./Stock_Daily/sz300976.csv
sz300977 深圳瑞捷
./Stock_Daily/sz300977.csv
sz300978 东箭科技
./Stock_Daily/sz300978.csv
sz300979 华利集团
./Stock_Daily/sz300979.csv
sz300980 祥源新材
./Stock_Daily/sz300980.csv
sz300981 中红医疗
./Stock_Daily/sz300981.csv
sz300982 苏文电能
./Stock_Daily/sz300982.csv
sz300983 尤安设计
./Stock_Daily/sz300983.csv
sz300984 金沃股份
./Stock_Daily/sz300984.csv
sz300985 致远新能
./Stock_Daily/sz300985.csv
sz300986 志特新材
./Stock_Daily/sz300986.csv
sz300987 川网传媒
./Stock_Daily/sz300987.csv
sz300988 津荣天宇
./Stock_Daily/sz300988.csv
sz300989 蕾奥规划
./Stock_Daily/sz300989.csv
sz300990 同飞股份
./Stock_Daily/sz300990.csv
sz300991 创益通
./Stock_Daily/sz300991.csv
sz300992 泰福泵业
./Stock_Daily/sz300992.csv
sz300993 玉马遮阳
./Stock_Daily/sz300993.csv
sz300994 久祺股份
./Stock_Daily/sz300994.csv
sz300995 奇德新材
./Stock_Daily/sz300995.csv
sz300996 普联软件
./Stock_Daily/sz300996.csv
sz300997 欢乐家
./Stock_Daily/sz300997.csv
sz300998 宁波方正
./Stock_Daily/sz300998.csv
sz300999 金龙鱼
./Stock_Daily/sz300999.csv
sz301000 肇民科技
./Stock_Daily/sz301000.csv
sz301001 凯淳股份
./Stock_Daily/sz301001.csv
sz301002 崧盛股份
./Stock_Daily/sz301002.csv
sz301003 江苏博云
./Stock_Daily/sz301003.csv
sz301004 嘉益股份
./Stock_Daily/sz301004.csv
sz301005 超捷股份
./Stock_Daily/sz301005.csv
sz301006 迈拓股份
./Stock_Daily/sz301006.csv
sz301007 德迈仕
./Stock_Daily/sz301007.csv
sz301008 宏昌科技
./Stock_Daily/sz301008.csv
sz301009 可靠股份
./Stock_Daily/sz301009.csv
sz301010 晶雪节能
./Stock_Daily/sz301010.csv
sz301011 华立科技
./Stock_Daily/sz301011.csv
sz301012 扬电科技
./Stock_Daily/sz301012.csv
sz301013 利和兴
./Stock_Daily/sz301013.csv
sz301015 百洋医药
./Stock_Daily/sz301015.csv
sz301016 雷尔伟
./Stock_Daily/sz301016.csv
sz301017 漱玉平民
./Stock_Daily/sz301017.csv
sz301018 申菱环境
./Stock_Daily/sz301018.csv
sz301019 宁波色母
./Stock_Daily/sz301019.csv
sz301020 密封科技
./Stock_Daily/sz301020.csv
sz301021 英诺激光
./Stock_Daily/sz301021.csv
sz301022 海泰科
./Stock_Daily/sz301022.csv
sz301023 江南奕帆
./Stock_Daily/sz301023.csv
sz301024 霍普股份
./Stock_Daily/sz301024.csv
sz301025 读客文化
./Stock_Daily/sz301025.csv
sz301026 浩通科技
./Stock_Daily/sz301026.csv
sz301027 华蓝集团
./Stock_Daily/sz301027.csv
sz301028 东亚机械
./Stock_Daily/sz301028.csv
sz301029 怡合达
./Stock_Daily/sz301029.csv
sz301030 仕净科技
./Stock_Daily/sz301030.csv
sz301031 中熔电气
./Stock_Daily/sz301031.csv
sz301032 新柴股份
./Stock_Daily/sz301032.csv
sz301033 迈普医学
./Stock_Daily/sz301033.csv
sz301035 润丰股份
./Stock_Daily/sz301035.csv
sz301036 双乐股份
./Stock_Daily/sz301036.csv
sz301037 保立佳
./Stock_Daily/sz301037.csv
sz301038 深水规院
./Stock_Daily/sz301038.csv
sz301039 中集车辆
./Stock_Daily/sz301039.csv
sz301040 中环海陆
./Stock_Daily/sz301040.csv
sz301041 金百泽
./Stock_Daily/sz301041.csv
sz301042 安联锐视
./Stock_Daily/sz301042.csv
sz301043 绿岛风
./Stock_Daily/sz301043.csv
sz301045 天禄科技
./Stock_Daily/sz301045.csv
sz301046 能辉科技
./Stock_Daily/sz301046.csv
sz301047 义翘神州
./Stock_Daily/sz301047.csv
sz301048 金鹰重工
./Stock_Daily/sz301048.csv
sz301049 超越科技
./Stock_Daily/sz301049.csv
sz301050 雷电微力
./Stock_Daily/sz301050.csv
sz301051 信濠光电
./Stock_Daily/sz301051.csv
sz301052 果麦文化
./Stock_Daily/sz301052.csv
sz301053 远信工业
./Stock_Daily/sz301053.csv
sz301055 张小泉
./Stock_Daily/sz301055.csv
sz301056 森赫股份
./Stock_Daily/sz301056.csv
sz301057 汇隆新材
./Stock_Daily/sz301057.csv
sz301058 中粮科工
./Stock_Daily/sz301058.csv
sz301059 金三江
./Stock_Daily/sz301059.csv
sz301060 兰卫医学
./Stock_Daily/sz301060.csv
sz301061 匠心家居
./Stock_Daily/sz301061.csv
sz301062 上海艾录
./Stock_Daily/sz301062.csv
sz301063 海锅股份
./Stock_Daily/sz301063.csv
sz301065 本立科技
./Stock_Daily/sz301065.csv
sz301066 万事利
./Stock_Daily/sz301066.csv
sz301067 显盈科技
./Stock_Daily/sz301067.csv
sz301068 大地海洋
./Stock_Daily/sz301068.csv
sz301069 凯盛新材
./Stock_Daily/sz301069.csv
sz301070 开勒股份
./Stock_Daily/sz301070.csv
sz301071 力量钻石
./Stock_Daily/sz301071.csv
sz301072 中捷精工
./Stock_Daily/sz301072.csv
sz301073 君亭酒店
./Stock_Daily/sz301073.csv
sz301075 多瑞医药
./Stock_Daily/sz301075.csv
sz301076 新瀚新材
./Stock_Daily/sz301076.csv
sz301077 星华新材
./Stock_Daily/sz301077.csv
sz301078 孩子王
./Stock_Daily/sz301078.csv
sz301079 邵阳液压
./Stock_Daily/sz301079.csv
sz301080 百普赛斯
./Stock_Daily/sz301080.csv
sz301081 严牌股份
./Stock_Daily/sz301081.csv
sz301082 久盛电气
./Stock_Daily/sz301082.csv
sz301083 百胜智能
./Stock_Daily/sz301083.csv
sz301085 亚康股份
./Stock_Daily/sz301085.csv
sz301086 鸿富瀚
./Stock_Daily/sz301086.csv
sz301087 可孚医疗
./Stock_Daily/sz301087.csv
sz301088 戎美股份
./Stock_Daily/sz301088.csv
sz301089 拓新药业
./Stock_Daily/sz301089.csv
sz301090 华润材料
./Stock_Daily/sz301090.csv
sz301091 深城交
./Stock_Daily/sz301091.csv
sz301092 争光股份
./Stock_Daily/sz301092.csv
sz301093 华兰股份

./Stock_Daily/sz301093.csv
sz301095 广立微
./Stock_Daily/sz301095.csv
sz301096 百诚医药
./Stock_Daily/sz301096.csv
sz301097 天益医疗
./Stock_Daily/sz301097.csv
sz301098 金埔园林
./Stock_Daily/sz301098.csv
sz301099 雅创电子
./Stock_Daily/sz301099.csv
sz301100 风光股份
./Stock_Daily/sz301100.csv
sz301101 明月镜片
./Stock_Daily/sz301101.csv
sz301102 兆讯传媒
./Stock_Daily/sz301102.csv
sz301103 何氏眼科
./Stock_Daily/sz301103.csv
sz301105 鸿铭股份
./Stock_Daily/sz301105.csv
sz301106 骏成科技
./Stock_Daily/sz301106.csv
sz301107 瑜欣电子
./Stock_Daily/sz301107.csv
sz301108 洁雅股份
./Stock_Daily/sz301108.csv
sz301109 军信股份
./Stock_Daily/sz301109.csv
sz301110 青木股份
./Stock_Daily/sz301110.csv
sz301111 粤万年青
./Stock_Daily/sz301111.csv
sz301112 信邦智能
./Stock_Daily/sz301112.csv
sz301113 雅艺科技
./Stock_Daily/sz301113.csv
sz301115 建科股份
./Stock_Daily/sz301115.csv
sz301116 益客食品
./Stock_Daily/sz301116.csv
sz301117 佳缘科技
./Stock_Daily/sz301117.csv
sz301118 恒光股份
./Stock_Daily/sz301118.csv
sz301119 正强股份
./Stock_Daily/sz301119.csv
sz301120 新特电气
./Stock_Daily/sz301120.csv
sz301121 紫建电子
./Stock_Daily/sz301121.csv
sz301122 采纳股份
./Stock_Daily/sz301122.csv
sz301123 奕东电子
./Stock_Daily/sz301123.csv
sz301125 腾亚精工
./Stock_Daily/sz301125.csv
sz301126 达嘉维康
./Stock_Daily/sz301126.csv
sz301127 天源环保
./Stock_Daily/sz301127.csv
sz301128 强瑞技术
./Stock_Daily/sz301128.csv
sz301129 瑞纳智能
./Stock_Daily/sz301129.csv
sz301130 西点药业
./Stock_Daily/sz301130.csv
sz301131 聚赛龙
./Stock_Daily/sz301131.csv
sz301132 满坤科技
./Stock_Daily/sz301132.csv
sz301133 金钟股份
./Stock_Daily/sz301133.csv
sz301135 瑞德智能
./Stock_Daily/sz301135.csv
sz301136 招标股份
./Stock_Daily/sz301136.csv
sz301137 哈焊华通
./Stock_Daily/sz301137.csv
sz301138 华研精机
./Stock_Daily/sz301138.csv
sz301139 元道通信
./Stock_Daily/sz301139.csv
sz301141 中科磁业
./Stock_Daily/sz301141.csv
sz301148 嘉戎技术
./Stock_Daily/sz301148.csv
sz301149 隆华新材
./Stock_Daily/sz301149.csv
sz301150 中一科技
./Stock_Daily/sz301150.csv
sz301151 冠龙节能
./Stock_Daily/sz301151.csv
sz301152 天力锂能
./Stock_Daily/sz301152.csv
sz301153 中科江南
./Stock_Daily/sz301153.csv
sz301155 海力风电
./Stock_Daily/sz301155.csv
sz301156 美农生物
./Stock_Daily/sz301156.csv
sz301157 华塑科技
./Stock_Daily/sz301157.csv
sz301158 德石股份
./Stock_Daily/sz301158.csv
sz301159 三维天地
./Stock_Daily/sz301159.csv
sz301160 翔楼新材
./Stock_Daily/sz301160.csv
sz301161 唯万密封
./Stock_Daily/sz301161.csv
sz301162 国能日新
./Stock_Daily/sz301162.csv
sz301163 宏德股份
./Stock_Daily/sz301163.csv
sz301165 锐捷网络
./Stock_Daily/sz301165.csv
sz301166 优宁维
./Stock_Daily/sz301166.csv
sz301167 建研设计
./Stock_Daily/sz301167.csv
sz301168 通灵股份
./Stock_Daily/sz301168.csv
sz301169 零点有数
./Stock_Daily/sz301169.csv
sz301170 锡南科技
./Stock_Daily/sz301170.csv
sz301171 易点天下
./Stock_Daily/sz301171.csv
sz301172 君逸数码
./Stock_Daily/sz301172.csv
sz301175 中科环保
./Stock_Daily/sz301175.csv
sz301176 逸豪新材
./Stock_Daily/sz301176.csv
sz301177 迪阿股份
./Stock_Daily/sz301177.csv
sz301178 天亿马
./Stock_Daily/sz301178.csv
sz301179 泽宇智能
./Stock_Daily/sz301179.csv
sz301180 万祥科技
./Stock_Daily/sz301180.csv
sz301181 标榜股份
./Stock_Daily/sz301181.csv
sz301182 凯旺科技
./Stock_Daily/sz301182.csv
sz301183 东田微
./Stock_Daily/sz301183.csv
sz301185 鸥玛软件
./Stock_Daily/sz301185.csv
sz301186 超达装备
./Stock_Daily/sz301186.csv
sz301187 欧圣电气
./Stock_Daily/sz301187.csv
sz301188 力诺特玻
./Stock_Daily/sz301188.csv
sz301189 奥尼电子
./Stock_Daily/sz301189.csv
sz301190 善水科技
./Stock_Daily/sz301190.csv
sz301191 菲菱科思
./Stock_Daily/sz301191.csv
sz301192 泰祥股份
./Stock_Daily/sz301192.csv
sz301193 家联科技
./Stock_Daily/sz301193.csv
sz301195 北路智控
./Stock_Daily/sz301195.csv
sz301196 唯科科技
./Stock_Daily/sz301196.csv
sz301197 工大科雅
./Stock_Daily/sz301197.csv
sz301198 喜悦智行
./Stock_Daily/sz301198.csv
sz301199 迈赫股份
./Stock_Daily/sz301199.csv
sz301200 大族数控
./Stock_Daily/sz301200.csv
sz301201 诚达药业
./Stock_Daily/sz301201.csv
sz301202 朗威股份
./Stock_Daily/sz301202.csv
sz301203 国泰环保
./Stock_Daily/sz301203.csv
sz301205 联特科技
./Stock_Daily/sz301205.csv
sz301206 三元生物
./Stock_Daily/sz301206.csv
sz301207 华兰疫苗
./Stock_Daily/sz301207.csv
sz301208 中亦科技
./Stock_Daily/sz301208.csv
sz301209 联合化学
./Stock_Daily/sz301209.csv
sz301210 金杨股份
./Stock_Daily/sz301210.csv
sz301211 亨迪药业
./Stock_Daily/sz301211.csv
sz301212 联盛化学
./Stock_Daily/sz301212.csv
sz301213 观想科技
./Stock_Daily/sz301213.csv
sz301215 中汽股份
./Stock_Daily/sz301215.csv
sz301216 万凯新材
./Stock_Daily/sz301216.csv
sz301217 铜冠铜箔
./Stock_Daily/sz301217.csv
sz301218 华是科技
./Stock_Daily/sz301218.csv
sz301219 腾远钴业
./Stock_Daily/sz301219.csv
sz301220 亚香股份
./Stock_Daily/sz301220.csv
sz301221 光庭信息
./Stock_Daily/sz301221.csv
sz301222 浙江恒威
./Stock_Daily/sz301222.csv
sz301223 中荣股份
./Stock_Daily/sz301223.csv
sz301225 恒勃股份
./Stock_Daily/sz301225.csv
sz301226 祥明智能
./Stock_Daily/sz301226.csv
sz301227 森鹰窗业
./Stock_Daily/sz301227.csv
sz301228 实朴检测
./Stock_Daily/sz301228.csv
sz301229 纽泰格
./Stock_Daily/sz301229.csv
sz301230 泓博医药
./Stock_Daily/sz301230.csv
sz301231 荣信文化
./Stock_Daily/sz301231.csv
sz301232 飞沃科技
./Stock_Daily/sz301232.csv
sz301233 盛帮股份
./Stock_Daily/sz301233.csv
sz301234 五洲医疗
./Stock_Daily/sz301234.csv
sz301235 华康医疗
./Stock_Daily/sz301235.csv
sz301236 软通动力
./Stock_Daily/sz301236.csv
sz301237 和顺科技
./Stock_Daily/sz301237.csv
sz301238 瑞泰新材
./Stock_Daily/sz301238.csv
sz301239 普瑞眼科
./Stock_Daily/sz301239.csv
sz301246 宏源药业
./Stock_Daily/sz301246.csv
sz301248 杰创智能
./Stock_Daily/sz301248.csv
sz301251 威尔高
./Stock_Daily/sz301251.csv
sz301252 同星科技
./Stock_Daily/sz301252.csv
sz301255 通力科技
./Stock_Daily/sz301255.csv
sz301256 华融化学
./Stock_Daily/sz301256.csv
sz301257 普蕊斯
./Stock_Daily/sz301257.csv
sz301258 富士莱
./Stock_Daily/sz301258.csv
sz301259 艾布鲁
./Stock_Daily/sz301259.csv
sz301260 格力博
./Stock_Daily/sz301260.csv
sz301261 恒工精密
./Stock_Daily/sz301261.csv
sz301262 海看股份
./Stock_Daily/sz301262.csv
sz301263 泰恩康
./Stock_Daily/sz301263.csv
sz301265 华新环保
./Stock_Daily/sz301265.csv
sz301266 宇邦新材
./Stock_Daily/sz301266.csv
sz301267 华厦眼科
./Stock_Daily/sz301267.csv
sz301268 铭利达
./Stock_Daily/sz301268.csv
sz301269 华大九天
./Stock_Daily/sz301269.csv
sz301270 汉仪股份
./Stock_Daily/sz301270.csv
sz301272 英华特
./Stock_Daily/sz301272.csv
sz301273 瑞晨环保
./Stock_Daily/sz301273.csv
sz301276 嘉曼服饰
./Stock_Daily/sz301276.csv
sz301277 新天地
./Stock_Daily/sz301277.csv
sz301278 快可电子
./Stock_Daily/sz301278.csv
sz301279 金道科技
./Stock_Daily/sz301279.csv
sz301280 珠城科技
./Stock_Daily/sz301280.csv
sz301281 科源制药
./Stock_Daily/sz301281.csv
sz301282 金禄电子
./Stock_Daily/sz301282.csv
sz301283 聚胶股份
./Stock_Daily/sz301283.csv
sz301285 鸿日达
./Stock_Daily/sz301285.csv
sz301286 侨源股份
./Stock_Daily/sz301286.csv
sz301287 康力源
./Stock_Daily/sz301287.csv
sz301288 清研环境
./Stock_Daily/sz301288.csv
sz301289 国缆检测
./Stock_Daily/sz301289.csv
sz301290 东星医疗
./Stock_Daily/sz301290.csv
sz301291 明阳电气
./Stock_Daily/sz301291.csv
sz301292 海科新源
./Stock_Daily/sz301292.csv
sz301293 三博脑科
./Stock_Daily/sz301293.csv
sz301295 美硕科技
./Stock_Daily/sz301295.csv
sz301296 新巨丰
./Stock_Daily/sz301296.csv
sz301297 富乐德
./Stock_Daily/sz301297.csv
sz301298 东利机械
./Stock_Daily/sz301298.csv
sz301299 卓创资讯
./Stock_Daily/sz301299.csv
sz301300 远翔新材
./Stock_Daily/sz301300.csv
sz301301 川宁生物
./Stock_Daily/sz301301.csv
sz301302 华如科技
./Stock_Daily/sz301302.csv
sz301303 真兰仪表
./Stock_Daily/sz301303.csv
sz301305 朗坤环境
./Stock_Daily/sz301305.csv
sz301306 西测测试
./Stock_Daily/sz301306.csv
sz301307 美利信
./Stock_Daily/sz301307.csv
sz301308 江波龙
./Stock_Daily/sz301308.csv
sz301309 万得凯
./Stock_Daily/sz301309.csv
sz301310 鑫宏业
./Stock_Daily/sz301310.csv
sz301311 昆船智能
./Stock_Daily/sz301311.csv
sz301312 智立方
./Stock_Daily/sz301312.csv
sz301313 凡拓数创
./Stock_Daily/sz301313.csv
sz301314 科瑞思
./Stock_Daily/sz301314.csv
sz301315 威士顿
./Stock_Daily/sz301315.csv
sz301316 慧博云通
./Stock_Daily/sz301316.csv
sz301317 鑫磊股份
./Stock_Daily/sz301317.csv
sz301318 维海德
./Stock_Daily/sz301318.csv
sz301319 唯特偶
./Stock_Daily/sz301319.csv
sz301320 豪江智能
./Stock_Daily/sz301320.csv
sz301321 翰博高新
./Stock_Daily/sz301321.csv
sz301322 绿通科技
./Stock_Daily/sz301322.csv
sz301323 新莱福
./Stock_Daily/sz301323.csv
sz301325 曼恩斯特
./Stock_Daily/sz301325.csv
sz301326 捷邦科技
./Stock_Daily/sz301326.csv
sz301327 华宝新能
./Stock_Daily/sz301327.csv
sz301328 维峰电子
./Stock_Daily/sz301328.csv
sz301329 信音电子
./Stock_Daily/sz301329.csv
sz301330 熵基科技
./Stock_Daily/sz301330.csv
sz301331 恩威医药
./Stock_Daily/sz301331.csv
sz301332 德尔玛
./Stock_Daily/sz301332.csv
sz301333 诺思格
./Stock_Daily/sz301333.csv
sz301335 天元宠物

./Stock_Daily/sz301335.csv
sz301336 趣睡科技
./Stock_Daily/sz301336.csv
sz301337 亚华电子
./Stock_Daily/sz301337.csv
sz301338 凯格精机
./Stock_Daily/sz301338.csv
sz301339 通行宝
./Stock_Daily/sz301339.csv
sz301345 涛涛车业
./Stock_Daily/sz301345.csv
sz301348 蓝箭电子
./Stock_Daily/sz301348.csv
sz301349 信德新材
./Stock_Daily/sz301349.csv
sz301353 普莱得
./Stock_Daily/sz301353.csv
sz301355 南王科技
./Stock_Daily/sz301355.csv
sz301356 天振股份
./Stock_Daily/sz301356.csv
sz301357 北方长龙
./Stock_Daily/sz301357.csv
sz301358 湖南裕能
./Stock_Daily/sz301358.csv
sz301359 东南电子
./Stock_Daily/sz301359.csv
sz301360 荣旗科技
./Stock_Daily/sz301360.csv
sz301361 众智科技
./Stock_Daily/sz301361.csv
sz301362 民爆光电
./Stock_Daily/sz301362.csv
sz301363 美好医疗
./Stock_Daily/sz301363.csv
sz301365 矩阵股份
./Stock_Daily/sz301365.csv
sz301366 一博科技
./Stock_Daily/sz301366.csv
sz301367 怡和嘉业
./Stock_Daily/sz301367.csv
sz301368 丰立智能
./Stock_Daily/sz301368.csv
sz301369 联动科技
./Stock_Daily/sz301369.csv
sz301370 国科恒泰
./Stock_Daily/sz301370.csv
sz301371 敷尔佳
./Stock_Daily/sz301371.csv
sz301372 科净源
./Stock_Daily/sz301372.csv
sz301373 凌玮科技
./Stock_Daily/sz301373.csv
sz301376 致欧科技
./Stock_Daily/sz301376.csv
sz301377 鼎泰高科
./Stock_Daily/sz301377.csv
sz301378 通达海
./Stock_Daily/sz301378.csv
sz301379 天山电子
./Stock_Daily/sz301379.csv
sz301380 挖金客
./Stock_Daily/sz301380.csv
sz301381 赛维时代
./Stock_Daily/sz301381.csv
sz301382 蜂助手
./Stock_Daily/sz301382.csv
sz301383 天键股份
./Stock_Daily/sz301383.csv
sz301386 未来电器
./Stock_Daily/sz301386.csv
sz301387 光大同创
./Stock_Daily/sz301387.csv
sz301388 欣灵电气
./Stock_Daily/sz301388.csv
sz301389 隆扬电子
./Stock_Daily/sz301389.csv
sz301390 经纬股份
./Stock_Daily/sz301390.csv
sz301391 卡莱特
./Stock_Daily/sz301391.csv
sz301393 昊帆生物
./Stock_Daily/sz301393.csv
sz301395 仁信新材
./Stock_Daily/sz301395.csv
sz301396 宏景科技
./Stock_Daily/sz301396.csv
sz301397 溯联股份
./Stock_Daily/sz301397.csv
sz301398 星源卓镁
./Stock_Daily/sz301398.csv
sz301399 英特科技
./Stock_Daily/sz301399.csv
sz301408 华人健康
./Stock_Daily/sz301408.csv
sz301418 协昌科技
./Stock_Daily/sz301418.csv
sz301419 阿莱德
./Stock_Daily/sz301419.csv
sz301421 波长光电
./Stock_Daily/sz301421.csv
sz301428 世纪恒通
./Stock_Daily/sz301428.csv
sz301429 森泰股份
./Stock_Daily/sz301429.csv
sz301439 泓淋电力
./Stock_Daily/sz301439.csv
sz301446 福事特
./Stock_Daily/sz301446.csv
sz301448 开创电气
./Stock_Daily/sz301448.csv
sz301456 盘古智能
./Stock_Daily/sz301456.csv
sz301468 博盈特焊
./Stock_Daily/sz301468.csv
sz301469 恒达新材
./Stock_Daily/sz301469.csv
sz301486 致尚科技
./Stock_Daily/sz301486.csv
sz301487 盟固利
./Stock_Daily/sz301487.csv
sz301488 豪恩汽电
./Stock_Daily/sz301488.csv
sz301489 思泉新材
./Stock_Daily/sz301489.csv
sz301498 乖宝宠物
./Stock_Daily/sz301498.csv
sz301499 维科精密
./Stock_Daily/sz301499.csv
sz301500 飞南资源
./Stock_Daily/sz301500.csv
sz301503 智迪科技
./Stock_Daily/sz301503.csv
sz301505 苏州规划
./Stock_Daily/sz301505.csv
sz301507 民生健康
./Stock_Daily/sz301507.csv
sz301509 金凯生科
./Stock_Daily/sz301509.csv
sz301510 固高科技
./Stock_Daily/sz301510.csv
sz301511 德福科技
./Stock_Daily/sz301511.csv
sz301512 智信精密
./Stock_Daily/sz301512.csv
sz301515 港通医疗
./Stock_Daily/sz301515.csv
sz301517 陕西华达
./Stock_Daily/sz301517.csv
sz301518 长华化学
./Stock_Daily/sz301518.csv
sz301519 舜禹股份
./Stock_Daily/sz301519.csv
sz301520 万邦医药
./Stock_Daily/sz301520.csv
sz301525 儒竞科技
./Stock_Daily/sz301525.csv
sz301528 多浦乐
./Stock_Daily/sz301528.csv
sz301529 福赛科技
./Stock_Daily/sz301529.csv
sz301533 威马农机
./Stock_Daily/sz301533.csv
sz301548 崇德科技
./Stock_Daily/sz301548.csv
sz301550 斯菱股份
./Stock_Daily/sz301550.csv
sz301555 惠柏新材
./Stock_Daily/sz301555.csv
sz301558 三态股份
./Stock_Daily/sz301558.csv
sz301559 中集环科
./Stock_Daily/sz301559.csv

In [33]:
import glob
import pandas as pd
import os
folder_path = './Stock_Daily'

# Get all csv files
csv_files = glob.glob(os.path.join(folder_path, '*.csv'))
print(csv_files)
# New dataframe
df = pd.DataFrame()

# Iterate every csv file and concat data together
for f in csv_files:
    data = pd.read_csv(f)
    df = pd.concat([df, data])

# 
df.to_csv('Fact_Stock_Daily.csv', index=False)

['./Stock_Daily/sh688136.csv', './Stock_Daily/sh603105.csv', './Stock_Daily/sz002435.csv', './Stock_Daily/sz002353.csv', './Stock_Daily/sz000544.csv', './Stock_Daily/sh603663.csv', './Stock_Daily/sz000550.csv', './Stock_Daily/sz001896.csv', './Stock_Daily/sh603677.csv', './Stock_Daily/sz002347.csv', './Stock_Daily/sz301190.csv', './Stock_Daily/sh600418.csv', './Stock_Daily/sz002421.csv', './Stock_Daily/sh688122.csv', './Stock_Daily/sh603111.csv', './Stock_Daily/sz002409.csv', './Stock_Daily/sh603139.csv', './Stock_Daily/sh603887.csv', './Stock_Daily/sh600356.csv', './Stock_Daily/sh688678.csv', './Stock_Daily/sh603893.csv', './Stock_Daily/sh688693.csv', './Stock_Daily/sh603878.csv', './Stock_Daily/sz002390.csv', './Stock_Daily/sz300259.csv', './Stock_Daily/sz301153.csv', './Stock_Daily/sz002384.csv', './Stock_Daily/sh688687.csv', './Stock_Daily/sz000593.csv', './Stock_Daily/sz300503.csv', './Stock_Daily/sh600395.csv', './Stock_Daily/sz300265.csv', './Stock_Daily/sh603688.csv', './Stock_Daily/sh600381.csv', './Stock_Daily/sz300271.csv', './Stock_Daily/sz300517.csv', './Stock_Daily/sh601921.csv', './Stock_Daily/sz301386.csv', './Stock_Daily/sh600168.csv', './Stock_Daily/sz300098.csv', './Stock_Daily/sz002151.csv', './Stock_Daily/sz002637.csv', './Stock_Daily/sz300926.csv', './Stock_Daily/sz000020.csv', './Stock_Daily/sh603307.csv', './Stock_Daily/sh688334.csv', './Stock_Daily/sz000034.csv', './Stock_Daily/sh603313.csv', './Stock_Daily/sh688320.csv', './Stock_Daily/sz002623.csv', './Stock_Daily/sz300932.csv', './Stock_Daily/sz002145.csv', './Stock_Daily/sz000752.csv', './Stock_Daily/sh688308.csv', './Stock_Daily/sh600626.csv', './Stock_Daily/sz000008.csv', './Stock_Daily/sz001316.csv', './Stock_Daily/sz002179.csv', './Stock_Daily/sz002192.csv', './Stock_Daily/sz301345.csv', './Stock_Daily/sz000785.csv', './Stock_Daily/sh600815.csv', './Stock_Daily/sz002838.csv', './Stock_Daily/sh600801.csv', './Stock_Daily/sz300729.csv', './Stock_Daily/sz000791.csv', './Stock_Daily/sh688485.csv', './Stock_Daily/sz000949.csv', './Stock_Daily/sz002186.csv', './Stock_Daily/sz000961.csv', './Stock_Daily/sz300067.csv', './Stock_Daily/sh600197.csv', './Stock_Daily/sz301379.csv', './Stock_Daily/sz002810.csv', './Stock_Daily/bj836433.csv', './Stock_Daily/sh600829.csv', './Stock_Daily/sz300701.csv', './Stock_Daily/sz300715.csv', './Stock_Daily/sz300073.csv', './Stock_Daily/sh600183.csv', './Stock_Daily/sz000975.csv', './Stock_Daily/sz000632.csv', './Stock_Daily/sh603515.csv', './Stock_Daily/sh688526.csv', './Stock_Daily/sz002025.csv', './Stock_Daily/sz300852.csv', './Stock_Daily/sz002743.csv', './Stock_Daily/sh603273.csv', './Stock_Daily/sh603267.csv', './Stock_Daily/sz300846.csv', './Stock_Daily/sz002757.csv', './Stock_Daily/sz002031.csv', './Stock_Daily/sh600008.csv', './Stock_Daily/sz000626.csv', './Stock_Daily/sh603501.csv', './Stock_Daily/sz002019.csv', './Stock_Daily/sh600020.csv', './Stock_Daily/sh603529.csv', './Stock_Daily/sh605158.csv', './Stock_Daily/sh600746.csv', './Stock_Daily/sh688268.csv', './Stock_Daily/sz301231.csv', './Stock_Daily/sz000829.csv', './Stock_Daily/sz001289.csv', './Stock_Daily/sh688283.csv', './Stock_Daily/sz300649.csv', './Stock_Daily/sz002780.csv', './Stock_Daily/sh600961.csv', './Stock_Daily/sz300891.csv', './Stock_Daily/sz002958.csv', './Stock_Daily/sh600975.csv', './Stock_Daily/sz300885.csv', './Stock_Daily/sh688297.csv', './Stock_Daily/sz301225.csv', './Stock_Daily/sz000815.csv', './Stock_Daily/bj836221.csv', './Stock_Daily/sz300113.csv', './Stock_Daily/sz300675.csv', './Stock_Daily/sh600785.csv', './Stock_Daily/sh603298.csv', './Stock_Daily/bj832735.csv', './Stock_Daily/sz300661.csv', './Stock_Daily/sh600791.csv', './Stock_Daily/sz002970.csv', './Stock_Daily/sz301219.csv', './Stock_Daily/sz300107.csv', './Stock_Daily/sz000801.csv', './Stock_Daily/sh603071.csv', './Stock_Daily/sz002541.csv', './Stock_Daily/sh601666.csv', './Stock_Daily/sz300488.csv', './Stock_Daily/sh600578.csv', './Stock_Daily/sh601100.csv', './Stock_Daily/sz002227.csv', './Stock_Daily/sh605366.csv', './Stock_Daily/sh603717.csv', './Stock_Daily/sz000430.csv', './Stock_Daily/sh603703.csv', './Stock_Daily/sz002233.csv', './Stock_Daily/sz002555.csv', './Stock_Daily/sh603065.csv', './Stock_Daily/sh688056.csv', './Stock_Daily/sh601882.csv', './Stock_Daily/sh688718.csv', './Stock_Daily/sh600222.csv', './Stock_Daily/sh600236.csv', './Stock_Daily/sh601128.csv', './Stock_Daily/sh603059.csv', './Stock_Daily/sz002569.csv', './Stock_Daily/sh600550.csv', './Stock_Daily/sz002582.csv', './Stock_Daily/sh688081.csv', './Stock_Daily/sz301033.csv', './Stock_Daily/sz300339.csv', './Stock_Daily/sz301027.csv', './Stock_Daily/sh603918.csv', './Stock_Daily/sh688095.csv', './Stock_Daily/sh601869.csv', './Stock_Daily/sz002596.csv', './Stock_Daily/sh600587.csv', './Stock_Daily/sz300477.csv', './Stock_Daily/sh601699.csv', './Stock_Daily/sz300311.csv', './Stock_Daily/sh605399.csv', './Stock_Daily/sz300305.csv', './Stock_Daily/sh600593.csv', './Stock_Daily/sz300463.csv', './Stock_Daily/sz300304.csv', './Stock_Daily/sz300462.csv', './Stock_Daily/sh600592.csv', './Stock_Daily/sh601698.csv', './Stock_Daily/sz300476.csv', './Stock_Daily/sh600586.csv', './Stock_Daily/bj832522.csv', './Stock_Daily/sh605398.csv', './Stock_Daily/sh603931.csv', './Stock_Daily/sz300310.csv', './Stock_Daily/sh603919.csv', './Stock_Daily/sz301026.csv', './Stock_Daily/sz300338.csv', './Stock_Daily/sz002597.csv', './Stock_Daily/sh601868.csv', './Stock_Daily/sh688080.csv', './Stock_Daily/sz002583.csv', './Stock_Daily/sz301032.csv', './Stock_Daily/bj832278.csv', './Stock_Daily/sz000419.csv', './Stock_Daily/sh600237.csv', './Stock_Daily/sh600551.csv', './Stock_Daily/sz002568.csv', './Stock_Daily/sh603058.csv', './Stock_Daily/sh600545.csv', './Stock_Daily/sh600223.csv', './Stock_Daily/sh688719.csv', './Stock_Daily/sz002232.csv', './Stock_Daily/sz000425.csv', './Stock_Daily/sh688057.csv', './Stock_Daily/sz002554.csv', './Stock_Daily/sh600579.csv', './Stock_Daily/sz300489.csv', './Stock_Daily/sz002540.csv', './Stock_Daily/sh603070.csv', './Stock_Daily/sh603716.csv', './Stock_Daily/sz002226.csv', './Stock_Daily/bj871396.csv', './Stock_Daily/sh601101.csv', './Stock_Daily/sz002971.csv', './Stock_Daily/sh600790.csv', './Stock_Daily/sz300660.csv', './Stock_Daily/sh603299.csv', './Stock_Daily/sz000800.csv', './Stock_Daily/sz300106.csv', './Stock_Daily/sz301218.csv', './Stock_Daily/sz300112.csv', './Stock_Daily/sz002965.csv', './Stock_Daily/sh600784.csv', './Stock_Daily/sz300674.csv', './Stock_Daily/sh688296.csv', './Stock_Daily/sz300884.csv', './Stock_Daily/sz002795.csv', './Stock_Daily/bj836208.csv', './Stock_Daily/sz000828.csv', './Stock_Daily/sz301230.csv', './Stock_Daily/sz002959.csv', './Stock_Daily/sz300890.csv', './Stock_Daily/sh600960.csv', './Stock_Daily/sz300648.csv', './Stock_Daily/sh688282.csv', './Stock_Daily/sz001288.csv', './Stock_Daily/sh688269.csv', './Stock_Daily/sh600753.csv', './Stock_Daily/sh600035.csv', './Stock_Daily/sh603528.csv', './Stock_Daily/sh600021.csv', './Stock_Daily/sz002756.csv', './Stock_Daily/sz300847.csv', './Stock_Daily/sh603266.csv', './Stock_Daily/sh688255.csv', './Stock_Daily/sh688533.csv', './Stock_Daily/sh603500.csv', './Stock_Daily/sz000627.csv', './Stock_Daily/sh600009.csv', './Stock_Daily/sz002030.csv', './Stock_Daily/sz002024.csv', './Stock_Daily/sz000633.csv', './Stock_Daily/sz000155.csv', './Stock_Daily/sh603272.csv', './Stock_Daily/sz002742.csv', './Stock_Daily/sz300853.csv', './Stock_Daily/sz002805.csv', './Stock_Daily/sh600182.csv', './Stock_Daily/sz300072.csv', './Stock_Daily/sz301378.csv', './Stock_Daily/sh600196.csv', './Stock_Daily/sz300066.csv', './Stock_Daily/sh601288.csv', './Stock_Daily/sz000960.csv', './Stock_Daily/sz300700.csv', './Stock_Daily/sh600828.csv', './Stock_Daily/sz002811.csv', './Stock_Daily/sh600800.csv', './Stock_Daily/bj839729.csv', './Stock_Daily/sz002839.csv', './Stock_Daily/sz002187.csv', './Stock_Daily/sz000948.csv', './Stock_Daily/sh688484.csv', './Stock_Daily/sz000790.csv', './Stock_Daily/sz002193.csv', './Stock_Daily/sh600814.csv', './Stock_Daily/bj873152.csv', './Stock_Daily/sz001317.csv', './Stock_Daily/sz000009.csv', './Stock_Daily/sz002178.csv', './Stock_Daily/sh600141.csv', './Stock_Daily/sh600155.csv', './Stock_Daily/sh600633.csv', './Stock_Daily/sh688309.csv', './Stock_Daily/sz300933.csv', './Stock_Daily/sz002622.csv', './Stock_Daily/sh688321.csv', './Stock_Daily/sz000035.csv', './Stock_Daily/sz000753.csv', './Stock_Daily/sh605005.csv', './Stock_Daily/sz002144.csv', './Stock_Daily/sz301393.csv', './Stock_Daily/sz002150.csv', './Stock_Daily/sz300099.csv', './Stock_Daily/sh600169.csv', './Stock_Daily/sz301387.csv', './Stock_Daily/sh605011.csv', './Stock_Daily/sh688335.csv', './Stock_Daily/sh603306.csv', './Stock_Daily/sz000021.csv', './Stock_Daily/sz300927.csv', './Stock_Daily/sz002636.csv', './Stock_Daily/sz300270.csv', './Stock_Daily/sh600380.csv', './Stock_Daily/sh603689.csv', './Stock_Daily/bj834033.csv', './Stock_Daily/sz300516.csv', './Stock_Daily/sz300502.csv', './Stock_Daily/sz300264.csv', './Stock_Daily/sz000592.csv', './Stock_Daily/sh688686.csv', './Stock_Daily/sz002385.csv', './Stock_Daily/sz301152.csv', './Stock_Daily/bj871553.csv', './Stock_Daily/bj835305.csv', './Stock_Daily/sh601908.csv', './Stock_Daily/sz300258.csv', './Stock_Daily/sz002391.csv', './Stock_Daily/sz000586.csv', './Stock_Daily/sh603879.csv', './Stock_Daily/sh688679.csv', './Stock_Daily/sh600343.csv', './Stock_Daily/sh600425.csv', './Stock_Daily/sh603138.csv', './Stock_Daily/sz002408.csv', './Stock_Daily/sh603886.csv', './Stock_Daily/sz301191.csv', './Stock_Daily/sh601061.csv', './Stock_Daily/sz002346.csv', './Stock_Daily/sh603676.csv', './Stock_Daily/sz000551.csv', './Stock_Daily/sh603110.csv', './Stock_Daily/sh688123.csv', './Stock_Daily/sz002420.csv', './Stock_Daily/sh600419.csv', './Stock_Daily/sz002434.csv', './Stock_Daily/sh688137.csv', './Stock_Daily/sh688651.csv', './Stock_Daily/sh603662.csv', './Stock_Daily/sz000545.csv', './Stock_Daily/sz301185.csv', './Stock_Daily/sz002352.csv', './Stock_Daily/sz002422.csv', './Stock_Daily/sh688121.csv', './Stock_Daily/sh603112.csv', './Stock_Daily/sz000553.csv', './Stock_Daily/bj872925.csv', './Stock_Daily/sz002344.csv', './Stock_Daily/sz301193.csv', './Stock_Daily/sz002350.csv', './Stock_Daily/sz300299.csv', './Stock_Daily/sh601077.csv', './Stock_Daily/sz301187.csv', './Stock_Daily/sh600369.csv', './Stock_Daily/sz000547.csv', './Stock_Daily/sh603660.csv', './Stock_Daily/sh688653.csv', './Stock_Daily/sh605577.csv', './Stock_Daily/sh688135.csv', './Stock_Daily/sh603106.csv', './Stock_Daily/sz002436.csv', './Stock_Daily/bj838810.csv', './Stock_Daily/sz002378.csv', './Stock_Daily/bj831834.csv', './Stock_Daily/sh603648.csv', './Stock_Daily/sh603890.csv', './Stock_Daily/sh600355.csv', './Stock_Daily/sh600433.csv', './Stock_Daily/sh688109.csv', './Stock_Daily/sz300528.csv', './Stock_Daily/sz301150.csv', './Stock_Daily/sz002387.csv', './Stock_Daily/sz000590.csv', './Stock_Daily/sh688690.csv', './Stock_Daily/sz000584.csv', './Stock_Daily/sz002393.csv', './Stock_Daily/sz300514.csv', './Stock_Daily/sh600382.csv', './Stock_Daily/bj839273.csv', './Stock_Daily/sz300272.csv', './Stock_Daily/sh600396.csv', './Stock_Daily/sz301178.csv', './Stock_Daily/sh601088.csv', './Stock_Daily/sz300266.csv', './Stock_Daily/sh605588.csv', './Stock_Daily/sz300500.csv', './Stock_Daily/sz301391.csv', './Stock_Daily/sz002146.csv', './Stock_Daily/sh605007.csv', './Stock_Daily/sz000989.csv', './Stock_Daily/sz000751.csv', './Stock_Daily/sz000037.csv', './Stock_Daily/sh688323.csv', './Stock_Daily/sz002620.csv', './Stock_Daily/sh600619.csv', './Stock_Daily/sz300931.csv', './Stock_Daily/sz002634.csv', './Stock_Daily/sz300925.csv', './Stock_Daily/sz000023.csv', './Stock_Daily/sh688337.csv', './Stock_Daily/sz002152.csv', './Stock_Daily/sh688479.csv', './Stock_Daily/sh600143.csv', './Stock_Daily/sh603338.csv', './Stock_Daily/sz001301.csv', './Stock_Daily/sz002608.csv', './Stock_Daily/sz300919.csv', './Stock_Daily/bj836395.csv', './Stock_Daily/sh600157.csv', './Stock_Daily/sz000779.csv', './Stock_Daily/sz000792.csv', './Stock_Daily/sh688486.csv', './Stock_Daily/sz002185.csv', './Stock_Daily/sh600802.csv', './Stock_Daily/bj871753.csv', './Stock_Daily/sh600816.csv', './Stock_Daily/sz300058.csv', './Stock_Daily/sz002191.csv', './Stock_Daily/sz000786.csv', './Stock_Daily/sz300070.csv', './Stock_Daily/sh600180.csv', './Stock_Daily/sh603489.csv', './Stock_Daily/sz000976.csv', './Stock_Daily/sz002807.csv', './Stock_Daily/sz301408.csv', './Stock_Daily/sz300716.csv', './Stock_Daily/sz002813.csv', './Stock_Daily/sz300702.csv', './Stock_Daily/sz000962.csv', './Stock_Daily/sz002032.csv', './Stock_Daily/sz000625.csv', './Stock_Daily/sh688531.csv', './Stock_Daily/sh688257.csv', './Stock_Daily/sz300845.csv', './Stock_Daily/sz300851.csv', './Stock_Daily/sh600779.csv', './Stock_Daily/sz002998.csv', './Stock_Daily/sz300689.csv', './Stock_Daily/sz002740.csv', './Stock_Daily/sh603270.csv', './Stock_Daily/sz000157.csv', './Stock_Daily/sz000631.csv', './Stock_Daily/sh603516.csv', './Stock_Daily/sh688525.csv', './Stock_Daily/sh605167.csv', './Stock_Daily/sz002026.csv', './Stock_Daily/sz000619.csv', './Stock_Daily/sh600037.csv', './Stock_Daily/sz300879.csv', './Stock_Daily/sh600751.csv', './Stock_Daily/sz002768.csv', './Stock_Daily/sh600989.csv', './Stock_Daily/sh603258.csv', './Stock_Daily/sh600745.csv', './Stock_Daily/sh600023.csv', './Stock_Daily/sh688519.csv', './Stock_Daily/sz301226.csv', './Stock_Daily/bj838227.csv', './Stock_Daily/sz300138.csv', './Stock_Daily/sh600976.csv', './Stock_Daily/sz002797.csv', './Stock_Daily/sz300886.csv', './Stock_Daily/sh688280.csv', './Stock_Daily/sh600962.csv', './Stock_Daily/sz002783.csv', './Stock_Daily/sz300892.csv', './Stock_Daily/sz301232.csv', './Stock_Daily/sz000802.csv', './Stock_Daily/sz300662.csv', './Stock_Daily/sz002973.csv', './Stock_Daily/sh600792.csv', './Stock_Daily/sz300676.csv', './Stock_Daily/sz002967.csv', './Stock_Daily/sz000816.csv', './Stock_Daily/sh605198.csv', './Stock_Daily/sz300110.csv', './Stock_Daily/sz002556.csv', './Stock_Daily/sh603066.csv', './Stock_Daily/sh688055.csv', './Stock_Daily/sh688733.csv', './Stock_Daily/sh603700.csv', './Stock_Daily/sh601117.csv', './Stock_Daily/sz002230.csv', './Stock_Daily/sz002224.csv', './Stock_Daily/sh605365.csv', './Stock_Daily/bj833819.csv', './Stock_Daily/sh688041.csv', './Stock_Daily/sz002542.csv', './Stock_Daily/sh601665.csv', './Stock_Daily/sh688069.csv', './Stock_Daily/sh600235.csv', './Stock_Daily/sh603728.csv', './Stock_Daily/sh600221.csv', './Stock_Daily/sz002218.csv', './Stock_Daily/sh600547.csv', './Stock_Daily/sh601881.csv', './Stock_Daily/sh688096.csv', './Stock_Daily/sz002595.csv', './Stock_Daily/sz301024.csv', './Stock_Daily/sz301030.csv', './Stock_Daily/sz002581.csv', './Stock_Daily/sz300448.csv', './Stock_Daily/sh688082.csv', './Stock_Daily/sh600590.csv', './Stock_Daily/sz300460.csv', './Stock_Daily/sh603099.csv', './Stock_Daily/sh603927.csv', './Stock_Daily/sz300306.csv', './Stock_Daily/sz301018.csv', './Stock_Daily/sh603933.csv', './Stock_Daily/sh600584.csv', './Stock_Daily/sz300474.csv', './Stock_Daily/sz300313.csv', './Stock_Daily/sz300475.csv', './Stock_Daily/sh600585.csv', './Stock_Daily/sh603098.csv', './Stock_Daily/sz300461.csv', './Stock_Daily/sh601857.csv', './Stock_Daily/sz301019.csv', './Stock_Daily/sz300307.csv', './Stock_Daily/sh603926.csv', './Stock_Daily/sz301031.csv', './Stock_Daily/bj838030.csv', './Stock_Daily/sh688083.csv', './Stock_Daily/sz300449.csv', './Stock_Daily/sz002580.csv', './Stock_Daily/sz002594.csv', './Stock_Daily/sh688097.csv', './Stock_Daily/bj833171.csv', './Stock_Daily/sz301025.csv', './Stock_Daily/sz002219.csv', './Stock_Daily/sh600220.csv', './Stock_Daily/sh603729.csv', './Stock_Daily/sh605358.csv', './Stock_Daily/sh601880.csv', './Stock_Daily/bj838971.csv', './Stock_Daily/sh600546.csv', './Stock_Daily/sh601658.csv', './Stock_Daily/sh600552.csv', './Stock_Daily/sh688068.csv', './Stock_Daily/sh600234.csv', './Stock_Daily/sz002225.csv', './Stock_Daily/sz002543.csv', './Stock_Daily/sh603073.csv', './Stock_Daily/sh603067.csv', './Stock_Daily/sz002557.csv', './Stock_Daily/sz002231.csv', './Stock_Daily/sh601116.csv', './Stock_Daily/sh600208.csv', './Stock_Daily/sz000426.csv', './Stock_Daily/sh603701.csv', './Stock_Daily/sh600787.csv', './Stock_Daily/sz002966.csv', './Stock_Daily/sz300677.csv', './Stock_Daily/sz300111.csv', './Stock_Daily/sh605199.csv', './Stock_Daily/sz000803.csv', './Stock_Daily/sz300105.csv', './Stock_Daily/sh600793.csv', './Stock_Daily/sz002972.csv', './Stock_Daily/sz300663.csv', './Stock_Daily/bj833429.csv', './Stock_Daily/sz301555.csv', './Stock_Daily/sz300893.csv', './Stock_Daily/sz002782.csv', './Stock_Daily/sh600963.csv', './Stock_Daily/sh688281.csv', './Stock_Daily/sz301233.csv', './Stock_Daily/sz300139.csv', './Stock_Daily/sz301227.csv', './Stock_Daily/sh688295.csv', './Stock_Daily/sz300887.csv', './Stock_Daily/sz002796.csv', './Stock_Daily/sh600977.csv', './Stock_Daily/sh600744.csv', './Stock_Daily/sh688518.csv', './Stock_Daily/sh600022.csv', './Stock_Daily/sh600036.csv', './Stock_Daily/sh601328.csv', './Stock_Daily/sh603259.csv', './Stock_Daily/sz001260.csv', './Stock_Daily/sh600988.csv', './Stock_Daily/sz002769.csv', './Stock_Daily/sh600750.csv', './Stock_Daily/sz300878.csv', './Stock_Daily/sz000156.csv', './Stock_Daily/sz002741.csv', './Stock_Daily/sz300688.csv', './Stock_Daily/sz002999.csv', './Stock_Daily/sh600778.csv', './Stock_Daily/sz300850.csv', './Stock_Daily/sz002027.csv', './Stock_Daily/sh605166.csv', './Stock_Daily/bj430556.csv', './Stock_Daily/sh603517.csv', './Stock_Daily/sz000630.csv', './Stock_Daily/sz002033.csv', './Stock_Daily/sz002755.csv', './Stock_Daily/sz300844.csv', './Stock_Daily/sh688256.csv', './Stock_Daily/sz300703.csv', './Stock_Daily/sz002812.csv', './Stock_Daily/sh600195.csv', './Stock_Daily/sz300065.csv', './Stock_Daily/sz000963.csv', './Stock_Daily/sz000977.csv', './Stock_Daily/bj835892.csv', './Stock_Daily/sh603488.csv', './Stock_Daily/sz300071.csv', './Stock_Daily/sz300717.csv', './Stock_Daily/sz002806.csv', './Stock_Daily/sh600817.csv', './Stock_Daily/sz301421.csv', './Stock_Daily/bj833575.csv', './Stock_Daily/sz002190.csv', './Stock_Daily/sz300059.csv', './Stock_Daily/sz301353.csv', './Stock_Daily/sz002184.csv', './Stock_Daily/sz000793.csv', './Stock_Daily/sh600803.csv', './Stock_Daily/bj836419.csv', './Stock_Daily/sz300918.csv', './Stock_Daily/sh600630.csv', './Stock_Daily/sz002609.csv', './Stock_Daily/sz001300.csv', './Stock_Daily/sh603339.csv', './Stock_Daily/sz000778.csv', './Stock_Daily/sh600156.csv', './Stock_Daily/sh688478.csv', './Stock_Daily/sz001314.csv', './Stock_Daily/sh600624.csv', './Stock_Daily/sh688336.csv', './Stock_Daily/sh603305.csv', './Stock_Daily/sh601512.csv', './Stock_Daily/sz002635.csv', './Stock_Daily/sz002153.csv', './Stock_Daily/sh688450.csv', './Stock_Daily/sz000750.csv', './Stock_Daily/sh603477.csv', './Stock_Daily/sz000988.csv', './Stock_Daily/sh605006.csv', './Stock_Daily/sz301390.csv', './Stock_Daily/sz300930.csv', './Stock_Daily/sh600618.csv', './Stock_Daily/sz002621.csv', './Stock_Daily/sz001328.csv', './Stock_Daily/sh688322.csv', './Stock_Daily/sh603311.csv', './Stock_Daily/sz000036.csv', './Stock_Daily/sz300267.csv', './Stock_Daily/sh601089.csv', './Stock_Daily/sz301179.csv', './Stock_Daily/sh600397.csv', './Stock_Daily/sz300501.csv', './Stock_Daily/sh605589.csv', './Stock_Daily/sz300515.csv', './Stock_Daily/sh600383.csv', './Stock_Daily/sz002392.csv', './Stock_Daily/bj832469.csv', './Stock_Daily/sz300529.csv', './Stock_Daily/sz000591.csv', './Stock_Daily/sh688685.csv', './Stock_Daily/sz002386.csv', './Stock_Daily/sz301151.csv', './Stock_Daily/sh600354.csv', './Stock_Daily/sh603885.csv', './Stock_Daily/sh688108.csv', './Stock_Daily/sh600426.csv', './Stock_Daily/sh600340.csv', './Stock_Daily/sz002379.csv', './Stock_Daily/sh603661.csv', './Stock_Daily/sz000546.csv', './Stock_Daily/sh600368.csv', './Stock_Daily/sz30

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1121608 entries, 0 to 216
Data columns (total 12 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   FSD_ID                  1121608 non-null  int64
 1   Stock_ID                1121608 non-null  object
 2   Date_ID                 1121608 non-null  int64
 3   Open                    1121608 non-null  float64
 4   High                    1121608 non-null  float64
 5   Low                     1121608 non-null  float64
 6   Volume                  1121608 non-null  int64
 7   Turnover                1121608 non-null  float64
 8   Amplitude               1121608 non-null  float64
 9   Percent_Of_Incre_Decre  1121608 non-null  float64
 10  Amount_Of_Incre_Decre   1121608 non-null  float64
 11  Turnover_Rate           1121608 non-null  float64
dtypes: float64(8), int64(3), object(1)
memory usage: 111.2+ MB

In [46]:
#df['Stock_ID'] = df['Stock_ID'].str[2:].astype(int)
df.to_csv('Fact_Stock_Daily.csv', index=False)

In [47]:
df[:10]

           FSD_ID  Stock_ID   Date_ID   Open   High    Low  Volume    Turnover  Amplitude  Percent_Of_Incre_Decre  Amount_Of_Incre_Decre  Turnover_Rate
0  20230103688136    688136  20230103  22.42  23.30  22.38   31113  70592264.0       4.29                    5.83                   1.25           4.65
1  20230104688136    688136  20230104  23.09  23.11  22.16   22331  49972060.0       4.19                   -2.12                  -0.48           3.34
2  20230105688136    688136  20230105  22.45  22.66  22.01   19076  42887068.0       2.93                    1.31                   0.29           2.85
3  20230106688136    688136  20230106  22.61  22.77  22.20   14789  33142754.0       2.53                   -1.11                  -0.25           2.21
4  20230109688136    688136  20230109  22.38  22.38  22.05   14773  32768919.0       1.48                    0.13                   0.03           2.21
5  20230110688136    688136  20230110  22.23  22.67  21.88   16460  36865904.0       3.55                    0.85                   0.19           2.46
6  20230111688136    688136  20230111  22.31  22.57  22.11   10677  23877667.0       2.05                   -1.47                  -0.33           1.60
7  20230112688136    688136  20230112  22.40  22.44  22.06   11328  25184610.0       1.72                   -0.05                  -0.01           1.69
8  20230113688136    688136  20230113  22.15  22.98  22.07   21321  48000754.0       4.11                    2.71                   0.60           3.19
9  20230116688136    688136  20230116  22.59  23.20  22.54   21920  50191384.0       2.90                    0.26                   0.06           3.28

# Update Daily Data into Postgres

In [7]:
code_list = pd.read_csv('CodeList.csv')
def check_sql_exist(Current_Date:str, stockid:str):
    sql = "SELECT COUNT(fsd_id) from \"Trading\".Fact_Stock_Daily\
                where Date_ID=" + Current_Date + " and Stock_ID=" + stockid+";"
    conn = psycopg2.connect(host="localhost", database="yuzhuoran", user="postgres", password="YZRyzr010306!")
    cur = conn.cursor()
    conn.commit()
    conn.rollback()
    conn.autocommit = True
    cur.execute(sql)
    col_names = [desc [0] for desc in cur.description]
    results = cur.fetchall()
    cur.close()
    return col_names,results
    
def update_daily_data(Current_Date:str):
    conn = psycopg2.connect(host="localhost", database="yuzhuoran", user="postgres", password="YZRyzr010306!")
    cur = conn.cursor()
    conn.commit()
    conn.rollback()
    conn.autocommit = True
    for CodeDes in code_list.values:
        ak_code, ak_name = CodeDes[1],CodeDes[2]
        print(ak_code,ak_name)
        col,result = check_sql_exist(Current_Date,ak_code[2:])
        if result[0][0] > 0:
            print(True)
            continue
        try:
            stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=ak_code[2:], start_date=Current_Date, end_date=Current_Date, period='daily', adjust='')
        except Exception as e:
            print(e)
            continue
        if len(stock_zh_a_hist_df)==0:
            continue
            #‘2023-12-01’
        stock_zh_a_hist_df['Date_ID'] = stock_zh_a_hist_df['日期'].apply(lambda x:x.strftime("%Y%m%d")).astype(int)
        stock_zh_a_hist_df['FSD_ID'] = stock_zh_a_hist_df['Date_ID']*1000000+int(ak_code[2:])
        stock_zh_a_hist_df['Stock_ID'] = int(ak_code[2:])
        stock_zh_a_hist_df.rename(columns = {'日期':'Date','开盘':'Open','收盘':'Close','最高':'High','最低':'Low',
                                                    '成交量':'Volume','成交额':'Turnover','振幅':'Amplitude',
                                             '涨跌幅':'Percent_Of_Incre_Decre','涨跌额':'Amount_Of_Incre_Decre','换手率':'Turnover_Rate'},inplace = True)
        stock_zh_a_hist_df = stock_zh_a_hist_df[['FSD_ID','Stock_ID','Date_ID','Open','Close','High','Low','Volume',
                                                 'Turnover','Amplitude','Percent_Of_Incre_Decre','Amount_Of_Incre_Decre','Turnover_Rate']]
        
        sql = "INSERT INTO \"Trading\".Fact_Stock_Daily (FSD_ID, Stock_ID, Date_ID, Open, Close, High, Low, Volume, \
                                        Turnover, Amplitude, Percent_Of_Incre_Decre, Amount_Of_Incre_Decre, Turnover_Rate) \
                                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        
        for index, row in stock_zh_a_hist_df.iterrows():
            values = (row['FSD_ID'], row['Stock_ID'],row['Date_ID'],row['Open'],row['Close'], row['High'],row['Low'],row['Volume'],
                    row['Turnover'],row['Amplitude'],row['Percent_Of_Incre_Decre'],row['Amount_Of_Incre_Decre'],row['Turnover_Rate']) 
            cur.execute(sql, values)
    cur.close()

In [11]:
Current_Date = '20231201'
update_daily_data(Current_Date)

bj430017 星昊医药
bj430047 诺思兰德
bj430090 同辉信息
bj430139 华岭股份
bj430198 微创光电
bj430300 辰光医疗
bj430418 苏轴股份
bj430425 乐创技术
bj430476 海能技术
bj430478 峆一药业
bj430489 佳先股份
bj430510 丰光精密
bj430556 雅达股份
bj430564 天润科技
bj430685 新芝生物
bj430718 合肥高科
bj830779 武汉蓝电
bj830799 艾融软件
bj830809 安达科技
bj830832 齐鲁华信
bj830839 万通液压
bj830879 基康仪器
bj830896 旺成科技
bj830946 森萱医药
bj830964 润农节水
bj830974 凯大催化
bj831010 凯添燃气
bj831039 国义招标
bj831087 秋乐种业
bj831152 昆工科技
bj831167 鑫汇科
bj831195 三祥科技
bj831278 泰德股份
bj831304 迪尔化工
bj831305 海希通讯
bj831370 新安洁
bj831445 龙竹科技
bj831526 凯华材料
bj831627 力王股份
bj831641 格利尔
bj831689 克莱特
bj831726 朱老六
bj831768 拾比佰
bj831832 科达自控
bj831834 三维股份
bj831855 浙江大农
bj831856 浩淼科技
bj831906 舜宇精工
bj831961 创远信科
bj832000 安徽凤凰
bj832023 田野股份
bj832089 禾昌聚合
bj832110 雷特科技
bj832145 恒合股份
bj832149 利尔达
bj832171 志晟信息
bj832175 东方碳素
bj832225 利通科技
bj832278 鹿得医疗
bj832419 路斯股份
bj832469 富恒新材
bj832471 美邦科技
bj832491 奥迪威
bj832522 纳科诺尔
bj832566 梓橦宫
bj832651 天罡股份
bj832662 方盛股份
bj832735 德源药业
bj832786 骑士乳业
bj832802 保丽洁
bj832876 慧为智能
bj832885 星辰科技
bj832978 开特股份
bj832982 锦波生物
bj833030 立方控股
bj833075 柏星龙
bj833171 国航远洋
bj833230 欧康医药
bj833266 生物谷
bj833346 威贸电子
bj833394 民士达
bj833427 华维设计
bj833429 康比特
bj833454 同心传动
bj833455 汇隆活塞
bj833509 同惠电子
bj833523 德瑞锂电
bj833533 骏创科技
bj833575 康乐卫士
bj833580 科创新材
bj833751 惠同新材
bj833781 瑞奇智造
bj833819 颖泰生物
bj833873 中设咨询
bj833914 远航精密
bj833943 优机股份
bj834014 特瑞斯
bj834021 流金科技
bj834033 康普化学
bj834058 华洋赛车
bj834062 科润智控
bj834261 一诺威
bj834407 驰诚股份
bj834415 恒拓开源
bj834475 三友科技
bj834599 同力股份
bj834639 晨光电缆
bj834682 球冠电缆
bj834765 美之高
bj834770 艾能聚
bj834950 迅安科技
bj835174 五新隧装
bj835179 凯德石英
bj835184 国源科技
bj835185 贝特瑞
bj835207 众诚科技
bj835237 力佳科技
bj835305 云创数据
bj835368 连城数控
bj835508 殷图网联
bj835640 富士达
bj835670 数字人
bj835857 百甲科技
bj835892 中科美菱
bj835985 海泰新能
bj836077 吉林碳谷
bj836149 旭杰科技
bj836208 青矩技术
bj836221 易实精密
bj836239 长虹能源
bj836247 华密新材
bj836260 中寰股份
bj836263 中航泰达
bj836270 天铭科技
bj836395 朗鸿科技
bj836414 欧普泰
bj836419 万德股份
bj836422 润普食品
bj836433 大唐药业
bj836504 博迅生物
bj836675 秉扬科技
bj836699 海达尔
bj836717 瑞星股份
bj836720 吉冈精密
bj836807 奔朗新材
bj836826 盖世食品
bj836871 派特尔
bj836892 广咨国际
bj836942 恒立钻具
bj836957 汉维科技
bj837006 晟楠科技
bj837046 亿能电力
bj837092 汉鑫科技
bj837174 宏裕包材
bj837212 智新电子
bj837242 建邦科技
bj837344 三元基因
bj837592 华信永道
bj837663 明阳科技
bj837748 路桥信息
bj837821 则成电子
bj838030 德众汽车
bj838163 方大新材
bj838171 邦德股份
bj838227 美登科技
bj838262 太湖雪
bj838275 驱动力
bj838402 硅烷科技
bj838670 恒进感应
bj838701 豪声电子
bj838810 春光药装
bj838837 华原股份
bj838924 广脉科技
bj838971 天马新材
bj839167 同享科技
bj839273 一致魔芋
bj839371 欧福蛋业
bj839493 并行科技
bj839680 广道数字
bj839719 宁新新材
bj839725 惠丰钻石
bj839729 永顺生物
bj839790 联迪信息
bj839792 东和新材
bj839946 华阳变速
bj870199 倍益康
bj870204 沪江材料
bj870299 灿能电力
bj870357 雅葆轩
bj870436 大地电气
bj870508 丰安股份
bj870726 鸿智科技
bj870866 绿亨科技
bj870976 视声智能
bj871245 威博液压
bj871396 常辅股份
bj871478 巨能股份
bj871553 凯腾精工
bj871634 新威凌
bj871642 通易航天
bj871694 中裕科技
bj871753 天纺标
bj871857 泓禧科技
bj871970 大禹生物
bj871981 晶赛科技
bj872190 雷神科技
bj872351 华光源海
bj872374 云里物里
bj872392 佳合科技
bj872541 铁大科技
bj872808 曙光数创
bj872895 花溪科技
bj872925 锦好医疗
bj872953 国子软件
bj873001 纬达光电
bj873122 中纺标
bj873132 泰鹏智能
bj873152 天宏锂电
bj873167 新赣江
bj873169 七丰精工
bj873223 荣亿精密
bj873305 九菱科技
bj873339 恒太照明
bj873527 夜光明
bj873576 天力复合
bj873593 鼎智科技
bj873665 科强股份
bj873679 前进科技
bj873693 阿为特
bj873726 卓兆点胶
bj873833 美心翼申
sh600000 浦发银行
sh600004 白云机场
sh600006 东风汽车
sh600007 中国国贸
sh600008 首创环保
sh600009 上海机场
sh600010 包钢股份
sh600011 华能国际
sh600012 皖通高速
sh600015 华夏银行
sh600016 民生银行
sh600017 日照港
sh600018 上港集团
sh600019 宝钢股份
sh600020 中原高速
sh600021 上海电力
sh600022 山东钢铁
sh600023 浙能电力
sh600025 华能水电
sh600026 中远海能
sh600027 华电国际
sh600028 中国石化
sh600029 南方航空
sh600030 中信证券
sh600031 三一重工
sh600032 浙江新能
sh600033 福建高速
sh600035 楚天高速
sh600036 招商银行
sh600037 歌华有线
sh600038 中直股份
sh600039 四川路桥
sh600048 保利发展
sh600050 中国联通
sh600051 宁波联合
sh600052 东望时代
sh600053 九鼎投资
sh600054 黄山旅游
sh600055 万东医疗
sh600056 中国医药
sh600057 厦门象屿
sh600058 五矿发展
sh600059 古越龙山
sh600060 海信视像
sh600061 国投资本
sh600062 华润双鹤
sh600063 皖维高新
sh600064 南京高科
sh600066 宇通客车
sh600067 冠城大通
sh600070 ST富润
sh600071 凤凰光学
sh600072 中船科技
sh600073 上海梅林
sh600075 新疆天业
sh600076 康欣新材
sh600078 ST澄星
sh600079 人福医药
sh600080 金花股份
sh600081 东风科技
sh600082 海泰发展
sh600083 博信股份
sh600084 中信尼雅
sh600085 同仁堂
sh600088 中视传媒
sh600089 特变电工
sh600094 大名城
sh600095 湘财股份
sh600096 云天化
sh600097 开创国际
sh600098 广州发展
sh600099 林海股份
sh600100 同方股份
sh600101 明星电力
sh600103 青山纸业
sh600104 上汽集团
sh600105 永鼎股份
sh600106 重庆路桥
sh600107 美尔雅
sh600108 亚盛集团
sh600109 国金证券
sh600110 诺德股份
sh600111 北方稀土
sh600112 ST天成
sh600113 浙江东日
sh600114 东睦股份
sh600115 中国东航
sh600116 三峡水利
sh600117 *ST西钢
sh600118 中国卫星
sh600119 长江投资
sh600120 浙江东方
sh600121 郑州煤电
sh600123 兰花科创
sh600125 铁龙物流
sh600126 杭钢股份
sh600127 金健米业
sh600128 苏豪弘业
sh600129 太极集团
sh600130 波导股份
sh600131 国网信通
sh600132 重庆啤酒
sh600133 东湖高新
sh600135 乐凯胶片
sh600136 *ST明诚
sh600137 浪莎股份
sh600138 中青旅
sh600141 兴发集团
sh600143 金发科技
sh600148 长春一东
sh600149 廊坊发展
sh600150 中国船舶
sh600151 航天机电
sh600152 维科技术
sh600153 建发股份
sh600155 华创云信
sh600156 华升股份
sh600157 永泰能源
sh600158 中体产业
sh600159 大龙地产
sh600160 巨化股份
sh600161 天坛生物
sh600162 香江控股
sh600163 中闽能源
sh600165 宁科生物
sh600166 福田汽车
sh600167 联美控股
sh600168 武汉控股
sh600169 太原重工
sh600170 上海建工
sh600171 上海贝岭
sh600172 黄河旋风
sh600173 卧龙地产
sh600176 中国巨石
sh600177 雅戈尔
sh600178 东安动力
sh600179 安通控股
sh600180 瑞茂通
sh600182 S佳通
sh600183 生益科技
sh600184 光电股份
sh600185 格力地产
sh600186 莲花健康
sh600187 国中水务
sh600188 兖矿能源
sh600189 泉阳泉
sh600190 锦州港
sh600191 华资实业
sh600192 长城电工
sh600193 创兴资源
sh600195 中牧股份
sh600196 复星医药
sh600197 伊力特
sh600198 大唐电信
sh600199 金种子酒
sh600200 江苏吴中
sh600201 生物股份
sh600202 哈空调
sh600203 福日电子
sh600206 有研新材
sh600207 安彩高科
sh600208 新湖中宝
sh600210 紫江企业
sh600211 西藏药业
sh600212 绿能慧充
sh600213 亚星客车
sh600215 派斯林
sh600216 浙江医药
sh600217 中再资环
sh600218 全柴动力
sh600219 南山铝业
sh600220 江苏阳光
sh600221 海航控股
sh600222 太龙药业
sh600223 福瑞达
sh600225 卓朗科技
sh600226 瀚叶股份
sh600227 赤天化
sh600228 返利科技
sh600229 城市传媒
sh600230 沧州大化
sh600231 凌钢股份
sh600232 金鹰股份
sh600233 圆通速递
sh600234 科新发展
sh600235 民丰特纸
sh600236 桂冠电力
sh600237 铜峰电子
sh600238 海南椰岛
sh600239 云南城投
sh600241 时代万恒
sh600243 青海华鼎
sh600246 万通发展
sh600248 陕建股份
sh600249 两面针
sh600250 南纺股份
sh600251 冠农股份
sh600252 中恒集团
sh600255 鑫科材料
sh600256 广汇能源
sh600257 大湖股份
sh600258 首旅酒店
sh600259 广晟有色
sh600261 阳光照明
sh600262 北方股份
sh600265 ST景谷
sh600266 城建发展
sh600267 海正药业
sh600268 国电南自
sh600269 赣粤高速
sh600271 航天信息
sh600272 开开实业
sh600273 嘉化能源
sh600276 恒瑞医药
sh600277 亿利洁能
sh600278 东方创业
sh600279 重庆港
sh600280 中央商场
sh600281 华阳新材
sh600282 南钢股份
sh600283 钱江水利
sh600284 浦东建设
sh600285 羚锐制药
sh600287 江苏舜天
sh600288 大恒科技
sh600289 ST信通
sh600290 *ST华仪
sh600292 远达环保
sh600293 三峡新材
sh600295 鄂尔多斯
sh600297 广汇汽车
sh600298 安琪酵母
sh600299 安迪苏
sh600300 维维股份
sh600301 华锡有色
sh600302 标准股份
sh600303 ST曙光
sh600305 恒顺醋业
sh600306 *ST商城
sh600307 酒钢宏兴
sh600308 华泰股份
sh600309 万华化学
sh600310 广西能源
sh600312 平高电气
sh600313 农发种业
sh600315 上海家化
sh600316 洪都航空
sh600318 新力金融
sh600319 亚星化学
sh600320 振华重工
sh600321 正源股份
sh600322 津投城开
sh600323 瀚蓝环境
sh600325 华发股份
sh600326 西藏天路
sh600327 大东方
sh600328 中盐化工
sh600329 达仁堂
sh600330 天通股份
sh600331 宏达股份
sh600332 白云山
sh600333 长春燃气
sh600335 国机汽车
sh600336 澳柯玛
sh600337 美克家居
sh600338 西藏珠峰
sh600339 中油工程
sh600340 华夏幸福
sh600343 航天动力
sh600345 长江通信
sh600346 恒力石化
sh600348 华阳股份
sh600350 山东高速
sh600351 亚宝药业
sh600352 浙江龙盛
sh600353 旭光电子
sh600354 敦煌种业
sh600355 精伦电子
sh600356 恒丰纸业
sh600358 国旅联合
sh600359 新农开发
sh600360 华微电子
sh600361 创新新材
sh600362 江西铜业
sh600363 联创光电
sh600365 ST通葡
sh600366 宁波韵升
sh600367 红星发展
sh600368 五洲交通
sh600369 西南证券
sh600370 三房巷
sh600371 万向德农
sh600372 中航机载
sh600373 中文传媒
sh600375 汉马科技
sh600376 首开股份
sh600377 宁沪高速
sh600378 昊华科技
sh600379 宝光股份
sh600380 健康元
sh600381 青海春天
sh600382 广东明珠
sh600383 金地集团
sh600386 北巴传媒
sh600387 ST海越
sh600388 龙净环保
sh600389 江山股份
sh600390 五矿资本
sh600391 航发科技
sh600392 盛和资源
sh600395 盘江股份
sh600396 *ST金山
sh600397 安源煤业
sh600398 海澜之家
sh600399 抚顺特钢
sh600400 红豆股份
sh600403 大有能源
sh600405 动力源
sh600406 国电南瑞
sh600408 安泰集团
sh600409 三友化工
sh600410 华胜天成
sh600415 小商品城
sh600416 湘电股份
sh600418 江淮汽车
sh600419 天润乳业
sh600420 国药现代
sh600421 华嵘控股
sh600422 昆药集团
sh600423 柳化股份
sh600425 青松建化
sh600426 华鲁恒升
sh600428 中远海特
sh600429 三元股份
sh600433 冠豪高新
sh600435 北方导航
sh600436 片仔癀
sh600438 通威股份
sh600439 瑞贝卡
sh600444 国机通用
sh600446 金证股份
sh600448 华纺股份
sh600449 宁夏建材
sh600452 涪陵电力
sh600455 博通股份
sh600456 宝钛股份
sh600458 时代新材
sh600459 贵研铂业
sh600460 士兰微
sh600461 洪城环境
sh600462 ST九有
sh600463 空港股份
sh600467 好当家
sh600468 百利电气
sh600469 风神股份
sh600470 六国化工
sh600475 华光环能
sh600476 湘邮科技
sh600477 杭萧钢构
sh600478 科力远
sh600479 千金药业
sh600480 凌云股份
sh600481 双良节能
sh600482 中国动力
sh600483 福能股份
sh600486 扬农化工
sh600487 亨通光电
sh600488 津药药业
sh600489 中金黄金
sh600490 鹏欣资源
sh600491 龙元建设
sh600493 凤竹纺织
sh600495 晋西车轴
sh600496 精工钢构
sh600497 驰宏锌锗
sh600498 烽火通信
sh600499 科达制造
sh600500 中化国际
sh600501 航天晨光
sh600502 安徽建工
sh600503 华丽家族
sh600505 西昌电力
sh600506 统一股份
sh600507 方大特钢
sh600508 上海能源
sh600509 天富能源
sh600510 黑牡丹
sh600511 国药股份
sh600512 腾达建设
sh600513 联环药业
sh600515 海南机场
sh600516 方大炭素
sh600517 国网英大
sh600518 ST康美
sh600519 贵州茅台
sh600520 文一科技
sh600521 华海药业
sh600522 中天科技
sh600523 贵航股份
sh600525 长园集团
sh600526 菲达环保
sh600527 江南高纤
sh600528 中铁工业
sh600529 山东药玻
sh600530 ST交昂
sh600531 豫光金铅
sh600533 栖霞建设
sh600535 天士力
sh600536 中国软件
sh600537 亿晶光电
sh600538 国发股份
sh600539 狮头股份
sh600540 新赛股份
sh600543 *ST莫高
sh600545 卓郎智能
sh600546 山煤国际
sh600547 山东黄金
sh600548 深高速
sh600549 厦门钨业
sh600550 保变电气
sh600551 时代出版
sh600552 凯盛科技
sh600556 天下秀
sh600557 康缘药业
sh600558 大西洋
sh600559 老白干酒
sh600560 金自天正
sh600561 江西长运
sh600562 国睿科技
sh600563 法拉电子
sh600565 迪马股份
sh600566 济川药业
sh600567 山鹰国际
sh600568 ST中珠
sh600569 安阳钢铁
sh600570 恒生电子
sh600571 信雅达
sh600572 康恩贝
sh600573 惠泉啤酒
sh600575 淮河能源
sh600576 祥源文旅
sh600577 精达股份
sh600578 京能电力
sh600579 克劳斯
sh600580 卧龙电驱
sh600581 八一钢铁
sh600582 天地科技
sh600583 海油工程
sh600584 长电科技
sh600585 海螺水泥
sh600586 金晶科技
sh600587 新华医疗
sh600588 用友网络
sh600589 *ST榕泰
sh600590 泰豪科技
sh600592 龙溪股份
sh600593 大连圣亚
sh600594 益佰制药
sh600595 中孚实业
sh600596 新安股份
sh600597 光明乳业
sh600598 北大荒
sh600599 ST熊猫
sh600600 青岛啤酒
sh600601 方正科技
sh600602 云赛智联
sh600603 广汇物流
sh600604 市北高新
sh600605 汇通能源
sh600606 绿地控股
sh600608 ST沪科
sh600609 金杯汽车
sh600610 中毅达
sh600611 大众交通
sh600612 老凤祥
sh600613 神奇制药
sh600615 丰华股份
sh600616 金枫酒业
sh600617 国新能源
sh600618 氯碱化工
sh600619 海立股份
sh600620 天宸股份
sh600621 华鑫股份
sh600622 光大嘉宝
sh600623 华谊集团
sh600624 复旦复华
sh600626 申达股份
sh600628 新世界
sh600629 华建集团
sh600630 龙头股份
sh600633 浙数文化
sh600635 大众公用
sh600636 国新文化
sh600637 东方明珠
sh600638 新黄浦
sh600639 浦东金桥
sh600640 国脉文化
sh600641 万业企业
sh600642 申能股份
sh600643 爱建集团
sh600644 乐山电力
sh600645 中源协和
sh600647 *ST同达
sh600648 外高桥
sh600649 城投控股
sh600650 锦江在线
sh600651 飞乐音响
sh600653 申华控股
sh600654 ST中安
sh600655 豫园股份
sh600657 信达地产
sh600658 电子城
sh600660 福耀玻璃
sh600661 昂立教育
sh600662 外服控股
sh600663 陆家嘴
sh600664 哈药股份
sh600665 天地源
sh600666 ST瑞德
sh600667 太极实业
sh600668 尖峰集团
sh600671 *ST目药
sh600673 东阳光
sh600674 川投能源
sh600675 中华企业
sh600676 交运股份
sh600678 四川金顶
sh600679 上海凤凰
sh600681 百川能源
sh600682 南京新百
sh600683 京投发展
sh600684 珠江股份
sh600685 中船防务
sh600686 金龙汽车
sh600688 上海石化
sh600689 上海三毛
sh600690 海尔智家
sh600691 阳煤化工
sh600692 亚通股份
sh600693 东百集团
sh600694 大商股份
sh600696 岩石股份
sh600697 欧亚集团
sh600698 湖南天雁
sh600699 均胜电子
sh600702 舍得酒业
sh600703 三安光电
sh600704 物产中大
sh600705 中航产融
sh600706 曲江文旅
sh600707 彩虹股份
sh600708 光明地产
sh600710 苏美达
sh600711 盛屯矿业
sh600712 南宁百货
sh600713 南京医药
sh600714 金瑞矿业
sh600715 文投控股
sh600716 凤凰股份
sh600717 天津港
sh600718 东软集团
sh600719 大连热电
sh600720 祁连山
sh600721 百花医药
sh600722 金牛化工
sh600724 宁波富达
sh600725 云维股份
sh600726 华电能源
sh600727 鲁北化工
sh600728 佳都科技
sh600729 重庆百货
sh600730 中国高科
sh600731 湖南海利
sh600732 爱旭股份
sh600733 北汽蓝谷
sh600734 ST实达
sh600735 新华锦
sh600736 苏州高新
sh600737 中粮糖业
sh600738 丽尚国潮
sh600739 辽宁成大
sh600740 山西焦化
sh600741 华域汽车
sh600742 一汽富维
sh600743 华远地产
sh600744 华银电力
sh600745 闻泰科技
sh600746 江苏索普
sh600748 上实发展
sh600749 西藏旅游
sh600750 江中药业
sh600751 海航科技
sh600753 庚星股份
sh600754 锦江酒店
sh600755 厦门国贸
sh600756 浪潮软件
sh600757 长江传媒
sh600758 辽宁能源
sh600759 *ST洲际
sh600760 中航沈飞
sh600761 安徽合力
sh600763 通策医疗
sh600764 中国海防
sh600765 中航重机
sh600766 *ST园城
sh600768 宁波富邦
sh600769 祥龙电业
sh600770 综艺股份
sh600771 广誉远
sh600773 西藏城投
sh600774 汉商集团
sh600775 南京熊猫
sh600776 东方通信
sh600777 新潮能源
sh600778 友好集团
sh600779 水井坊
sh600780 通宝能源
sh600782 新钢股份
sh600783 鲁信创投
sh600784 鲁银投资
sh600785 新华百货
sh600787 中储股份
sh600789 鲁抗医药
sh600790 轻纺城
sh600791 京能置业
sh600792 云煤能源
sh600793 宜宾纸业
sh600794 保税科技
sh600795 国电电力
sh600796 钱江生化
sh600797 浙大网新
sh600798 宁波海运
sh600800 渤海化学
sh600801 华新水泥
sh600802 福建水泥
sh600803 新奥股份
sh600804 ST鹏博士
sh600805 悦达投资
sh600807 济南高新
sh600808 马钢股份
sh600809 山西汾酒
sh600810 神马股份
sh600811 东方集团
sh600812 华北制药
sh600814 杭州解百
sh600815 厦工股份
sh600816 建元信托
sh600817 宇通重工
sh600818 中路股份
sh600819 耀皮玻璃
sh600820 隧道股份
sh600821 金开新能
sh600822 上海物贸
sh600823 ST世茂
sh600824 益民集团
sh600825 新华传媒
sh600826 兰生股份
sh600827 百联股份
sh600828 茂业商业
sh600829 人民同泰
sh600830 香溢融通
sh600831 广电网络
sh600833 第一医药
sh600834 申通地铁
sh600835 上海机电
sh600836 上海易连
sh600837 海通证券
sh600838 上海九百
sh600839 四川长虹
sh600841 动力新科
sh600843 上工申贝
sh600844 丹化科技
sh600845 宝信软件
sh600846 同济科技
sh600847 万里股份
sh600848 上海临港
sh600850 电科数字
sh600851 海欣股份
sh600853 龙建股份
sh600854 春兰股份
sh600855 航天长峰
sh600857 宁波中百
sh600858 银座股份
sh600859 王府井
sh600860 京城股份
sh600861 北京人力
sh600862 中航高科
sh600863 内蒙华电
sh600864 哈投股份
sh600865 百大集团
sh600866 星湖科技
sh600867 通化东宝
sh600868 梅雁吉祥
sh600869 远东股份
sh600871 石化油服
sh600872 中炬高新
sh600873 梅花生物
sh600874 创业环保
sh600875 东方电气
sh600876 凯盛新能
sh600877 电科芯片
sh600879 航天电子
sh600880 博瑞传播
sh600881 亚泰集团
sh600882 妙可蓝多
sh600883 博闻科技
sh600884 杉杉股份
sh600885 宏发股份
sh600886 国投电力
sh600887 伊利股份
sh600888 新疆众和
sh600889 南京化纤
sh600892 大晟文化
sh600893 航发动力
sh600894 广日股份
sh600895 张江高科
sh600897 厦门空港
sh600898 ST美讯
sh600900 长江电力
sh600901 江苏金租
sh600903 贵州燃气
sh600905 三峡能源
sh600906 财达证券
sh600908 无锡银行
sh600909 华安证券
sh600916 中国黄金
sh600917 重庆燃气
sh600918 中泰证券
sh600919 江苏银行
sh600925 苏能股份
sh600926 杭州银行
sh600927 永安期货
sh600928 西安银行
sh600929 雪天盐业
sh600933 爱柯迪
sh600935 华塑股份
sh600936 广西广电
sh600938 中国海油
sh600939 重庆建工
sh600941 中国移动
sh600955 维远股份
sh600956 新天绿能
sh600958 东方证券
sh600959 江苏有线
sh600960 渤海汽车
sh600961 株冶集团
sh600962 国投中鲁
sh600963 岳阳林纸
sh600965 福成股份
sh600966 博汇纸业
sh600967 内蒙一机
sh600968 海油发展
sh600969 郴电国际
sh600970 中材国际
sh600971 恒源煤电
sh600973 宝胜股份
sh600975 新五丰
sh600976 健民集团
sh600977 中国电影
sh600979 广安爱众
sh600980 北矿科技
sh600981 汇鸿集团
sh600982 宁波能源
sh600983 惠而浦
sh600984 建设机械
sh600985 淮北矿业
sh600986 浙文互联
sh600987 航民股份
sh600988 赤峰黄金
sh600989 宝丰能源
sh600990 四创电子
sh600992 贵绳股份
sh600993 马应龙
sh600995 南网储能
sh600996 贵广网络
sh600997 开滦股份
sh600998 九州通
sh600999 招商证券
sh601000 唐山港
sh601001 晋控煤业
sh601002 晋亿实业
sh601003 柳钢股份
sh601005 重庆钢铁
sh601006 大秦铁路
sh601007 金陵饭店
sh601008 连云港
sh601009 南京银行
sh601010 文峰股份
sh601011 宝泰隆
sh601012 隆基绿能
sh601015 陕西黑猫
sh601016 节能风电
sh601018 宁波港
sh601019 山东出版
sh601020 华钰矿业
sh601021 春秋航空
sh601022 宁波远洋
sh601028 玉龙股份
sh601038 一拖股份
sh601058 赛轮轮胎
sh601059 信达证券
sh601061 中信金属
sh601065 江盐集团
sh601066 中信建投
sh601068 中铝国际
sh601069 西部黄金
sh601077 渝农商行
sh601086 国芳集团
sh601088 中国神华
sh601089 福元医药
sh601098 中南传媒
sh601099 太平洋
sh601100 恒立液压
sh601101 昊华能源
sh601106 中国一重
sh601107 四川成渝
sh601108 财通证券
sh601111 中国国航
sh601113 华鼎股份
sh601116 三江购物
sh601117 中国化学
sh601118 海南橡胶
sh601121 宝地矿业
sh601126 四方股份
sh601127 赛力斯
sh601128 常熟银行
sh601133 柏诚股份
sh601136 首创证券
sh601137 博威合金
sh601138 工业富联
sh601139 深圳燃气
sh601155 新城控股
sh601156 东航物流
sh601158 重庆水务
sh601162 天风证券
sh601163 三角轮胎
sh601166 兴业银行
sh601168 西部矿业
sh601169 北京银行
sh601177 杭齿前进
sh601179 中国西电
sh601186 中国铁建
sh601187 厦门银行
sh601188 龙江交通
sh601198 东兴证券
sh601199 江南水务
sh601200 上海环境
sh601208 东材科技
sh601211 国泰君安
sh601212 白银有色
sh601216 君正集团
sh601218 吉鑫科技
sh601222 林洋能源
sh601225 陕西煤业
sh601226 华电重工
sh601228 广州港
sh601229 上海银行
sh601231 环旭电子
sh601233 桐昆股份
sh601236 红塔证券
sh601238 广汽集团
sh601279 英利汽车
sh601288 农业银行
sh601298 青岛港
sh601311 骆驼股份
sh601318 中国平安
sh601319 中国人保
sh601326 秦港股份
sh601328 交通银行
sh601330 绿色动力
sh601333 广深铁路
sh601336 新华保险
sh601339 百隆东方
sh601360 三六零
sh601366 利群股份
sh601368 绿城水务
sh601369 陕鼓动力
sh601375 中原证券
sh601377 兴业证券
sh601388 怡球资源
sh601390 中国中铁
sh601398 工商银行
sh601399 国机重装
sh601456 国联证券
sh601500 通用股份
sh601512 中新集团
sh601515 东峰集团
sh601518 吉林高速
sh601519 大智慧
sh601528 瑞丰银行
sh601555 东吴证券
sh601566 九牧王
sh601567 三星医疗
sh601568 北元集团
sh601577 长沙银行
sh601579 会稽山
sh601588 北辰实业
sh601595 上海电影
sh601598 中国外运
sh601599 浙文影业
sh601600 中国铝业
sh601601 中国太保
sh601606 长城军工
sh601607 上海医药
sh601608 中信重工
sh601609 金田股份
sh601611 中国核建
sh601615 明阳智能
sh601616 广电电气
sh601618 中国中冶
sh601619 嘉泽新能
sh601628 中国人寿
sh601633 长城汽车
sh601636 旗滨集团
sh601658 邮储银行
sh601665 齐鲁银行
sh601666 平煤股份
sh601668 中国建筑
sh601669 中国电建
sh601677 明泰铝业
sh601678 滨化股份
sh601686 友发集团
sh601688 华泰证券
sh601689 拓普集团
sh601696 中银证券
sh601698 中国卫通
sh601699 潞安环能
sh601700 风范股份
sh601702 华峰铝业
sh601717 郑煤机
sh601718 际华集团
sh601727 上海电气
sh601728 中国电信
sh601766 中国中车
sh601777 力帆科技
sh601778 晶科科技
sh601788 光大证券
sh601789 宁波建工
sh601798 蓝科高新
sh601799 星宇股份
sh601800 中国交建
sh601801 皖新传媒
sh601808 中海油服
sh601811 新华文轩
sh601816 京沪高铁
sh601818 光大银行
sh601825 沪农商行
sh601827 三峰环境
sh601828 美凯龙
sh601838 成都银行
sh601857 中国石油
sh601858 中国科传
sh601860 紫金银行
sh601865 福莱特
sh601866 中远海发
sh601868 中国能建
sh601869 长飞光纤
sh601872 招商轮船
sh601877 正泰电器
sh601878 浙商证券
sh601880 辽港股份
sh601881 中国银河
sh601882 海天精工
sh601886 江河集团
sh601888 中国中免
sh601890 亚星锚链
sh601898 中煤能源
sh601899 紫金矿业
sh601900 南方传媒
sh601901 方正证券
sh601908 京运通
sh601916 浙商银行
sh601918 新集能源
sh601919 中远海控
sh601921 浙版传媒
sh601928 凤凰传媒
sh601929 吉视传媒
sh601933 永辉超市
sh601939 建设银行
sh601949 中国出版
sh601952 苏垦农发
sh601956 东贝集团
sh601958 金钼股份
sh601963 重庆银行
sh601965 中国汽研
sh601966 玲珑轮胎
sh601968 宝钢包装
sh601969 海南矿业
sh601975 招商南油
sh601985 中国核电
sh601988 中国银行
sh601989 中国重工
sh601990 南京证券
sh601991 大唐发电
sh601992 金隅集团
sh601995 中金公司
sh601996 丰林集团
sh601997 贵阳银行
sh601998 中信银行
sh601999 出版传媒
sh603000 人民网
sh603001 ST奥康
sh603002 宏昌电子
sh603003 龙宇股份
sh603005 晶方科技
sh603006 联明股份
sh603007 ST花王
sh603008 喜临门
sh603009 北特科技
sh603010 万盛股份
sh603011 合锻智能
sh603012 创力集团
sh603013 亚普股份
sh603015 弘讯科技
sh603016 新宏泰
sh603017 中衡设计
sh603018 华设集团
sh603019 中科曙光
sh603020 爱普股份
sh603021 山东华鹏
sh603022 新通联
sh603023 威帝股份
sh603025 大豪科技
sh603026 胜华新材
sh603027 千禾味业
sh603028 赛福天
sh603029 天鹅股份
sh603030 *ST全筑
sh603031 安孚科技
sh603032 德新科技
sh603033 三维股份
sh603035 常熟汽饰
sh603036 如通股份
sh603037 凯众股份
sh603038 华立股份
sh603039 泛微网络
sh603040 新坐标
sh603041 美思德
sh603042 华脉科技
sh603043 广州酒家
sh603045 福达合金
sh603048 浙江黎明
sh603050 科林电气
sh603051 鹿山新材
sh603052 可川科技
sh603053 成都燃气
sh603055 台华新材
sh603056 德邦股份
sh603057 紫燕食品
sh603058 永吉股份
sh603059 倍加洁
sh603060 国检集团
sh603061 金海通
sh603062 麦加芯彩
sh603063 禾望电气
sh603065 宿迁联盛
sh603066 音飞储存
sh603067 振华股份
sh603068 博通集成
sh603069 海汽集团
sh603070 万控智造
sh603071 物产环能
sh603073 彩蝶实业
sh603075 热威股份
sh603076 乐惠国际
sh603077 和邦生物
sh603078 江化微
sh603079 圣达生物
sh603080 新疆火炬
sh603081 大丰实业
sh603083 剑桥科技
sh603085 天成自控
sh603086 先达股份
sh603087 甘李药业
sh603088 宁波精达
sh603089 正裕工业
sh603090 宏盛股份
sh603093 南华期货
sh603095 越剑智能
sh603096 新经典
sh603097 江苏华辰
sh603098 森特股份
sh603099 长白山
sh603100 川仪股份
sh603101 汇嘉时代
sh603102 百合股份
sh603103 横店影视
sh603105 芯能科技
sh603106 恒银科技
sh603107 上海汽配
sh603108 润达医疗
sh603109 神驰机电
sh603110 东方材料
sh603111 康尼机电
sh603112 华翔股份
sh603113 金能科技
sh603115 海星股份
sh603116 红蜻蜓
sh603117 ST万林
sh603118 共进股份
sh603119 浙江荣泰
sh603121 华培动力
sh603122 合富中国
sh603123 翠微股份
sh603125 常青科技
sh603126 中材节能
sh603127 昭衍新药
sh603128 华贸物流
sh603129 春风动力
sh603130 云中马
sh603131 上海沪工
sh603132 金徽股份
sh603133 *ST碳元
sh603135 中重科技
sh603136 天目湖
sh603137 恒尚节能
sh603138 海量数据
sh603139 康惠制药
sh603150 万朗磁塑
sh603151 邦基科技
sh603153 上海建科
sh603155 新亚强
sh603156 养元饮品
sh603158 腾龙股份
sh603159 上海亚虹
sh603160 汇顶科技
sh603161 科华控股
sh603162 海通发展
sh603163 圣晖集成
sh603165 荣晟环保
sh603166 福达股份
sh603167 渤海轮渡
sh603168 莎普爱思
sh603169 兰石重装
sh603170 宝立食品
sh603171 税友股份
sh603172 万丰股份
sh603173 福斯达
sh603176 汇通集团
sh603177 德创环保
sh603178 圣龙股份
sh603179 新泉股份
sh603180 金牌厨柜
sh603181 皇马科技
sh603182 嘉华股份
sh603183 建研院
sh603185 弘元绿能
sh603186 华正新材
sh603187 海容冷链
sh603188 亚邦股份
sh603189 网达软件
sh603190 亚通精工
sh603191 望变电气
sh603192 汇得科技
sh603193 润本股份
sh603195 公牛集团
sh603196 日播时尚
sh603197 保隆科技
sh603198 迎驾贡酒
sh603199 九华旅游
sh603200 上海洗霸
sh603201 常润股份
sh603203 快克智能
sh603206 嘉环科技
sh603208 江山欧派
sh603209 兴通股份
sh603211 晋拓股份
sh603212 赛伍技术
sh603213 镇洋发展
sh603214 爱婴室
sh603215 比依股份
sh603216 梦天家居
sh603217 元利科技
sh603218 日月股份
sh603219 富佳股份
sh603220 中贝通信
sh603221 爱丽家居
sh603222 济民医疗
sh603223 恒通股份
sh603225 新凤鸣
sh603226 菲林格尔
sh603227 雪峰科技
sh603228 景旺电子
sh603229 奥翔药业
sh603230 内蒙新华
sh603232 格尔软件
sh603233 大参林
sh603235 天新药业
sh603236 移远通信
sh603237 五芳斋
sh603238 诺邦股份
sh603239 浙江仙通
sh603255 鼎际得
sh603256 宏和科技
sh603258 电魂网络
sh603259 药明康德
sh603260 合盛硅业
sh603261 立航科技
sh603266 天龙股份
sh603267 鸿远电子
sh603268 松发股份
sh603269 海鸥股份
sh603270 金帝股份
sh603272 联翔股份
sh603273 天元智能
sh603275 众辰科技

# Check Data Accuracy

In [9]:
def SQLSearch(s:str):
    conn = psycopg2.connect(host="localhost", database="yuzhuoran", user="postgres", password="YZRyzr010306!")
    cur = conn.cursor()
    conn.commit()
    conn.rollback()
    conn.autocommit = True
    cur.execute(s)
    col_names = [desc [0] for desc in cur.description]
    results = cur.fetchall()
    cur.close()
    return col_names,results

In [10]:
sql = "SELECT * from \"Trading\".Fact_Stock_Daily\
                where Date_ID=" + Current_Date + ";"
col,res = SQLSearch(sql)
df = pd.DataFrame(res,columns=col)
df.tail()

              fsd_id  stock_id   date_id   open   high    low  volume      turnover amplitude percent_of_incre_decre amount_of_incre_decre turnover_rate  close
5301  20231130301550    301550  20231130  52.60  54.28  50.90   37437  195432600.84      6.45                  -0.15                 -0.08         14.35  52.31
5302  20231130301555    301555  20231130  44.46  44.75  42.79   28345  122974809.12      4.40                  -2.76                 -1.23         12.96  43.29
5303  20231130301558    301558  20231130  14.43  14.66  14.33  174293  252760222.96      2.32                   1.62                  0.23         15.67  14.46
5304  20231130301559    301559  20231130  19.68  19.78  19.24   34348   66771365.12      2.74                  -2.03                 -0.40          4.06  19.31
5305  20231130301169    301169  20231130  54.65  58.50  54.65   79768  454020982.00      6.92                   2.71                  1.51         28.36  57.16